### ISSUE TITLE
Doesn´t render chat video

### ISSUE THREAD

**Issue by Tuskraider** [lay295/TwitchDownloader#1]
So basically, when trying to render the chat it goes past the render comments and emotes etc but when it comes to render video it renders only a couple seconds etc depending on video size anywhere from 0% to 30% (see attached gif). Then the created video length is only a couple seconds (seems to be stuck around 23 seconds for the most part) in comparison to the full length VOD which is atleast an hour. I've tried with multiple JSON downloads and videos with the same result.

![Twitchdownloader bug](https://user-images.githubusercontent.com/55399766/64973739-d5d4a180-d8ab-11e9-80d5-e7a76c1455d9.gif)

**Comment by Tuskraider** [comment]
It doesnt seem to matter what settings I use either.

**Comment by lay295** [comment]
Could you upload your json file somewhere or give me the VOD ID so I can try and reproduce it?

Thanks.

**Comment by Tuskraider** [comment]
Sry for not responding quicker. Okay, so this is one of the longer ones i've tried 467599592 its about 7 hours and this is a shorter one of only 3 min: 463863335 , same issue on both. Oh and here is my .json so you can maybe compare with the ones you get https://gofile.io/?c=nX7OPz

**Comment by lay295** [comment]
I found the issue, was one of the gif emotes causing some trouble.

It should be fixed in the release I just put up. Feel free to re-open this if there's still a problem.

Thanks for the report 👍
