### ISSUE TITLE
chat renderer crashing.

### ISSUE THREAD

**Issue by lejark** [lay295/TwitchDownloader#10]
First, Thanks for creating nice tool.

BTW, I tried chat rendering but crashed when this tool tried rendering after fetching emoticon.
Could you solve this?

I attached the json file what I tried.

Thanks!
[shenmue3_1_chat.zip](https://github.com/lay295/TwitchDownloader/files/3925962/shenmue3_1_chat.zip)

**Comment by lay295** [comment]
It renders fine on my end.

Do you have C++ 2015 Redistributable installed?
https://www.microsoft.com/en-us/download/details.aspx?id=52685
