### ISSUE TITLE
[Question] How to overlay the chat video file on the stream with transparant background with ffmpeg

### ISSUE THREAD

**Issue by Stinosko** [lay295/TwitchDownloader#100]
I'm trying to overlay rendered chat file on top of the stream-video with a transparant background through ffmpeg but I can't seem to get that to work. I use `TwitchDownloaderCLI -m ChatRender -i chat.json --background-color "#00000000" -o output.mp4` to render the chat with transparent background (according to issue #85) but using that file to overlay doesn't give a transparent background. I used a lot of ffmpeg commands from googling but so far none of them rendered the chat video with transparent background on top of the stream. 

Most simple ffmpeg command to overlay them: `ffmpeg -i stream.mp4 -i chat.mp4 -filter_complex overlay output.mp4`

Anyone a idea how to do it with ffmpeg?

**Comment by lay295** [comment]
I'm not entirely sure, but MrBrax gave an example of an effort command he uses in #79 that you could give a try

**Comment by Stinosko** [comment]
That actually worked! Thank you!

Maybe add it to the CLI documentation for others to use it? 🙂
