### ISSUE TITLE
What does the "Download Threads" section mean?

### ISSUE THREAD

**Issue by dapperdap** [lay295/TwitchDownloader#1008]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates

### Write stuff here

I just don't know what it means and would like to now if it effects my download in any way. Thank you.

**Comment by ScrubN** [comment]
Threads are the number of simultaneous connections to Twitch servers.

For most scenarios the default of 4 threads is fine, but if Twitch limits the maximum individual connection speed for your country or if you are downloading in low resolution then you will want to increase the thread count.

**Comment by dapperdap** [comment]
Ok. Im just download in standard 720, so ill just leave it alone. Thank you
