### ISSUE TITLE
Error with chat downloading

### ISSUE THREAD

**Issue by Peter-Soeiro** [lay295/TwitchDownloader#1009]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

"ERROR: Object reference not set to an instance of an object."

Vod download works fine, but chat gives this error

After checking the issue page I didn't find a specific solution. help?

### Add any related files or extra information here

VOD id: 1125963052

**Comment by ScrubN** [comment]
Did you mean to say download instead of render? I'm able to render the chat just fine, but I was having problems downloading it and ended up needing to make a change.

**Comment by Peter-Soeiro** [comment]
Yes I'm having a problem with the download, sorry

**Comment by ScrubN** [comment]
I will release a new update soon, but until then you will find a temporary workflow build here in a few minutes: https://github.com/lay295/TwitchDownloader/actions/runs/8413404737?pr=1011
