### ISSUE TITLE
Suggestion: Automatic repair of video chunks

### ISSUE THREAD

**Issue by George620** [lay295/TwitchDownloader#101]
I'm downloading some video with number of threads of 10. When downloading, semi-bad internet strikes and it will left 7 or 2 seconds chunks of videos instead of 10s. But that's not the biggest issue. When this happens in like 5 chunks, it will fullfill the number of threads (so instead of downloading 10 chunks at same time I'm downloading 5 because the next five are like "unfinished" forever). So I want to ask you if you don't add something to detect these "unfinished" chunks and redownload it or something and not leave it there.

PS: I find out in Temp about these chunks. While the finished ones have like tapes, the unfinished have the paper with the program.
PS2: This issue is not related to my previous 99% problem, in that case all chunks are finished.

**Comment by goldbattle** [comment]
Right now the program will try 10 times to get the video files, and then throw and error otherwise. I think this is pretty reasonable.
