### ISSUE TITLE
I've been getting a 403 trying to render chat

### ISSUE THREAD

**Issue by RvsTW** [lay295/TwitchDownloader#1013]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

I've been trying to render a json file for twitch chat and everytime it shows me this error "ERROR: Response status code does not indicate success: 403 (Forbidden)." I've used the software on this pc before without any issues but this time it just doesn't let me no matter what I0ve tried. Already tried redownload it, restart the pc, tried to download the chat into different parts instead of one big file, different fonts, encoding options. But to no avail since it keeps throwing me the same error everytime. It let me download the twitch vod and json file no problem, is the chat rendering where I'm running into this issue.

**Comment by ScrubN** [comment]
Send the json file or the ID of the vod.

**Comment by RvsTW** [comment]
> Send the json file or the ID of the vod.

[[3-26-24] Flats - CONTENT FARMING_ 5V5 VS 6V6_ THEN IDK !ironside - Chat.json](https://github.com/lay295/TwitchDownloader/files/14766060/3-26-24.Flats.-.CONTENT.FARMING_.5V5.VS.6V6_.THEN.IDK.ironside.-.Chat.json)

**Comment by ScrubN** [comment]
I'm unable to reproduce your issue. If you could enable "Verbose error output" in the application settings and send a screenshot of the resulting popup, it would make debugging this much easier.

**Comment by RvsTW** [comment]
> I'm unable to reproduce your issue. If you could enable "Verbose error output" in the application settings and send a screenshot of the resulting popup, it would make debugging this much easier.

![image](https://github.com/lay295/TwitchDownloader/assets/122754585/61c6b0b0-3436-468b-a559-556f2e0b4b46)

**Comment by ScrubN** [comment]
7TV is probably blocking your IP for whatever reason. Try disabling it in the render settings.

**Comment by RvsTW** [comment]
> 7TV is probably blocking your IP for whatever reason. Try disabling it in the render settings.

That worked great, thanks a lot, been trying to make this work for like 3 hours now. Really appreaciate the help ♥

**Comment by ScrubN** [comment]
I have been meaning to make BTTV/FFZ/7TV issues more clear. Would you want the program automatically disabled emote vendors when they fail, or would you rather it log an error and you manually disable the emote provider?

**Comment by RvsTW** [comment]
> I have been meaning to make BTTV/FFZ/7TV issues more clear. Would you want the program to automatically disable emote vendors when they fail, or would you rather it log an error and you manually disable the emote provider?

I think disable them automatically would work best, just have a message on the log or a pop up that says what provider was turned off just so we know in case we want to turn them on later

**Comment by superbonaci** [comment]
@RvsTW can you retry using a VPN or something?

**Comment by RvsTW** [comment]
> @RvsTW can you retry using a VPN or something?

Already did before posting in here, didn't tried many locations but I tried at least one or two. It's surfshark if that's relevant
