### ISSUE TITLE
error: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by meguygirl** [lay295/TwitchDownloader#1017]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Command Line Interface

### Describe your issue here

For Macos commnad line: After downloading the chat json, the command to download the mp4 from json returns the error: "Object reference not set to an instance of an object". This is a new problem whereas before following the steps and entering the commands were successful in downloading chat as mp4
<img width="1579" alt="0 cmd" src="https://github.com/lay295/TwitchDownloader/assets/165354957/cd5e4fab-20fa-47d1-98ae-af7a6cf03887">
.

### Add any related files or extra information here

I am on macosarm

**Comment by ScrubN** [comment]
It seems an emoji failed to decode and the program assumes it would always succeed. Until the next release, you can use the system emojis CLI option.

**Comment by meguygirl** [comment]
> It seems an emoji failed to decode and the program assumes it would always succeed. Until the next release, you can use the system emojis CLI option.
Thank you! Adding the --emoji-vendor option has started the status to "rendering video"

**Comment by ScrubN** [comment]
If you really want the non-system emojis, you can find a workflow build here: https://github.com/lay295/TwitchDownloader/actions/runs/8478210320?pr=1018
