### ISSUE TITLE
Cropped VOD downloads have incorrect length in metadata if only start is selected

### ISSUE THREAD

**Issue by jacob-song5** [lay295/TwitchDownloader#1022]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

When downloading vods with only the start time selected, the output mp4 file has the correct file size and start time, but it still has the full length of the vod in the metadata. So if you try to download the last 10 minutes of an 8 hour vod for example, the file size will be appropriately small and the video will start at the correct point in time of the vod. However, the file will show up as an 8 hour long mp4 file and therefore affect playback functionality such as time seeking in video players such as VLC. Otherwise, VLC seems to be able to playback the video properly, but if you seek past the true length of the video file, it will simply end playback.

There is a very simple workaround for this currently, which is to simply set the end time for the vod when downloading, which defaults to the very end of the vod anyways. Doing so will create an mp4 file with the correct length.

Example:
![image](https://github.com/lay295/TwitchDownloader/assets/34046849/41eee828-990f-453e-b0d8-85b0a2bc8005)
![image](https://github.com/lay295/TwitchDownloader/assets/34046849/e56816ab-8d1f-4f18-886c-18c01332078a)

### Add any related files or extra information here

VOD ID:2105185100
Crop Video:
  Start = 9:10:0
  Do not set end time
  Output video will report a length of 9:13:15

**Comment by ScrubN** [comment]
I'm unable to reproduce the issue. Can you send the video file so I can check the metadata?
![Untitled](https://github.com/lay295/TwitchDownloader/assets/72096833/9f80e8f4-8341-4e66-88a1-82e87a10d01e)

**Comment by jacob-song5** [comment]
https://github.com/lay295/TwitchDownloader/assets/34046849/601e0cf2-e660-41bd-87dd-534c701f5948

Here is a smaller example started from timestamp 9:13:05 to reduce file size. Chrome's built-in video player seems to handle the length just fine, but VLC and the Windows Media Player app both seem to report the full video length as does the file properties in Windows Explorer.

**Comment by ScrubN** [comment]
I was unable to reproduce when testing on the latest commit, however I was able to reproduce when using the latest release. This makes me think that the issue may have already been fixed.

You can help me verify that it has been fixed by testing a [workflow build](https://github.com/lay295/TwitchDownloader/actions/runs/8500698462).

**Comment by jacob-song5** [comment]
You're right, I just tested on that workflow build and the output video had the correct length. Thanks for the help, I'll mark the issue as closed.
