### ISSUE TITLE
Error when rendering twitch chat JSON file: "ERROR: Response status code does not indicate success: 403 (Forbidden)."

### ISSUE THREAD

**Issue by LachesZA** [lay295/TwitchDownloader#1025]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

Trying to render a JSON file of chat using chat render gives me the error "ERROR: Response status code does not indicate success: 403 (Forbidden)." I was able to download the VOD perfectly fine and it is not subscriber only. Someone else who is using version 1.54.0 is able to render the same file. Not sure what the problem is.

### Add any related files or extra information here

[[3-27-24] CHAT.json](https://github.com/lay295/TwitchDownloader/files/14838138/3-27-24.CHAT.json)
![Render](https://github.com/lay295/TwitchDownloader/assets/165807650/87ede08d-1008-4330-94d8-30904e945c3b)

**Comment by superbonaci** [comment]
Maybe it's some setting? Can you try with a clean profile of TwitchDownloaderGUI?

Try with the latest release from here:
https://github.com/lay295/TwitchDownloader/actions/runs/8504752965

**Comment by LachesZA** [comment]
I've Isolated the issue to 7tv emotes. I only get the issue when that is selected. Not sure how to fix it though. 
![Isolated issue marked](https://github.com/lay295/TwitchDownloader/assets/165807650/eb562e3f-a9e1-41e5-8c97-8e326b77c05a)

**Comment by ScrubN** [comment]
7TV is probably blocking your IP for some reason. The error message for bttv/ffz/7tv acting up will be better in the next version.

**Comment by superbonaci** [comment]
Try using some VPN or cell phone instead of home connection.

**Comment by LachesZA** [comment]
> Try using some VPN or cell phone instead of home connection.

I'll give this a try soon. thanks guys!

**Comment by ScrubN** [comment]
The error message should now be better in 1.54.2
