### ISSUE TITLE
Date in [] on the file will not correct saved

### ISSUE THREAD

**Issue by tuvok81** [lay295/TwitchDownloader#1030]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Select an Option

### Describe your issue here

Hello, when the downloader will download a VOD it save not correct the Date.
this will be saved [2024-54-16] correct is [2024-02-16] can you show what is the problem?

**Comment by ScrubN** [comment]
You probably typed `mm` (minutes) instead of `MM` (months)

**Comment by tuvok81** [comment]
[{date_custom="yyyy-m-d"}] {channel} - {title} <- this is what is in the settings

**Comment by ScrubN** [comment]
Yes, `m` is minutes. You must use `M` for months.
