### ISSUE TITLE
Chat Render Does Not Use Embedded Emotes

### ISSUE THREAD

**Issue by goldbattle** [lay295/TwitchDownloader#104]
I am rendering some chats, but all the emotes (for example LULW) get overwritten by their christmas versions.
For example I have this chat which has the correct LULW image embedded in the `emotes/thirdparty` json file.
https://gist.github.com/goldbattle/291d08729691d03d5dde4af14c7a4f7b

I believe the issue is that the embedded emotes are first loaded and then overwritten with whatever is on the website (for both thirdparty and twitch emotes). Maybe this is ok logic, but I think one would want to embedded the emotes to ensure the chat renders exactly as original recorded.
https://github.com/lay295/TwitchDownloader/blob/3477c878ef8467fe185fd2157c71a527f81c580a/TwitchDownloaderCore/TwitchHelper.cs#L84-L97

**Comment by lay295** [comment]
Yeah admittedly my embedded emotes isn't very well tested since it was just an idea I had. In the next update I'll fix the bug.

When I implemented it I was just mainly thinking an old emote would be gone form the channel and forgot about possible duplicates.
