### ISSUE TITLE
Rendering chat with Readable Colors

### ISSUE THREAD

**Issue by Peter-Soeiro** [lay295/TwitchDownloader#1047]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

In Chat Settings -> Chat Appearance, there is an option "Readable Colors" which makes all the names with dark colors more light, I think, which makes reading chat much easier and more enjoyable.

Is it possible to add that option, like a checkmark, to be able to render chat with "Readable Colors"?

**Comment by ScrubN** [comment]
It looks like we already have this implemented, but only when users don't have custom colors. I'll look into making it a checkbox instead.

**Comment by Peter-Soeiro** [comment]
Can you force it on every user, like Twitch?

**Comment by ScrubN** [comment]
That is the idea

**Comment by ScrubN** [comment]
> It looks like we already have this implemented, but only when users don't have custom colors. I'll look into making it a checkbox instead.

I misread the code when I posted this comment. Readable colors were always being applied, but the correction was _very_ weak.

**Comment by ScrubN** [comment]
Please review the screenshots in #1072 and tell me if the adjustment is good enough or if I need to increase it even more.

**Comment by Peter-Soeiro** [comment]
The dark blue is better but could be a little lighter. The others look good.

Thank you
