### ISSUE TITLE
Random green frames in chat render

### ISSUE THREAD

**Issue by SimplyBLGDev** [lay295/TwitchDownloader#105]
They appear at random points during the video, it happens independently in both the mask and the chat itself:
![image](https://user-images.githubusercontent.com/61010688/100807554-4ca67d80-3411-11eb-9314-55b55ced4dfd.png)

Here's my chat render settings:
![image](https://user-images.githubusercontent.com/61010688/100807637-7495e100-3411-11eb-9251-fc8cacf6a569.png)

**Comment by lay295** [comment]
Someone had a similar issue with sony vegas, and I have no idea how they fixed it.

https://github.com/lay295/TwitchDownloader/issues/74

You can send me the generated video file and mask and see if I can reproduce it with the same files, but with the previously mentioned issue it worked for me with the same video files in my sony vegas (version 15)

**Comment by SimplyBLGDev** [comment]
Video is too long to share, I will investigate in my own and let you know if it's a sony vegas problem

**Comment by SimplyBLGDev** [comment]
I can confirm this *is* a Sony Vegas issue, the broken frames are not present on other video editors (I tried with blender), I have yet to find a workaround, will post if/when I find a workaround.

**Comment by SimplyBLGDev** [comment]
Was not able to find a workaround, ended up using blender for everything.
