### ISSUE TITLE
beginning/ending time format error

### ISSUE THREAD

**Issue by SourLemonJuice** [lay295/TwitchDownloader#1056]
### Checklist

- [x] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Command Line Interface

### Describe your issue here

I want to use CLI to download a VOD to test this tool. But it returnes:

```text
ERROR(S):
  Option 'b, beginning' is defined with a bad format.
  Option 'e, ending' is defined with a bad format.
```

If I just use second it still can work, but most format of [CLI Readme](https://github.com/lay295/TwitchDownloader/blob/master/TwitchDownloaderCLI/README.md#time-durations) was not.

Even the example `TwitchDownloaderCLI videodownload --id 612942303 -b 0:01:40 -e 0:03:20 -o video.mp4` or `-b '0:01:40' -e '0:03:20'` can't works.

### Add any related files or extra information here

VOD id: 2144848002
Full command: `TwitchDownloaderCLI videodownload --id 2144848002 --quality 360p30 -b 0:40:00 -e 0:41:00 --output ./test.mp4`
I have tried both github release and AUR version on Archlinux.

**Comment by ScrubN** [comment]
Sorry, the new time format isn't released yet. I know it's awkward when the readme is not in sync with release features, but the next version should be out soon.

**Comment by ScrubN** [comment]
1.54.3 is now out.
