### ISSUE TITLE
New vods not working

### ISSUE THREAD

**Issue by 28animation** [lay295/TwitchDownloader#1059]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

![link](https://github.com/lay295/TwitchDownloader/assets/149686460/ed1bfbfa-2b42-4c25-bfef-6f0ceaf8e4c3)

All the new VODs that have been generated today 17/5 are giving an error when I try to get the info. 
However, the older VODs that I've tried are working, and I am able to download them.

Are there any workarounds to download the newest ones?

**Comment by ScrubN** [comment]
Duplicate #1057
