### ISSUE TITLE
Feature request: Add oauth token field for downloading sub-only VODs and chats.

### ISSUE THREAD

**Issue by tolekk** [lay295/TwitchDownloader#106]
I don't know the technical aspects of how this would work, but using an OAuth token to verify if a user is a sub or not would enable us to download sub-only VODs and render chats from them.

Additionally I don't see any donation button on this page - I'm using this tool almost every day and I'd love to support the development in any way I can.

**Comment by lay295** [comment]
You can actually already do that. In the VOD downloaded section there is an OAuth field you can enter to download sub only videos. You would need to get the OAuth ftom your web browser, if you click the ? next to OAuth it should bring you to a video showing how to do it.

https://youtu.be/1MBsUoFGuls

I could actually just make the program bypass sub-only VODs, but I feel that really wouldn't be a good idea. Also unless Twitch has changed something, you don't need authentication to download chat form a sub only VOD.

I was going to add a donation button next update, just a bit busy with schools and finals. Would appreciate a small donation when it does though :)

**Comment by lay295** [comment]
Donation button has been added in 1.39.
