### ISSUE TITLE
Error when writing output file chat json

### ISSUE THREAD

**Issue by meguygirl** [lay295/TwitchDownloader#1060]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Select an Option

### Describe your issue here

I downloaded the latest version and when I enter the command to download chat json I get: "Unhandled exception. System.AggregateException: One or more errors occurred. (Access to the path (Folder) is denied." I took the same steps as before and gave the binary executable rights in the terminal: chmod +x TwitchDownloaderCLI
<img width="778" alt=" 0tw" src="https://github.com/lay295/TwitchDownloader/assets/165354957/7aa1ab4e-05ae-449e-b3db-671803d50a59">

**Comment by ScrubN** [comment]
Does the file already exist and is open in another application/is read-only/is hidden?
![image](https://github.com/lay295/TwitchDownloader/assets/72096833/1088b9a9-ac56-4e6f-8d78-3b26da380074)

**Comment by meguygirl** [comment]
Ah yeah, I figured it out. I did a reboot and my antivirus had to ask if I could give it permission. It didn't pop up before until I did a reboot but I granted it permission. Thanks!
