### ISSUE TITLE
Error when getting chat info  "ERROR: Value was either too large or too small for an Int32."

### ISSUE THREAD

**Issue by Springwald** [lay295/TwitchDownloader#1063]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

When I try to download the chat, I get the message "ERROR: Value was either too large or too small for an Int32."

Die Video URL works fine in browser.

<img width="465" alt="image" src="https://github.com/lay295/TwitchDownloader/assets/8228546/68536cd2-03be-4c9f-a543-581178b21375">

### Add any related files or extra information here

Here is the video URL https://www.twitch.tv/videos/2148189776

**Comment by Springwald** [comment]
Same with the full clip URL: 
<img width="467" alt="image" src="https://github.com/lay295/TwitchDownloader/assets/8228546/11c6a8ee-c26b-4934-a9fe-5b6b89fbb10d">

**Comment by Stav06** [comment]
I had this same issue while using v1.54.2 but the problem was resolved when I used v1.54.3

**Comment by Springwald** [comment]
Oh, perfect - thanks for the tip.
I was actually sure I was using the latest version, but somehow I must have got the downloads mixed up.
It's working for me now too - I'll close the bug.
Thank you very much.
