### ISSUE TITLE
Change Temp Directory

### ISSUE THREAD

**Issue by DarkSynopsis** [lay295/TwitchDownloader#107]
Anyway to change the directory files are temporarily stored before we get the final output? just had my machine complain about running out of storage since it was downloading the VOD to my smaller OS SSD and noticed all that data was being stored in the Local Users Temp.

If no way, would be nice for the future.

**Comment by lay295** [comment]
Yeah it's been requested a few times in the past, and I plan to make a settings page where you can change it. Just busy currently with my finals so maybe in a few weeks :)

As a workaround, you probably could make a symbolic directory link from %TEMP%/TwitchDownloader to wherever you'd like the files to be stored.

**Comment by lay295** [comment]
Selecting your own temp directory has been added in 1.39, feel free to comment if it's not working as expected and I will re-open.
