### ISSUE TITLE
Can't Write To External Drive?

### ISSUE THREAD

**Issue by ThoughtzThruKeyz** [lay295/TwitchDownloader#1079]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

So, I've trying to download a pretty beefy VOD, and my local PC doesn't necessarily have enough space, but I have an external HDD that I wanted to write the VOD to, which has more than enough storage. However, when I press the download button and I'm able to choose the location of the download, I choose my HDD and yet when the download starts, it'll say "You may not have enough storage on drive C:/" even though my HDD is, say, Drive "D:/". So I was just curious is this just something I'm dealing with? Or might it be a bug of some sort?

**Comment by ScrubN** [comment]
Downloads are written to a cache location before finalized and written to
the destination location.

You want to set the cache location to be on your D: drive in the settings.

**Comment by ThoughtzThruKeyz** [comment]
This was it! Thanks so much for the speedy response!
