### ISSUE TITLE
Wrong rendering for Right To Left languages

### ISSUE THREAD

**Issue by mohad12211** [lay295/TwitchDownloader#108]
I'm trying to render a clip that has arabic in it (Right to left language)
the letters are from left to right that's the first issue
the second issue is that the letters are not connected together
the json file is fine, so it must be ffmpeg rendering
I tried to add this argument to ffmpeg :  -vf "drawtext=text_shaping=1"
which I found in a similar problem [here ](https://stackoverflow.com/questions/31753132/unicode-drawtext-right-to-left-language-issue-in-graphicsmagick-for-node)
but every time I try to add it I get an error. I don't know if I added the argument correctly though, I don't use ffmpeg a lot.
example : 
this is the wrong rendering : 
![image](https://user-images.githubusercontent.com/51754973/101396390-4f571600-38dc-11eb-871f-9e1f5b27da6e.png)

this is the right rendering (from twitch website) : 
![image](https://user-images.githubusercontent.com/51754973/101396496-731a5c00-38dc-11eb-9764-d53d56918a55.png)

if you want to experiment, this is the [clip ](https://www.twitch.tv/raforo/clip/WrongMoralRadicchioRalpherZ)

**Comment by lay295** [comment]
This isn't something you can fix in ffmpeg, as my program is rendering it wrong. I tried to fix it locally, but this is as far as I got.

![image](https://user-images.githubusercontent.com/1060681/102705023-ced7d400-4250-11eb-86eb-db7a1cd32c6f.png)

It's still clearly wrong, but I don't really understand why since I don't know any right to left languages. How my program renders text is one word at a time, so "Hello world" would render "Hello" then "world" separate. In arabic do separate words connect somehow so I need to draw them at the same time?

**Comment by goldbattle** [comment]
![image](https://user-images.githubusercontent.com/2222562/102705259-81a93180-4253-11eb-949c-0224d34af266.png)

```
    {
      "_id": "841ea7e3-62c4-4c8c-b01f-04f891b89e33",
      "created_at": "2020-12-03T16:27:52.468Z",
      "updated_at": "2020-12-03T16:27:52.468Z",
      "channel_id": "131750426",
      "content_type": "video",
      "content_id": "824138386",
      "content_offset_seconds": 13528.768,
      "commenter": {
        "display_name": "iiyasser_",
        "_id": "243221472",
        "name": "iiyasser_",
        "type": "user",
        "bio": null,
        "created_at": "2018-07-28T20:01:12.586914Z",
        "updated_at": "2020-12-16T07:47:02.318809Z",
        "logo": "https://static-cdn.jtvnw.net/user-default-pictures-uv/13e5fa74-defa-11e9-809c-784f43822e80-profile_image-300x300.png"
      },
      "source": "chat",
      "state": "published",
      "message": {
        "body": "نايس ايم",
        "fragments": [
          {
            "text": "نايس ايم"
          }
        ],
        "is_action": false,
        "user_color": "#FF69B4",
        "user_notice_params": {}
      }
    },
```

Not sure but to me, the api returns exactly what is displayed on the twitch site from the looks of it.

**Comment by lay295** [comment]
Oh wait, mine does look right... just out of order.

**Comment by mohad12211** [comment]
yeah the json file (the api) is fine, no problems with it, it's a rendering problem
you rendered the letters correctly, but it's out of order(like saying "world hello" instead of "hello world", you said your program renders the words one by one right?
if the words are in a list or array, just reverse the array and it'll be in order, this might solve it

**Comment by zdevoz** [comment]
Was this issue ever resolved? 
I just checked the json file and it seems ok. However, the render seems to be the issue.

**Comment by mohad12211** [comment]
I tried 1.40.1 and Arabic text renders as intended, very small issue tho. the outline for the Arabic text is not correct. example: 
![image](https://user-images.githubusercontent.com/51754973/134784164-d884be89-65c8-4c69-a02c-2260cc51f876.png)

I can open a new issue for that if you want, but I thought mentioning it here would be better. btw Thank you for supporting Arabic!

**Comment by lay295** [comment]
@mohad12211 I'll try and fix the issue when I have some free time, but it probably wont be for a while honestly. I'd suggest try just getting an outline in whatever video editor you use.
