### ISSUE TITLE
TD stopped working on Mac (Terminal commands)

### ISSUE THREAD

**Issue by KIBOLG** [lay295/TwitchDownloader#1090]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Command Line Interface

### Describe your issue here

I've been following the guide and been copy-pasting the same commands in the Terminal for months and downloaded many vods and chats successfully (HUGE THANKS FOR THAT), but it suddenly stopped working a few days ago.

I get this message "Unhandled exception. System.OverflowException: Value was either too large or too small for an Int32."
Followed by a lot more stuff that I don't understand.

Has there been any changes applied or anything that would stop it from working?

THanks!

**Comment by ScrubN** [comment]
> I get this message "Unhandled exception. System.OverflowException: Value was either too large or too small for an Int32."
> Followed by a lot more stuff that I don't understand.

Can you post the rest of the message that you didn't understand?

**Comment by KIBOLG** [comment]
> > I get this message "Unhandled exception. System.OverflowException: Value was either too large or too small for an Int32."
> > Followed by a lot more stuff that I don't understand.
> 
> Can you post the rest of the message that you didn't understand?

To be honest, I was told that I have to be careful about sharing things from the terminal because it can be private or sensitive information about my system. So I'm not sure about what I can share or not.

**Comment by ScrubN** [comment]
If you are not downloading a sub-only video, then the only potentially sensitive info that may be present would be your account name, which you can just exclude from the screenshot/copy-paste.

**Comment by ScrubN** [comment]
If you *are* downloading a sub-only video then you will have needed to pass an OAuth token, which I do not want you to post. If you accidentally post your OAuth token, log out of Twitch to invalidate it.

**Comment by KIBOLG** [comment]
Ah ok. It's not a sub-only video.
Here's a screenshot of the result I get after the same command I've been using for months to download vods
<img width="569" alt="Screenshot 2024-06-07 at 3 50 28 AM" src="https://github.com/lay295/TwitchDownloader/assets/156294709/1b8aaa5e-2da5-42b3-ac3b-917b0270750c">

**Comment by ScrubN** [comment]
The version you are using is 5 months old. Please download the latest version.

**Comment by KIBOLG** [comment]
Ok. Seems to work. Thanks! I guess I'll check from time to time for new versions.
