### ISSUE TITLE
Chat render and chat download (with embed images on) gives a HTTPClient error.

### ISSUE THREAD

**Issue by mikebozo** [lay295/TwitchDownloader#1096]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

Everything works fine, except if I try to download chat, with the Embed images settings on.

And Chat render just doesn't work at all. I keep getting a HTTPClient Error. I have added the program to my antivirus as acceptable/safe but that doesn't seem to matter. Which makes sense, as I can just download the vods perfectly fine. I tried to look for past issues, and new issues, but did not see this particular error/bug.
![Schermafbeelding 2024-06-13 175224](https://github.com/lay295/TwitchDownloader/assets/128156538/0834d2d5-11ae-45b3-93fb-c77b75923952)

### Add any related files or extra information here

Here is the vod ID 2132906356 I think its unrelated though.

**Comment by ScrubN** [comment]
For whatever reason, Twitch didn't respond to the network request for a badge image in time. I'm not really sure if there's anything that can be done about it, besides maybe adding some extra error handling like I did in #1014.

**Comment by mikebozo** [comment]
Thank you for responding, it seems to work fine now, for some reason. I tried so long to try and get this to work, now it works without issue. But I will try the fixes if it will happen again. But I guess the fix is simply to wait and try again later untill the connection gets accepted. Its good to know atleast nothing is wrong on my part, or the program. :)
