### ISSUE TITLE
Im not a coder so I have no idea what it is but I keep getting this error ever since i updated to the newest version 

### ISSUE THREAD

**Issue by Erastal** [lay295/TwitchDownloader#1097]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

when I try to download chat json file i get a fatal error 
![bug](https://github.com/lay295/TwitchDownloader/assets/172869673/0c015a22-6ace-443d-95e4-0c9587b47304)

**Comment by Erastal** [comment]
i have already tried reinstalling the program as it is the only thing my chimp brain can come up with lol

**Comment by ScrubN** [comment]
It looks like some information about the stream is missing (title, streamer name, or game/category) and I forgot to make sure the service could handle missing information. Fixing it now.

**Comment by ScrubN** [comment]
Until the next release is out, you should be able to find a workflow build with the fix here: https://github.com/lay295/TwitchDownloader/actions/runs/9525350185?pr=1098
