### ISSUE TITLE
chatdownload failure results in zero-length file

### ISSUE THREAD

**Issue by glubsy** [lay295/TwitchDownloader#1099]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Command Line Interface

### Describe your issue here

Since 1.54.4, if a `chatdownload` command fails (due to video Id not found), an empty output file is left in the file system.

Example:

```shell
> TwitchDownloaderCLI_1.54.4 chatdownload --id "51277891293" -E -o 51277891293.json
 ---> System.NullReferenceException: Invalid VOD, deleted/expired VOD possibly? 
[...]
zsh: abort      /opt/TwitchDownloaderCLI_1.54.4 chatdownload --id  -E -

> ls -alh
-rw-r--r-- 1 user group     0 2024-06-16 12:25  51277891293.json 
```

This also happens with any of the `--collision` flags. 
Also happens with 1.54.5.
This did not happen before (ie. 1.54.3).

### Expected behaviour:

The output JSON file should not be created.

### Add any related files or extra information here

Here is a VOD Id that does not exist: 51277891293

**Comment by ScrubN** [comment]
This is a byproduct of creating the output file immediately to protect against possible file collisions. It is present in all modes.

**Comment by ScrubN** [comment]
As I was typing out my response ~~defense of my laziness~~, I thought of a somewhat uncomplicated solution to this problem. I'll see about implementing it for 1.54.6.
