### ISSUE TITLE
'Download' stuck on 'Fetching Video Data' - times out

### ISSUE THREAD

**Issue by Eric-Hong99** [lay295/TwitchDownloader#1113]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

![image](https://github.com/lay295/TwitchDownloader/assets/34068439/81f1a138-e289-491c-b908-540adaad44f1)

Also, It takes almost a minute to load up Twitch VOD information after pressing 'Get Info'. 

### Add any related files or extra information here

https://www.twitch.tv/videos/2182568349

https://www.twitch.tv/videos/2181708241

Don't think it is a VOD specific issue.

**Comment by ScrubN** [comment]
Twitch servers were probably having issues. Try again now.

**Comment by Eric-Hong99** [comment]
> Twitch servers were probably having issues. Try again now.

Works fine now, thanks.
