### ISSUE TITLE
chat download not working

### ISSUE THREAD

**Issue by groundyy** [lay295/TwitchDownloader#1115]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

trying to download a clips chat causes it to crash with nullexception
![Kudkz3K](https://github.com/lay295/TwitchDownloader/assets/155473249/8db829b4-484d-44a8-aaba-7297390f1de3)

### Add any related files or extra information here

https://www.twitch.tv/papaplatte/clip/InnocentFrozenChowderOMGScoots-ztlBBgCNEQoI5Yzv

**Comment by ScrubN** [comment]
This was already fixed for the next release (#1097). You can download a workflow build to get access to the fix before the next version is released: https://github.com/lay295/TwitchDownloader/actions/runs/9684458893,
