### ISSUE TITLE
Downloading a VOD that starts with a muted segment results in the entire video being muted

### ISSUE THREAD

**Issue by Dawcr** [lay295/TwitchDownloader#1123]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

Using v1.54.7 to download a VOD that starts with a muted segment or by trimming the VOD to start at a muted segment results in the entire video being muted, v1.54.5 does not appear to have the same issue.

### Add any related files or extra information here

[FFmpeg log](https://github.com/user-attachments/files/16054674/ffmpegLog.txt)

**Comment by ScrubN** [comment]
This seems like a bug in FFmpeg, which _really_ sucks.

I'm honestly not too sure how to go about fixing it either without completely abandoning the new, vastly superior video finalization method.
