### ISSUE TITLE
log-level option is confusing

### ISSUE THREAD

**Issue by superbonaci** [lay295/TwitchDownloader#1127]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Unsure

### Describe your issue here

The CLI readme:
https://github.com/lay295/TwitchDownloader/blob/master/TwitchDownloaderCLI/README.md#global-arguments

Does not explain if some options include others (like ffmpeg) or each one is independent (which is confusing since programs don't work that way).

For example this could help people know that each one works independently:

**--log-level**
(Default: `Status+Info+Warning+Error`) Sets the log level flags. Applicable values are: `None`, `Status`, `Verbose`, `Info`, `Warning`, `Error`, `Ffmpeg`. When `None` is passed, any other log level flags are ignored and `--banner=false` is implied.

**Comment by superbonaci** [comment]
Thanks

**Comment by ScrubN** [comment]
> (Default: `Status+Info+Warning+Error`)

This is not valid syntax for the crappy argument parser we use.

<br>

I'm not sure why I wrote the section on enum flags only to not link to it. It's fixed now.

**Comment by superbonaci** [comment]
Still it's not clear if Info includes Warning and Error or they offer "separate" information (like ffmpeg) but maybe some software works like that.
