### ISSUE TITLE
ChatRender issue

### ISSUE THREAD

**Issue by dvdmlnk** [lay295/TwitchDownloader#113]
I’m using the CLI from 1.38 for MacOS, tried to render some popular streamers’ chats and I get this:

[STATUS] - Fetching Chat Badges
[STATUS] - Fetching Emotes
[STATUS] - Fetching 3rd Party Emotes
[STATUS] - Fetching Cheer Emotes
[STATUS] - Fetching Emojis
[STATUS] - Rendering Comments
Segmentation fault: 11

The segmentation fault appears right as it starts rendering comments. I’ve managed to make it work in Windows (boot camp) with the GUI though.

**Comment by lay295** [comment]
The MacOS version was never tested as I don't have a Mac or easy access to one. Setting up a VM seems to be quite annoying. I'll try and borrow a mac from a friend and test it.
