### ISSUE TITLE
ERROR: The SSL connection could not be established, see inner exception

### ISSUE THREAD

**Issue by insordescent2** [lay295/TwitchDownloader#1132]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

I'm trying to download a video, it gives an error:

**ERROR: The SSL connection could not be established, see inner exception.**

Everything was working before. I don't know why something should have changed.
I saw topics about such errors, it was suggested to change Win7 to win 10. But I already have windows 10

### Add any related files or extra information here

![05-07-2024 12-51-46](https://github.com/lay295/TwitchDownloader/assets/174759471/bc13fe42-9bd5-40f2-b478-c33e8f6b0c92)

**Comment by ScrubN** [comment]
Please enable "Verbose error output" in the settings and try again. If the error happens again, there will be a popup that will help me diagnose the issue.

**Comment by insordescent2** [comment]
> Пожалуйста, включите "Подробный вывод ошибки" в настройках и попробуйте снова. Если ошибка повторится, появится всплывающее окно, которое поможет мне диагностировать проблему.

![image](https://github.com/lay295/TwitchDownloader/assets/174759471/a7d2fade-9bb3-46ab-9719-63f571b052c0)

**Comment by ScrubN** [comment]
Sorry for the late response.

The issue is likely with Twitch servers, so unfortunately there's not much I can do besides recommending that you:
- disable any proxies/vpns
- update to the latest version of windows 10/11
- just wait a bit and try again
