### ISSUE TITLE
Add download from m3u8 link support

### ISSUE THREAD

**Issue by Mishasama** [lay295/TwitchDownloader#1140]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

Something like this:
`https://*.cloudfront.net/*/*/index-dvr.m3u8`
It's playable by VLC.

**Comment by ScrubN** [comment]
If I were to add support for the m3u8 links it would need to be in the CLI, since there is no way to get the original video info from the m3u8 link.

**Comment by Mishasama** [comment]
> If I were to add support for the m3u8 links it would need to be in the CLI, since there is no way to get the original video info from the m3u8 link.

Maybe something like "M3U8 mode" without display any info? Just download all ts file that include, then convent them to mp4.

**Comment by Mishasama** [comment]
Found a [replacement](https://github.com/orestonce/m3u8d).
