### ISSUE TITLE
Trouble rendering some common unicode emotes

### ISSUE THREAD

**Issue by DrivebyCoding** [lay295/TwitchDownloader#115]
Did some rendering tests with a short clip and discovered that some reasonably common unicode smileys did not render. Here's how they look like rendered by Twitchs replay in Chrome:

![twitch-replay](https://user-images.githubusercontent.com/71575966/101988202-72951300-3c98-11eb-8c65-6b385a6aee74.jpg)

Here's how the TwitchDownloader GUI release downloaded today does it running on Windows 10 with font Arial:

![downloader-replay](https://user-images.githubusercontent.com/71575966/101988127-22b64c00-3c98-11eb-9c4d-d2ae474e8bc3.jpg)
 
The clip: https://www.twitch.tv/a_seagull/clip/AmusedPlainNostrilNomNom

**Comment by lay295** [comment]
Whoops, was an easy fix. Guess I never tried multiple emojis in a row.
![image](https://user-images.githubusercontent.com/1060681/101999334-e4298d00-3ca9-11eb-97e2-55bcbe97eaac.png)

It'll be in the next release in like a week probably. thanks for the report :)

**Comment by lay295** [comment]
Should be fixed in 1.39, feel free to comment if it's not and I will re-open
