### ISSUE TITLE
[CLI] chatdownload does not reach 100%

### ISSUE THREAD

**Issue by superbonaci** [lay295/TwitchDownloader#1150]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Both

### Describe your issue here

Only 99%:

```
TwitchDownloaderCLI chatdownload -u 2193121344 -o output.html -E --temp-path './temp'
TwitchDownloaderCLI 1.54.9 Copyright (c) lay295 and contributors
[STATUS] - Downloading 99%
[STATUS] - Downloading Embed Images 100%
[STATUS] - Embedding Images 100%
[STATUS] - Writing output file
```

**Comment by ScrubN** [comment]
Is it really that big of a deal? I have many other CLI tools that also never reach 100% because of floating point rounding.

**Comment by superbonaci** [comment]
Which other CLI tools?

**Comment by ScrubN** [comment]
This is a waste of my time.
