### ISSUE TITLE
Filename template timespan error

### ISSUE THREAD

**Issue by Mishasama** [lay295/TwitchDownloader#1153]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

My chats filename template is this:
`[{date_custom="yyyy-MM-dd"}] {channel} - {title} - Chat [{trim_start_custom="HH-mm-ss"} - {trim_end_custom="HH-mm-ss"}]`

When I click download, it popup error.
What's going wrong?

### Add any related files or extra information here

![image](https://github.com/user-attachments/assets/53653ab0-2e8a-42e6-99c4-add05c4711f1)

**Comment by ScrubN** [comment]
`H` is not valid for timespans, you want to use `h` instead.

**Comment by Mishasama** [comment]
> `H` is not valid for timespans, you want to use `h` instead.

Same popup error with:
`[{date_custom="yyyy-MM-dd"}] {channel} - {title} - Chat [{trim_start_custom="h-mm-ss"} - {trim_end_custom="h-mm-ss"}]`

**Comment by ScrubN** [comment]
Oops, you'll also need to escape the dashes `hh\-mm\-ss`. If you just use `trim_start` though, it will be in the format you're expecting: https://github.com/lay295/TwitchDownloader/blob/db0928aa799e81141b38859162c0070308c6b8ab/TwitchDownloaderCore/Tools/FilenameService.cs#L23-L25

**Comment by Mishasama** [comment]
> Oops, you'll also need to escape the dashes `hh\-mm\-ss`.

THX
