### ISSUE TITLE
Add create time parameter to filename template

### ISSUE THREAD

**Issue by Mishasama** [lay295/TwitchDownloader#1162]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

If stream/clip more than one time in a day, we can't sort it by filename for now.

**Comment by ScrubN** [comment]
Unless I'm misunderstanding, `{date_custom=""}` already covers this.

**Comment by Mishasama** [comment]
> Unless I'm misunderstanding, `{date_custom=""}` already covers this.

That one only contains the date, not the time.

**Comment by ScrubN** [comment]
`{date_custom="MM-dd-yyyy hh-mm-ss tt"}` should work
![image](https://github.com/user-attachments/assets/49578e33-5de8-4d8e-8dbd-0c8921eecad4)
