### ISSUE TITLE
Make Task Queue statuses match the individual download ones

### ISSUE THREAD

**Issue by indeboss** [lay295/TwitchDownloader#1170]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

When you download an individual VOD, you see its different statuses: Fetching Video Info, Downloading, and Rendering. However, in Task Queue it's all just "Running", not giving you enough information on what kind of process your PC is currently busy with.
The request is to make these statuses match.

**Comment by ScrubN** [comment]
Duplicate #828
