### ISSUE TITLE
Settings do not upgrade when updating to a newer version

### ISSUE THREAD

**Issue by KockyB** [lay295/TwitchDownloader#1178]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [ ] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

Any way to keep the settings when updating? I'm getting a notifications of updates every time I open the app but I'm keeping it at an older version because last time I updated I lost all my settings and I need them to stay the same.

**Comment by ScrubN** [comment]
I have not personally experienced this issue, however I think I may have found the fix for it.
