### ISSUE TITLE
"bash: ./TwitchDownloaderCLI: Is a directory" (solved)

### ISSUE THREAD

**Issue by ThatMacKenzieMan** [lay295/TwitchDownloader#1179]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Command Line Interface

### Describe your issue here

so I am new to linux and I just downloaded the twitchdownloader and every time Try to use the downloader I keep getting "bash: ./TwitchDownloaderCLI: Is a directory". please help .-.

### Add any related files or extra information here

andrew@Andrew:~$ ./TwitchDownloaderCLI -m videodownload --id 2194153516 -o video.mp4
bash: ./TwitchDownloaderCLI: Is a directory

**Comment by ScrubN** [comment]
You are 1 directory above where the TwitchDownloader executable is located. Try `cd TwitchDownloaderCLI`, then your `./TwitchDownloaderCLI ...`.

**Comment by ThatMacKenzieMan** [comment]
It worked! Thank you!
