### ISSUE TITLE
ERROR: Unable to find thumbnail

### ISSUE THREAD

**Issue by thib3113** [lay295/TwitchDownloader#118]
Hello,

Some days ago, I got this error, and can't download nothing ... then it's good, and finally, the same error now ...

So, I clone the repo, and try to debug a little ( I'm not a C# developper, doesn't use VS in general ) . 

So the thumbUrl is ok ( the url is correct, and when I open it on the browser, I saw the picture ) ( I retest multiples times, and it's work on the browser, not in the app ) . 

I try to get the exception, and it just say

```
Task canceled
from : 
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
``` 

hum, no idea of what I can try :/ ... 

My versions : 
 - TwitchDownloader : 1.38 commit : 3477c878ef8467fe185fd2157c71a527f81c580a
 - windows 20H2
 
 Any ideas of what I can test next time ?

**Comment by lay295** [comment]
I'm not at my computer at the moment, but you should still be able to download stuff if it can't find the thumbnail. I remember changing it so it could a while back. Can you not just ignore the error and download anyways?

**Comment by thib3113** [comment]
Hum, I think I try to comment the try catch (totally) for the await thumbImage, and it's works (I get the info, and can download the VOD) ... And When I retry, it freeze now ...

No ideas :/

**Comment by goldbattle** [comment]
Closing due to old age, feel free to reopen if still an issue with the newest release.
