### ISSUE TITLE
Request was canceled while rendering a chat file

### ISSUE THREAD

**Issue by Shrezno** [lay295/TwitchDownloader#1186]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

Too dumb to know if this is a me issue, a twitch issue or a downloader issue but whenever i try to render a chat file it starts running then a minute later hits me with the error
"ERROR: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing."

Tried a clean reinstall but nothing. Downloaded the chat file just fine

### Add any related files or extra information here

Idk what to put here cause I tried 3 different chat files from different channels and none worked

**Comment by ScrubN** [comment]
Try disabling 7TV emotes. Their emote API tends to cause the most issues.

**Comment by Shrezno** [comment]
Ah ok, yeah seems like it's a 7TV issue

**Comment by ScrubN** [comment]
If you are still able to reproduce the issue, can you enable "verbose error outputs" in the settings and send a picture of the popup? I would like to know which request is timing out so I can add a log message instead of failing.
