### ISSUE TITLE
Tickbox for default action for duplicate file names before it occurs

### ISSUE THREAD

**Issue by Contemplative05** [lay295/TwitchDownloader#1188]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

Currently, if you need to download multiple VODs with the same name, you will only be able to click the tickbox to "remember my choice for this session" once VOD 1 is done and VOD 2 attempts to start. Having this option available to select beforehand would be helpful.

**Comment by ScrubN** [comment]
I decided to go with a global setting instead of adding a random button to force open the overwrite dialog. Hope that's alright.
![image](https://github.com/user-attachments/assets/4a61e8f5-bbd7-42db-8de1-78ef225309ef)

**Comment by Contemplative05** [comment]
Hey, how do I enable the feature in my version of the app? I am not super familiar with GitHub so idk if you being a collaborator vs the OG creator has anything to do with it.

**Comment by ScrubN** [comment]
I have not released a new version of the app with the change yet as I am waiting to see if #1176 goes anywhere, however until then you can download a workflow/nightly build here: https://github.com/lay295/TwitchDownloader/actions/runs/10607271667
