### ISSUE TITLE
Overlay emotes

### ISSUE THREAD

**Issue by sunkhaskasis** [lay295/TwitchDownloader#119]
I dunno if anyone had started a similar issue before, but feel free to link me to the duplicate if that's the case.

I'm sure you're familiar with overlay (call them hat emotes if you want) emotes which are usually added on holidays. You can stack them on top of other emotes to make them look like they're wearing a hat. Here's one of them from BTTV: https://betterttv.com/emotes/58487cc6f52be01a7ee5f205

I was wondering if you could try adding them to the Twitch Downloader? I personally am not quite sure how difficult it would be because I'm not thoroughly familiar with BTTV's API.

**Comment by lay295** [comment]
Yeah it's definitely on my list of TODOs, it just is a little hard with certain emotes like SoSnowy because it would be a GIF on top of a GIF. Eventually :)
