### ISSUE TITLE
Cant Download Clip

### ISSUE THREAD

**Issue by TRYB1K** [lay295/TwitchDownloader#12]
Hello i cant download clip when I add a link to clip this window pops up someone know how to fix it?
The window says:

Unable to get info
     
                 Unable to get Clip information. Please double check the Clip Slug and try again.

**Comment by lay295** [comment]
What url are you putting in?
I really need to make this program give better error messages and logs...

**Comment by lay295** [comment]
Looks like they deprecated the api I was using. https://clips.twitch.tv/api/v2/clips/{0}/status
"{"message": "This Clips route is deprecated."}"

I'll try and find an alternative API or way to get the links in a bit.

**Comment by TRYB1K** [comment]
I just paste a normal link after creating a clip like this:
https://clips.twitch.tv/CredulousColdbloodedDonutKeepo
And it gaves me error.

pt., 13 gru 2019 o 19:06 lay295 <notifications@github.com> napisał(a):

**Comment by lay295** [comment]
Sorry been busy, fixed with the newest release. I wanted to avoid using twitch's GQL but guess I have no choice now ¯\\\_(ツ)\_/¯
