### ISSUE TITLE
ERROR: Failed to finalize video (code -1094995529)

### ISSUE THREAD

**Issue by victory708** [lay295/TwitchDownloader#1217]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Select an Option

### Describe your issue here

I have this problem permanently with certain Twitch VOD
ERROR: Failed to finalize video (code -1094995529)
What can I do to fix it? Thank you so much!

ffmpegLog.txt

ffmpeg version 7.0.1-essentials_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 13.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-ffnvcodec --enable-libvpl --enable-nvdec --enable-nvenc --enable-vaapi --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001a1d9c6b8c0] could not find corresponding trex (id 1)
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001a1d9c6b8c0] could not find corresponding track id 0
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001a1d9c6b8c0] trun track id unknown, no tfhd was found
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001a1d9c6b8c0] error reading header
[concat @ 000001a1d9c50c00] Impossible to open 'C:\Users\user408\AppData\Local\Temp\TwitchDownloader\2258026509_638627981570422414\258.mp4'
[in#0 @ 000001a1d9c4f880] Error opening input: Invalid data found when processing input
Error opening input file C:\Users\user408\AppData\Local\Temp\TwitchDownloader\2258026509_638627981570422414\concat.txt.
Error opening input files: Invalid data found when processing input
ffmpeg version 7.0.1-essentials_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 13.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-ffnvcodec --enable-libvpl --enable-nvdec --enable-nvenc --enable-vaapi --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000027fe58ab8c0] could not find corresponding trex (id 1)
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000027fe58ab8c0] could not find corresponding track id 0
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000027fe58ab8c0] trun track id unknown, no tfhd was found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000027fe58ab8c0] error reading header
[concat @ 0000027fe5890c00] Impossible to open 'C:\Users\user408\AppData\Local\Temp\TwitchDownloader\2258026509_638627981570422414\258.mp4'
[in#0 @ 0000027fe588f880] Error opening input: Invalid data found when processing input
Error opening input file C:\Users\user408\AppData\Local\Temp\TwitchDownloader\2258026509_638627981570422414\concat.txt.
Error opening input files: Invalid data found when processing input

### Add any related files or extra information here

Windows 10
VOD id 2258026509

**Comment by ScrubN** [comment]
Duplicate #1016 - Twitch uses a different format for streams encoded by the streamer instead of by Twitch servers. We are actively working on a solution.

**Comment by victory708** [comment]
Thanks for your answer ScrubN!
