### ISSUE TITLE
Localized display name start with "_" would be werid _❒❒

### ISSUE THREAD

**Issue by aswq206** [lay295/TwitchDownloader#122]
Hi i'm Chinese user.
There is a problem for me.
![image](https://user-images.githubusercontent.com/59400568/103184668-10711a80-48f4-11eb-8610-3edbb335247b.png)
left is user _小龜 in twitch original vod 
right  is user _小龜 in  ChatRendering  _❒❒

it's a problem because there are at least 5 users using name start with "_" in our community.
so 
it's really confusing when these people chat at the same time......
like
![image](https://user-images.githubusercontent.com/59400568/103184931-1ddad480-48f5-11eb-8bc2-5172f5202eb6.png)

and it's the vod these  two user chat at the start 
https://www.twitch.tv/videos/850321001
Thanks so much.

**Comment by sunkhaskasis** [comment]
@lay295 Seeing that the VOD has been deleted, I saved a sample JSON from the same streamer in case you'll be doing some testing. The name OP has reported is included in the file.

https://i.nuuls.com/wHH_A.json

**Comment by lay295** [comment]
Thanks for downloading it, I actually already fixed it on my end and was gonna put in the latest release when I get around to it, just forgot to reply here. There have been quite a few times in the past where I didn't fix an issue immediately and lost the JSON needed to reproduce it, so appreciate it.

![image](https://user-images.githubusercontent.com/1060681/103387544-669bb480-4ad2-11eb-8ed0-a24d2d71bb7e.png)

**Comment by aswq206** [comment]
Thank you so much!!

**Comment by lay295** [comment]
Should be fixed in 1.39
