### ISSUE TITLE
The arrow keys don't actually modify the settings in the time

### ISSUE THREAD

**Issue by Mishasama** [lay295/TwitchDownloader#1222]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

![image](https://github.com/user-attachments/assets/3e583da6-2095-4f05-8943-68ff8799894a)
When you try to change the time with the arrow keys, the number displayed on the time setting doesn't change, but the one that calculates the file size changes with the keystrokes.

When the time cursor loses focus, the file size reverts to what it was before the crop. Means that the time control is buggy when using keyboard operations.

**Comment by ScrubN** [comment]
Duplicate #1029. This is a bug in the control library, which was fixed by my PR however we are still waiting on a new release with the fix.
