### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Mishasama** [lay295/TwitchDownloader#1223]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

![image](https://github.com/user-attachments/assets/49edce3d-95b9-4c5a-bc5b-f768f60fcfe9)
When I'm using the Video Mass Downloader.

1. Input the channel ID
2. Click "Set Channel"
3. See Error

### Add any related files or extra information here

No idea. Maybe it's caused by unstable internet, but as always, I hope the program will avoid crashing for this reason.

I'm using the latest version from the [Actions build](https://github.com/lay295/TwitchDownloader/actions/runs/10877111354). So... Still need to fix it.

**Comment by Mishasama** [comment]
> but it did not deliver the next page of content.

Maybe it wasn't received because the network lost packets?

**Comment by ScrubN** [comment]
> Maybe it wasn't received because the network lost packets?

The request response is JSON compressed GZip, so packet loss that didn't corrupt the GZip or the JSON syntax is very unlikely.

**Comment by Mishasama** [comment]
It just happened that some of the VODs expired and disappeared?

For example, when requesting the first page it learns that there are 32/30 VODs, but when requesting the second page it expires 3, resulting in something like 29/30 in the end?
