### ISSUE TITLE
Add a way to download the VOD & chat (json) with the same trim in one window?

### ISSUE THREAD

**Issue by sakarai0** [lay295/TwitchDownloader#1225]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

Possibly add a window / way to download the vod and chat json with the same trim.
More convenient so I don't have to put trim in vod, download, go to chat, put trim, download, (then render chat)

**Comment by Mishasama** [comment]
![image](https://github.com/user-attachments/assets/89408e63-21dc-4851-b9b0-5499653aa652)
Do you mean this?

**Comment by sakarai0** [comment]
oh my god...

**Comment by ScrubN** [comment]
Sorry for the confusion. I do want to redo the UX eventually to make things like this more clear, but I really don't have the time for it right now :(
