### ISSUE TITLE
VOD Timestamps

### ISSUE THREAD

**Issue by DavidHilly** [lay295/TwitchDownloader#123]
Please add a feature where you can have the text file display VOD timestamps instead of UTC, makes It easier If you're looking/searching for something specific.

**Comment by lay295** [comment]
I'll add that option in the next update, I just kept it as UTC because I was trying to keep it in the same format as OverrustleLogs

**Comment by AJBauer92** [comment]
You responded on 1/8 that it would be in the next update. It has been updated since 1/21 and it is currently 2/15 and it's still showing UTC instead of timestamps. Has it still not been updated or did I miss some sort of setting?

**Comment by lay295** [comment]
I just haven't really worked on this in a little bit, only get motivation every few months or so, most of the updates have just been big fixes. Eventually when I work on new features, I will add it.

**Comment by AJBauer92** [comment]
Alright. I'm hoping you do though. My occupation requires me to download Twitch chat logs and your program is more reliable and convenient than the one I'm currently using. The timestamps are the only major issue.

**Comment by 753github** [comment]
Consider adding a feature that resets the timestamps to start from 00:00:00 in a partially downloaded chat. So if I download a 1 hour long VOD that's 3 hours in and the chat for it, the timestamps will match.
