### ISSUE TITLE
ERROR: BetterTTV (and others) returned HTTP 

### ISSUE THREAD

**Issue by jenijopes** [lay295/TwitchDownloader#1233]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

When I try to download chat (or render it) 3rd party emotes throw out an error. I've read in a previous thread that you should retry for many times for it to work. But no matter how many times I retry, it won't.

### Add any related files or extra information here

![twitch chat](https://github.com/user-attachments/assets/d29a9ef8-ac1b-4a82-b241-4ad86f692686)

**Comment by jenijopes** [comment]
Should I use a non-russian IP address?

**Comment by jenijopes** [comment]
It works with VPN. Maybe you should warn russian bajs about it somewhere LULE

**Comment by jenijopes** [comment]
network issue

**Comment by Mishasama** [comment]
> It works with VPN. Maybe you should warn russian bajs about it somewhere LULE

Не забывайте, что мы находимся под полным санкциями США... а Amazon — это компания, расположенная в США.
