### ISSUE TITLE
will macOS version of twitchdlder auto update, or do i need to download latest release when a new one comes out?

### ISSUE THREAD

**Issue by comfortablemilk4454** [lay295/TwitchDownloader#1234]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates

### Write stuff here

noob question—do i need to download latest release when a new one comes out, or will it auto update? im on macOS apple silicon. thanks!

**Comment by ScrubN** [comment]
This might change in the future, but for the time being you must download updates manually.

**Comment by comfortablemilk4454** [comment]
tysm
