### ISSUE TITLE
Chat Render: ERROR: The pipe has been ended

### ISSUE THREAD

**Issue by xxxqq55** [lay295/TwitchDownloader#1238]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

I couldn't render the video with the nvidia decoder,H264.H265 Always report errors，The pipe has been ended。I can't seem to find a solution
![屏幕截图 2024-10-28 002022](https://github.com/user-attachments/assets/a074914e-7717-4176-9d6b-6298199f7e0c)

**Comment by xxxqq55** [comment]
@ScrubN Is that what you're talking about?
![屏幕截图 2024-10-30 215616](https://github.com/user-attachments/assets/c622d34a-edfa-4e4f-9313-ca50b47b0fe4)

**Comment by ScrubN** [comment]
I just need the output from FFmpeg `--log-level Status,Info,Warning,Error,Ffmpeg`

**Comment by xxxqq55** [comment]
> I need the output from FFmpeg `--log-level Status,Info,Warning,Error,Ffmpeg`

I find that I seem to make errors whenever I add parameters: --output-args=，So will the default
![屏幕截图 2024-10-30 225303](https://github.com/user-attachments/assets/b0c7fd22-722d-4fbe-87b4-b246821b7735)

**Comment by ScrubN** [comment]
It looks like the save path is being split on the space and thus interpreted as more than 1 argument. But why? It's properly escaped with <kbd>"</kbd>s.

**Comment by ScrubN** [comment]
I'll add a verbose log of the FFmpeg arg string to help with debugging. You can run the workflow build to test it out so we can fix it for the next release (hopefully within the next few days).

**Comment by xxxqq55** [comment]
@ScrubN  I'm sorry. I think I've found the problem. I'm really sorry I wasted your time

**Comment by ScrubN** [comment]
I'm really curious what the issue was though, if you're comfortable sharing

**Comment by xxxqq55** [comment]
@ScrubN  The nvidia driver I installed for 23 years, is not supported, I use ffmpeg to process video through nvidia indicates that 12.1 is just one version less than the supported 12.2api,It's a stupid thing to do
