### ISSUE TITLE
Delete chat json files after render

### ISSUE THREAD

**Issue by therealmaxkim** [lay295/TwitchDownloader#124]
Hi. Love your program - its the best way to download clips and chat at the moment. Really love that you've kept updating this for a long time. 

1. Automatically delete the chat json file after we render the chat. I use this program for batch downloading a lot and its a burden to have to find the correct json file when choosing to render a chat. It would be a lot easier to use if any json file i select end up being not rendered yet. (because the ones rendered will have their corresponding jsons deleted). This feature can just be like a checkbox on the chat render screen. 

2. Prevent/notify on duplicate downloads. Give us an option to "save" the video IDs or links somewhere after we download the vods/clips, that notifies us if we attempt to download it again in the future. Basically if you are batch downloading clips/vods, its hard to keep track of which ones i have downloaded already without having to keep all the files in a single location (so i will be notified with a "do you want to overwrite this file" when i try to download them again).

**Comment by lay295** [comment]
1. The chat render options are already pretty cluttered, so I'm hesitant on adding even more options. I'll add that option in the general options next update.

2. I could, but with many other requests I feel this is too niche of one. It would help with your workflow most likely, but maybe not for others. To avoid clutter, I probably won't implement this.

**Comment by ScrubN** [comment]
I disagree with 1 as it is not unlikely that a user will want to re-render and having an option to delete the json files could be very dangerous for users who forgot it was checked.

As for 2 I agree with lay.
