### ISSUE TITLE
error thingy

### ISSUE THREAD

**Issue by accountOrSumidk** [lay295/TwitchDownloader#1245]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

trying to download a vod and keeps giving me "ERROR: Failed to finalize video (code -28), retrying in 5 seconds...
ERROR: Failed to finalize video (code -28), retrying in 5 seconds...
ERROR: Failed to finalize video. The download cache has not been cleared and can be found at C:\Users\chang\AppData\Local\Temp\TwitchDownloader\2295501779_638666598720734571 along with a log file.
" what do i do about it?

**Comment by ScrubN** [comment]
Assuming this is a duplicate of #1216
