### ISSUE TITLE
permission on script.google.com

### ISSUE THREAD

**Issue by NicolaMalgieri** [lay295/TwitchDownloader#1257]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates

### Write stuff here

why the latest update requests permissions to write and read on https://script.google.com/*?

**Comment by ScrubN** [comment]
I think you are on the wrong repo or downloaded a malicious fork, TwitchDownloader does not interact with your browser.
