### ISSUE TITLE
Malware detected by VirusTotal

### ISSUE THREAD

**Issue by alejandrogmvva2** [lay295/TwitchDownloader#1258]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates

### Write stuff here

Here is the VirusTotal link:
https://www.virustotal.com/gui/file/ef2a78c199d50749e2fd50c30b8c9197d098a33ac856d1e0c360ec907f695857/detection

**Comment by ScrubN** [comment]
This repository is for TwitchDownloader, not [TwitchLeecher Dx](https://github.com/schneidermanuel/TwitchLeecher-Dx).

![image](https://github.com/user-attachments/assets/f3524a44-5273-45b8-8e61-a729f538aebf)
![image](https://github.com/user-attachments/assets/99363256-6086-4739-b1fa-b34d47aeabe9)
