### ISSUE TITLE
Ridiculous file sizes

### ISSUE THREAD

**Issue by EhmD1** [lay295/TwitchDownloader#126]
Whenever I render chat with a vod, the final file for the chat is like 150gb for a 2h vod. i checked the details in properties and it says the bitrate is 141k, how do i fix this? 
![image](https://user-images.githubusercontent.com/77209848/104107313-0d6d1700-5270-11eb-9fa8-41cfa34ad073.png)

**Comment by lay295** [comment]
I haven't looked into ProRes too much, I thought you couldn't change the bitrate but apparently you can with qscale. You can edit the ffmpeg arguments yourself if you know how to, but I will look into this for the next release.

**Comment by EhmD1** [comment]
Thank you very much and thank you for creating such a useful tool :D

**Comment by lay295** [comment]
In 1.39 I changed the arguments and the bitrate should be about 30k now, I really don't know how to make it go any lower. So it should be 1/5th the size, but it'll still be pretty big.

If it's still too big I'd recommend using a transparency mask.
https://www.youtube.com/watch?v=D-_TD1-w3fY
