### ISSUE TITLE
VOD Enqueue Download can't add .gzip to a compressed JSON

### ISSUE THREAD

**Issue by Mishasama** [lay295/TwitchDownloader#1261]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

![image](https://github.com/user-attachments/assets/144ee960-bdba-434d-afc3-511ec6b2d083)

1. VOD Download
2. Enqueue Download
3. Check Download Chat
4. Select Gzip
5. Add To Queue
6. You get an compress Gzip file, but with JSON extension instead.

**Comment by Mishasama** [comment]
![image](https://github.com/user-attachments/assets/76a4f6ec-2230-4e31-8fba-a85068e5bf9d)
Also, is it possible to introduce formats with higher compression rates, such as LZMA2, etc.?

**Comment by ScrubN** [comment]
Appending `.gzip` to compressed chats is implemented in such a hacky way, it was basically bound to break after #1085. I'll look into it.

> Also, is it possible to introduce formats with higher compression rates, such as LZMA2, etc.?

I would need to make gzip chat file support less hacky first, but different compression formats _is_ on the todo list.

**Comment by superbonaci** [comment]
7z has very high compression ratio and now Windows can extract it natively.

**Comment by Tristar7** [comment]
> 7z has very high compression ratio and now Windows can extract it natively.

compression rates differ little (few %), not worth the bother both longer processing times nor implementation effort

**Comment by Mishasama** [comment]
> > 7z has very high compression ratio and now Windows can extract it natively.
> 
> compression rates differ little (few %), not worth the bother both longer processing times nor implementation effort

The compression ratio and processing time are related to the user's usage methods and hardware performance. The idea here is not to change the functionality, but to add more options on top of the functionality. I don't think it should be a point of contention that it doesn't harm the vast majority of users, except that it causes the program to be slightly larger.

**Comment by ScrubN** [comment]
Thinking about it more, I don't see that much value in supporting other compression standards. I tested on a chat just now with embedded data. I compared the 7-Zip Ultra presets against the GZip output from TD and the most I saved was 9.06MB -> 8.98MB.

**Comment by Mishasama** [comment]
> 9.06MB -> 8.98MB.

This is a random clip.
![Image](https://github.com/user-attachments/assets/fd7ff957-fd0c-4e12-abde-7401c5704d5b)

It has a 11% compression rate improvement for me.

**Comment by superbonaci** [comment]
If the chat json is about 1 GB it can take a lot of RAM, depending on dictionary size. It may require 32 or 64 GB of free ram depending on the compression type and settings. It can open lots of bugs too...

**Comment by Mishasama** [comment]
> It may require 32 or 64 GB of free ram depending on the compression type and settings. It can open lots of bugs too...

7zip already has auto ram used setting...

**Comment by ScrubN** [comment]
My primary condition for adding more options is that they must be a C# Stream type. I am not dealing with managing a headless 7zip process.

**Comment by superbonaci** [comment]
This is has been requested: https://github.com/dotnet/runtime/issues/1542

7-zip has the SDK, but they claim the limit is 2GB per file.
