### ISSUE TITLE
keep the case of a channel name

### ISSUE THREAD

**Issue by LazySlavik** [lay295/TwitchDownloader#1264]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

Sorry if i worded it wrong. I would like to save vods with a channel name like you see it on a twitch page, for example: 
ArtGamesLP instead of artgameslp
thanks.

**Comment by superbonaci** [comment]
The name is not something that you can count too much on it, because ArtGamesLP and artgameslp can't exist at the same time, and sometimes the guy can change its display name, but the name will still be the first one and lowercase.

**Comment by LazySlavik** [comment]
Its about the looks not the function

**Comment by superbonaci** [comment]
The metadata.txt has it the way you like in `artist=CDawgVA` if you use the CLI.

**Comment by LazySlavik** [comment]
i just noticed, "vod download" does keep the case, but "task queue" does not

**Comment by superbonaci** [comment]
you are talking about the Windows UI not the CLI?

**Comment by LazySlavik** [comment]
Windows UI

**Comment by ScrubN** [comment]
Sorry for the late reply. I already noticed this issue while working on #1247 and will be resolved when that is merged.
