### ISSUE TITLE
7TV EMOTES NOT SHOWING

### ISSUE THREAD

**Issue by Mainfang** [lay295/TwitchDownloader#1265]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Select an Option

### Describe your issue here

When I download Twitch chat and render it this error shows up on Log section "ERROR: 7TV returned HTTP . 7TV emotes may not be present for this session" .And on my video editing sofware 7TV emotes not showing up.

**Comment by superbonaci** [comment]
Any id that we can test?

**Comment by ScrubN** [comment]
It is likely that 7TV is having issues in your area. Try waiting a while, or if you are in a country that is being sanctioned you may need to use a VPN.

**Comment by Mainfang** [comment]
> Any id that we can test?


https://github.com/user-attachments/assets/6488ee13-2935-4073-8c92-778a8e0094a6

**Comment by superbonaci** [comment]
@Mainfang you can paste one of the IDs here with expire date: https://pastebin.com/

so can I check and tell if there's any issue with any emote.

**Comment by ScrubN** [comment]
@Mainfang I greatly improved the error message a while back. Could you please try again with this workflow build? The files are at the bottom of the page. https://github.com/lay295/TwitchDownloader/actions/runs/12306650104

**Comment by Mainfang** [comment]
Error Message changed into this: ERROR: The SSL connection could not be established, see inner exception. Some 7TV emotes may not be present for this session. But unfortunately 7TV still not working. Kindly check the sample that I rendered below. Thanks

https://github.com/user-attachments/assets/5cd6ef60-79ef-45c2-a3ed-57d9e1f80e18

**Comment by ScrubN** [comment]
Would I be correct in assuming that you are unable to access either https://7tv.app/ or https://7tv.io/ in your web browser?

**Comment by superbonaci** [comment]
why don't you paste the id in pastebin so we can download and render the subs? we will not publish the id.

**Comment by superbonaci** [comment]
is it possible that they ban your ip if you download too many chats?

**Comment by Mainfang** [comment]
> Would I be correct in assuming that you are unable to access either https://7tv.app/ or https://7tv.io/ in your web browser?

I can access them on my end 
![Screenshot (3381)](https://github.com/user-attachments/assets/fb54f736-51ab-41ee-b1fd-bb9237325978)

**Comment by Mainfang** [comment]
> why don't you paste the id in pastebin so we can download and render the subs? we will not publish the id.

Sorry i dont know how to use pastebin.com but here's what im trying to download and render its twitch chat https://www.twitch.tv/videos/2329862631

**Comment by superbonaci** [comment]
It's working for me. The chat goes from minute 27 to 28:

https://github.com/user-attachments/assets/669863a6-2d08-4383-941d-9e3bd62457f5

I could send you the temp dir to use with chatrender, but I think it will try to re-download again from the internet. Would be awesome if we could just provide the images from archive or local zip, like suggested here: https://github.com/lay295/TwitchDownloader/issues/1241

**Comment by Mainfang** [comment]
> > > why don't you paste the id in pastebin so we can download and render the subs? we will not publish the id.
> > 
> > 
> > Sorry i dont know how to use pastebin.com but here's what im trying to download and render its twitch chat https://www.twitch.tv/videos/2329862631
> 
> It's working for me. The chat goes from minute 27 to 28:
> 
> Did you add the `-E` flag? It's false by default and I think should be true.
> 
>  clip.mp4 
> I could send you the temp dir to use with chatrender, but I think it will try to re-download again from the internet. Would be awesome if we could just provide the images from archive or local zip, like suggested here: #1241

I didn't add the E flag. Where can I see the E-Flag btw? Can I have the temp dir to use with chatrender? Maybe that will make 7TV Emotes show up on my end. Thanks a lot

**Comment by superbonaci** [comment]
> I didn't add the E flag. Where can I see the E-Flag btw? Can I have the temp dir to use with chatrender? Maybe that will make 7TV Emotes show up on my end. Thanks a lot

So now is working? The flag is explained here:
https://github.com/lay295/TwitchDownloader/blob/master/TwitchDownloaderCLI/README.md#arguments-for-mode-chatdownload

> -E / --embed-images (Default: false) Embed first party emotes, badges, and cheermotes into the download file for offline rendering. Useful for archival purposes, file size will be larger.

You could change the title to "-E flag enabled by default" or something like that, so @ScrubN hopefully fixes it. No idea about the graphics ui. I think it's what most people expect.

**Comment by superbonaci** [comment]
[Chat files](https://mega.nz/file/xDxCQYAQ#cSJqGHWQDsMBKEeYigdNXxdPS94sZ3UyGyYBXEr0D5Y)

Let me know when you download it so I can free up space.

**Comment by Mainfang** [comment]
> > I didn't add the E flag. Where can I see the E-Flag btw? Can I have the temp dir to use with chatrender? Maybe that will make 7TV Emotes show up on my end. Thanks a lot
> 
> So now is working? The flag is explained here: https://github.com/lay295/TwitchDownloader/blob/master/TwitchDownloaderCLI/README.md#arguments-for-mode-chatdownload
> 
> > -E / --embed-images (Default: false) Embed first party emotes, badges, and cheermotes into the download file for offline rendering. Useful for archival purposes, file size will be larger.
> 
> You could change the title to "-E flag enabled by default" or something like that, so @ScrubN hopefully fixes it. No idea about the graphics ui. I think it's what most people expect.

![Screenshot (3484)](https://github.com/user-attachments/assets/3886124a-5bb9-4d33-8294-17f41db865d2)
This is what im currently into right now. I already downloaded the "Chat Files". How do I use that? Should I put that on the Input/Output Arguments?

**Comment by ScrubN** [comment]
This issue is not at all related to the `-E` flag @superbonaci. If Mainfang did not have emotes enabled when rendering, then TD would not be fetching emotes from 7TV, which would mean the SSL errors could not occur.

**Comment by Mainfang** [comment]
> This issue is not at all related to the `-E` flag @superbonaci. If Mainfang did not have emotes enabled when rendering, then TD would not be fetching emotes from 7TV, which would mean the SSL errors could not occur.

![Screenshot (3485)](https://github.com/user-attachments/assets/3059709f-ade0-432a-8f46-67749baa3c77)
Yeah, I selected all the emotes btw

**Comment by ScrubN** [comment]
I'm assuming your system clock is correct, so my next best guesses are that 7TV is improperly rejecting your connection, either because you live in a country that is currently being sanctioned or you are using a VPN/proxy that they have disallowed, or you are using a network with heavy firewall rules (like Fortinet/Cisco NGFWs) that block certain websites and strip certificates.

If none of those are the issue, then I would need to create a special build for you that collects extra diagnostic information, and if even that doesn't work then we might need to contact someone at 7TV.

**Comment by superbonaci** [comment]
@ScrubN if you paste the url of one of the emotes then @Mainfang can open the picture directly in the web browser to see if loads or not. What is the Offline option that has a question mark?

**Comment by Mainfang** [comment]
> I'm assuming your system clock is correct, so my next best guesses are that 7TV is improperly rejecting your connection, either because you live in a country that is currently being sanctioned or you are using a VPN/proxy that they have disallowed, or you are using a network with heavy firewall rules (like Fortinet/Cisco NGFWs) that block certain websites and strip certificates.
> 
> If none of those are the issue, then I would need to create a special build for you that collects extra diagnostic information, and if even that doesn't work then we might need to contact someone at 7TV.

![Screenshot (3486)](https://github.com/user-attachments/assets/4b0004f7-5c26-4407-b3c4-f245767b9a62)
Im downloading from the Philippines (not sure if this country is under the sanction thingy) Im also not using any VPN.. This is also the same network that im using to download before and was doing fine with all the emotes though..

**Comment by superbonaci** [comment]
@Mainfang can you see sodaSpin in the website?

https://7tv.app/emotes/01FJB58DRG0005ZW4QCZF2K063

**Comment by Mainfang** [comment]
> @Mainfang can you see sodaSpin in the website?
> 
> https://7tv.app/emotes/01FJB58DRG0005ZW4QCZF2K063

I cant see it
![Uploading Screenshot (3491).png…]()

**Comment by Mainfang** [comment]
![Screenshot (3491)](https://github.com/user-attachments/assets/974a68ff-7230-4d3f-94df-81aba61df74c)


> @Mainfang can you see sodaSpin in the website?
> 
> https://7tv.app/emotes/01FJB58DRG0005ZW4QCZF2K063

I can't see it 
![Screenshot (3491)](https://github.com/user-attachments/assets/d7e48f25-a239-43e7-9fef-59e0eff1be15)

**Comment by superbonaci** [comment]
@Mainfang can you see AVIF files on your web browser? Check these

https://discourse.gnome.org/t/proposal-to-implement-support-for-animated-avif-images-in-gimp/23337

Github doesn't allow to attach AVIF files to play here.

**Comment by Mainfang** [comment]
![BVIs70M](https://github.com/user-attachments/assets/af7b3e85-eaf4-48c8-bab1-96fec17a23be)
I asked on the 7tv discord and they said that 7TV is having an issue in my country, gave me that instruction. I tried that and now it's working. Thanks a lot

**Comment by ScrubN** [comment]
> I asked on the 7tv discord and they said that 7TV is having an issue in my country, gave me that instruction. I tried that and now it's working. Thanks a lot

I'm glad you've got it working now. In about a month or 2, you should remove that line from your hosts file and see if it still works. If it doesn't then put it back, but if it does then you should not put it back just in case 7TV's IP changes in the future.

**Comment by syrtsevser** [comment]
**Solution for BTTV and FFZ:** add following ip/domain pairs to hosts file:
`104.26.7.201		frankerfacez.com api.frankerfacez.com cdn.frankerfacez.com cdn2.frankerfacez.com
104.26.1.19		betterttv.net cdn.betterttv.net api.betterttv.net`

You can look up updated IPs using sites like [https://www.nslookup.io](https://www.nslookup.io/).
