### ISSUE TITLE
[v1.55.0] downloadchat with --beginning and --ending hangs indefinitely at certain parts of VODs

### ISSUE THREAD

**Issue by feelixs** [lay295/TwitchDownloader#1266]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Command Line Interface

### Describe your issue here

I'm encountering strange behavior that seems to be related to how the CLI is interacting with downloading chat at certain timestamps in some VODs.

For example, I'll show the result of using different -b and -e params on the same VOD. The current status thats shown in the output is where the program was hanging for me:

### Add any related files or extra information here

```

>TwitchDownloaderCLI --mode chatdownload --id 2320829169 --output l.json --beginning 25031 --ending 25100 --collision Overwrite
[INFO] The program has switched from --mode <mode> to verbs (like 'git <verb>'), consider using verbs instead. Run 'TwitchDownloaderCLI.exe help' for more information.
TwitchDownloaderCLI 1.55.0 Copyright (c) lay295 and contributors
[STATUS] - Downloading 2%
```

```
>TwitchDownloaderCLI --mode chatdownload --id 2320829169 --output l.json --beginning 25031 --ending 25060 --collision Overwrite
[INFO] The program has switched from --mode <mode> to verbs (like 'git <verb>'), consider using verbs instead. Run 'TwitchDownloaderCLI.exe help' for more information.
TwitchDownloaderCLI 1.55.0 Copyright (c) lay295 and contributors
[STATUS] - Downloading 6%
```

```
>TwitchDownloaderCLI --mode chatdownload --id 2320829169 --output l.json --beginning 25031 --ending 25039 --collision Overwrite
[INFO] The program has switched from --mode <mode> to verbs (like 'git <verb>'), consider using verbs instead. Run 'TwitchDownloaderCLI.exe help' for more information.
TwitchDownloaderCLI 1.55.0 Copyright (c) lay295 and contributors
[STATUS] - Downloading 24%
```

This only happens in some situations. When I changed the -e to 25038 (instead of 25039 from the previous example) it worked: 

```

>TwitchDownloaderCLI --mode chatdownload --id 2320829169 --output l.json --beginning 25031 --ending 25038 --collision Overwrite
[INFO] The program has switched from --mode <mode> to verbs (like 'git <verb>'), consider using verbs instead. Run 'TwitchDownloaderCLI.exe help' for more information.
TwitchDownloaderCLI 1.55.0 Copyright (c) lay295 and contributors
[STATUS] - Downloading 50%
[STATUS] - Backfilling Commenter Info 100%
[STATUS] - Writing Output File
```

**EDIT** It looks like this is an issue with the downloader not properly detecting the end of a VOD. Since the VOD ends around 25038s, maybe the CLI is hanging because its trying to download chatlogs that are outside of the VOD length?

**Comment by ScrubN** [comment]
It seems that something with your VOD causes Twitch to encounter server errors
![image](https://github.com/user-attachments/assets/50f4c4e8-3ff2-427d-b54c-81f380f8a5e6)

**Comment by ScrubN** [comment]
Interestingly, reducing the amount of download threads to 1 seems to circumvent it.

**Comment by ScrubN** [comment]
> It looks like this is an issue with the downloader not properly detecting the end of a VOD. Since the VOD ends around 25038s, maybe the CLI is hanging because its trying to download chatlogs that are outside of the VOD length?

You are absolutely right, I misread the length of the VOD and thought that 25100 was in range. I'll be fixing that, as well as changing the protections around getting null video comments.
