### ISSUE TITLE
Request - Cookies and or Token for TwitchDownloaderCLI

### ISSUE THREAD

**Issue by Kozi801** [lay295/TwitchDownloader#1268]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

Would it be possible to have a way to pass cookies or token in order to download chat from VOD for Paid content that I purchased. I prefer  the CLI version to the GUI version. I wish I could do that part in the CLI tool. I don't know if this is a popular feature for people.

**Comment by superbonaci** [comment]
But can you from GUI?

**Comment by Kozi801** [comment]
Yes for GUi it works. This is for the CLI part.

**Comment by superbonaci** [comment]
Where is the option to enter the cookie or token for chat? I don't think you need any to download the chat. I've only seen the option for VOD.

**Comment by Kozi801** [comment]
Thank you, you are right. I formulated my question wrong. However, today must be a good day, I could never get the command --oauth my-token-authorisation to work. I was most likely doing it quite wrong. When chat was not working, there must have been something wrong in my commands. I will do some tweaking it should be good now. I suppose rendering should work as well without oauth?

twitchDownloaderCLI videodownload --id 2332784419 --oauth My-AuthorizationOAuthCode -o video.mp4

**Comment by superbonaci** [comment]
You can download and render it no problem:

```
$ TwitchDownloaderCLI chatdownload -E -u 2332784419 --temp-path 'temp-path' -o 2332784419.json
TwitchDownloaderCLI 1.55.0 Copyright (c) lay295 and contributors
[STATUS] - Downloading 100%
[STATUS] - Downloading Embed Images 100%
[STATUS] - Embedding Images 100%        
[STATUS] - Backfilling Commenter Info 100%
[STATUS] - Writing Output File
```

```
$ TwitchDownloaderCLI chatdownload -E -u 2332784419 --temp-path 'temp-path' -o 2332784419.html
TwitchDownloaderCLI 1.55.0 Copyright (c) lay295 and contributors
[STATUS] - Downloading 100%
[STATUS] - Downloading Embed Images 100%
[STATUS] - Embedding Images 100%        
[STATUS] - Writing Output File
```

But for some reason fails to render, looks like there's some issue that didn't happen before:

```
$ TwitchDownloaderCLI chatrender -i 2332784419.json -o 2332784419.mp4 --temp-path 'temp-path'
TwitchDownloaderCLI 1.55.0 Copyright (c) lay295 and contributors
[STATUS] - Fetching Images [1/2]
[STATUS] - Rendering Video 0% (0h0m7s Elapsed | 0h32m10s Remaining) 
[WARNING] - No valid typefaces were found for some messages.
[STATUS] - Rendering Video 3% (0h0m50s Elapsed | 0h31m58s Remaining)Bus error
```

@ScrubN could you take a look at this?

**Comment by ScrubN** [comment]
Chatdownload does not support OAuth because I have never had the opportunity to look into it.

**Comment by superbonaci** [comment]
But may chatdownload require OAuth in some cases, or is it never needed?

**Comment by ScrubN** [comment]
> But may chatdownload require OAuth in some cases, or is it never needed?

I just purchased a subscription to a streamer with sub-only VODs for this issue and found that OAuth is not needed to download chats from sub-only VODs.

Downloading chats from private VODs is impossible because not even the website can show the chat messages.

**Comment by superbonaci** [comment]
>
> I just purchased a subscription to a streamer with sub-only VODs for this issue and found that OAuth is not needed to download chats from sub-only VODs.
> 
> Downloading chats from private VODs is impossible because not even the website can show the chat messages.

Do you mean that the chat does not exist for private VODs or that can't be viewed after the streams ends?

**Comment by ScrubN** [comment]
> Do you mean that the chat does not exist for private VODs or that can't be viewed after the streams ends?

When a stream is privated/unpublished, the chat becomes unobtainable over the API; not even the Twitch website can view the chat.
![image](https://github.com/user-attachments/assets/c71bf82f-1f76-4fb6-9896-cdcd43f18580)

The ability to download the chat can be restored by making the private VOD public again.
![image](https://github.com/user-attachments/assets/f29c2b78-88e3-4307-bd84-1ac9bb4caf5a)

**Comment by superbonaci** [comment]
I see that for unpublished or private VODS you can't see the video nor the chat, but the important thing is for those that require a subscription. Seems that subscriber-only VOD is for the video itself not the chat (makes sense since the chat is not the main thing to sell).

**Comment by ScrubN** [comment]
> I see that for unpublished or private VODS you can't see the video nor the chat

Private VODs can be downloaded with an OAuth token from the broadcaster or an account with editor permissions. Chat cannot be downloaded by anyone.

**Comment by ScrubN** [comment]
Regardless, I'm confused about what this issue is asking for. You just want to know about `./TwitchDownloaderCLI videodownload --oauth <token> --id ...`?

**Comment by superbonaci** [comment]
@ScrubN he just wants to download and render chat for VOD. Does this happen to you?

```
$ TwitchDownloaderCLI chatrender -i 2332784419.json -o 2332784419.mp4 --temp-path 'temp-path'
TwitchDownloaderCLI 1.55.0 Copyright (c) lay295 and contributors
[STATUS] - Fetching Images [1/2]
[STATUS] - Rendering Video 0% (0h0m7s Elapsed | 0h32m10s Remaining) 
[WARNING] - No valid typefaces were found for some messages.
[STATUS] - Rendering Video 3% (0h0m50s Elapsed | 0h31m58s Remaining)Bus error
```

**Comment by superbonaci** [comment]
Works now after latest commits:

```
$ TwitchDownloaderCLI chatrender -i 2332784419.json -o 2332784419.mp4 --temp-path 'temp-path'
TwitchDownloaderCLI 1.55.0 Copyright (c) lay295 and contributors
[STATUS] - Fetching Images [1/2]
[STATUS] - Rendering Video 100% (0h5m40s Elapsed | 0h0m0s Remaining)
[INFO] - FINISHED. RENDER TIME: 340.1s SPEED: 53.27x
```

**Comment by ScrubN** [comment]
I cannot reproduce the bus error using 1.55.0 on either Windows or Linux

**Comment by superbonaci** [comment]
this issue is fixed.
