### ISSUE TITLE
New twitch encoder - fail to download

### ISSUE THREAD

**Issue by wolfgangam31** [lay295/TwitchDownloader#1269]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

Hello,

There is a new twitch encoder for videos and vod downloading does not work for it, 
I'm attaching the logs.
this is the vod I tried - https://www.twitch.tv/videos/2334138509

[concat.txt](https://github.com/user-attachments/files/18232605/concat.txt)
[ffmpegLog.txt](https://github.com/user-attachments/files/18232606/ffmpegLog.txt)
[metadata.txt](https://github.com/user-attachments/files/18232607/metadata.txt)

### Add any related files or extra information here

Technically, when watching live you see 1440p and 1080p available, but the vod only show 720p available. I think because the live stream up scaled with Nvidia partnership or something like that...

**Comment by nikmurder** [comment]
1440p and 1080p both 60 fps r in 265 (HEVC) now for select streamers who opted in for it (?)
in this case older browsers will show 720p60 in 264 (AVC) as the highest quality "transcode" so will the TD
(tho this is not true as 1080p60 HEVC/265 would be the highest quality transcode of the 1440p60 HEVC/265 source)

**Comment by ScrubN** [comment]
Duplicate #1216

**Comment by ScrubN** [comment]
> 1440p and 1080p both 60 fps r in 265 (HEVC) now for select streamers who opted in for it (?) in this case older browsers will show 720p60 in 264 (AVC) as the highest quality "transcode" so will the TD (tho this is not true as 1080p60 HEVC/265 would be the highest quality transcode of the 1440p60 HEVC/265 source)

Twitch does not provide transcoding above 720. All streams with >1080 source that also have a 1080 option are being transcoded locally by the streamer. The 720, 480, 360, 160 resolutions are still being provided by Twitch though.

**Comment by wolfgangam31** [comment]
Sorry for the duplicate, didn't realize this was Av1 issue. 
In any case, I still wonder why I can't even play the individual download files on my PC? I mean even if I directly download them from chrome network tab .

**Comment by ScrubN** [comment]
Because the video files are missing their headers. The M3U8 provides the
header file name, which needs to be inserted at the beginning of every
video file.

**Comment by ScrubN** [comment]
[1.55.1](https://github.com/lay295/TwitchDownloader/releases/tag/1.55.1) now supports downloading HEVC/AV1 streams
