### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Izofeu** [lay295/TwitchDownloader#127]
When trying to render chat, I get an error "Object reference not set to an instance of an object."
Other VOD chats (other .json files) render fine, but this one just doesn't want to work.
Problematic .json: https://drive.google.com/file/d/1ZRfQlhAWfWeRVUUccfw-V0rgY3cKlawk/view?usp=sharing
I cleared the TwitchDownloader\cache folder, as well as tried downloading the chat with embed emotes option. Didn't help, chat render is still failing.
My settings:
![image](https://user-images.githubusercontent.com/60717460/104667258-f302c580-56d5-11eb-933f-521d241aac52.png)
App version: 1.39 (newest)

**Comment by lay295** [comment]
Strangely, a lot of the commenters in the JSON is null. I've never seen this before, so my program knows the message but it doesn't know the username to render.

Could you give me the VOD ID you downloaded this from to see if it's a problem on Twitch's end?

**Comment by sleepygibbz** [comment]
I'm having the same problem too! Never used this program before , but I'm sticking around to find out what's going wrong :)

**Comment by gmgameschris** [comment]
This is happening to me tonight as well. VOD download works, but the Chat Render using the JSON produced has the same error.

**Comment by lay295** [comment]
If someone could give a VOD ids for one of the effected JSONs I can look into it. I remember Twitch chat bugged out today giving everyone the bot tag and stuff, and went down for others, it's probably related to that.

**Comment by Izofeu** [comment]
https://www.twitch.tv/videos/873663505

**Comment by gmgameschris** [comment]
> If someone could give a VOD id for one of the effected JSONs I can look into it. I remember Twitch chat bugged out today giving everyone the bot tag and stuff, and went down for others, it's probably related to that.

https://www.twitch.tv/videos/873833795

**Comment by sleepygibbz** [comment]
My replay works but it looks like chat stops working after a certain point https://www.twitch.tv/videos/873720797

**Comment by lay295** [comment]
Yeah, it's on Twitch's end. I've put out 1.39.1 which should allow you to render the chat without it erroring out, however any chat messages with a null commentor will be skipped.

This weird situation should only apply to VODs that were recorded today when Twitch was having a lot of issues with chat.

**Comment by gmgameschris** [comment]
I'm not sure it matters because of Twitch but I got the same error in 1.39.1 ERROR: Object reference not set to an instance of an object.

**Comment by lay295** [comment]
I might have missed something, I'll take a look

**Comment by gmgameschris** [comment]
> I might have missed something, I'll take a look

This is my VOD url https://www.twitch.tv/videos/873833795

**Comment by lay295** [comment]
> 
> 
> > I might have missed something, I'll take a look
> 
> This is my VOD url https://www.twitch.tv/videos/873833795

Can you double check you're on 1.39.1? I was able to render it fine.

![image](https://user-images.githubusercontent.com/1060681/104674377-8970c000-56b1-11eb-9a58-704d9e72eef0.png)

**Comment by gmgameschris** [comment]
Sorry about the confusion I think we're good
