### ISSUE TITLE
Unable to Fetch Video Info 

### ISSUE THREAD

**Issue by NeroP2020** [lay295/TwitchDownloader#128]
When I try to download a VOD I am getting an error saying cannot find video info. In the logs it says Error 404, the remote server returned an error. Is some wrong with my application or is it something on Twitch's side?

![88973e78330ced710f6ebd721aff7155](https://user-images.githubusercontent.com/77471449/104668889-faf74100-56a6-11eb-864e-2d1dd8c5aab2.png)

**Comment by lay295** [comment]
This was fixed yesterday in 1.39
