### ISSUE TITLE
404 errors when trying to get download VOD

### ISSUE THREAD

**Issue by Kurzdor** [lay295/TwitchDownloader#129]
https://github.com/Franiac/TwitchLeecher/issues/551

**Comment by Kurzdor** [comment]
Oh, I didn't see that fix was released, sorry.
It would be cool if there was a updater in the program =)

**Comment by IzaGz** [comment]
@Kurzdor  when the app will be able to download? Where we can download the fixed app?

**Comment by Kurzdor** [comment]
@IzaGz https://github.com/lay295/TwitchDownloader/releases
