### ISSUE TITLE
Instant Close for Chat Render

### ISSUE THREAD

**Issue by Ronaldo246** [lay295/TwitchDownloader#13]
When I render chat, the programmes fetches the data then crashes before it begins the download, I tried different versions, restarting PC, clearing space, same issue occurs.

**Comment by Ronaldo246** [comment]
I also do have https://www.microsoft.com/en-us/download/details.aspx?id=52685, I uninstalled and re-installed. It was all working last night but suddenly broken now.

**Comment by JikoUnderscore** [comment]
I have the same problem. When I tried rendering without FFZ emotes and BTTV emotes it worked fine, also i tried rendering with only BTTV emotes it worked fine. 

It only crashes if i tried to renders FFZ emotes.

**Comment by Ronaldo246** [comment]
BTTV Works for me but FFZ crashes the programme for me and doesnt finish the render.

**Comment by Daniil1288** [comment]
the api's deprecated and will be removed soon, suggesting a rewrite to use ffz's api: https://api.frankerfacez.com/v1/set/global

**Comment by Ronaldo246** [comment]
> the api (bttv v2) is deprecated and will be removed soon, suggesting a rewrite to use ffz's api: https://api.frankerfacez.com/v1/set/global

sorry im a complete noob, is this a fix or explaining the reason its broken, sorry im confused.

**Comment by Daniil1288** [comment]
explaining why it's broken, I'm not the owner of this repo
tried fixing myself using bttv's v3 api (https://api.betterttv.net/3/cached/emotes/global for example), looks like there's more work to be done that I thought there would be, need to use JArray instead of JObject, let's wait for @lay295 since he's much more knowledgeable

**Comment by Ronaldo246** [comment]
> explaining why it's broken, I'm not the owner of this repo
> tried fixing myself using bttv's v3 api (https://api.betterttv.net/3/cached/emotes/global for example), looks like there's more work to be done that I thought there would be, need to use JArray instead of JObject, let's wait for @lay295 since he's much more knowledgeable

Okay, I dont know what do atm, because chat looks scuffed with only BTTV and no FFZ.

**Comment by lay295** [comment]
Yeah I haven't had time to look into it, and don't have access to my computer at the moment. I'll fix it later today.

**Comment by lay295** [comment]
Give the new version a try :)
