### ISSUE TITLE
Improvement suggestions

### ISSUE THREAD

**Issue by Kurzdor** [lay295/TwitchDownloader#130]
Hello!
Thanks for your work!

Is it possible to add things like updater, download list/availablity to bulk download VODS/clips/chats and add checkbox to download chat JSON when downloading VOD?

1. Updater - so users will know when the update was released
2. Download list - like in Twitch Leecher, but Twitch Downloader for me is better atm.
3. Checkbox "Download chat JSON" in VOD download tab.

**Comment by holndonner** [comment]
+1

**Comment by ScrubN** [comment]
You can use the enqueue button to also download the chat at the same time.
