### ISSUE TITLE
No clip appearing after downloading it

### ISSUE THREAD

**Issue by SanderToni** [lay295/TwitchDownloader#131]
Clip doesn't appear in the folder I downloaded it to.

**Comment by lay295** [comment]
Does this happen with every clip? The clip downloading code is pretty simple, so I don't really know what would be wrong.

**Comment by SanderToni** [comment]
Yes, I tried it today for like 20 times, it merged all the clips together in the temp folder and then just disappears.

**Comment by SanderToni** [comment]
Downloading chat works but vod doesnt

**Comment by lay295** [comment]
Oh it's for the VOD downloading not the clips. I assume it's running into trouble with ffmpeg for some reason. I assume there is an ffmpeg.exe in the same directory the program is in right?

**Comment by SanderToni** [comment]
yes

**Comment by lay295** [comment]
Can you give this version a try? And copy/paste me what shows up in your log box.

https://drive.google.com/file/d/10VbTMF14Reh-qtvwGmNd4Z0bQgODCfnk/view?usp=sharing

Maybe you have ffmpeg in your PATH and something is wrong with the locally installed version? Not really sure.

**Comment by SanderToni** [comment]
Ffmpeg Path: ffmpeg
Input File: D:\videos\Twitch downloader\Twitch Downloader\TwitchDownloader\873735672\output.ts
Output File: D:\videos\sum\[1-15-21] summit1g - eft chillin. [ @summit1g ].mp4
ffmpeg version git-2020-08-31-4a11a6f Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.2.1 (GCC) 20200805
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --enable-librav1e --enable-libsvtav1 --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 58.100 / 56. 58.100
  libavcodec     58.101.101 / 58.101.101
  libavformat    58. 51.101 / 58. 51.101
  libavdevice    58. 11.101 / 58. 11.101
  libavfilter     7. 87.100 /  7. 87.100
  libswscale      5.  8.100 /  5.  8.100
  libswresample   3.  8.100 /  3.  8.100
  libpostproc    55.  8.100 / 55.  8.100
Invalid duration specification for ss: 1,18299999999999

**Comment by lay295** [comment]
Ahhh, I see the issue now. I'll release a fix later today, thanks for the help

**Comment by lay295** [comment]
You can give 1.39.2 a try

**Comment by SanderToni** [comment]
yes, works now, thank you
