### ISSUE TITLE
Bug or my fail?

### ISSUE THREAD

**Issue by Cowboyserg** [lay295/TwitchDownloader#132]
Wrote this command id cmd
`"D:\github_d\release\Twitch Downloader\TwitchDownloaderCLI" -m VideoDownload -b 0 -e 5400 -u 873223398 -q 1080 -o D:\videos\new\22__0_00_00__1_30_00__[{date_custom="M_d_yyyy"}].mp4`
after that was created file, named
`0_00_00__1_30_00__[{date_custom=M_d_yyyy}].mp4`
There is no "22_" in it, and date_custom didn't transform.
What did I do wrong?

**Comment by lay295** [comment]
I don't really know what happened to the 22_, but the formatting options aren't supported in the command line version, just in the GUI version for right now. I might add it in the future.

**Comment by Cowboyserg** [comment]
One more problem (I don't want create new issue ), when I make cropping not from 0 second (in commmand line) all information shows in console
```
[STATUS] - Downloading 100% (1/3)
[STATUS] - Combining Parts (2/3)

[STATUS] - Finalizing MP4 (3/3)
```
but video doesn't appears in folder, but if I start from not o sec, then all is okey.

**Comment by lay295** [comment]
It's probably the same bug as in #131, I assume your OS settings are in a language where . and , are swapped for numbers. So instead of 1.00 ffmpeg is getting 1,00 and erroring out. I'll have an update in a sec to try and fix it.

**Comment by lay295** [comment]
You can give 1.39.2 a try

**Comment by Cowboyserg** [comment]
Thank you for fix, but there is no trouble. Now I can download not from 0 second, but the result is without sound.

**Comment by lay295** [comment]
Huh, can you share specifically what argument you're using? 

TwitchDownloaderCLI -m VideoDownload -b 0 -e 5400 -u 873223398 -q 1080 -o video.mp4
What time are you setting for the beginning?

**Comment by Cowboyserg** [comment]
`"D:\github_d\release1\Twitch Downloader\TwitchDownloaderCLI" -m VideoDownload -b 5400 -e 10800 -u 873223398 -q 1080 -o D:\videos\new\23__1_30_00__3_00_00__jan_14_2024.mp4`
If I try another time settings, same problem.

**Comment by lay295** [comment]
For me, with that command output only the first 6 minutes are muted, because the 873223398 VOD is muted at that time.

The rest of the VOD has sound for me, can you check to see if you have sound after 6 minutes?

**Comment by Cowboyserg** [comment]
Excuse me for false alarm, audio is in another time, you are right.
