### ISSUE TITLE
downloader crashes at 97% downloading and overloads file location of program (not dowload location of vod)

### ISSUE THREAD

**Issue by canary04** [lay295/TwitchDownloader#133]
i was dowloading a vod to a fiolder in my D: drive but i got error coded at 97% and the program crashed. now my C: drive (where i dowloaded the vod) is overloaded and at 99% capacity where it was at about 70 before

**Comment by lay295** [comment]
In the settings, clear the cache to get your storage back.

To prevent it in the future, open the settings and change the Temp Folder to be a folder in your D drive
