### ISSUE TITLE
Does not delete from temp folder

### ISSUE THREAD

**Issue by goldbattle** [lay295/TwitchDownloader#135]
Right now the `output.ts` file is not deleted from the temp folder for me with version 1.39.2.
Was wondering why my system's harddrive was filling up.
![image](https://user-images.githubusercontent.com/2222562/105285457-7151e280-5b82-11eb-80ca-90323d5247e1.png)

**Comment by lay295** [comment]
Whoops your right... I'll release a fix tomorrow

**Comment by lay295** [comment]
Fixed in the newest version, thanks for the bug report!
