### ISSUE TITLE
Suggestion: Allow custom temp directory

### ISSUE THREAD

**Issue by SimplyBLGDev** [lay295/TwitchDownloader#137]
When downloading large VODs I sometimes get storage warnings on my C drive, it would be very useful to allow a custom directory for the temp files or just create them in the output directory by default.

**Comment by lay295** [comment]
You can in the newer versions in the settings. Are you on an older version?

**Comment by SimplyBLGDev** [comment]
Yes, I was using a previous version. Thanks.
