### ISSUE TITLE
CFR instead of VFR?

### ISSUE THREAD

**Issue by Nutri626** [lay295/TwitchDownloader#141]
hello, i want to edit vods in adobe premiere/vegas 18 but audio becomes out of sync because downloaded vods have variable frame rate and not constant, is there way to download vods with constant frame rates via your program?  (to auto convert it or something like that,programs like handbrake has some problems with first frames)

**Comment by DrawTR** [comment]
you can just [handbrake](https://handbrake.fr/)

**Comment by lay295** [comment]
I used to have an option to re-encode to CFR after downloading, however I found that Adobe Premiere handles VFR video fine. I think there are still issues in Sony Vegas though.

**Comment by Nutri626** [comment]
> I used to have an option to re-encode to CFR after downloading, however I found that Adobe Premiere handles VFR video fine. I think there are still issues in Sony Vegas though.

i have latest premiere pro/vegas and there is still a problem, is there available version of your program that still has that option to use?

**Comment by Nutri626** [comment]
> you can use [handbrake](https://handbrake.fr/)

i already have handbrake but sometimes video is black screen for few seconds and overall its time consuming ....

**Comment by Nutri626** [comment]
> you can use [handbrake](https://handbrake.fr/)

i already have handbrake but sometimes video has black screen for few seconds overall its time consuming to render every video with that ....

**Comment by lay295** [comment]
Are you cropping the video? Can you share the VOD ID and version of premiere you're having trouble with?

Also even if I re-add CFR back, it still be a very time consumig process similar to handbrake, since the whole video would have to be re-encoeded.

**Comment by Nutri626** [comment]
> Are you cropping the video? Can you share the VOD ID and version of premiere you're having trouble with?
> 
> Also even if I re-add CFR back, it still be a very time consumig process similar to handbrake, since the whole video would have to be re-encoeded.

yes im downloading short parts (1 ~ minute) 
Premiere Pro CC 2019 (13.1) Magician
vod id does not really matter since every single vod has vfr but some videos are synced with audio and some are not

**Comment by Nutri626** [comment]
> Are you cropping the video? Can you share the VOD ID and version of premiere you're having trouble with?
> 
> Also even if I re-add CFR back, it still be a very time consumig process similar to handbrake, since the whole video would have to be re-encoeded.


yes im downloading short parts (1 ~ minute)

it appears that i dont really have latest version but its still not THAT old, Premiere Pro CC 2019 (13.1) Magician
also vegas is pro 18 (2020) 
vod id does not really matter since every single vod is vfr but some videos are synced with audio and some are not

**Comment by lay295** [comment]
The issue is likely the cropping, not the VFR. There are black framed because it's cutting on at a keyframe, and it's using codec copy. I think there is a way to fix it by re-encoding the 1st chunk in the program but I haven't tried it.

You can try cropping in 10 second intervals and it might fix it.

So instead of cropping at 1:07-2:07 for a 1 minute crop, instead use 1:10-2:10

**Comment by Nutri626** [comment]
> The issue is likely the cropping, not the VFR. There are black framed because it's cutting not on a keyframe, and it's using codec copy. I think there is a way to fix it by re-encoding the 1st chunk in the program but I haven't tried it.
> 
> You can try cropping in 10 second intervals and it might fix it.
> 
> So instead of cropping at 1:07-2:07 for a 1 minute crop, instead use 1:10-2:10

okay im gonna try, also since we are here im gonna ask another question, is there no "new" format for true transparency for the chat? for example for short clip of mp4 format file is 1mb (with background ofc) , for transparent mov rle its around 10mb and for mov prores its around 12mb and they have normal speed, on another had we have vp8 (vp9 is really slow) which takes muuch longer time than mov and file is larger so i wonder is there is some format that can be added for more balanced render (a bit longer render than mp4 but not 10x larger file)

**Comment by Nutri626** [comment]
> The issue is likely the cropping, not the VFR. There are black framed because it's cutting not on a keyframe, and it's using codec copy. I think there is a way to fix it by re-encoding the 1st chunk in the program but I haven't tried it.
> 
> You can try cropping in 10 second intervals and it might fix it.
> 
> So instead of cropping at 1:07-2:07 for a 1 minute crop, instead use 1:10-2:10

okay im gonna try, also since we are here im gonna ask another question, is there no "new" format for true transparency for the chat? im talking about balance between time of render/file size, it takes really long and file is smaller or it takes no time and file is 10x larger than mp4, is there no way to balance it with some other format or you tried everything ?

**Comment by lay295** [comment]
> 
> 
> > The issue is likely the cropping, not the VFR. There are black framed because it's cutting not on a keyframe, and it's using codec copy. I think there is a way to fix it by re-encoding the 1st chunk in the program but I haven't tried it.
> > You can try cropping in 10 second intervals and it might fix it.
> > So instead of cropping at 1:07-2:07 for a 1 minute crop, instead use 1:10-2:10
> 
> okay im gonna try, also since we are here im gonna ask another question, is there no "new" format for true transparency for the chat? im talking about balance between time of render/file size, it takes really long and file is smaller or it takes no time and file is 10x larger than mp4, is there no way to balance it with some other format or you tried everything ?

As far as I'm aware, there is no codec that has low filesize, fast encoding, and an alpha channel. In 1.39 ProRes bitrate was made as low as I could figure out how to make it go, which results in 1/5th the file size compared to before. It's still massive compared to h264 though. Apple has a h265 version with alpha support but it's not in ffmpeg as far as I'm aware.

**Comment by Nutri626** [comment]
> > > The issue is likely the cropping, not the VFR. There are black framed because it's cutting not on a keyframe, and it's using codec copy. I think there is a way to fix it by re-encoding the 1st chunk in the program but I haven't tried it.
> > > You can try cropping in 10 second intervals and it might fix it.
> > > So instead of cropping at 1:07-2:07 for a 1 minute crop, instead use 1:10-2:10
> > 
> > 
> > okay im gonna try, also since we are here im gonna ask another question, is there no "new" format for true transparency for the chat? im talking about balance between time of render/file size, it takes really long and file is smaller or it takes no time and file is 10x larger than mp4, is there no way to balance it with some other format or you tried everything ?
> 
> As far as I'm aware, there is no codec that has low filesize, fast encoding, and an alpha channel. In 1.39 ProRes bitrate was made as low as I could figure out how to make it go, which results in 1/5th the file size compared to before. It's still massive compared to h264 though. Apple has a h265 version with alpha support but it's not in ffmpeg as far as I'm aware.

okay i got it, thanks for the answers and thanks for that program overall,  gonna close it
