### ISSUE TITLE
[Suggestion] Bulk download clips

### ISSUE THREAD

**Issue by yingersun** [lay295/TwitchDownloader#143]
Is there a way to bulk download multiple clips? If I properly format a bunch of twitch clip links (ex: clip1, clip2, clip3), it would be a great feature to download them all at once, instead of having to paste each clip and Get Info and Download.

**Comment by DrawTR** [comment]
Adding onto this, it would be cool to have some sort of queue system where you load up a bunch at once and it goes through them one at a time

**Comment by PeporJ** [comment]
Would also love a bulk download option for chat downloads. Really the one feature I miss.
