### ISSUE TITLE
ERROR: Can't open video files

### ISSUE THREAD

**Issue by Infiniya** [lay295/TwitchDownloader#146]
Hi, thanks so much for making this! For me everything works smoothly - until I try to open the video file, which my media player attributes to error 0xc00d36c4. It's either a problem with the file extension, or a corrupted/damaged file. I try loading it in Premiere Pro, but there it says that the file has an unsupported compression type. VLC doesn't do anything, it just shows a black screen. 

Is it because the video I tried downloading was too long? (3 hours, approx.) or is it something else. And if anyone has experienced something similar, I'm looking forward to hearing how you fixed it. 

Thanks!

**Comment by ScrubN** [comment]
I've not personally had any corruption issues. If you experience it again you can use the program "ffprobe" that is bundled with the GUI to diagnose what was wrong.
