### ISSUE TITLE
Chat render issue

### ISSUE THREAD

**Issue by dds12** [lay295/TwitchDownloader#15]
This worked perfect for me like 3 or 4 days ago. But now when i try to render chat from the json file, the program always crashes on rendering chat.

**Comment by lay295** [comment]
Are you sure you're using the newest version? There was a breaking change BTTV made to their API a few days ago which broke the program and it needed to be updated.

**Comment by Insayno** [comment]
I am also having this issue and am using the most recent version.

**Comment by Insayno** [comment]
It is even happening when I turn off BTTV emotes.

**Comment by lay295** [comment]
@Insayno are you perhaps using a 32bit version of Windows 10?

**Comment by Insayno** [comment]
No, 64bit.

**Comment by lay295** [comment]
It might have to do with a dependency I got rid of in the newest release. So you can give that a try and maybe it'll atleast spit out an error instead of crashing.

**Comment by Insayno** [comment]
Render completed, seems to be fixed.
