### ISSUE TITLE
Chat render crash

### ISSUE THREAD

**Issue by Read1337** [lay295/TwitchDownloader#150]
I'm having this issue where the twitch downloader crashes when it tries to render the chat.
No error appears, the app just closes.
I tried with a smaller json and it worked, maybe it's a problem with larger json files?

**Comment by lay295** [comment]
Redownload 1.39.4

**Comment by Read1337** [comment]
It works, I updated to the lasted version just yesterday never crossed my mind to redownload. Thanks
