### ISSUE TITLE
ERROR: Can't download chat

### ISSUE THREAD

**Issue by bagynalint17** [lay295/TwitchDownloader#151]
Hey! First of all thanks for making this. The last 2 days whenever i try to download a json file or render out a chat it says "ERROR: The remote server returned an error: (400) Bad Request.". I have the latest release downloaded.

**Comment by dobisan** [comment]
I have a very similar problem. I got 404 error messages when I want to render a chat video. Can download a chat but the chat render don't work. I tried a bunch of thing.

There was a profile picture (logo) of one of the users in the chat json. I changed that to another url. Wasn't a solution.

I figured I got the error when it's in the "fetching chat badges" phase so I edited the json and set all the badges to NULL. Wasn't a solution. 

Finally I tried with another VOD and it didn't work there as well. Maybe I had to start the whole process with that. :D

**Comment by lay295** [comment]
@bagynalint17 can you post the JSON you're trying to render?

@dobisan just update to 1.39.4

**Comment by bagynalint17** [comment]
> @bagynalint17 can you post the JSON you're trying to render?
> 
> @dobisan just update to 1.39.4

**Comment by bagynalint17** [comment]
> @bagynalint17 can you post the JSON you're trying to render?
> 
> @dobisan just update to 1.39.4
https://drive.google.com/file/d/1bsGheFVWh8O7iBYGbiCeE_5Woy_WHYlH/view?usp=sharing
it didn't allow me to post it so i uploaded it to drive

**Comment by lay295** [comment]
Did you manage to fix it yourself or did you close the issue on accident?
