### ISSUE TITLE
ERROR: Cannot deserialize the current JSON object

### ISSUE THREAD

**Issue by brawlpro** [lay295/TwitchDownloader#153]
I'm just trying to render the downloaded chat.

ERROR: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[Comment]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'emotes', line 2, position 11.
ERROR: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[Comment]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'emotes', line 2, position 11.

**Comment by lay295** [comment]
Can you upload the JSON somewhere and post it?

**Comment by MrBrax** [comment]
I'm getting the same thing but only because I'm trying to recreate the format manually. Would be nice if it somehow was more detailed in its error message.
