### ISSUE TITLE
ERROR: Videos at 1080p60 don't open

### ISSUE THREAD

**Issue by UmagaSamoa666** [lay295/TwitchDownloader#158]
They won't open, just shows a black screen in VLC, and their size is 3,99GB. A 720p one does it correctly tho.

**Comment by lay295** [comment]
Could you post the video you're trying to download? Also are you using any cropping options?

**Comment by UmagaSamoa666** [comment]
https://www.twitch.tv/videos/966414502 this one for example, but tried with a 2 hour one and it also happens. Tried cropping and not cropping and it's the same. I have the latest version

**Comment by lay295** [comment]
I'm inclined to believe it's an issue decoding the video on your end. I've downloaded that VOD and I could open it in VLC and MPCH just fine. Could you maybe upload a VOD you're unable to play somewhere and I can see if I can play it?
