### ISSUE TITLE
Can I convert JSON files into regular text that includes the timestamps?

### ISSUE THREAD

**Issue by AJBauer92** [lay295/TwitchDownloader#160]
I was on here asking if there's a way to have timestamps relative to the video's start as opposed to the time of day. Unfortunately, I have to use a different program to download chat logs because I require those timestamps. However, I _do_ use the Twitch chat renderer so I can include the chat in my videos.

Unfortunately, a Twitch VOD needed to be deleted. Someone tried to save the chatlogs for me but used this program instead of Rechat, making it borderline useless since the timestamps show the time of day and not the point of when the VOD starts. I need to be able to CTRL+F and find exact timestamps for my job, which I obviously cannot do.

However, I noticed when that the rendered Twitch chat feature shows the proper timestamps in the video. Is there a way to use the JSON file to transcribe the chat into text instead of video in a way that lets me see the timestamps?

**Comment by lay295** [comment]
Yeah been busy with school, added the relative timestamps to the text chat downloading options just now.

So, you have a JSON file and you want it to just be a regular chat log? There is a json property content_offset_seconds which does indicate how far from the beginning of the VOD it is. If this is just a one time thing, just post the json here and I can convert it for you. Or email it to admin@twitcharchives.com and I'll send the converted one back.

**Comment by AJBauer92** [comment]
Thank you very much for adding that feature. Here's the [JSON file](https://drive.google.com/file/d/1GKdiK5Sr7Eqh9P53Ux4rsgyC2aRrfw8Y/view).

**Comment by lay295** [comment]
[chat.txt](https://github.com/lay295/TwitchDownloader/files/6293120/chat.txt)

Here is the converted chat log

**Comment by AJBauer92** [comment]
Thank you very much!

**Comment by SingleTractor** [comment]
> 
> 
> [chat.txt](https://github.com/lay295/TwitchDownloader/files/6293120/chat.txt)
> 
> Here is the converted chat log

Is there a way that this can be done through the program? I'm interested in converting many json log files to simple text logs and haven't found a way to do it.

**Comment by ScrubN** [comment]
If you need to convert more json chats to txt you can now use the Chat Updater feature
