### ISSUE TITLE
chat wont open with Codec H264

### ISSUE THREAD

**Issue by FrostyJeff** [lay295/TwitchDownloader#165]
if i choose codec h264 when rendering the chat, the mp4 wont open

![image](https://user-images.githubusercontent.com/83232180/116107022-4fa15380-a6bb-11eb-9664-361cb065c611.png)
![image](https://user-images.githubusercontent.com/83232180/116107182-7b243e00-a6bb-11eb-9443-64a1565d635c.png)

**Comment by FrostyJeff** [comment]
i meant codec h265 sorry i made a mistake

**Comment by lay295** [comment]
I don't think Windows has a h265 codec built in, this isn't an issue with the program.

https://www.google.com/search?q=windows+h265+codec
