### ISSUE TITLE
[Suggestion or Question] Can I somehow ban keywords/emotes like I can in bttv or ffz?

### ISSUE THREAD

**Issue by Maj-ew** [lay295/TwitchDownloader#166]
If that's impossible right now you could add this feature if you want, it shouldn't be hard probably.

**Comment by fresc81** [comment]
As a temporary solution you might just want to search and replace the banned words in the JSON with a proper text editor like Notepad++.

**Comment by Maj-ew** [comment]
ow I get iitttttttt. Wow I thought about some config file in JSON but couldn't find it. I get it now you meant in downloaded chat JSON
