### ISSUE TITLE
Slow download speeds compared to Twitch Leecher

### ISSUE THREAD

**Issue by hapdrag** [lay295/TwitchDownloader#17]
Hey, I just started using this program and i thought it's gonna replace Twitch Leecher for me, but, Twitchdownloader's speeds are 60% slower than TwitchLeecher's.

In task manager, under the network tab, Twitch Leecher would always max out at 100%, however Twitchdownloader jumps up to 100% when started and then doesn't go above 30-40%.

I've experimented with "download threads" by putting in random values up to 100000, and it did get faster, but never broke beyond 40% of network usage.

Is there some sort of a limiter and can i disable it? I rather download vods in 10 minutes than in an hour.

Thanks.

Edit: Screenshots

Downloading with twitch leecher:
![Twitchleech](https://user-images.githubusercontent.com/61080539/74586518-3271ef00-4ff9-11ea-8ecb-ba7c8e3e47dc.png)

Downloading with twitch downloader:
![twitchdownload](https://user-images.githubusercontent.com/61080539/74586522-3d2c8400-4ff9-11ea-9f22-02912f8f33fd.png)

**Comment by hapdrag** [comment]
After 30 minutes started using all of the network usage. Possibly there was a problem with twitch servers.

**Comment by hapdrag** [comment]
Never mind, twitch leecher works fine while twitchdownloader's speeds are heavily throttled

**Comment by lay295** [comment]
Honestly I just made this program to do things TwitchLeecher couldn't and I just threw the vod downloader in there to try and be a complete toolkit. I'll give it a look to utalize more bandwidth when I have some free time. If you download a lot of videos I'd still recommend TwitchLeecher though as you can download a lot of videos more easily.

**Comment by hapdrag** [comment]
> Honestly I just made this program to do things TwitchLeecher couldn't and I just threw the vod downloader in there to try and be a complete toolkit. I'll give it a look to utalize more bandwidth when I have some free time. If you download a lot of videos I'd still recommend TwitchLeecher though as you can download a lot of videos more easily.

Well, you succeeded in that, the chat downloader is very good (except for black name problem). It would be handy if I would use this program for everything though, i currently use 3 different programs and this one is everything in one, no need to change paths everyone a billion different times, everything would go in the same folder at once and I can start editing straight away.

It's totally fine if you won't be able to fix this though, chat downloader alone is a huge saver at the moment.

**Comment by lay295** [comment]
I think I figured it out, with the newest version it downloads videos at the same speed as TwitchLeecher for me, give it a try whenever you have a chance.

**Comment by lay295** [comment]
Fixed in 1.21
