### ISSUE TITLE
What's Going On With The Chat

### ISSUE THREAD

**Issue by IndianBoy6** [lay295/TwitchDownloader#171]
Hi. I downloaded the chat and created an array based on the chat offset of the number of chats per second. I'm doing this with a popular streamer (tommyinnit) so there should always be chat, but the numbers are 0 for a lot of the time. ([data](https://pastebin.com/dM6cHD7i)) I don't think this is a problem with your code because I tried it myself and it did the same thing but I was just wondering if you had any ideas why this is happening.

**Comment by lay295** [comment]
Hmmm, would you mind sharing what VOD you made this array from? Or the JSON file. I see his chat does move pretty fast, so I can't think of a reason there would be such a large amount of 0s before the next message.

**Comment by lay295** [comment]
Assuming you're talking about [this one](https://www.twitch.tv/videos/989812870) I can't help but feel how you're calculating the array is incorrect somehow, or I'm misinterpreting what the array should represent.

![image](https://user-images.githubusercontent.com/1060681/117557585-5aa49e00-b042-11eb-8d73-7ca4cb86c63f.png)

My C# code just simply loops over every second of chat, counts how many messages occurred within that second, then adds that count to an array. I've manually verified with the VOD that the count matches what I expect. For exmaple, the beginning of my array looks like [0, 0, 0, 0, 0, 0, 4, 10] which has 4 messages during second 6, and 10 messages during second 7.

![image](https://user-images.githubusercontent.com/1060681/117557620-d7377c80-b042-11eb-8a89-4df2df3bb13b.png)

Maybe you're calculating how many chat messages per second different than me, but looking at your numbers compared to how fast his chat is actually is moving they seem really low. In mine there are gaps of 0's which looks to be about 3-4 seconds at most, but I think that's on Twitch's end.

**Comment by IndianBoy6** [comment]
Hmmm. So regardless, I wouldn't be able to fix the 0s completely?

**Comment by IndianBoy6** [comment]
Ok yeah I checked a few streams and It's pretty obvious that even Twitch can't determine the exact second of each message. There will be a second where there are no chats and then 100 chats the next second. I don't think there's anything I can do to get the exact time. If there is, feel free to reopen this and I might be able to to try to help to fix it.
