### ISSUE TITLE
The README should start with windows instructions for non technical users

### ISSUE THREAD

**Issue by mvoncken** [lay295/TwitchDownloader#172]
I want to help a friend, but just linking to your project would be confusing to him.

All he needs to know is how to download and install.
Please make the beginning of the readme a start page for non-technical users, Or make a separate start-page for non-technical users and link it from the readme

**Comment by ScrubN** [comment]
Comparing the readme from 2021 to now I assume it is noob-friendly enough in regards to how the GUI works? If not we can add another README for the GUI specifically and link to it just like we do the CLI README.

Honestly it's not such a bad idea, I might do that regardless as some users are confused by how certain settings or modes work.
