### ISSUE TITLE
JSON file requirements for chat render to work

### ISSUE THREAD

**Issue by OnlyTunesRadio** [lay295/TwitchDownloader#174]
Heyo,

We wanted to make a thing to pull chat live and convert into a json file for this to render however the sample json file provided is very out of date and doesnt contain half of the required parameters to actually render.

Just wondering what are the requirements in the json file for the chat render to work. Its mainly just the tags used for 'Name Badges' / 'Cheers' / 'Subs - Gifted Subs' and any other required parameters in the actual json file.

If your able to provide a new sample json file that would also be greatly appreciated.

**Comment by lay295** [comment]
Yeah the JSON file that's in the program is just for the render preview, it's not in the same format required to actually render the chat. 

If you just want a barebones example, you could just run the program and download the JSON for 10 seconds. For example, I downloaded 10 seconds in the middle of a sodapoppin vod and here is the output.

[[5-12-21] sodapoppin - poggers](https://github.com/lay295/TwitchDownloader/files/6481383/5-12-21.sodapoppin.-.poggers.www.sodapoppin.shop.Discount.code.POOR.txt)

There is a streamer object, video object, and emotes object (embedded emotes) that my program puts in the JSON, the comments array is in the format that is returned from Twitch.

![image](https://user-images.githubusercontent.com/1060681/118337917-da1eeb00-b4e2-11eb-9682-d0401ec7646f.png)

It's in a really weird format, and I can't really remember each and every property of the comment I use, but yeah. If you do some digging you can figure out the format. I have a live chat to JSON already but there are a few problems with it and it's public but it works pretty much. [Here](https://pastebin.com/swdm25PE) is part of it, specifically on line 247 GetComment it takes a raw IRC message and converts it into a compatible Comment object with the chat render.

**Comment by OnlyTunesRadio** [comment]
Ah thanks bud I will have a look through that code later. this will be a great help for this project and should help us progress this project further. Also thanks for responding so quickly.
