### ISSUE TITLE
Old settings are default and are applied on launch everytime

### ISSUE THREAD

**Issue by hengyu95** [lay295/TwitchDownloader#177]
Tried re-downloading the whole thing and deleting the temp folder in AppData.

I can't quite figure out where the default settings are being stored and would appreciate some insight!

**Comment by lay295** [comment]
Ahhh, didn't think that would be an issue when I made it so it restored from old settings after upgrading, I'll try and fix that later.

The settings should be in AppData/Local/Twitch DownloaderWPF

**Comment by hengyu95** [comment]
Thanks for the quick response! Deleting all those files and set my settings and now they seem to stay properly

**Comment by ScrubN** [comment]
Assuming this was fixed
