### ISSUE TITLE
404 error on clip download

### ISSUE THREAD

**Issue by toho00** [lay295/TwitchDownloader#178]

**Comment by tonizera** [comment]
Up bro

**Comment by lay295** [comment]
Whoops, I kinda ignored this issue this morning when I read it because I assumed you just didn't update the program. I see that's not the case and fixed it and should be in 1.39.7 which is being uploaded now.

**Comment by goldbattle** [comment]
Works for me in 1.39.7, I would try that to see if you still have the issues.
