### ISSUE TITLE
Feature Request: Fixed rate message rendering

### ISSUE THREAD

**Issue by ibex-are-goats** [lay295/TwitchDownloader#180]
I had an idea to used TCD to download only messages with the word "birthday", then render out a quick scroll of all those birthday wishes. But of course, they all have random time codes, and it makes for a long random video.

My feature request is a "fixed rate rendering" option that lets you set ".1" for example, and have every message come with .1 second between each.

Thanks for your great work, the app is excellent!

**Comment by lay295** [comment]
Ehhhh, this is too niche of a request I feel to be useful to many people, so I don't think I will be adding it. If this is just a one time thing though, if you just shoot me over the json I can modify it to render each message every .1 seconds.

**Comment by ibex-are-goats** [comment]
That's really nice of you! I'm happy to take you up on your offer. Maybe you'll like the result so much the feature will make sense ;) How should I send the json?

**Comment by ibex-are-goats** [comment]
> Ehhhh, this is too niche of a request I feel to be useful to many people, so I don't think I will be adding it. If this is just a one time thing though, if you just shoot me over the json I can modify it to render each message every .1 seconds.

I just clued in that I could pastebin it ;)
https://pastebin.com/BTs990qJ

**Comment by ibex-are-goats** [comment]
> Ehhhh, this is too niche of a request I feel to be useful to many people, so I don't think I will be adding it. If this is just a one time thing though, if you just shoot me over the json I can modify it to render each message every .1 seconds.

Okay, I managed to hack it together by taking screenshots of the TD video and attaching them together in Photoshop and then animating them in Premiere and then uploading it to Giphy. :D So you need not manually tweak the json for me anymore! That's one adventure squashed, I'm sorry lol ;) But below is the animation for you to see how it looks. Maybe this will be up your alley at some point!

https://giphy.com/gifs/6bxveM1ip1goq7o7Zz
