### ISSUE TITLE
Request to add 7TV, another third party emote service

### ISSUE THREAD

**Issue by 3Gigs** [lay295/TwitchDownloader#181]
Add support for [7tv](7tv.app), another third party emote service like BTTV or FFZ.

**Comment by goldbattle** [comment]
Information:
- website: https://7tv.app/
- github org: https://github.com/SevenTV
- github golang server: https://github.com/SevenTV/ServerGo/

GraphQL Endpoint:
- api schema: https://github.com/SevenTV/ServerGo/blob/master/src/server/api/v2/gql/scheme/scheme.gql
- graphql endpoint: https://api.7tv.app/v2/gql
- use this explorer: https://graphiql-online.com/

Discord FAQ
> Is there documentation for the API?
> Not at this time but there will be once more public-facing endpoints go live.


Didn't investigate that far to be honest.
