### ISSUE TITLE
[Suggestion] Unmute muted sections of vods

### ISSUE THREAD

**Issue by JunkiEDM** [lay295/TwitchDownloader#182]
Since this could be used for archiving vods for reupload in the midst of dmca claims on Twitch, it would be nice to have a toggle to download unmuted vod streams.  

This can be done by replacing 
`.../index-muted-XXXXXXXXXX.m3u8` with `.../index-dvr.m3u8` at the end of the playlist url for the vod.  

I'm not sure if theres a way to get timestamps of the muted parts but that could be an idea to log too.

**Comment by Zibbp** [comment]
I didn't know this could be done so I decided to try it out and ran into a problem. When downloading a vod using the unmuted index-dvr.m3u8 playlist some parts of the, I'm assuming muted parts, are cut out of the index-dvr version resulting in the duration being shorter than the muted index-muted version. Have you ran into this issue?

**Comment by JunkiEDM** [comment]
Yeah just tried it again and looks like you're right, they must have fixed that out of fear that people could dmca deleted or muted vods since I remember doing it a while ago with no issues. It is returning a 403 instead of a 404 so there could be a loophole somewhere but until then I'm sorry for throwing you for a loop, I should've checked if it still worked before suggesting it.

**Comment by lay295** [comment]
They delete the unmuted segments after a day or so if I remember right. So soon after the vod is muted this suggestion could probably work.
