### ISSUE TITLE
The remote server returned an error: (504) Gateway Timeout.

### ISSUE THREAD

**Issue by Nutri626** [lay295/TwitchDownloader#183]
when im trying to download chat sometimes it goes to 10 % sometimes 50 % and then it says ERROR: The remote server returned an error: (504) Gateway Timeout.

p.s
it works fine if its shorter but if its 1+ hours then im getting that error and yes i tried with old and newer versions

**Comment by Nutri626** [comment]
well i guess i was wrong, it still happens time to time, never happened before ....

**Comment by lay295** [comment]
504 basically means it's on Twitch's end. I guess I should be using some simply retry logic on failure because it looks like I don't. Is there a VOD that I can try that it's happening a lot on?

**Comment by Nutri626** [comment]
> 504 basically means it's on Twitch's end. I guess I should be using some simply retry logic on failure because it looks like I don't. Is there a VOD that I can try that it's happening a lot on?

yeah currently im trying with this vod 1046795201

**Comment by lay295** [comment]
Yeah downloading that forsen VOD I was getting about 8 errors before it would complete. I added some retry logic on a network request failure and I was able to download the chat fine. Give 1.39.8 a try.

**Comment by Nutri626** [comment]
> Yeah downloading that forsen VOD I was getting about 8 errors before it would complete. I added some retry logic on a network request failure and I was able to download the chat fine. Give 1.39.8 a try.

yeah it works fine now, thanks, really appreciate fast solution & update
