### ISSUE TITLE
504 Error on chat download with new release

### ISSUE THREAD

**Issue by ethanbreck** [lay295/TwitchDownloader#184]
I downloaded the GUI under the new release, (the one released 14 hours as of writing), and the 504 error for downloading chat is still happening. I am trying to download as simple text, and relative timestamps. Here is the video I'm trying to download: https://www.twitch.tv/videos/1047430328

**
![image](https://user-images.githubusercontent.com/6488051/120926999-1d105080-c694-11eb-8ac1-b782632c5883.png)
**

**Comment by lay295** [comment]
I'm currently unable to reproduce it, perhaps it was just a blip on Twitch's servers? They certainly changed something and made their servers error out more. In the new update if it still 504 timeouts then it tried 10 times on the same web request and they all failed.

So, hopefully Twitch will fix it eventually. In the meantime I can only recommend to just try again.
