### ISSUE TITLE
[ENHANCEMENT] Request to add timestamp to chat by default

### ISSUE THREAD

**Issue by MycroftHolmes1989** [lay295/TwitchDownloader#185]
Currently, there are no timestamps in the downloaded chat. It would be helpful if there was a way to add the timestamps to the chat.
The format could be like `[HH:MM:SS]MessageSenderName: Message`.

**Comment by lay295** [comment]
For chat download? Or chat render? There are options in both for timestamps, please clarify.

**Comment by MycroftHolmes1989** [comment]
Chat Download

**Comment by MycroftHolmes1989** [comment]
Checked the Documentation. There seems to be --timestamp-format. Sorry.

**Comment by MycroftHolmes1989** [comment]
I would request to change the default timestamp option from none to relative.

**Comment by MycroftHolmes1989** [comment]
Also, I used `TwitchDownloaderCLI -m ChatDownload --id $1 --timestamp-format Relative -o $1.txt` where $1 is the id of the video, and the timestamps are not downloaded. Could you please tell me what I am doing wrong?

**Comment by lay295** [comment]
Yeah that seems like a more sensible default rather than none. It'll be in the next release.
