### ISSUE TITLE
[BUG] Timestamp not working in ChatDownload

### ISSUE THREAD

**Issue by MycroftHolmes1989** [lay295/TwitchDownloader#187]
This is on Linux CLI version.
Executing `TwitchDownloaderCLI -m ChatDownload --id $streamid --timestamp-format Utc -o chat.txt` does not pull the timestamps. It does not work with Relative timestamp either.

**Comment by lay295** [comment]
I'm unable to reproduce this, both "Relative" and "Utc" as timestamp formats are working for me on my Ubuntu VM. Copy/pasting the command you gave me also worked with Utc by just replacing the $streamid with a streamid.

![image](https://user-images.githubusercontent.com/1060681/121120580-da618c00-c7eb-11eb-9ec4-924efc94c6d6.png)
![image](https://user-images.githubusercontent.com/1060681/121120603-e2213080-c7eb-11eb-95d6-89498385b3e9.png)

**Comment by MycroftHolmes1989** [comment]
Oddly enough, this is what I get. 
![Screenshot from 2021-06-08 16-56-28](https://user-images.githubusercontent.com/29265539/121177019-8782e580-c87a-11eb-9c10-bbae580defdc.png)

**Comment by lay295** [comment]
Are you on the newest version? The timestamp format was added very recently in 1.39.5.

Also if you're on Arch and installed that AUR package I don't maintain that and it's on an older version it looks like.

If it's neither of those what OS is it so I can try and reproduce it.

**Comment by MycroftHolmes1989** [comment]
Solved with latest version. I was using AUR version.
