### ISSUE TITLE
 Problem with "highlighted-message" in Chat Render

### ISSUE THREAD

**Issue by Tiranno** [lay295/TwitchDownloader#19]
First of all hello and thank you very much for your fantastic program.

I found out TwitchDownloader for a few days and I found it immediately fantastic but I encountered a problem in the Chat Render, the function that interests me most.

Checking the video renders that I made I realized that the highlighted messages were not shown.

Checking the downloaded JSON file (with not a few problems since notepad opens the file on a single line, very inconvenient to check. Tips?) I found the messages that are not shown in the videos made with the Chat Render.
The highlighted messages are present in the JSON file and have the following string: {"msg-id": "highlighted-message"}.

But when I create the video all the highlighted messages are not shown, as if they didn't exist.
The generated video does not have holes in the presence of the highlighted messages, it has all the messages below skipping the highlighted ones.

Example of message not shown in the video:
{"_id":"86b490d6-0f5b-407d-8a96-a4cad98bff76","created_at":"2020-02-28T18:04:06.53Z","updated_at":"2020-02-28T18:04:06.53Z","channel_id":"452387754","content_type":"video","content_id":"559233388","content_offset_seconds":43.83,"commenter":{"display_name":"il_mago","_id":"478768988","name":"il_mago","type":"user","bio":null,"created_at":"2019-12-19T20:50:46.200116Z","updated_at":"2020-02-28T17:58:44.09117Z","logo":"https://static-cdn.jtvnw.net/user-default-pictures-uv/de130ab0-def7-11e9-b668-784f43822e80-profile_image-300x300.png"},"source":"chat","state":"published","message":{"body":" MESSAGE EDIT iltronGRR iltronGRR iltronGRR","emoticons":[{"_id":"301377886","begin":215,"end":223},{"_id":"301377886","begin":225,"end":233},{"_id":"301377886","begin":235,"end":243}],"fragments":[{"text":"MESSAGE EDIT"},{"text":"ltronGRR ","emoticon":{"emoticon_id":"301377886","emoticon_set_id":""}},{"text":"i"},{"text":"ltronGRR ","emoticon":{"emoticon_id":"301377886","emoticon_set_id":""}},{"text":"iltronGRR"}],"is_action": false,"user_badges":[{"_id":"subscriber","version":"0"}],"user_notice_params":{"msg-id":"highlighted-message"}}},

Did I only encounter this problem? Solutions?
Thanks so much

**Comment by lay295** [comment]
Yeah a few things don't show up, new sub notifications, bits, highlighted messages, and colored /me and I'm sure a few others. I just mainly haven't gotten around to adding them yet.

The question is whether I should actually highlight the messages in my program or just print them like normal, and I don't really know of a way to highlight them without making them look ugly. (I think the way twitch shows them is pretty ugly). So, i'll make them visible in the next release as a normal message.

Also the JSON is minified to save on file space, for larger chat downloads. You can use online tooks like JSON pretty print or JSON parsing tools online to view the data better.

**Comment by Tiranno** [comment]
Checking myself better I realized that no other notifications and donations are shown, but from my point of view they are less important than chat messages.

Those who search and use your program most likely do so to save the chat of those streamers who do not already include it in their videos, and therefore want to save the interactions between the streamer and the chat. For example, talk shows and question times.

The highlighted messages often represent a large percentage of those interactions and the fact of not being shown greatly limits the overall usefulness of the Chat Render. In fact, approaching your program for the first time, I considered it a bug of the Chat Render since the messages not shown were still present in the JSON file downloaded with the Chat Downloader.

In my opinion, for the moment it would be perfect if they were printed anyway in order to have complete interactions between chat and streamer. Then if in the future you will be able to highlight them in a pleasant way so much better, but the highlighted messages are more "important" during the live and are generally aimed at the streamer so in a future recording it is not important if that message appears highlighted or not, but it is important that it is present.

Thanks for the advice on the JSON file.

Thanks also for the quick reply and congratulations for the excellent work done so far.

**Comment by lay295** [comment]
Well like 2 months later and it's added. Anyways messages should show up now in the newest release along with animated bits. Feel free to re-open if something is amiss.
