### ISSUE TITLE
CLI File Format and Codec

### ISSUE THREAD

**Issue by cyperdark** [lay295/TwitchDownloader#198]
So how to add these https://i.imgur.com/9FLaek3.jpeg parameters in CLI?

**Comment by lay295** [comment]
You would have to manually set the output-args parameter in the CLI.

The codecs are just hard coded in the GUI version [here](https://github.com/lay295/TwitchDownloader/blob/e5f551afa77735d1694b630a987717450fe1be9c/TwitchDownloaderWPF/PageChatRender.xaml.cs#L325)

So for example one for RLE would be this and it should work.
TwitchDownloaderCLI -m ChatRender -i chat.json --output-args='-c:v qtrle -pix_fmt argb "{save_path}"' -o chat.mov

**Comment by cyperdark** [comment]
i tried but got that error https://i.imgur.com/1ir6x99.jpeg
https://i.imgur.com/UWFBWT5.jpeg

**Comment by lay295** [comment]
I can't really tell what's going on without the full python code, it may have something to do with no quotes around the input file and output file?

If you could just show the output failing on a regular Windows cmd or the terminal of whatever operating system you're running, it would be easier to tell what's wrong.

**Comment by cyperdark** [comment]
https://cyperdark.s-ul.eu/54vAke7M

**Comment by cyperdark** [comment]
any updates?

**Comment by lay295** [comment]
I setup a similar python program to yours and changing the output args from
--output-args='-c:v qtrle -pix_fmt argb "{save_path}'"
to 
--output-args="-c:v qtrle -pix_fmt argb "{save_path}""

Works for me. I don't parse the command line arguments myself I use [a library](https://github.com/commandlineparser/commandline) for it so I'm not entirely sure how it works. Next time I'll probably just parse the arguments myself.

**Comment by cyperdark** [comment]
sorry for the wait
1. I rewrote the program from scratch, and now it works, I think I was mistaken in the writing of the arguments
but then i got this error
![pwsh_fslQm4kt6f](https://user-images.githubusercontent.com/21735205/131306192-3e4bb477-66a0-4123-8fce-a0aed888df1c.jpg)

test folder: https://drive.google.com/uc?id=1bL6TI9zyuCNV8ggwqYOpJn3iNCwWaMLq
Command:
```sh
.\TwitchDownloaderCLI.exe -m ChatRender -i "1133785110.json" --output-args="-c:v qtrle -pix_fmt argb '{save_path}'" -o "1133785110_chat.mp4"```

it's CLI bug or im doing smth wrong?

**Comment by cyperdark** [comment]
nvm i forgot to change .mp4 to .mov, now it works fine
