### ISSUE TITLE
Make the #000000 hue of black lighter

### ISSUE THREAD

**Issue by MiracleBlessing** [lay295/TwitchDownloader#2]
As someone who has a completely black name on Twitch, it bugs me when I download the logs and can barely read it on the dark background. I'd like you to make it similar to BTTV's. I've included two screenshots: the one with BTTV's colors and the one with vanilla colors.
https://i.imgur.com/qVuFNop.png
https://i.imgur.com/jndqqa5.png

**Comment by lay295** [comment]
I've seen the issue before but didn't really know how to fix it tbh. I've made a fix which works well enough I feel but haven't put a release out yet. In a day or 2 I'll put a release out with the fix and can lemme know if it works for you.

Pure black names look like this now with the default background.
![image](https://user-images.githubusercontent.com/1060681/67630567-05d67380-f860-11e9-8874-21a754f02ea5.png)

**Comment by lay295** [comment]
I've added the changes in the latest release. Feel free to reopen this issue if there are still problems with it or it doesn't behave as expected.
