### ISSUE TITLE
Clip Batch Downloading and chat rendering automation?

### ISSUE THREAD

**Issue by argash** [lay295/TwitchDownloader#200]
I know this is a huge ask but would it be possible to add the ability on the clip downloader to specify a channel and a date range to grab all clips in the range. Additionally add a check box to automatically download/render the companion chat and name that file to match the clip at the same time. 

This would automate a huge time sink for highlight editors everywhere!

**Comment by roythegans** [comment]
That would be a huge help indeed! I like this idea.

**Comment by lay295** [comment]
You can give 1.40 a shot
https://i.imgur.com/JXIlkVK.gif

Just make sure in your naming template in the settings the chat format is different than the VOD/Clip format, or the chat will overwrite the video since it has the same name.
