### ISSUE TITLE
Chat Downloader significantly slower than VOD Downloader

### ISSUE THREAD

**Issue by hengyu95** [lay295/TwitchDownloader#202]
Downloading the chat .json has always been significantly slower than the VOD Downloader. Checking my Resource Monitor I find that the VOD downloading is literally ~500x faster in terms of speed and maybe about 5x slower to download to completion. 

Might there be a reason why this is the case? Would it also be possible to implement multiple download threads for the chat downloader?

**Comment by lay295** [comment]
I answered it [here](https://github.com/lay295/TwitchDownloader/issues/163#issuecomment-822042465), but I have to make the web requests in sequential order for the most part which limits speed. I can speed it up by having different download threads start downloading at different times spread throughout the VOD until it reaches the starting point of another thread, then stitch the result together at the end.

So it's definitely possible, just not a huge priority for me as it'll add a bit of complexity and I feel the chat downloads fast enough for me. But if it is 5x slower than the VOD I should probably give it a shot eventually.
