### ISSUE TITLE
ERROR: Unable to find thumbnail ERROR: One or more errors occurred.

### ISSUE THREAD

**Issue by shyvyivy** [lay295/TwitchDownloader#205]
When I find info on a link or a video it always return as  ERROR: Unable to find thumbnail
ERROR: One or more errors occurred.

**Comment by shyvyivy** [comment]
![issue](https://user-images.githubusercontent.com/88387394/128027118-98a0b20e-8d0e-4026-9536-092ee332a2f4.PNG)

**Comment by ScrubN** [comment]
This has probably been fixed
