### ISSUE TITLE
Wrong /tmp folder permissions on Linux? (775, should be 777 or 1777?)

### ISSUE THREAD

**Issue by suvis1** [lay295/TwitchDownloader#206]
When creating a ChatRender on Linux with the CLI tool, it creates a TwitchDownloader folder on the /tmp directory. That folder has the permissions of drwxrwxr-x.

The problem is that no other user can use ChatRender since they cant write into that folder, and the /tmp directory doesnt get cleared after the program exits.  This leads to usage of ChatRender being "locked" to the first user that creates the /tmp directories, unless they are manually deleted or changed permissions to 777.

`
Unhandled exception. System.AggregateException: One or more errors occurred. (Access to the path'/tmp/TwitchDownloader/Chat Render/353f8c11-35ea-4a76-8310-0e8de146652e' is denied`

**Comment by ScrubN** [comment]
The renderer has since been rewritten and no longer renders to a predefined temp folder.
