### ISSUE TITLE
Error When Rendering Chat

### ISSUE THREAD

**Issue by yo-mama-yo-papa** [lay295/TwitchDownloader#208]
Hi, I'm having an issue where every time I try to use the chat render feature, it produces the error "The pipe has been ended." I've tried reinstalling, restarting my computer, running the application in administrator mode, and searching for any solutions but have hit a dead end. Please help with this issue thanks.
![image](https://user-images.githubusercontent.com/81585948/128654689-6498fb39-a41e-4920-9960-c9628631dd45.png)

**Comment by lay295** [comment]
It means ffmpeg is erroring out, this shouldn't happen with the default arguments unless you've edited them. Could you copy/paste your ffmpeg arguments?

**Comment by yo-mama-yo-papa** [comment]
I downloaded version 1.39.19 and it seemed to fix the issues. I was also having constant crashes with the newest build but I must've messed something like you said.
