### ISSUE TITLE
I can't render any chats

### ISSUE THREAD

**Issue by dozzzz02** [lay295/TwitchDownloader#21]
Unable to fetch emote xqcK_HE(ID:301361407_HE)
ERROR: De pipe is beëindigd.

ERROR: De pipe is beëindigd.

ERROR: De pipe is beëindigd.

As you can see, I've tried 3 times. This is what I'm trying to render.

[123.zip](https://github.com/lay295/TwitchDownloader/files/4356928/123.zip)

**Comment by lay295** [comment]
Strange, am able to render that myself. Could be a few things, the error handling reporting in the program is pretty lacking.

Are you sure ffmpeg.exe is in the same directory as TwitchDownloader.exe? Also have you changed any command line arguments in the options for the chat rendering?

If no to both, try this version and it should print a lot more to the error log and post the results here.

https://drive.google.com/open?id=15aKnPF5HzurwwK6vIC_qU49SqMyDJVWq

**Comment by dozzzz02** [comment]
@lay295 The problem was the window size. Since I fullscreen I set the window height to 1079. It worked when I set it to 900.
