### ISSUE TITLE
Will it be possible to unmute muted sections that were muted a while ago of VODs?

### ISSUE THREAD

**Issue by George620** [lay295/TwitchDownloader#210]
Some video was muted 8 hours ago at the time of writing this. It's possible to unmute it with some sort of tool or not?

**Comment by CactusPuppy** [comment]
As far as I know, it is not possible. Twitch mutes the audio for a reason (DMCA), and any method for unmuting would mean that the mute was entirely pointless.

**Comment by George620** [comment]
Ok, but the video and many others are falsely claimed and Twitch's doing nothing for years, so that's why I'm asking. It will be cool to bypass this crap.

**Comment by CactusPuppy** [comment]
Any tools to bypass mutes on falsely flagged content are tools which bypass mutes on actual DMCA content, and record labels will gladly incorporate those tools into their DMCA scanners to find DMCA violations, thus making the original mute entirely pointless.

Unfortunately, unmute functionality is not possible in any 3rd party tool, and it looks to remain that way for the foreseeable future.

**Comment by lay295** [comment]
It might have been possible to recover the unmuted segments, but the window isn't very long. I haven't really bothered to check exactly how long, but it's less than 24 hours. 

I checked on a VOD that was muted 6 hours ago as when I'm posting then, and removing the -muted at the end of the .ts segment still gives me the unmuted version. It'll soon be deleted by Twitch though, I don't know why it takes them so long, maybe they delay the unmuted segment deletion, or maybe it takes a while for the deletion to propagate through their CDN. I could probably make TwitchDownloader check if there is an unmuted segment when it encounters a muted segment, it might help some people but again the window doesn't last very long.

**Comment by George620** [comment]
I would be happy to unmute at least 2 hours after the stream ends, so hope you implement it, so I don't need to preventively download it before. You never know when the sound will be muted or not in this case :/

**Comment by lay295** [comment]
I added trying to unmute the VOD if it's less than 24 hours old in 1.40. Give it a try sometime.

**Comment by lay295** [comment]
Yeah it's just automatic, I haven't tested it too much but it worked for me on a few Forsen and Ludwig VODs that were muted. The program checks how old the VOD is from the time the stream ended, it doesn't include the length of the stream. So if a 24 hour VOD just ended by program would see it as 0 hours old.

**Comment by lay295** [comment]
> Today I tried the muted video after done livestreaming for 7 hours; 3 hours 10m ago from posting this. I tried to download it but it wasn't unmuted. "Hope" I catch one later. The Twitch muting system sucks because it's far from perfect. In this video it was even worse. The "mutable part" is unmuted and Twitch is like: "Yeah let's mute the 3 minutes after that xd". Will be cool if someone can literally "drain" the audio from all done new VODs after the streamer go offline and keep them in his storage for at least 24 hours, in case they got muted. But that can be impossible. :/

If your computer is on 24/7 you can give my desktop archiver program a try. I don't really have a way to delete older VODs though after like 24 hours.
https://github.com/lay295/TwitchArchiverWPF

You can just add the streamer and select "Download VOD Broadcast" and it'll download the VOD as it's being recorded. 

As for being unable to unmute around 7 hours, it sucks but nothing I can really do unfortunately.

**Comment by George620** [comment]
So finally I catch a muted VOD. I downloaded it right after it was muted and it worked 99%, but one 10s chunk was still muted (I think this is Twitch's problem). So for me is still better to download VOD before it was muted (which I did with this one too), but it's good to implement the unmuting feature either way, even when unmuting doesn't work on some chunks.
