### ISSUE TITLE
Chat flickering when using Mask

### ISSUE THREAD

**Issue by BigBossFTW** [lay295/TwitchDownloader#211]
i did the tutorial on how to do the mask in Vegas, did the same in the video and was transparent, but the chat keeps flickering white
![nymn gif](https://user-images.githubusercontent.com/89302183/130320807-b7e246ed-607c-4877-9cea-bb475dc5dc37.gif)

**Comment by lay295** [comment]
Same issue as #74 and dfg555 posted a possible solution [here](https://github.com/lay295/TwitchDownloader/issues/74#issuecomment-878184001)

This is not a problem with TwitchDownloader, it's some problem with Vegas that I won't really be able to help you with.

**Comment by BigBossFTW** [comment]
> Same issue as #74 and dfg555 posted a possible solution [here

**Comment by BigBossFTW** [comment]
oh that worked, thank you :)
