### ISSUE TITLE
Render Chat Error "The specified executable is not a valid application for this operating system platform

### ISSUE THREAD

**Issue by Rainer3232** [lay295/TwitchDownloader#215]
When rendering the chat I get an error: "The specified executable is not a valid application for this operating system platform."
I have a 32-bit operating system and Windows 7 is that?
Because I really have no idea

**Comment by Rainer3232** [comment]
When rendering the chat I get an error: "The specified executable is not a valid application for this operating system platform."
I have a 32-bit operating system and Windows 7 is that?
Because I really have no idea

**Comment by AltTabris** [comment]
This is from the ffmpeg.exe that is in with the release. You can replace the ffmpeg with a 32 bit version to work around that message.

**Comment by Rainer3232** [comment]
> This is from the ffmpeg.exe that is in with the release. You can replace the ffmpeg with a 32 bit version to work around that message.

Can you give me a link where I can download the 32-bit file?

**Comment by lay295** [comment]
Sorry to say, but windows builds are likely going to be 64-bit only in the future. When rendering multiple chats I ran into a 4GB limit of 32-bit builds a few times.

![image](https://user-images.githubusercontent.com/1060681/134281924-43a54f63-3e8b-42b5-841b-1579a737171a.png)

As I'm adding queueing, and people might queue up a lot of VODs/Clips to be rendered at the same time, this issue has come up. Looking at the Steam hardware survey, about 0.13% of Windows users use a 32-bit OS.

![image](https://user-images.githubusercontent.com/1060681/134282107-726d14c7-0f9a-4b5a-ae4d-7707f068c2cc.png)

I'm kinda surprised Windows 10 has a 32-bit build, or that people are still putting out 32-bit ffmpeg builds. But I don't think I will support 32-bit on the windows GUI in the future.
