### ISSUE TITLE
Chat render doesn't display Highlighted Messages

### ISSUE THREAD

**Issue by excuses** [lay295/TwitchDownloader#216]
When someone uses channel points to highlight a message, even if it appears in the json file, it does not get rendered out in the video. Comparing it to normal messages, my guess is because message.fragments is null on these, and I assume it's grabbing the text from message.fragments.text.
message.user_notice_params['msg-id'] is "highlighted-message" on these messages, so a case could be added use the text from message.body, as both that and message.emoticons still exist.

`{
    "_id": "0",
    "created_at": "2021-08-21T05:03:00.9Z",
    "updated_at": "2021-08-21T05:03:00.9Z",
    "channel_id": "0",
    "content_type": "video",
    "content_id": "0",
    "content_offset_seconds": 0,
    "commenter": {
        // snip
    },
    "source": "chat",
    "state": "published",
    "message": {
        "body": "CurseLit CurseLit CurseLit test",
        "bits_spent": 0,
        "fragments": null,
        "is_action": false,
        "user_badges": null,
        "user_color": "#FF69B4",
        "user_notice_params": { "msg-id": "highlighted-message" },
        "emoticons": [
            { "_id": "116625", "begin": 0, "end": 7 },
            { "_id": "116625", "begin": 9, "end": 16 },
            { "_id": "116625", "begin": 18, "end": 25 }
        ]
    },
    "more_replies": false
},`

While actually highlighting these would be nice, even just displaying the chat message is better than nothing in the meantime!

**Comment by lay295** [comment]
Oh, I guess Twitch changed the response data at some point. Looking at the original issue of highlighted messages #19 it shows that highlighted messages fragments weren't null.

I'm working on a few things before I release the next version but this will be fixed by the next version, thanks for the report :)

**Comment by excuses** [comment]
No problem! fragments being null definitely made it look like an issue on Twitch's end but I don't expect THEM to fix it lmao

**Comment by goldbattle** [comment]
Need to check if this is still a problem in 1.51.1.

**Comment by ScrubN** [comment]
Not a problem as of master.
