### ISSUE TITLE
Rendering chat "Error: Index was out of range."

### ISSUE THREAD

**Issue by yuemangetsu** [lay295/TwitchDownloader#221]
Every time I try to render a chat I get the same error message:

"Index was out of range. Must be non-negative and less than the size of the collection parameter name:index"

I haven't changed anything in the config, I have just downloaded a chat in json and tried to render it, both with the default configuration.

I've been searching, but haven't found anyone with this same error using "Twich Downloader".

JSON file as it was created: https://mega.nz/file/0xAUzJwS#4ZT9RG3GO2fNJM1Xkge0WU1FNe5hwH4wxysKCtym2UA

**Comment by lay295** [comment]
Is this on version 1.40 or 1.39?

**Comment by yuemangetsu** [comment]
Version 1.40, I downloaded the latest version, but I just realized that it says that it is a pre-realease. Maybe that's why.

**Comment by yuemangetsu** [comment]
I have tried version 1.39 and everything has been perfect. That was why, I'm sorry for the inconvenience.

**Comment by lay295** [comment]
Yeah the pre-releases usually contain some bugs, I release them and wait and see if people report bugs before I put it as a normal release. I'm away for a few days but I will fix it eventually so thanks for the report.
