### ISSUE TITLE
Cheermotes aren't being fetched

### ISSUE THREAD

**Issue by sunkhaskasis** [lay295/TwitchDownloader#222]
It appears that the bit emotes/cheermotes aren't being fetched. This applies to both the global ones and the user-specific ones. The final render either ends up being the lowest cheer (a.k.a cheer1 instead of cheer100) or doesn't work at all, resulting in plain text.

Example 1, of the user-specific cheermote:
![image](https://user-images.githubusercontent.com/19194315/134749303-13370bbf-f811-4ebe-9f3a-bbd8fb3487d3.png)
The actual emote should be this (ninjaCheer100): ![image](https://d3aqoihi2n8ty8.cloudfront.net/partner-actions/19571641/b3d48b7c-c04d-40ac-8974-bdf876ac246c/100/light/animated/2.gif)

Example 2, of the global cheermote:
![image](https://user-images.githubusercontent.com/19194315/134749425-4538f33a-f5d9-497e-99a7-97966263aaf5.png)
The actual emote should be this (cheer100): ![image](https://d3aqoihi2n8ty8.cloudfront.net/actions/cheer/dark/animated/100/2.gif)

You can use these two jsons as a test:
https://www.dropbox.com/s/q9n1qhv2nxycvix/user.json?dl=1
https://www.dropbox.com/s/qamor0qwi72jfvn/global.json?dl=1

**Comment by lay295** [comment]
Should be fixed in 1.40.2, thanks for the report!
![image](https://user-images.githubusercontent.com/1060681/135959783-ca8505b6-5181-4fd7-a636-8f089e26f4cb.png)
![image](https://user-images.githubusercontent.com/1060681/135959791-c4a542bb-18c7-49f9-bb66-fcd3ba2290a0.png)
