### ISSUE TITLE
Documentation for CLI transparency background color

### ISSUE THREAD

**Issue by gvquach** [lay295/TwitchDownloader#226]
Is there a step-by-step tutorial on how to make the chat background transparent using the CLI? Would be helpful for the steps to be documented. Having a hard time figuring out how to do so.

**Comment by lay295** [comment]
Yeah it's not too straightforward admittedly.  In the GUI version there is a dropdown of codecs that you can select from, I probably should make an enum of codecs so people don't have to mess with input/output args.

https://github.com/lay295/TwitchDownloader/blob/798f0dc97f90417b003189f611c71f8599958b5b/TwitchDownloaderWPF/PageChatRender.xaml.cs#L335

But, it really depends what kind of transparency you want. For codecs that support an alpha channel, just change the input/ouput args to that codec, use --background-color "#00000000", and it should work.

If you want a transparency mask with a codec like H264 that doesn't support an alpha channel, use --generate-mask with --background-color "#00000000" and you should have 2 files, one of them being a transparency mask.

**Comment by gvquach** [comment]
Thanks for the help, it works. What would I do once I have the 2 files, the transparency mask mp4 and the regular chat mp4.

**Comment by lay295** [comment]
If you use Adobe Premiere or Sony Vegas you can watch [this](https://www.youtube.com/watch?v=D-_TD1-w3fY) and I'm sure you can do it in other video editors I'm not sure how though.

**Comment by gvquach** [comment]
Is there anyway to do this in the command-line instead with ffmpeg?

**Comment by lay295** [comment]
What would you like to do with the chat? Overlay it on top of another video such as a VOD/Clip?

**Comment by gvquach** [comment]
Yes, is it possible to create the chat with a white font/ visible emotes with a transparent background using ffmpeg?

Like this: 
![image](https://user-images.githubusercontent.com/44882665/135778562-b7c14d56-8790-42bd-a632-86d45bee6314.png)

Afterwards, I would take that chat and just separately overlay the chat onto a clip with Moviepy.

**Comment by lay295** [comment]
You can overlay the 2 files over another video with ffmpeg
https://github.com/lay295/TwitchDownloader/issues/79#issuecomment-699648513

If you're trying to combine the 2 files into a single chat file, it kind of defeats the purpose of the transparency mask and you should just export it in a codec that supports an alpha channel.

For example, a common codec and container is .mp4 with an h264 codec. Each pixel value only stores R,G,B values, and it cannot store an alpha channel (transparency information). To get around this, we store the RGB values in 1 file, and transparency values in another file called a mask. You could just export it to ProRes or something right off of the bat if you want 1 chat file.

**Comment by gvquach** [comment]
Gotcha, thanks for the help
