### ISSUE TITLE
[Feature] Add cache for badges

### ISSUE THREAD

**Issue by sunkhaskasis** [lay295/TwitchDownloader#228]
I believe having badge images stored in the temp cache folder, just like the third party emotes, emojis and bits, could significantly reduce the time needed to fetch them. Right now, it takes about 5 to 8 seconds to fetch the global + user badges, but if there was a folder with the images, would it reduce the time to about 3-4 seconds?

Edit: I just realized that it probably wouldn't work for the streamer sub badges. They all have the name "Subscriber (X Tier)", meaning every time a chat file from a different streamer is rendered, the images would overwrite themselves.

**Comment by goldbattle** [comment]
Right now twitch badges are cached. There is also now an `--offline` mode which doesn't download anything and just loads the data from the json file.
