### ISSUE TITLE
BTTV channel emotes don't work

### ISSUE THREAD

**Issue by wierdchamp** [lay295/TwitchDownloader#23]
Program doesn't render BTTV personal emotes/ emotes uploaded by channel owner

**Comment by lay295** [comment]
Could you give me a channel and emote name with such an emote?

**Comment by wierdchamp** [comment]
For example NymN  Dogege https://betterttv.com/emotes/5e74af5a8c0f5c3723a98944

It doesn't render for me

**Comment by lay295** [comment]
Should work now in the newest release 

![image](https://user-images.githubusercontent.com/1060681/79739069-a8c9f080-82cb-11ea-893b-ec78c83a1245.png)

Thanks for the bug report :)

**Comment by wierdchamp** [comment]
Thank you. That was quick. I love your program, it's a game changer
