### ISSUE TITLE
Instant crash using queue

### ISSUE THREAD

**Issue by xaolin** [lay295/TwitchDownloader#230]
Hey,

I'm trying to use the new queue feature from the VOD and clips tabs but I can't, it instantly crashes when I want to start the process with no error message. It just closes.

I tried the mass clips downloader and that one works somehow.

Also, huge thanks for bringing feature. Got me really excited. Was waiting for it for so long :D

**Comment by lay295** [comment]
Not really sure why it would crash. Does it crash when you try and download a VOD only? Or when you try and download chat + render it?

**Comment by agenttud** [comment]
It also crashes for me when I try to queue up anything (VOD or chat). I don't know what I can do about it, since I also don't get an error message (it simply quits).
