### ISSUE TITLE
(Chat Render) Change size of the text and emotes separately.

### ISSUE THREAD

**Issue by MonkeSmart** [lay295/TwitchDownloader#231]
Good day, first of all, thank you, great program. Thing is, now, it is only possible to render a small (normal) size text with normal size emotes, but, if you, say, want to make text bigger (for mobile use readability), emotes will become huge, with visible low quality. You can see this if you will set text size to 22, which is readable on mobile, some emotes even start to lay onto each other, not even talking that they are not looking good. Request is to make possible, for example, to have normal size emotes with 22 text size. Maybe, option to exclude the scaling of the emotes.
Cheers.

**Comment by MonkeSmart** [comment]
"I could decouple the text size and emote scaling but it would be such a niche setting" I understand your position. But also, I think that if this setting would exist, many would use it. Mobile is a main platform for watching the video content on YouTube. Last word here is yours, of course. In any way, I thank you for the program.
Also, what settings would you recommend to set for mobile now (font, size)?
Cheers.

**Comment by lay295** [comment]
I will eventually implement it, but I don't know if it'll be any time soon really. I kinda just work on this project once every few months when I have bursts of motivation. I'll probably make an advanced settings option where a slider can be changed.

But I would argue that Streamlabs are the ones scaling emotes incorrectly, not TwitchDownloader. I based my scaling off of the actual twitch chat and the emotes are definitely bigger than what Streamlabs is showing. I'm on my phone at the moment so I can't offer a screenshot, but yeah.

**Comment by ScrubN** [comment]
This is implemented as the "emote scale" input in the GUI with an equivalent in the CLI
