### ISSUE TITLE
[Feature] Direct load VOD URL from "Task Queue" into "VOD Downloader" tab

### ISSUE THREAD

**Issue by Coldblackice** [lay295/TwitchDownloader#237]
The latest update _rocks_. Fantastic idea on the "Task Queue" functions of clips/VOD/URL list, I use these all the time now. 

It'd be great if there was an ability to direct-load VODs/clips URLs from the "Task Queue" directly into the respective tabs, enabling editing the start/end times and whatnot. Currently, it requires finding and copying the URLs through the web browser.

**Comment by ScrubN** [comment]
To add context to the closing, loading tasks from the Task Queue tab into an operation tab would require rewriting the backend of the GUI. I've thought of this too but it's honestly not super easy to achieve.
