### ISSUE TITLE
TimeSpan could not be parsed

### ISSUE THREAD

**Issue by PurifierUnit** [lay295/TwitchDownloader#24]
Win7, attempting to download chat for a stream nearly an hour in length (VOD downloaded just fine).  Chat download gives the following error every time:

"ERROR: The TimeSpan could not be parsed because at least one of the numeric components is out of range or contains too many digits."

VOD link: https://www.twitch.tv/videos/598981736

**Comment by lay295** [comment]
Are you trying to crop the chat? Could you add a screenshot of the settings you're using so I can try and replicate?

**Comment by PurifierUnit** [comment]
No chat cropping involved.

![image](https://user-images.githubusercontent.com/64235120/80164707-54f72a00-859f-11ea-9b9f-ccd2f02c9129.png)

**Comment by PurifierUnit** [comment]
Interestingly, the VOD downloader appears to think the stream is an hour longer than it actually is.  Length shown on Twitch and on the download is ~57:30, but the VOD downloader shows 01:57:30.  I wonder if this might be related.

![image](https://user-images.githubusercontent.com/64235120/80166269-23805d80-85a3-11ea-97ba-3eb29876db49.png)

**Comment by lay295** [comment]
Ahhhh well that was just a small bug on my part on the length of the VOD, but uhhh perhaps your system language culture isn't English? I remember reading a few youtube comments about foreign people getting that error.

Would you mind giving this build a shot and letting me know if it works?

https://drive.google.com/open?id=1d3SPFVbg68mNR0C1E5wuXtS_QBhssKiZ

**Comment by PurifierUnit** [comment]
I'm very much operating an English-language system here.  =)

Test build produces the same error when attempting chat download (although VOD length appears to be displaying correctly now).  Is there anything else I can provide that would be helpful for debugging?

**Comment by lay295** [comment]
Whoops completely misunderstood the problem!

Give the newest release a try, should be fixed.

**Comment by PurifierUnit** [comment]
Confirmed fixed, for me at least.  Thanks!
