### ISSUE TITLE
Chat render object reference.

### ISSUE THREAD

**Issue by BJohhnyB** [lay295/TwitchDownloader#240]
Hiya, in the new version chat render doesnt seem to work for me. After the fetching emotes stuff it stops with an ERROR: Object reference not set to an instance of an object.

The vod in question:
https://www.twitch.tv/videos/960557920?collection=TjMBbnAWbxb1gg&filter=collections&sort=time

**Comment by sunkhaskasis** [comment]
Gone on my end. Waiting on OP's response I guess.
