### ISSUE TITLE
Wrong encoding for non-latin symbols if view a Twitch channel or add VOD to queue

### ISSUE THREAD

**Issue by soksanichenko** [lay295/TwitchDownloader#243]
Hi.
I got non-readable titles if I view a Twitch channel or add VOD to queue

http://u.cubeupload.com/ZelGray/screenshot2021102300.png

Also, a file name is saved in the same wrong encoding

http://u.cubeupload.com/ZelGray/9cescreenshot2021102300.png

**Comment by lay295** [comment]
Could you give me a VOD URL/ID so I can try and reproduce it?

**Comment by sunkhaskasis** [comment]
Not the OP, however I was able to identify the issue: it downloads fine when using the ordinary chat downloader option, but corrupts the unicode characters when using Mass Downloader. 
![image](https://user-images.githubusercontent.com/19194315/138575071-48e0e4da-76fa-411a-a78b-877487afa0b0.png)

The channel is called "Gleborg", which is a streamer that seems to be using Russian in his stream titles. You can try downloading chat from one of his VODs, which is shown in the OP's picture: https://www.twitch.tv/videos/1183874290
