### ISSUE TITLE
Fonts and video size problems

### ISSUE THREAD

**Issue by HellbringerOnline** [lay295/TwitchDownloader#246]
Hello. I'm trying to create a video identical to a twitch chat, I downloaded a woff2 font, converted it to ttf but it doesn't render correctly. And I'm trying to set the chat width in the settings to match the original - 340 pixels, but 191 pixels are displayed, but the video format is 340 * 1920. If I record a chat using bandikam, I get the truth 340 * 1920
Render
![444](https://user-images.githubusercontent.com/14059683/139504652-f6bc94f4-1377-4c4f-9326-bd42cbd5bee9.png)
ScreenCapture (bandicam)
![4444](https://user-images.githubusercontent.com/14059683/139504669-409357dc-ce86-4686-9ef8-5ed032c04cf9.png)
Settings
![image](https://user-images.githubusercontent.com/14059683/139504730-be11ebf8-61f2-4536-9ace-4d37bbecc18b.png)
If I change the font to regular (Arial), then it is rendered correctly, but not identical to the chat on twitch (Because it has an Inter.woff2 font)
Rendered Video
https://user-images.githubusercontent.com/14059683/139505328-e8530d7a-994f-44ce-bfba-cd795facd526.mp4

**Comment by lay295** [comment]
Yeah guess I don't have font fallback for the timestamps + usernames, and I'm guessing ASCII characters aren't included in Inter.woff2. I'll try and fix it when I have some free time.
