### ISSUE TITLE
Not recognizing command after conducted chmod

### ISSUE THREAD

**Issue by OliverGronowski** [lay295/TwitchDownloader#247]
Hey,

I am unable to call the `TwitchDownloaderCLI` command after conducting the following steps in Ubuntu shown in the picture below.

Thanks in advance!

![Screenshot from 2021-10-30 17-10-17](https://user-images.githubusercontent.com/45373843/139538886-0baf841c-5520-4e55-96f3-02f28a242d12.png)

**Comment by lay295** [comment]
If you want to run an executable in your current directory in Linux, you have to put ./ before it because without it bash will try and find TwitchDownloaderCLI from a directory in the $PATH which it isn't. So ./TwitchDownloaderCLI will run the executable.

**Comment by OliverGronowski** [comment]
![Screenshot from 2021-11-04 13-48-56](https://user-images.githubusercontent.com/45373843/140316323-522fc096-01b5-4fce-9088-987da024bbdd.png)

This is what it shows now. Feels like it is the right command, just that somehow the permission is blocked?

**Comment by lay295** [comment]
Well, you did chmod -x which took away executable permissions instead of doing chmod +x

Otherwise it looks fine

**Comment by OliverGronowski** [comment]
![Screenshot from 2021-11-04 16-07-32](https://user-images.githubusercontent.com/45373843/140339562-796969d2-85a5-4d42-a522-1b773c9ff8fa.png)

It shows me this now. I wonder if the ID one has to specify would be 1190043715 in https://www.twitch.tv/videos/1190043715

**Comment by lay295** [comment]
The id parameter has 2 dashes, single letter 1 dash, more than that 2 dashes.
