### ISSUE TITLE
User colors in ChatRender

### ISSUE THREAD

**Issue by SpeedK** [lay295/TwitchDownloader#248]
Current Behaviour: TwitchDownloader gives a random color to the same user everytime it renders the chat from json.
Target Behaviour: In every message, there's specified parameter user_color. Why not use that info to set user colors in chat render? and make it as a parameter in TwitchDownloaderCLI and probably making it default would make sense.

example: "user_color": "#1E90FF"

**Comment by lay295** [comment]
It only gives a random color if the user hasn't set their username color, aka it's null. (Twitch does this in their chat too if a user hasn't set their color)

https://github.com/lay295/TwitchDownloader/blob/ddee12931494bb29a0fd1395cbb3ee5f00247130/TwitchDownloaderCore/ChatRenderer.cs#L93

**Comment by SpeedK** [comment]
Apparently i was using version 1.0.0 so i tried with TwitchDownloaderCLI 1.40.4 but it looks like colors are still mapped randomly everytime i render chat. I gotta say I generated chat JSON file from twitch IRC Chat. So I thought problems would come from that but then I downloaded a vod chat via mode ChatDownload and tried to render that but that still happens. Colors are still mapped randomly. Is this only my problem?

**Comment by lay295** [comment]
Can you upload a json you're trying to render so I can take a look?

**Comment by SpeedK** [comment]
VOD url: https://www.twitch.tv/videos/1193796187
using: `TwitchDownloaderCLI.exe -m ChatRender -i 1193796187.json -o test.mp4`
gives me an mp4 file with incriminated behaviour.

[1193796187.zip](https://github.com/lay295/TwitchDownloader/files/7477107/1193796187.zip)

**Comment by lay295** [comment]
So, for example the 2nd commenter has his username color set. Is his username changing colors for you?

![image](https://user-images.githubusercontent.com/1060681/140394303-14081c84-d29e-400c-844e-4ea8f1d1294c.png)

His name is always that red color for me and every time I render it. If you could give an example of a comment username changing color where their color isn't null then it would help.

**Comment by SpeedK** [comment]
I accidentally did not put user_color inside message object but outside instead. Everything works now. Sorry for wasting your time and opening a ticket only cause i failed coding. If you want, you can delete this thread. Thank you for your help. Have a nice day! :)
