### ISSUE TITLE
Channel name not populating in filename

### ISSUE THREAD

**Issue by cr08** [lay295/TwitchDownloader#250]
Hoping this isn't a duplicate issue. I was not able to locate anyone else here mentioning it.

Simple enough, but it seems like in my own use case the channel name is not being populated in the filename despite being included in the template. Here's an example:

Template:
`{date_custom="u"} {channel} - {id} - {title} - Chat`

Output:
`2021-10-29 215724Z  - 1190584732 - Return of the Obra Dinn Putting the pieces together. - Chat.json`

Currently running the latest Windows GUI release on the current stable release of Windows 11 (21H2, 22000.282)

**Comment by lay295** [comment]
Uhhh, I'm really not sure to be honest. I'm on Windows 11 as well and it seems to be working fine here.

![image](https://user-images.githubusercontent.com/1060681/140165323-657471b8-400e-4990-b166-c0946e9154ae.png)

So, I'm not 100% sure. Does this problem happen 100% of the time?

**Comment by lay295** [comment]
Ohhhh it's when you enqueue the download from the "Search VODs" page, I can reproduce it. I will try and fix it next release.

**Comment by cr08** [comment]
Yep. I just replicated that myself. I had been using the task queue the entire time but doing a one-off it included the channel name just fine.

Thanks for looking into it :)

**Comment by Hannah-GBS** [comment]
Any progress on this?

**Comment by lay295** [comment]
> Any progress on this?

Tbh I thought I already fixed this, anyways put a fix in so next release it should actually be fixed, I promise.

**Comment by xzipyx** [comment]
i have the same issue with the latest release
