### ISSUE TITLE
ERROR: The system cannot find the file specified

### ISSUE THREAD

**Issue by erorr30045** [lay295/TwitchDownloader#253]
When I try to download apart from a vod I get this ERROR: The system cannot find the file specified. what does it mean? how can I fix it?  
![image](https://user-images.githubusercontent.com/87334494/140627246-d9a26261-0ee0-4943-9a18-7d2caafdf113.png)

**Comment by erorr30045** [comment]
Note: this is the news V 1.40.4 and other stuff like downloading clips works fine

**Comment by lay295** [comment]
Not sure, I imagine you're running low on disk space so something is failing and it cannot find the file?

How much free disk space do you have?

**Comment by erorr30045** [comment]
![image](https://user-images.githubusercontent.com/87334494/140841038-c7456611-c299-4673-aace-3626a3918a02.png)

**Comment by erorr30045** [comment]
ohh it worked, i extracted the files from the winrar file thing
