### ISSUE TITLE
ERROR 403 ONLY ON VODS NOT CLIPS?

### ISSUE THREAD

**Issue by samuraipinkish** [lay295/TwitchDownloader#255]
![unkdsadasnown](https://user-images.githubusercontent.com/93949301/140818741-af07b032-f64a-4f61-96aa-15744299f5ec.png)
![undsadasknown](https://user-images.githubusercontent.com/93949301/140818886-069fbaf8-3bdd-4942-93d6-b9b6b950d9e7.png)

**Comment by lay295** [comment]
![Screenshot_20211108-170827](https://user-images.githubusercontent.com/1060681/140826032-0ec8fa98-49d2-44e4-9fec-54a56686f26a.jpg)
