### ISSUE TITLE
Download live chats (and streams)

### ISSUE THREAD

**Issue by Oondanomala** [lay295/TwitchDownloader#258]
Would it be possible to save the live chat when a person is not streaming, like chatterino does with its logging setting, but supporting all the formatting options like the current chat download?
This would be helpful if the stream crashes to prevent loss of messages.

This would also be great for streams if a channel doesnt have VODs enabled for archival purposes.

Thank you for making this tool :)

**Comment by lay295** [comment]
I will not be adding that functionality to this program since I feel it's a bit out of the scope of this project.

If you're on Windows can try my other program [TwitchArchiverWPF](https://github.com/lay295/TwitchArchiverWPF) though which can download chats live to json and streams :)

**Comment by Oondanomala** [comment]
Ok, thank you :)

**Comment by Ashdemai** [comment]
> I will not be adding that functionality to this program since I feel it's a bit out of the scope of this project.
> 
> If you're on Windows can try my other program [TwitchArchiverWPF](https://github.com/lay295/TwitchArchiverWPF) though which can download chats live to json and streams :)

Is there a way to make the TwitchArchiverWPF work with Linux? I'm still looking for such functionality.
