### ISSUE TITLE
Tutorial for Chat mask

### ISSUE THREAD

**Issue by holeekebab** [lay295/TwitchDownloader#260]
hi i remember you making a tutorial for Chat mask and how to use it properly

do you still have it and where can i find it?

really love the program btw

**Comment by mohad12211** [comment]
![image](https://user-images.githubusercontent.com/51754973/141692818-22601a4f-0cbc-4e0b-ba31-7d3c76d9bd29.png)
if you click on the question mark here it will take you to the video.
this is the link of the video:
https://www.youtube.com/watch?v=D-_TD1-w3fY
