### ISSUE TITLE
[feature request] render a specific part of chat.

### ISSUE THREAD

**Issue by tiny-fidget** [lay295/TwitchDownloader#262]
love this program. i think it would be very useful to be able to render out a specific section of chat when rendering chat through a JSON file. i try to make short content from streams and sometimes i need to put up something said in chat on the screen. 
i can do that easily when the VOD is still online on twitch, i can just forward to the part where the thing was being said and screenshot it and use it. but with vods that are no longer there i rely on the JSON chat file thing that i've downloaded and i can only render the whole thing and it takes time. it feels really impractical to render a 5hr chat just for a screenshot of of one comment. 

sorry if this is not the place to post this. i hope this feature gets considered!

**Comment by ScrubN** [comment]
You can now use the partial-render button in the windows GUI to do that
