### ISSUE TITLE
Chat mask

### ISSUE THREAD

**Issue by bwalton24** [lay295/TwitchDownloader#264]
> Yep it works, nice.
> 
> `ffmpeg.exe -ss 37 -i chat.mp4 -i chat_mask.mp4 -i vod.mp4 -filter_complex [0][1]alphamerge[ia];[2][ia]overlay=main_w-overlay_w:0 -c:a copy -c:v libx264 -preset slow -crf 26 burned.mp4`
> 
> dunno how useful this is, but i added this to my own project to burn chat into the vod without any video editing software
> 
> _Originally posted by @MrBrax in https://github.com/lay295/TwitchDownloader/issues/79#issuecomment-699648513_

Does this command still work?  When I run it, the chat doesn't appear on the burned mp4

**Comment by MrBrax** [comment]
i doubt ffmpeg would have pushed any breaking changes, but what do i know

haven't tried in a long while

**Comment by bwalton24** [comment]
Here's what I'm running

> ffmpeg -ss 37 -i SlipperyFastGrouseSpicyBoy-aSgd6LhBZHyuceNH.mp4 -i SlipperyFastGrouseSpicyBoy-aSgd6LhBZHyuceNH_mask.mp4 -i 000.mp4 -filter_complex "[0][1]alphamerge[ia];[2][ia]overlay=main_w-overlay_w:0" -c:a copy -c:v libx264 -preset slow -crf 26 burned.mp4

https://user-images.githubusercontent.com/60165419/143729087-c3641135-a024-4027-a33e-351542a1c5af.mp4

https://user-images.githubusercontent.com/60165419/143729090-4345e309-b84b-4d6f-bdd7-b9ab2786a1d3.mp4

https://user-images.githubusercontent.com/60165419/143729091-15e9851a-d935-44da-8886-f150ca220e05.mp4

https://user-images.githubusercontent.com/60165419/143729095-0a624057-9ef6-489f-8fac-69c8ad198643.mp4

**Comment by MrBrax** [comment]
remove the `-ss 37` at the beginning, probably something i left in
