### ISSUE TITLE
Feature request: Don't overwrite existing files.

### ISSUE THREAD

**Issue by tolekk** [lay295/TwitchDownloader#266]
My usecase requires me to download multiple parts of the same vod, and while that works great, I need to manually rename each file before downloading to make sure they're not overwritten. Would be lovely to add an option of adding vod timestamps to each file, so it's easy to find them, and they're not overwritten. 

Thank you!

**Comment by cyperdark** [comment]
click on settings icon, and replace `M-d-yy` to `M-d-yy HH_mm_ss`

**Comment by ScrubN** [comment]
> click on settings icon, and replace `M-d-yy` to `M-d-yy HH_mm_ss`

I don't believe that solves it as they all come from the source vod. In the current release of the application there is a new parameter in the custom file names called `{random_string}` and I believe its just 6 random letters to help in situations like this.
