### ISSUE TITLE
What happened to generate mask?

### ISSUE THREAD

**Issue by dfg555** [lay295/TwitchDownloader#268]
Just updated to 1.40.4 and I noticed I can no longer make chat transparent on vegas pro 15? Why does it have this white background mask now? vegas mask generator doesn't work with it.

**Comment by dfg555** [comment]
nevermind just made the background transparent, no clue if it's an update bug or the dev changed something...

**Comment by NotBlod** [comment]
I'm also having this issue, did you manage to find a solution and if so, what was it?
