### ISSUE TITLE
Private VODs?

### ISSUE THREAD

**Issue by tomma367** [lay295/TwitchDownloader#269]
Hi there Lewis, thanks for making this!
How do I download private VODs - those that require me to be logged in (I subscribed to the channel to have access to these VODs, so I have access when logged in, but they're not available publically).
Thank you!

**Comment by cyperdark** [comment]
this?

![explorer_pyOgRRlfR1](https://user-images.githubusercontent.com/21735205/145708160-d3743fba-229a-484a-8fe9-890f6b1ef77b.jpg)

**Comment by tomma367** [comment]
Wow that was fast! Thanks @cyperdark Cyberdark I'll check it out!
