### ISSUE TITLE
Default names for files 

### ISSUE THREAD

**Issue by therealmaxkim** [lay295/TwitchDownloader#27]
1. When you download anything - clip or json - make the name of the file the title of the clip. Easier when you download large number of clips. (Example: title.mp4 and title-chat.json) 

2. One button that does everything - download the clip, downloads the chat logs in json, downloads renders of chat. No need to switch between 3 tabs when you download large number of clips. (For example - another large grey button on top (next to Chat Render) that does everything). 

3. Option to delete json chat log after you render chat. 

Thanks! By the way, do you have some donation/paypal link? I've been using this for a while and its super useful. Would love to buy you a cup of coffee.

**Comment by lay295** [comment]
I'm planning to implement a queue system eventually which should streamline doing lots of things. School semester is almost over and I'm pretty busy so I'll work on it over the summer. Lots of stuff has to be rewritten as it's kinda a mess...

I'm also planning to add command line parameters so people could easily make a script to do exactly what they want.

I'll add suggestion 1 in the next update along with #26 as it shouldn't be that hard. Suggestion 2 should be possible when I implement the queue system and honestly probably won't implement 3, but if you have a set routine you follow it'd be pretty easy to make a script for it in the future.

I don't have a donation link, but I'd appreciate it if you stared the project :) thanks for the kind words though.

**Comment by ScrubN** [comment]
Suggestion 1 and 2 have been implemented. I disagree with suggestion 3 incase a re-render is needed.
