### ISSUE TITLE
When rendering Korean chat it doesn't show some character

### ISSUE THREAD

**Issue by orion5567** [lay295/TwitchDownloader#271]
Blank and other symbol are not showing on rendered chat
But at json and txt files which download from this program shows all character correctly

I checked multiple vod and changing the font, changing the setting
But it still not work properly

Example

![original](https://user-images.githubusercontent.com/96343895/146666363-c8fa693f-4b2c-4558-840f-35873d489af4.JPG)
Original chat

![render](https://user-images.githubusercontent.com/96343895/146666365-8073109c-35de-4a3e-b76a-ef73d501a79c.JPG)
Rendered chat

![vs](https://user-images.githubusercontent.com/96343895/146666371-7330c03d-280a-4413-8abb-8387926de242.png)
Comparison

test vod link : https://www.twitch.tv/videos/1233176913
It's short 7min stream for test

Please fix this
Thank you

**Comment by aeongdesu** [comment]
> ![Screenshot_20220925_141318](https://user-images.githubusercontent.com/50764666/192129391-02618d0a-27d9-4c1b-a82c-89756081ee05.png)
> rendered chat

> ![Screenshot_20220925_141701](https://user-images.githubusercontent.com/50764666/192129461-184b14c6-b409-4dd6-baf8-6abb41a31127.png)
> original chat

it seems to be fixed on [1.15.0^](https://github.com/lay295/TwitchDownloader/releases/tag/1.50.0)
