### ISSUE TITLE
Blacklist for Chat Render

### ISSUE THREAD

**Issue by CatDany** [lay295/TwitchDownloader#272]
Hey, lay295. Considering YouTube's rules on swear words, I believe this feature would be much appreciated. At the moment, everyone I know uses Notepad++ to do multiple "Find & Replace" but that renders the queue feature useless since you need to create a JSON first, go through it with Notepad, and only then Render.

This is an example of how it would work.
1. Let's add a button to the Chat Render settings.
2. The button opens a little popup with a multi-line text box.
3. The user can enter "bad words" there, case insensitive.
4. During chat render, it checks every message for the "bad words" and replaces them with asterisks (*****) that match the length of the original word. I believe Regex is unnecessary and it would only complicate things although it could be a nice option.

You are way more knowledgeable on the code of TwitchDownloader than I am, so a pull request from me wouldn't be appreciated and it would just ruin your design intentions for this app, but I'm sure this is something that can fit into your to-do list and implement in the near future.

Thank you for making and supporting TwitchDownloader!

**Comment by ScrubN** [comment]
#485 a filter was added to remove messages containing banned words. I can see how instead replacing the banned words with asterisks could be preferable but it's much easier to just remove them.
