### ISSUE TITLE
ERROR WHILE DOWNLOADING CHAT

### ISSUE THREAD

**Issue by devusingh** [lay295/TwitchDownloader#273]
I am getting this error while downloading chat. It is happening from 2 days.
![bug](https://user-images.githubusercontent.com/60532332/147430187-9a92f91e-5b65-4c6f-9a99-8f3b518b4304.jpg)

ERROR: Unterminated string. Expected delimiter: ". Path 'comments[32].commenter.updated_at', line 1, position 30281.

**Comment by ScrubN** [comment]
No clue what the problem was. Assuming it was fixed as Twitch has changed APIs and I haven't personally run into this.
