### ISSUE TITLE
Auto start/end crop setting

### ISSUE THREAD

**Issue by Bozzeh** [lay295/TwitchDownloader#274]
Hey,

A request, rather than an issue - 
It would be awesome to paste a link with parameters that auto tick and prefill into the start and end crop fields
The below link will take you to a vod timestamp
https://www.twitch.tv/videos/1248211258?t=10h11m33s
and something like this would be cool to just paste into the vod downloader & chat downloader section
https://www.twitch.tv/videos/1248211258?t1=10h11m33st211h24m38s where t1 is start crop and t2 is end crop.

Thanks!

**Comment by ScrubN** [comment]
Added in #430
