### ISSUE TITLE
Automatically create non existing directories in CLI

### ISSUE THREAD

**Issue by Oondanomala** [lay295/TwitchDownloader#276]
Currently if given a path that doesnt exist it just gives an error, it would be better if instead it automatically created the directory
EX:
-o "E:\Twitch\Chats\Whatever.json"
if "Chats" doesnt exist it should create it instead of erroring out.

**Comment by goldbattle** [comment]
Need to check if this is still a problem in 1.15.1

**Comment by ScrubN** [comment]
> Need to check if this is still a problem in 1.15.1

Anywhere that `File.Create()` or similar is used without an accompanying `Directory.Create()`/`TwitchHelper.CreateDirectory()` it will occur.
