### ISSUE TITLE
Random crashes while downloading VODs (No error message)

### ISSUE THREAD

**Issue by AJBauer92** [lay295/TwitchDownloader#277]
This one I couldn't fix with a reinstall. It just randomly closes itself mid-download. I have no idea why. This is actually a huge problem since it leaves incomplete video files behind, so I don't know which ones have been downloaded incorrectly.

**Comment by lay295** [comment]
Does it crash when downloading a single video, or using the queue downloading? Does it crash for VODs, Clips, or both?

**Comment by AJBauer92** [comment]
Crashes when downloading VODs, whether it's queue or individual. I haven't run into issues with clips.

**Comment by ScrubN** [comment]
I'm assuming this was fixed since I haven't had any crashes since early 1.5x
