### ISSUE TITLE
WebClient Request Error

### ISSUE THREAD

**Issue by vextechs** [lay295/TwitchDownloader#278]
I am getting an error code when trying to download clips from twitch using the clip downloader tab.

Steps to reproduce:
1.) Paste a link from twitch then hit "Get Info"
2.)hit download
3.) displays error code in log

ERROR: An exception occurred during a WebClient request.

This is my first time making an issue on github, I hope you can help me.
Thanks

**Comment by ScrubN** [comment]
This is probably been fixed.
