### ISSUE TITLE
Trying to render chat from deleted vods/nonstandard JSONs

### ISSUE THREAD

**Issue by rocket5513** [lay295/TwitchDownloader#28]
I'm trying to render chat from a deleted vod, my friend uploads vods from a streamer that deletes them regularly and the JSONs he's saving are different from the ones that are created using your app, I was wondering if there was a way to render out chat using your app without having to download the JSON through your app, I have a JSON, .txt, SRT and an SSA file from the vod but idk what I'm doing with them to make the render out like your JSONs do.
[drive-download-20200430T222956Z-001.zip](https://github.com/lay295/TwitchDownloader/files/4561703/drive-download-20200430T222956Z-001.zip)

**Comment by lay295** [comment]
Responded to your Reddit PM, but I don't have time currently as the school semester is almost over to make changes right now.

Essentially if all the chats you're rendering from is from "JadezVR" you can simply paste this after the first open bracket in the JSON file to make it work.
`"streamer":{"name":"JadezVR","id":510556281},` 

It'll look like this if you did it right https://i.imgur.com/H0TVVyM.gifv

**Comment by lay295** [comment]
Added support in 1.25
