### ISSUE TITLE
Support for rendering yt-dlp downloaded live chat

### ISSUE THREAD

**Issue by Oondanomala** [lay295/TwitchDownloader#281]
[yt-dlp](https://github.com/yt-dlp/yt-dlp) supports downloading twitch live chat, it is very similar to what this app downloads, but with less info. (it can't embed emotes)
It would be great if the app could render that too.

EDIT:
It will work out of the box when adding `"streamer":{"name":"STREAMERNAME","id":STREAMERID},` after the first curly bracket like so: `{"streamer":{"name":"STREAMERNAME","id":STREAMERID},"comments":[{"_id":ETC`

I assume this is required to know what channel to get custom emotes from, maybe add an option to select a custom channel widouth needing it? It could only be in the CLI as if you are using yt-dlp you are probably already using that.

**Comment by Oondanomala** [comment]
Yes it is currently broken, it only downloads the first segment.
There is a pull request to make it actually work, tho i don't know when it's gonna get merged
(broken link to avoid unnecessary mentions) https://github.com/yt-dlp/yt-dlp/pull /1551

**Comment by goldbattle** [comment]
Might be interesting for the future, but closing for now since their implementation is broken.
