### ISSUE TITLE
Program deletes muted parts

### ISSUE THREAD

**Issue by Norinoku** [lay295/TwitchDownloader#283]
When I start downloading VOD within the first ~15 minutes after the end of the stream, it downloads all the muted parts that Twitch has not had time to remove the sound on yet, and then, which does not have time to download, just deletes. At the same time, when I start downloading VOD after these 15 minutes, when all the "muted" parts are already completely muted, it leaves these muted parts in the recording.

Therefore, the question is, removing muted parts in the first 15 minutes after the end of the stream is a bug or a feature?

Also, is it possible to add a function, due to which the program first downloads all the parts with "muted" sections, and then downloads the rest, and connects them at the end?

**Comment by lay295** [comment]
I've re-read your post multiple times but I really cannot get a grasp on what you're saying.

Are you saying that the video output of the program has the muted segments completely removed from the output?

**Comment by Norinoku** [comment]
https://youtu.be/gKzTOaQb3jc - downloaded video
https://www.twitch.tv/videos/1292245916 - original

As you can see, on my video there's a missing part on 1:18:40, when the original stream has it.

I started downloading this VOD after a few minutes after the end of the stream. As you most likely know, Twitch has a "window" which last for about 15 minutes after the end of the stream, when all the red parts which are supposed to be muted, haven't been muted yet.
So you can see, on my video 6:00 - 12:00 part didn't been deleted, and even has a sound, because program had time to download this part. But seems like it didn't have enough time to download the 1:18:00 - 1:24:00 part, only managed to download first 40 secs, and decided to just delete the rest (1:18:40 - 1:24:00). Seems like in that moment Twitch already muted copyright parts, which resulted in bug when downloading.
But if I download the same VOD now, all muted parts will be in there, just won't have a sound. So the problem only arises at the moment when Twitch completely mutes copyright parts.

**Comment by superbonaci** [comment]
The video is no longer available to check. If you view the video from the Twitch webpage, does it play the muted or the unmuted version?

**Comment by Norinoku** [comment]
It's been a long time since I opened this issue, and yes, now if you view the video from Twitch webpage you'll only be able to see the muted version, because Twitch now mutes copyright parts much faster. Therefore I don't think my problem is relevant anymore (and I haven't had that problem in a while), so I'll close it

**Comment by Norinoku** [comment]
It's been a long time since I opened this issue, and yes, now if you view the video from Twitch webpage you'll only be able to see the muted version, because Twitch now mutes copyright parts much faster. Therefore I don't think my problem is relevant anymore (and I haven't had that problem in a while), so I'll close it
