### ISSUE TITLE
[Suggestion] Update Cheermote Endpoint

### ISSUE THREAD

**Issue by sunkhaskasis** [lay295/TwitchDownloader#285]
The cheermotes [still use Kraken](https://github.com/lay295/TwitchDownloader/blob/master/TwitchDownloaderCore/TwitchHelper.cs#L568), which will become fully obsolete in a couple of weeks. I don't know what your current plans are regarding bit emotes, but I'd really appreciate if you've updated their endpoint, otherwise the program would most likely throw errors due to a non-existing API.

**Comment by lay295** [comment]
Yeah I just missed it somehow on the move to GQL. I think it's because I used Github search and it just shows the 1st 2 occurences in the file so I only fixed those 2. 

They have a global cheer config query so should be simple enough to fix. Will try and move it later today.
```
# GlobalCheerConfig contains information about (1) How to display Cheers and (2) What Cheermotes are globally available.
cheerConfig: GlobalCheerConfig!
```

**Comment by lay295** [comment]
1.40.7 should work now with GQL for the Cheermotes. Still works with channel specific cheermotes (used the json from your other issue)

![image](https://user-images.githubusercontent.com/1060681/153801984-f96e7a95-f873-4792-9328-f48283d18b59.png)
