### ISSUE TITLE
VOD Sub Only doesnt work

### ISSUE THREAD

**Issue by SantyOrtegaBanegas** [lay295/TwitchDownloader#292]

**Comment by SantyOrtegaBanegas** [comment]
Bro the option doesnt work without sub  :/  There a page (pogu.live)that shows the stream VOD Sub only ! 

I mean,you did a excellent work with the chat !  (the chat with emotes completely customizable work,great work!).

I dont a sub of this streamer (manijavi) :  https://www.twitch.tv/videos/1406994895
![image](https://user-images.githubusercontent.com/54714905/155815477-f6e897e7-7f1b-41d4-9b25-368a5a614d44.png)

I think there is a way to download the video bro ,im a trainee developer web may be can help you ,Thank you Lay and everyone!

**Comment by Zibbp** [comment]
If you want download the video there is a workaround without using TwitchDownloader. First get the playlist file using PogU.live's API `https://pogu.live/api/get-video/1406994895.m3u8` and use that in ffmpeg to download the video like so `ffmpeg -i https://pogu.live/api/get-video/1406994895.m3u8 -c copy test.mp4`.

The chat is not protected by Twitch unlike the video so you are able to download the chat using the VOD ID normally through TwitchDownloader and render the video.

**Comment by goldbattle** [comment]
The program currently only supports passing a oauth to download if you are subscribed. I don't think this will change.

**Comment by AAAndroid89** [comment]
I also encountered the difficulty of closed stream records for subscribers. The problem is that even if you are a subscriber of such a channel, the direct link to the record will still not download. You have to get a link in .m3u8 format

The only problem is that Twitch Downloader does not know how to work with such links. And I need to cut off certain pieces to save space on the hard drive.

**Comment by ScrubN** [comment]
> I also encountered the difficulty of closed stream records for subscribers. The problem is that even if you are a subscriber of such a channel, the direct link to the record will still not download. You have to get a link in .m3u8 format
> 
> The only problem is that Twitch Downloader does not know how to work with such links. And I need to cut off certain pieces to save space on the hard drive.

I am not sure what you are talking about. We internally fetch and parse m3u8 playlists when downloading a video, and sub-only/unpublished videos can be downloaded with an oauth token from an account with the necessary permissions.

**Comment by ScrubN** [comment]
> The fact is that I do not have a subscription to one channel, where recordings are available only if it is available. My friend sends me links in this format. And this link is not perceived by the program.

You need a subscription to download subscriber only videos. This is not a piracy tool.
