### ISSUE TITLE
No .exe file found in the downloads

### ISSUE THREAD

**Issue by Mysticlxl** [lay295/TwitchDownloader#30]
There is no run command, app or .exe in the download file

**Comment by Mysticlxl** [comment]
![image](https://user-images.githubusercontent.com/32917009/80908243-5c7ba900-8cec-11ea-85c3-654b1195097d.png)

![image](https://user-images.githubusercontent.com/32917009/80908249-63a2b700-8cec-11ea-8552-bcfaad6cda58.png)

**Comment by lay295** [comment]
You're downloading the source code, go into releases.
