### ISSUE TITLE
How merge manually with ffmpeg

### ISSUE THREAD

**Issue by v0mitkinnie** [lay295/TwitchDownloader#302]
vod downloading was interrupted on 98% but most parts are fine, what command i need use to merge them manually, my internet sucks and files are fine except lastest 5 they are 0 kb but its fine

**Comment by ScrubN** [comment]
The parts are not merged with ffmpeg. They are transport stream (.ts) files which means there is really no header blocks meaning the binary data can be appended together to form one long .ts video file. From there you can re-encode with ffmpeg or just copy it to a new container using our default ffmpeg args.
