### ISSUE TITLE
Crash when starting from Start Menu search

### ISSUE THREAD

**Issue by DinCahill** [lay295/TwitchDownloader#306]
Hi, thanks for making this. I appreciate your recent work on Kraken and .NET 6 🙂 .

The GUI and CLI both download ffmpeg to the current working directory.

If I put TwitchDownloader on my desktop, search for TwitchDownloader.exe in the Start Menu, and run it, it crashes, because it's running from System32.

Crash dump analysis:

![System.UnauthorizedAccessException: 'Access to the path 'C:\Windows\system32\ffmpeg.exe' is denied.'](https://user-images.githubusercontent.com/510163/159610591-9a41eb0b-277d-420b-856f-cfc22589023e.png)

**Comment by ScrubN** [comment]
I tried to add detection for when it was spawned from sys32/syswow64 but to no avail. *Could* just move ffmpeg to the temp folder but then it would get deleted every time you cleared your cache and that's rather annoying.
