### ISSUE TITLE
Feature Request: Chat renderer force bitrate 

### ISSUE THREAD

**Issue by NP-Gaming** [lay295/TwitchDownloader#311]
Hello, i think, it should be added an option to force bitrate, every time I render chat, it will render in huge size,
![Screenshot 2022-04-16 011531](https://user-images.githubusercontent.com/62297438/163651692-42554dc1-d5ac-4058-a0dc-afbd46c60cbb.png) 
maybe adding an option to lover it for example in my case to ~6000kbps would be great, and it would save a lot of storage space + speed up rendering

**Comment by goldbattle** [comment]
No re-encoding is done currently, so you would need to do that as a secondary process.
