### ISSUE TITLE
ability to render specific part of chat

### ISSUE THREAD

**Issue by tiny-fidget** [lay295/TwitchDownloader#314]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

i think it would be very useful to be able to select a time frame for chat render. sometimes i just need a specific part and dont need a whole 4hrs worth of chat in a video it can take time to render

**Comment by ScrubN** [comment]
This exists in the GUI as the partial render button and in the CLI as `-b` and `-e` respectively.
