### ISSUE TITLE
Add silent option for CLI

### ISSUE THREAD

**Issue by Oondanomala** [lay295/TwitchDownloader#315]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

An option in the CLI to hide all (or most) output like in many other programs.
`-s` would work.

**Comment by ScrubN** [comment]
Fixed in #1019
