### ISSUE TITLE
Temp folder location

### ISSUE THREAD

**Issue by DSCriErr** [lay295/TwitchDownloader#317]
Hi there.
How to change temp folder location, i don't like that it bothers my SSD.

**Comment by lay295** [comment]
![image](https://user-images.githubusercontent.com/1060681/166858129-820e51c3-a2e2-4711-a4ba-3a386670e453.png)

**Comment by DSCriErr** [comment]
Thanks mate.
I used Task Queue and didn't know settings propagate, makes sense.
