### ISSUE TITLE
ERROR: The remote server returned an error: (401) Unauthorized.

### ISSUE THREAD

**Issue by GaroShadowscale** [lay295/TwitchDownloader#32]
Hello, first off, I wanted to say that this tool is amazing, and I appreciate you creating it :D 

However 2 days ago and today, when trying to use the chat downloader on my own vods, I get this error:

ERROR: The remote server returned an error: (401) Unauthorized.

2 days ago the issue went away on its own after a couple hours, and yesterday the program worked just fine. However the error returned today, and I'm unable to download chat because of it, regardless of which vod I try. 

I am currently using the most recent version, 1.23

**Comment by lay295** [comment]
Zzz.... for some reason Twitch is making helix api calls use an oauth token. 
https://discuss.dev.twitch.tv/t/requiring-oauth-for-helix-twitch-api-endpoints/23916

I was wondering why TwitchLeecher wasn't effected, and the still use the older v5 API. So my only options are adding a login system (lol no), downgrading to v5 until its fully deprecated as well, or use their GraphQL which you're not supposed to do but don't have much of a choice.

Anyways, I'll downgrade the API I'm using in a bit and it should work for a while.

**Comment by Auxetics** [comment]
Yeah I'm having the same issue, current'y on 1.23 but i was using 1.7 and it was happening on it as well which is why i tried upgrading to 1.23. Another program (TwitchLeecher) i'm using to download VOD's as a backup is working fine but this is the only one i can use to download and render chats so i really hope it starts working soon.

also, using my oauth token to try and download a VOD not just chat isn't working.

**Comment by GaroShadowscale** [comment]
Thank you for the quick reply! I'm very ignorant when it comes to this stuff so I don't fully understand, but it sounds like you have a plan moving forward. I wish you the best with it :D

**Comment by lay295** [comment]
Should be fixed in 1.24 I just uploaded

**Comment by Auxetics** [comment]
> Should be fixed in 1.24 I just uploaded

Can confirm it is fixed, thanks so much for the speedy update!

**Comment by GaroShadowscale** [comment]
I can confirm it's fixed in 1.24 as well! Thank you so much :D
