### ISSUE TITLE
The problem with files of the same name

### ISSUE THREAD

**Issue by mirronake** [lay295/TwitchDownloader#320]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Describe your issue here

I started downloading clips from the channel that were made on the same date and with the same name. I want to save the clip with the date and title, but in order to avoid errors, I need to write {id}
It would be nice if files with the same name were simply renamed to something like "_01.01.01 title_ **(1)**_.mp4_"

**Comment by fraizzo** [comment]
you have to set it like this [{date_custom="T"}] {channel} - {title}

**Comment by goldbattle** [comment]
Tracking this in https://github.com/lay295/TwitchDownloader/issues/266
