### ISSUE TITLE
Error 400 When i download a CHAT

### ISSUE THREAD

**Issue by P-Gaz** [lay295/TwitchDownloader#322]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Describe your issue here

Hello, thank you for your beautiful software it is very, very useful I have a problem when I try to download a chat all the time I have an "ERROR 400" 

> %Unhandled exception. System.AggregateException: One or more errors occurred. (The remote server returned an error: (400) Bad Request.)
 ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at TwitchDownloaderCore.ChatDownloader.DownloadSection(IProgress`1 progress, CancellationToken cancellationToken, Double videoStart, Double videoEnd, String videoId, SortedSet`1 comments, Object commentLock)
   at TwitchDownloaderCore.ChatDownloader.DownloadAsync(IProgress`1 progress, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at TwitchDownloaderCLI.Program.DownloadChat(Options inputOptions)
   at TwitchDownloaderCLI.Program.Main(String[] args)
Abandon (core dumped)

and I never manage to download a chat (Windows or Linux), a developer friend gave me a workaround for linux, and it works I am located in France so with the command
`LANG=C ./TwitchDownloaderCLI -m ChatDownload --id 1433762528 -o chat.json` 
with this, the chat download work fine.

**Comment by Oondanomala** [comment]
Havent tested much but it looks like a problem with parallel chat downloading, either twitch is rate limiting or a bug, but without it it works.
Try setting it to 1 (use `--chat-connections 1` in the cli)

**Comment by FeozRu** [comment]
> Havent tested much but it looks like a problem with parallel chat downloading, either twitch is rate limiting or a bug, but without it it works. Try setting it to 1 (use `--chat-connections 1` in the cli)

Have a same ussue, using chat-connections helped for me

**Comment by P-Gaz** [comment]
> Havent tested much but it looks like a problem with parallel chat downloading, either twitch is rate limiting or a bug, but without it it works. Try setting it to 1 (use `--chat-connections 1` in the cli)

Hello, sorry for my late reply, but it works perfectly with the option you gave me, thank you very much.

**Comment by ScrubN** [comment]
This should be fixed
