### ISSUE TITLE
Cannot download VODs at all in any version

### ISSUE THREAD

**Issue by kayexee** [lay295/TwitchDownloader#328]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Describe your issue here

No matter what I do the VOD fails to download, I have all of the information correct... I am also on a time crunch because I need the muted bits unmuted so I can use the VOD to make a YouTube video.

**Comment by Samus419** [comment]
I'm having the same issue. I tried downloading 4 VODs at once and only the first one actually downloaded. Now nothing will download. They were a full 48 hours (47:57:55), so maybe the issue? But I also tried trimming/cropping the video before download and that didn't work either.

**Comment by ScrubN** [comment]
Sounds like your ip was being limited by Twitch.
