### ISSUE TITLE
Can't launch the app on Mac

### ISSUE THREAD

**Issue by arko72** [lay295/TwitchDownloader#329]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Describe your issue here

When I try to start the latest mac version of the file it just opens a text document with lines of code in it

**Comment by ScrubN** [comment]
You aren't invoking the program from the terminal, you're opening it with a text editor.

Currently, the MacOS builds from Nov. 5th 12:30am EDT (1667622600 UTC) and earlier are missing core library files. Once a build is released with the core files, please refer to __MacOS - Getting Started__ in the README: https://github.com/lay295/TwitchDownloader/blob/master/README.md#CLI
