### ISSUE TITLE
Error Rendering Chat "ERROR: The pipe has been ended."

### ISSUE THREAD

**Issue by semaj4712** [lay295/TwitchDownloader#33]
I get this error, I tried the last three or four releases and I get this error on all of them

**Comment by lay295** [comment]
Few questions, 
Has it ever worked for you?
Can you post the JSON you're trying to render?
Did you change any ffmpeg arguments?

**Comment by semaj4712** [comment]
I only installed it today and I have yet to get it to work, I have not changed any ffmpeg arguments

[ORL_051220.json.zip](https://github.com/lay295/TwitchDownloader/files/4630974/ORL_051220.json.zip)

**Comment by lay295** [comment]
Have you changed any render settings? If so can you screenshot them?

You can download this build a try and ffmpeg will output to the log. Copy/paste it here and should have an error message in it.

https://drive.google.com/open?id=1Tqf1JfkubmTTg77nbPSE4a8aFJ4X5lSS

**Comment by semaj4712** [comment]
I only changed width and height
<img width="729" alt="Screen Shot 2020-05-14 at 2 44 22 PM" src="https://user-images.githubusercontent.com/38870317/81989111-7c1aa780-95f1-11ea-950f-8cca4ced32f1.png">

I will try that build

**Comment by lay295** [comment]
Uhhhh I think width and height have to be an even number

**Comment by semaj4712** [comment]
Ok let me try that

**Comment by semaj4712** [comment]
Oh your right, that seems to have fixed it

**Comment by semaj4712** [comment]
It seems to have rendered out just fine, awesome!  Great tool btw, was looking for something like this for awhile
