### ISSUE TITLE
is there no more GUI?

### ISSUE THREAD

**Issue by AtdheGashi** [lay295/TwitchDownloader#332]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates

### Write stuff here

is there no more GUI? I cant get to it

**Comment by Templayer** [comment]
Umm... the Windows GUI version is here https://github.com/lay295/TwitchDownloader/tree/master/TwitchDownloaderWPF

If you want a binary released version, go to https://github.com/lay295/TwitchDownloader/releases , check the latest one, click on Assets and download release.zip, which is the Windows GUI executable version (after decompression, that is).

There is no Linux GUI version, but I made a tiny one (still CLI technically, but it only asks you for video ID) that just requires you to set the folders up and then upon each launch it asks you for video ID. After entering it, it downloads the VOD in the best quality available (so you don't have to figure commands and arguments etc. each time you want to use it). It's here https://github.com/lay295/TwitchDownloader/issues/333
