### ISSUE TITLE
a Linux script for easy and quick downloading

### ISSUE THREAD

**Issue by Templayer** [lay295/TwitchDownloader#333]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates

### Write stuff here

There is no Linux GUI version, but I made a tiny one (still CLI technically, but it only asks you for video ID) that just requires you to set the folders up (by editing the script provided) and then upon each launch it asks you for video ID.

After entering it, it downloads the VOD in the best quality available (so you don't have to figure commands and arguments etc. each time you want to use it).

And GitHub refuses to let me upload it here without compressing it first... WAIT, IT DOESN'T KNOW .7z?!? .zip it is, then. Go screw yourself, Micro$oft!

[Download Twitch video at max quality by using TwitchDownloader with user input (you need to install TwitchDownloader first and then edit the paths inside this file).zip](https://github.com/lay295/TwitchDownloader/files/9085234/Download.Twitch.video.at.max.quality.by.using.TwitchDownloader.with.user.input.you.need.to.install.TwitchDownloader.first.and.then.edit.the.paths.inside.this.file.zip)

Here's an alternate link (use the slow and free option):

https://ulozto.net/file/F5lKLxRRuCxO/download-twitch-video-at-max-quality-by-using-twitchdownloader-with-user-input-you-need-to-install-twitchdownloader-first-and-then-edit-the-paths-inside-this-file-sh#!ZJL3ZQR2ZmEwMQL1LJIvZQZ4ZGWzZ094D3ICE3DgLzIvqzD4MD==

**Comment by ScrubN** [comment]
Use [this](https://github.com/mohad12211/twitch-downloader-gui) instead for a GUI wrapper on Linux

**Comment by Templayer** [comment]
> Use [this](https://github.com/mohad12211/twitch-downloader-gui) instead for a GUI wrapper on Linux

Thank you. That didn't exist when I needed it, I think. Feel free to close the Issue.
