### ISSUE TITLE
Installer missing dependencies

### ISSUE THREAD

**Issue by Avtem** [lay295/TwitchDownloader#339]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Describe your issue here

Hello. Please make sure you add all dependencies with your installation before distributing your app (or handle cases where user doesn't have those). If you make your apps using Visual C++ Redistributable for Visual Studio, make sure the end user has it installed.
Personally i install a fresh Windows on Virtual machine and test apps there - this way you will know immediately which libraries are missing in order to launch your app.
(screenshot - i wasn't able to install your app because of that error)
![2b64f209-5e5f-4e07-9d19-c049c0bc1694](https://user-images.githubusercontent.com/65607782/181438122-4e0265cd-8eb2-45fc-b72f-5dccc02aa99e.png)

**Comment by goldbattle** [comment]
Is this still an issue?

**Comment by Avtem** [comment]
v.1.51.1 now runs fine on my machine, thank you
