### ISSUE TITLE
Application Closes Within Seconds of Opening

### ISSUE THREAD

**Issue by jip326** [lay295/TwitchDownloader#34]
I don't know if this is a problem specific to my computer, but with the latest release, I cannot download anything because the application closes about 15 seconds after I open it. Whether I download something or not, it closes. Again, I'm not sure if this is a problem specific to my computer, but even if it is, it renders the program virtually unusable.

On a side note, I was looking (in the small window of time that I had) for a way to download chat just to a txt file. Has that feature been removed and so now we can only download it as a json and then have to render it?

**Comment by jip326** [comment]
I deleted the program files and redownloaded them. That seemed to work. Not sure what was wrong.

**Comment by jip326** [comment]
My computer has restarted and now the problem is back. I timed it and the program automatically closes after 45 seconds regardless of whether I was actively using it or not (making it virtually impossible to download anything). I will try to delete the files and redownload them as that seemed to work last time, but there seems to be some sort of bug if this keeps happening.

**Comment by lay295** [comment]
Hmmm is there ffmpeg.exe and ffprobe.exe where the program is located? If its missing ffmpeg it tries to download it, maybe its failing and closing the program? Only thing I can think of really

**Comment by jip326** [comment]
It has both. It does work now. I don't know what was wrong before, but I will keep that in mind if it ever acts up again.
