### ISSUE TITLE
Number input boxes can go into the negatives

### ISSUE THREAD

**Issue by Oondanomala** [lay295/TwitchDownloader#342]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Describe your issue here

I don't think this is intended
![hmm](https://user-images.githubusercontent.com/87101222/182893643-a6fb8e92-abd5-4308-9dc1-6493b59b3c3e.png)

**Comment by ScrubN** [comment]
It's now been fixed
