### ISSUE TITLE
Min/Max framerate issue

### ISSUE THREAD

**Issue by Taytes** [lay295/TwitchDownloader#343]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates

### Write stuff here

Hello,i am using this program to download 8-10 hours VODs and also using the adobe Premiere Pro to render it, but there's a thing. It takes so much time just to render without changing anything, and after 10 minutes of googling i found out this ( https://community.adobe.com/t5/premiere-pro-discussions/premiere-pro-2020-long-export-times-with-h-264-format-and-no-effects/td-p/11616005 ) Apparently it takes so much time cuz of the min/max frame rate, is there any solution for it? 
![image](https://user-images.githubusercontent.com/42778808/183516763-ee57cb3b-38ec-44c5-a876-abb397c15953.png)
Screen of the file info of video downloaded by twitch downloader

**Comment by goldbattle** [comment]
You would need to re-encode it with ffmpeg probably. We just download it and live streams typically have variable framerate.
