### ISSUE TITLE
ERROR: A connection attempt failed because the connected party did not properly respond 

### ISSUE THREAD

**Issue by Nutri626** [lay295/TwitchDownloader#349]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Describe your issue here

When trying to render chat it says  
"ERROR: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. [::ffff:52.24.176.201]:443 (badges.twitch.tv:443)"

i disabled chat badges but problem is still there, i also tried different channels, file sizes etc nothing helps

**Comment by StrafeCat** [comment]
hi, how did u fixed that ,
