### ISSUE TITLE
ERROR: An error occurred trying to start process 'ffmpeg' with working directory

### ISSUE THREAD

**Issue by JmonkeyCS** [lay295/TwitchDownloader#350]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Describe your issue here

I havent done anything special I was just trying to download a vod https://www.twitch.tv/videos/1564267746 to edit for my friend and it gave me the Error code (ERROR: An error occurred trying to start process 'ffmpeg' with working directory 'C:\Users\user\AppData\Local\Temp\Rar$EXa11468.22864'. The system cannot find the file specified.) I dont know what to do

**Comment by MrBrax** [comment]
probably unpack the program and everything related to it before you run it?

**Comment by goldbattle** [comment]
Tracking ffmpeg issues in https://github.com/lay295/TwitchDownloader/issues/306

**Comment by ScrubN** [comment]
@goldbattle This issue is because the user did not extract the program from the zip archive, not related to the start menu crashing
