### ISSUE TITLE
ERROR: Reading JArray from JsonReader.

### ISSUE THREAD

**Issue by BrySuperSaurus** [lay295/TwitchDownloader#353]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Describe your issue here

I'm getting the following error when I try to use the Chat Downloader at the moment: ERROR: Error reading JArray from JsonReader. Current JsonReader item is not an array: StartObject. Path '', line 1, position 1.

I'm sorry, I'm very new to Github! I tried looking through the previous errors and couldn't see anything. Is there a known fix for this issue? Thanks for any help :)

**Comment by OwlRadiant** [comment]
Same issue here. More specifically, I got this exact error when trying to render out a .json chat file. i'm also intermitently getting a "Status: Failed" at 99% when downloading chat from a VOD.

**Comment by Hooboii2** [comment]
I just had the same issue too i tried every version there is still no luck.

**Comment by adamross94** [comment]
Same issue here:

ERROR: Error reading JArray from JsonReader. Current JsonReader item is not an array: StartObject. Path '', line 1, position 1.
ERROR: Error reading JArray from JsonReader. Current JsonReader item is not an array: StartObject. Path '', line 1, position 1.

**Comment by Kelkador** [comment]
Having the same issue, but only with newer vods. Chat render from a .JSON downloaded from 08-22-22 is successful. A vod from 2 days later is a no go. Twitch changed their format probably.

**Comment by BrySuperSaurus** [comment]
> 

ahhh interesting. I hope it can get resolved soon. I'm not sure how difficult it is. Hopefully not too hard!

**Comment by OwlRadiant** [comment]
> Having the same issue, but only with newer vods. Chat render from a .JSON downloaded from 08-22-22 is successful. A vod from 2 days later is a no go. Twitch changed their format probably, also should note new downloads of chats before that time (08-24-22) are fine.

Interesting, I'm getting a 100% Status: Failed for the chat download for a VOD more than 1 month old.

**Comment by BrySuperSaurus** [comment]
> 

Ahh my apologies!! I actually meant "Download" as well. I used the wrong term. Sorry :) I'm on the Chat Downloader page trying to download and that's where I'm getting my error.

**Comment by OwlRadiant** [comment]
Further details - I'm able to download chat individually, on the "Chat Downloader" tab, but when queued up in the "Task Queue" it fails at 99% or 100%.

**Comment by BrySuperSaurus** [comment]
> 

Interesting, maybe I'll try queueing something and see if it works

**Comment by BrySuperSaurus** [comment]
Still failed unfortunately :(

**Comment by Kelkador** [comment]
I'm confused because your initial post contained the exact error I got when trying to render chats from beyond that 08-22 mark. Can you provide a screen shot of the error so I can make sure we have the same issue?

**Comment by BrySuperSaurus** [comment]
> I'm confused because your initial post contained the exact error I got when trying to render chats from beyond that 08-22 mark. Can you provide a screen shot of the error so I can make sure we have the same issue?

Sure! Sorry to have caused confusion.
![Screenshot 2022-08-31 221150](https://user-images.githubusercontent.com/112553719/187675446-21d2f022-b864-4fbf-bf5f-651b724dd5cf.png)

**Comment by BrySuperSaurus** [comment]
So I can't create a JSON file of any Twitch chats at the moment basically.

**Comment by Kelkador** [comment]
can you try unchecking embed emotes? The issue might be twitch changed something with emotes (very technical term) which in some way affected twitch downloader's method of interacting with them. (Hence why rendering chat doesn't work with the same error)

**Comment by BrySuperSaurus** [comment]
> 

Good idea! let me try

**Comment by BrySuperSaurus** [comment]
ooooo @Kelkador that worked!! I could create a JSON file with no emotes. I'm trying to render it now.

**Comment by BrySuperSaurus** [comment]
It won't render in the "Chat Render" Section. Got the same error.
![Screenshot 2022-08-31 222218](https://user-images.githubusercontent.com/112553719/187677218-0c542a66-85c2-45e4-807e-536aa9eae98f.png)

**Comment by Kelkador** [comment]
I think I found the workaround! Uncheck FFZ Emotes.

**Comment by BrySuperSaurus** [comment]
> I think I found the workaround! Uncheck FFZ Emotes.

trying it now!

**Comment by BrySuperSaurus** [comment]
> 

Okay it looks like that worked! In the "Chat Downloader" screen, uncheck "Embed Emotes" and then in the "Chat Render" Section, untick "FFZ Emotes"! It worked! And I'm watching the mp4 file back now. Looks like all standard Twitch Emotes are included :) Thanks for your help @Kelkador !!
