### ISSUE TITLE
I would like to include user_badges,name when downloading chats as txt.

### ISSUE THREAD

**Issue by letitbe5863** [lay295/TwitchDownloader#354]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

I would like to include [user_badges],[name] when downloading chats as txt.
It is useful thank you😀

**Comment by ScrubN** [comment]
Tracking in #467
