### ISSUE TITLE
Time cropping not working on v1.50.0

### ISSUE THREAD

**Issue by Coldblackice** [lay295/TwitchDownloader#355]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Describe your issue here

FYI, v1.50.0's (W10/x64) time cropping ability doesn't work. No matter what time-crop you set, it downloads the entire VOD in its entirety up to the current running time (if live). 

Cropping still works with 1.40.9.

**Comment by ScrubN** [comment]
This was fixed at some point. Works on 1.50.5
