### ISSUE TITLE
Minor misc. adjustments

### ISSUE THREAD

**Issue by Coldblackice** [lay295/TwitchDownloader#357]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

Two minor suggestions:

1. **Version numbering**

Unless I'm blind, there's currently no indicators anywhere of what version of TwitchDownloader is being used, neither in the GUI nor the EXE's file properties. Adding version numbers to the GUI and file properties would be useful when comparing versions and also knowing whether one's release is up to date or not; even a "Readme.txt|md" at the root with the version number of the release would be beneficial.

Without these, I've had to resort to diff'ing release folders just to know which is which. Not a huge deal.

2. **Release name schema**

On the "Releases" page, it'd be useful if "release.zip" was changed to the title of the repo + version number/architecture. This would help clarify between releases, and also make it more easily distinguish on the releases page. 

More than once I've overlooked "release.zip" assuming the fully repo-named other files which are also named with separate architectures are the "main course", as typically found on most release pages in my experience. But also not a huge deal.

**Comment by ScrubN** [comment]
The CLI version has a version check but the GUI one doesn't, so I just submitted a PR to add it to the GUI.
