### ISSUE TITLE
a way to download chat and video in the same frame similar to theatre mode

### ISSUE THREAD

**Issue by liminalspacesarecool** [lay295/TwitchDownloader#358]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

I upload twitch streams with chat for the purpose of archival and so that people with bad WiFi can watch streams with chat. it would be very beneficial to me if their was an option to download the video and chat in a theater mod like orientation. I feel like this would be useful because currently I have to download  the chat and the VOD and then put them in an editor wait for that to export then upload them to YouTube which can take a very long time. your software is very nice and I won't be upset if you don't add this because its such a niche use case but thanks for reading this

**Comment by goldbattle** [comment]
Tracking in issue https://github.com/lay295/TwitchDownloader/issues/249
