### ISSUE TITLE
Please add

### ISSUE THREAD

**Issue by xaolin** [lay295/TwitchDownloader#36]
Hello mr. lay295

Could you please add a button to download VODs / Clips together with chat (JSON file) at the same time? Maybe you could also add a button for auto-rendering after finishing the chat file downloading?

**Comment by lay295** [comment]
Oh I guess I never commented on this issue, but I plan to have a queue system in the future. Or at the very least command line arguments being able to be passed through so people could automate it themselves. Just going to close this as it's a duplicate but hopefully in the future :)
