### ISSUE TITLE
Cant render this JSON

### ISSUE THREAD

**Issue by HellbringerOnline** [lay295/TwitchDownloader#361]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [x] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Describe your issue here

ERROR: Object reference not set to an instance of an object.
[1.50.0] Version
![image](https://user-images.githubusercontent.com/14059683/192626094-cbcaf01f-47b7-49ef-bb36-b2a0d2289696.png)
![image](https://user-images.githubusercontent.com/14059683/192626134-cce5b40f-bbc7-44d1-ae09-984620c3ea33.png)
![image](https://user-images.githubusercontent.com/14059683/192626157-c2de005c-5eb5-4502-b0fe-31d99592a703.png)
![image](https://user-images.githubusercontent.com/14059683/192626197-58d747f5-1693-4ffa-8222-a4e8719ff9b9.png)
Error after 2-3% of rendering (20 min 47 s)

[[8-19-22] VooDooSh - StreamHolidays День 1 - Chat 3.zip](https://github.com/lay295/TwitchDownloader/files/9659298/8-19-22.VooDooSh.-.StreamHolidays.1.-.Chat.3.zip)

**Comment by lay295** [comment]
Give the newest version a try, should be able to render this JSON now

**Comment by HellbringerOnline** [comment]
Thanks, I'll try the new version and for now I'll close the issue
