### ISSUE TITLE
No Audio

### ISSUE THREAD

**Issue by Samus419** [lay295/TwitchDownloader#362]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Describe your issue here

Everything seems to download fine, but there is no audio at all. Is there a way to find the audio in the files I've already downloaded?

**Comment by ScrubN** [comment]
If there is no audio then the vod must have been muted by Twitch or there is a very obscure bug I am yet to run in to. You can open your downloaded files in a video editing program like Blender's video sequence editor to verify if there is a sound track.
