### ISSUE TITLE
App crashes randomly while downloading

### ISSUE THREAD

**Issue by Neimod2004** [lay295/TwitchDownloader#363]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Describe your issue here

When I try to download a VOD the app sometimes just crashes. I don't get an error, it's always at a different moment in the downloading procces and unistalling and reinstalling didn't help. As you can expect, this is really annoying. Is there something I can do?

**Comment by ScrubN** [comment]
The pre-release 1.50 had some minor crashing issues. Update to 1.50.5 and it shouldn't occur anymore
