### ISSUE TITLE
Unable to fetch video info

### ISSUE THREAD

**Issue by nasdalol** [lay295/TwitchDownloader#364]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Describe your issue here

This is the 2nd time I tried to use TwitchDownloader to replace TwitchLeecher but I keep getting this message, "Unable to fetch video info."

I tried multiple different links from different streamers and I still got the same message.

I tried everything else as well, like turning on/off the VPN, adding the software to the white list of windows firewall, turning off any third party firewall software, opening the software with administrative mode etc. The software kept showing that 

The log said it couldn't get response from the server, connection attempt failed.

I for the life of me can't figure out what went wrong. Please help!

![TwitchDownload](https://user-images.githubusercontent.com/57670768/196028169-e7a155f0-5d22-4c2a-b699-4f692c40595a.png)
![TwitchDownload 1](https://user-images.githubusercontent.com/57670768/196028172-4ae6f1df-4d13-4ed3-8020-bebee46ede24.png)

**Comment by REEEV3S** [comment]
had this bug, resolved by turning off cloudflare dns through WARP. Might work for you too

**Comment by nasdalol** [comment]
> had this bug, resolved by turning off cloudflare dns through WARP. Might work for you too

Can you be a little bit specific plz? Thanks

**Comment by REEEV3S** [comment]
If you're using a DNS server you should turn that off and try again.
If you're like me and using cloudflare WARP disabling/enabling that somehow works for me.
![image](https://user-images.githubusercontent.com/70071363/197881692-ff1ba93c-9353-4522-9b03-dd40a31b6c0b.png)
Not sure why

**Comment by WazuWaha2** [comment]
I have the same problem. Clip function works fine.
But I can't download any VoDs. Tried a few things around firewall (router and PC), changed a bit of my privacy settings, tried different links (old and new VoDs).  Older Versions of TwitchDownloader. Nothing changed. Still the "Unable to fetch video info." error. 

Log says: 
"_ERROR: Unable to find thumbnail
ERROR: One or more errors occurred. (A task was canceled.)
ERROR: Unable to find thumbnail
ERROR: One or more errors occurred. (A task was canceled.)_"...

Does anyone know how to fix this? 
I would appreciate some help!

**Comment by Avtem** [comment]
The bug happens every time for me. i don't use WARP and don't know whether i use DNS server.

**Comment by goldbattle** [comment]
Likely your host doesn't have SSL configured correctly for twitch (see the error).
