### ISSUE TITLE
Not 100% match with screen recording

### ISSUE THREAD

**Issue by HellbringerOnline** [lay295/TwitchDownloader#365]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

Hello. I have accumulated a few notes that I would like to fix so that the chat rendering matches the original screen recording.

1. I see the 0 hour symbol in the first hour of the render, there is none in the screen recording. Perhaps add an option that removes the character 0: in the first hour.
2. I see longer spaces at the same font size. Perhaps you should add an option that sets the cropping of spaces in pixels
3. I see a more spacious space between messages, while everything is more compact in the screen recording. Perhaps it is worth adding an option that sets the cropping of space between messages in pixels
4. I miss the 1 pixel wide gray bar to the left of the chat that visually separates the video from the chat. It might be worth adding an option to include this bar.

Might be worth integrating the fonts that Twitch uses to better match the screen recording

I use the Inter font family, which I downloaded from the official Google site, and the font size that is rendered by the browser. All options are listed [here](https://github.com/lay295/TwitchDownloader/issues/361).

![image](https://user-images.githubusercontent.com/14059683/196250517-f1013814-c259-432e-ac7b-aabc5af220b6.png)

**Comment by lay295** [comment]
Give the newest version a try, I fixed a lot of the scaling and positioning issues. I re-wrote a lot of the rendering code which is why the pre-releases were pretty wonky.

It will probably never be 100%, but it should be pretty close now.

**Comment by HellbringerOnline** [comment]
Thanks, I'll try the new version and for now I'll close the issue
