### ISSUE TITLE
ERROR: Index and length must refer to a location within the string. (Parameter 'length')

### ISSUE THREAD

**Issue by GrummanPara** [lay295/TwitchDownloader#366]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Describe your issue here

When I try to download a VOD it gives me an error that says "ERROR: Index and length must refer to a location within the string. (Parameter 'length')" I tried to do everything like changing settings but it did not work.

System: Windows 11

**Comment by ScrubN** [comment]
I'm unable to reproduce, check if 1.50.5 release fixed your issue. If not please provide all of your download settings **(except oauth)** and the VOD id.

**Comment by Solelix** [comment]
Hello, I have the same problem. I am running the latest version 

Windows 10

**Comment by ScrubN** [comment]
> Hello, I have the same problem. I am running the latest version
> 
> Windows 10

Please provide more information.

**Comment by Solelix** [comment]
![สกรีนช็อต 2022-11-15 164352](https://user-images.githubusercontent.com/117352951/201886544-882d8c41-e8ca-45ae-a707-b5943397d38a.png)
![สกรีนช็อต 2022-11-15 164430](https://user-images.githubusercontent.com/117352951/201886587-c0b69e49-589d-46bf-9058-a4220f9b813d.png)

VOD-id = https://www.twitch.tv/videos/1649682915

**Comment by Solelix** [comment]
i reinstall windows but it still not work

**Comment by ScrubN** [comment]
> i reinstall windows but it still not work

Can you try making the Temp Folder only english characters?

**Comment by Solelix** [comment]
it doesn't work         // I'm sorry if sometimes my language is wrong, I use google translate

**Comment by ScrubN** [comment]
Closing this as I was unable to reproduce at the time. If you continue to experience it please enable "Verbose Errors" in the settings to help me diagnose.
![image](https://user-images.githubusercontent.com/72096833/215651546-9efd4f8b-09aa-463d-910e-a5265bb95ebf.png)
