### ISSUE TITLE
Batch download not having any resolution than maximum resolution

### ISSUE THREAD

**Issue by dawnte** [lay295/TwitchDownloader#369]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

Batch download not having any resolution than maximum resolution for downloading the vod. Please add new feature where people can choose what resolution that they want to download.

**Comment by lucasfbn** [comment]
I believe Twitch changed the quality settings. "360p" is now "360p30" for example. Since the old quality settings don't exist anymore, the downloader will default to the highest setting. Just specify the new quality settings, and it should work again (did for me).
