### ISSUE TITLE
Audio, video and chat all out of sync

### ISSUE THREAD

**Issue by JonasBjordal** [lay295/TwitchDownloader#37]
Title speaks for itself. When putting together all the files in a video editing software (double checking sample rate, fps and trying to realign the parts) I noticed that it all were out of sync and couldn't be fixed. The audio started out being slightly ahead by a few frames and ended up being 5 seconds ahead by the end of the 1 hour VOD (despite both files having the same length). The chat render was even more messed up and didn't align to either (was ahead by 35 seconds or so!)

I can't attach my files since they're too big but they were all of the entire stream video with this link:
https://www.twitch.tv/videos/623007641

The result was completely unusable and I had to download it with another software.

**Comment by lay295** [comment]
Why the chat was 35 seconds shorter than the VOD.
https://github.com/lay295/TwitchDownloader/issues/25#issuecomment-618856054

> This issue is a bit harder to solve, as currently the program determines when to start and end based on the first and last messages, not how long the stream went for. Currently in the .json that info isn't stored, but I can make it so it saves the VOD length on download. So for example if your stream is 20 minutes total long, but the first message only gets typed 5 minutes after your stream, and the last message 15 minutes after your stream, the resulting chat will only be 10 minutes.

> I usually use this for [archiving](https://www.youtube.com/watch?v=6M9hnpl0Vuk) streamers I watch, but their chat is pretty fast so it usually isn't a problem.

> I'll try and change it on the weekend to appropriately save information about the VOD into the json.

Been too busy with other stuff to make the change.

I assume the video editing software is adobe premiere? It doesn't handle VFR video very well, which is why I have an option to convert to CFR to fix the de-sync. If you hover over the (?) it explains it. Which other software did you use to download it which didnt have the desync issue? TwitchLeecher?

![](https://i.imgur.com/t8iYxHW.png)

**Comment by JonasBjordal** [comment]
The chat thing makes sense and I could put it into place along another recording of the VOD.

I use Hitfilm Express so I didn't use that option (+ I didn't wanna use even more time/risk quality loss). I'll just use youtube-dl for now and you can take your time. I'll check in here every eventually and be happy to use it when it's working

**Comment by lay295** [comment]
Ahhhh sweet, I looked into what youtube-dl was doing.
[ffmpeg] Fixing malformed AAC bitstream with -bsf:a aac_adtstoasc

Anyways added the fix to my program, and will be added in the next release. It fixed the desync for me on premiere where it usually would be desynced.

**Comment by lay295** [comment]
Both issues should now be fixed in 1.25, feel free to reopen after if it's not.
