### ISSUE TITLE
Error in Chat Render , ERROR: Response status code does not indicate success: 404 (Not Found).

### ISSUE THREAD

**Issue by gmgameschris** [lay295/TwitchDownloader#376]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Describe your issue here

Using 1.50.2

After chat downloading the JSON file being used in Chat Render, keeps giving the following error message.
It downloaded just fine the JSON and is 60kb but won't chat render. I will attach the JSON as well .. I renamed it to a txt to be able to upload it.

ERROR: Response status code does not indicate success: 404 (Not Found).

Thank you

![Screen Shot 2022-10-25 at 1 22 30 PM](https://user-images.githubusercontent.com/77471590/197667064-306e8935-e5ed-4dae-9183-07b278851ab5.png)
[chatlog-2029-selectionsunday.json.txt](https://github.com/lay295/TwitchDownloader/files/9856643/chatlog-2029-selectionsunday.json.txt)

**Comment by lay295** [comment]
Whoops... give 1.50.3 a try in a few minutes. Feel free to comment if it's not fixed.

**Comment by gmgameschris** [comment]
Works in previous versions
![Uploading Screen Shot 2022-10-25 at 1.50.18 PM.png…]()

**Comment by gmgameschris** [comment]
Fixed. That was fast :)

**Comment by editheus** [comment]
having the same error in 1.52.8
