### ISSUE TITLE
Attempting to download any videos via the Task Queue URL List results in "failed" as of the new update

### ISSUE THREAD

**Issue by SavagePenguin21** [lay295/TwitchDownloader#377]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Describe your issue here

I have entered multiple Twitch vods (both the video IDs, as well as the full URLs) into the Task Queue URL list, and while the chats download without fail, the VODs always result in a failed state within seconds. I had no issue downloading vods from these channels prior to this update. Furthermore, it does not demonstrate this behavior when the VODs are downloader from the VOD Downloader tab; they only fail when initiated from the Task Queue URL list.

**Comment by lay295** [comment]
Thanks for the report, give 1.50.4 a try in a few minutes. Feel free to comment again if the issue is not fixed.
