### ISSUE TITLE
donate buttons on new v1.50.4 

### ISSUE THREAD

**Issue by tharnosii** [lay295/TwitchDownloader#378]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Describe your issue here

donate buttons crash twitchdownloader, only in the vod dowloader section it works.

amazing program btw 👍

**Comment by lay295** [comment]
Thanks for the report, and thanks :) should be fixed in the just released version
