### ISSUE TITLE
Inter Font is always bold 1.50.4

### ISSUE THREAD

**Issue by HellbringerOnline** [lay295/TwitchDownloader#379]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Describe your issue here

Hello. I'm testing a new version of the program and got a problem with the Inter font. Now he is always bold.
The application does not support variable fonts and the font family that is installed in Windows is displayed as one font.

![image](https://user-images.githubusercontent.com/14059683/197862548-65790342-c2d3-4848-8004-83f5804e5ef4.png)
![image](https://user-images.githubusercontent.com/14059683/197862934-5e5baf27-a7fb-4b49-9fa3-7d110df1726d.png)

The Inter font built into the Twitch Downloader is also always bold.
For some reason, the static font Inter installed in Windows is also bold.

Chrome
![image](https://user-images.githubusercontent.com/14059683/197860717-ad7c94ae-fadc-4316-a297-9ce07b903a23.png)

Twitch Downloader
![333](https://user-images.githubusercontent.com/14059683/197857740-fbfbb7bb-2c4a-4487-8b5d-1a23f52796df.PNG)

**Comment by Zibbp** [comment]
Having the same issue. This occurs with the CLI also even when passing `--font Inter` and *only* having the Regular version installed.
```
/usr/share/fonts/opentype/Inter.otf: Inter:style=Regular
```

**Comment by lay295** [comment]
Yeah, I'll probably end up renaming the bundled Inter to be something else so it does not conflict with already existing system fonts.

Also both being bold is because of a typo :'( I fix later today

**Comment by lay295** [comment]
OK should be good in the latest release, give it a shot.
