### ISSUE TITLE
Block the counter or automatically activate the checkbox

### ISSUE THREAD

**Issue by HellbringerOnline** [lay295/TwitchDownloader#385]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

Hello. When I try to download a piece of chat, I most often set the time and do not pay attention to whether the checkbox is activated.
Is it possible to make the counter inactive until the checkbox is activated? Or it better to automatically activate the checkbox if any value is entered into it.

![image](https://user-images.githubusercontent.com/14059683/198101466-0b8b0517-b939-46df-acc6-6ca9b346323d.png)

**Comment by ScrubN** [comment]
This will be fixed once the PR is merged.
