### ISSUE TITLE
Chat render taking a long time?

### ISSUE THREAD

**Issue by NHLmegafan21** [lay295/TwitchDownloader#388]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates

### Write stuff here

Before the new v1.50.5 update, rendering the chat was taking me around 30 minutes for a 6-hour VOD. Now with the v1.50.5 it takes around 5 to 7 hours. Idk what's wrong, idk if it's a bug or something on not right in my settings, i would like some help if possible.

**Comment by mikroSlavek** [comment]
Hello. I have the same problem. In the new version, the conversion takes a very long time. I tried the same settings and in v1.50.5 (VOD 1635829917, length 03:59:14) coversion took **28 minutes**, in v1.40.7 only **8 minutes**.
Settings: 
![01](https://user-images.githubusercontent.com/37529521/198588959-0e54f3a0-b156-42fe-a97c-39acab384a95.png)
![02](https://user-images.githubusercontent.com/37529521/198589001-a3d10206-a573-4c8e-b827-984d2e6e607c.png)
![03](https://user-images.githubusercontent.com/37529521/198589015-0822271e-9843-499d-a213-e9c5d4109204.png)
(I didn't change anything ↓)
![04](https://user-images.githubusercontent.com/37529521/198589021-5c721e60-52aa-46a6-956a-55d6cedb7c1f.png)
![05](https://user-images.githubusercontent.com/37529521/198589028-d3c24cb4-fd7b-4362-a4a4-b1b1a35be68e.png)
(I didn't change anything ↓)
![06](https://user-images.githubusercontent.com/37529521/198589033-3568724b-0003-4519-8807-36f990d0a79e.png)


I have AMD Ryzen 5 5600X + 16 GB RAM.
The processor usage graphs are interesting...
v1.50.5:
![07](https://user-images.githubusercontent.com/37529521/198589713-a180e180-d8df-48cb-8ace-16e1d0424ccb.png)
v1.40.7:
![08](https://user-images.githubusercontent.com/37529521/198589769-ff3920fa-a3f6-418d-a323-8b285ec9b597.png)

**Comment by lay295** [comment]
Oh, maybe the update time is being parsed as 0 since your locale uses , instead of . for the separation. Give a 1 second update a try. I suspect that might be it but I'll try and look into it on the weekend.

**Comment by mikroSlavek** [comment]
Good idea! I tried it with value 1. Time was 10 minutes shorter but still... 
![b01](https://user-images.githubusercontent.com/37529521/198612636-7889d914-7f59-41ef-8ee2-cd569ef63133.png)
Thank you if you check it out later!
