### ISSUE TITLE
Sub only VoDs or any part of a vod

### ISSUE THREAD

**Issue by rofled69** [lay295/TwitchDownloader#39]
They stopped working, it downloads them but gives error on last part when finalizing, shows sad pepe.

**Comment by lay295** [comment]
Any error message?

**Comment by haka3l** [comment]
It just says one or more error occured and shows crying pepe. It happens on last step when its stitching downloaded data i think. Its not happening only for me.

**Comment by lay295** [comment]
RIP, well I guess I gotta sub to someone who has vod only subs again. I'll check out what's wrong later today.

**Comment by lay295** [comment]
I just tried a sub only VOD, it worked for me. Soooooo no clue m8. Do normal non-sub only VODs work for you?

**Comment by haka3l** [comment]
Any vod, doesn't make sense. Clips and chat works fine. Tried run as an admin but same error.
![tdgiff](https://user-images.githubusercontent.com/12548246/85284873-35da2300-b490-11ea-8a6d-8e0d7b3e5483.gif)

**Comment by ScrubN** [comment]
If you are still wondering, your OAuth token is required to download sub only vods. Instructions on how can be found in the readme
