### ISSUE TITLE
Rendered chat - different padding on the right and bottom

### ISSUE THREAD

**Issue by HellbringerOnline** [lay295/TwitchDownloader#391]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Describe your issue here

The overall situation with the video has improved, but it seems to me that the indents between the right edge of the chat and the indents between the block with the message are very different.
I overlay the render on the original for convenience. The original messages are highlighted with a white frame, and I put a render on a translucent background.

![333](https://user-images.githubusercontent.com/14059683/198362659-94c4387c-69a9-48d6-aa30-9ed22d62927c.png)

**Comment by lay295** [comment]
I do not think I'm really going to be fixing this one honestly. I plan to add more parameters to let people control the spacing a bit more, but I don't think I would want this behavior as the default.

If we're specifying a resolution, I want to use all the space I reasonably can. In my eyes it just seems like wasted space and if a video editor wanted that space it would be pretty easy to add after the fact. Again open to adding it as an option though so can leave it open.

**Comment by HellbringerOnline** [comment]
> I do not think I'm really going to be fixing this one honestly. I plan to add more parameters to let people control the spacing a bit more, but I don't think I would want this behavior as the default.
> 
> If we're specifying a resolution, I want to use all the space I reasonably can. In my eyes it just seems like wasted space and if a video editor wanted that space it would be pretty easy to add after the fact. Again open to adding it as an option though so can leave it open.

If i have the ability to customize the intervals myself that would be great, it is also possible to add some presets for this, for example Default (Twitch), spacious and compact

**Comment by ScrubN** [comment]
Spacing customization will be coming in the next release. It will probably be marked as a pre-release for a while so check back in a few days
