### ISSUE TITLE
Batch downloading

### ISSUE THREAD

**Issue by rak99** [lay295/TwitchDownloader#4]
Hey again

So I'll use myself as a use case, I have my own program that generates an array of clip links, that I then download in a separate program, what would be absolutely amazing is if I could take this array of links, (it doesn't really have to be an array just strings separated by spaces or commas or whatever) and do a sort of batch chat json/txt file download,

Maybe something like, on the 'Chat Downloader' you could add a button 'batch file' (or possibly create a new section called 'Batch Downloader', where ideally a user would then select a file containing let's say 10 clip links, side note:

(one thing I can think of is to disable batch downloading for vods maybe, as they're generally super long, I think it's easy to determine whether or not a link is a vod or clip as the vod links usually include a channels name and are not from clips.twitch.tv but just twitch.tv (I think))

But the idea is you then you take that file, parse it for all the links and then generate 10 json/txt files making the name of the generated json file(s) the title which you already find from the link. Ideally you can then go to 'Chat Render' or again maybe in the proposed 'Batch' section, you can then batch select all 10 json files, and render 10 mp4 files for each, again with the names prefilled with the json filenames, this is probably kinda hectic, but just a cool feature I though of that would probably take some time but would really set this apart! If you add this or not, I'm not sure but this is still a great program, thanks!

Imagine if this could automate downloading 10 clips from links, take those files downloaded, generate 10 Chat JSON files for each clip, and in turn then generate 10 mp4 files, so in 1 swoop you can download 10 clips and get all 10 of those chat's as well, semi-automated, this would be amazing!

**Comment by lay295** [comment]
It's kinda funny I did make something similar in the past to make easy YouTube videos.
I would just enter the streamer name and it would compile all their clips into 1 video with chat automatically.
https://www.youtube.com/watch?v=zUTcNwFMAvQ

But anyways it kinda seems like a pretty specific use case though, I'm not sure how many people will want to download a ton of clips or chats at once. I would like to implement something like that however currently how the program is made it's kinda fragmented and I need to remake some large parts of it. I would ideally like to have a queue system where different tasks can be done one after the other, but I just currently don't have the time right now for it.

So, when I have time I'll try to make a queue system and implement something similar to what you're suggesting.

**Comment by rak99** [comment]
Yeah now that you mention it, it does seem specific, that's completely fair. But great stuff, good luck on your further ventures mate!
