### ISSUE TITLE
Chat Render Issue

### ISSUE THREAD

**Issue by Ronaldo246** [lay295/TwitchDownloader#40]
When chat is finalising the render, i get an error saying, "ERROR: The pipe has been ended." with the peeposad bottom left saying "ERROR". VOD's and Chat Downloader works, just not the rendering stage.

EDIT: This is when im downloading a clip then rendering it and chat rendering.

**Comment by lay295** [comment]
Chat resolution has to be an even number in height and width, I was planning on adding a message next time. Let me know if that doesn't work.
