### ISSUE TITLE
Real time downloading

### ISSUE THREAD

**Issue by NeonVolta** [lay295/TwitchDownloader#400]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

i'm not sure if this is possible but it would be great if you could make a list of streamers to monitor and begin downloading the streams live as soon as they start along with settings for quality and chat download, the main reason i want this is some streamers don't make their vods public or twitch mutes large sections of the vods and this would help with archiving them properly

**Comment by ScrubN** [comment]
You can input the vod id of a running stream and it will download the entire stream up to live. Works better if you set it to less connections.

Example: BTMC has been streaming for a tad over 3 hours, starting with twitch rivals and now on osu
![1](https://user-images.githubusercontent.com/72096833/199315920-47309cfe-fe6a-4766-ab09-af4fdf056792.jpg)
By going to his videos page I can see the current vod for this stream, though the search vod window in the app also works
![2](https://user-images.githubusercontent.com/72096833/199316925-148745c2-9f3b-4795-a2c4-39991d1a3933.jpg)
![2_1](https://user-images.githubusercontent.com/72096833/199317240-0004a334-67b4-49a1-94ee-f6f752385f02.jpg)
Then set your preferences how you like, for the example I just set it to 360 and 1 thread, but depending on how long the vod is already you may want 2 or 3 threads to catch up
![3](https://user-images.githubusercontent.com/72096833/199317521-fde05df2-00ed-4bcb-bfa5-09fe22aeb301.jpg)

I'm not sure if this works on channels with vods disabled by default but it seems to me that the vod search window would probably work.

**Comment by ScrubN** [comment]
Also it will only download up to when you gave the the app the link. Yes this could be changed but I don't see it worth the trouble of rewriting the UI and some Core

**Comment by Zibbp** [comment]
I use [Streamlink](https://github.com/streamlink/streamlink) in [Ganymede](https://github.com/Zibbp/ganymede) and it works great. Streamlink provides a variety of options including the ability to remove ads.

**Comment by ScrubN** [comment]
> that doesn't work if the vod link isn't public which is one of the main reasons i requested this

Well the program downloads via a VOD ID. If neither of the ways I explained work then your request is impossible without full a rewrite of Core. I suggest you look into what glubsy and Zibbp mentioned, it will probably fit your needs.

**Comment by goldbattle** [comment]
I have a small program here if you want to download the live chat into the same format as this repo:
https://github.com/goldbattle/twitch_vods

The issue with getting things live, is you need to instead interface with the live stream api and chat IRC servers instead of the VOD system on twitch.

**Comment by goldbattle** [comment]
This won't be supported likely.
