### ISSUE TITLE
System.InvalidOperationException: Cannot access child value on Newtonsoft.Json.Linq.JValue.

### ISSUE THREAD

**Issue by Reuniko** [lay295/TwitchDownloader#401]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Describe your issue here

D:\Reuniko\TwitchDownloaderCLI>TwitchDownloaderCLI -m VideoDownload -u 1642266422 --ffmpeg-path ffmpeg.exe -o 1642266422.avi
Unhandled exception. System.AggregateException: One or more errors occurred. (Cannot access child value on Newtonsoft.Json.Linq.JValue.)
 ---> System.InvalidOperationException: Cannot access child value on Newtonsoft.Json.Linq.JValue.
   at Newtonsoft.Json.Linq.JToken.get_Item(Object key)
   at TwitchDownloaderCore.VideoDownloader.DownloadAsync(IProgress`1 progress, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at TwitchDownloaderCLI.Program.DownloadVideo(Options inputOptions)
   at TwitchDownloaderCLI.Program.Main(String[] args)

**Comment by ScrubN** [comment]
I'm unable to replicate using your exact input. Can you run `TwitchDownloaderCLI --version` to be sure you're using 1.50.5?

**Comment by Reuniko** [comment]
D:\Reuniko\TwitchDownloaderCLI>TwitchDownloaderCLI --version
TwitchDownloaderCLI 1.50.5


wierd, now its working, might be some kind of issue with twitch, cause I launched it right after stream ended

**Comment by gadi-playstream-gg** [comment]
@ScrubN  Since I'm downloading right after the stream has ended , I encounterd this issue several times. any idea how to solve this?

**Comment by ScrubN** [comment]
> @ScrubN Since I'm downloading right after the stream has ended , I encounterd this issue several times. any idea how to solve this?

I have a theory as to where the exception is thrown but I'm not 100% certain. Would you be willing to test a debug build? If so, what OS and GUI or CLI if applicable
