### ISSUE TITLE
Japanese chat messages not being rendered properly

### ISSUE THREAD

**Issue by FutanariPogging** [lay295/TwitchDownloader#402]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Describe your issue here

System: Windows 10

Problem: Chat rendering with Japanese VOD  always renders Japanese chat text as blank messages.
Specifics: It will display usernames in Japanese without issue, as well as emotes, but the actual messages they send won't have their Japanese text rendered

What I've done/checked:
JSON file has messages show up without issue
Changed settings such as mask rendering, encoding
Checked to make sure nothing was being filtered or ignored

![bug](https://user-images.githubusercontent.com/28612643/199878354-3095beb6-8f80-4b65-8977-a9d01bb312cd.png)
Above is a demonstration of how chat looks. I've seen other users have similar issues, but they've been resolved already.

**Comment by ScrubN** [comment]
Fixed, just wait for the PR merge :)

**Comment by FutanariPogging** [comment]
> Fixed, just wait for the PR merge :)

I can confirm that this issue has been fixed. Thanks!
