### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Gadzzaa** [lay295/TwitchDownloader#408]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Describe your issue here

![image](https://user-images.githubusercontent.com/60661008/200166075-a94b7c15-cfba-40ce-baad-392e6771a49c.png)
i barely got this screenshot, it crashes as soon as this message shows.

**Comment by Zibbp** [comment]
It appears you're attempting to launch the CLI. This needs to be done by opening a terminal, navigating to the directory, and executing the file like so `./TwitchDownloader.exe`. Double clicking the CLI will not work as you need to pass in arguments.
There is also a GUI version if you prefer which can be found at the same place you downloaded the CLI from as is named "release.zip".

**Comment by ScrubN** [comment]
This is not a crash. The program is simply closing because you did not execute it correctly and thus it had no actions to perform. In a future update there will now be a help message displayed in similar scenarios.
