### ISSUE TITLE
Chat JSON Property Order

### ISSUE THREAD

**Issue by striker4150** [lay295/TwitchDownloader#409]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

Hi, I would very much appreciate if chat files downloaded in the JSON format could have their properties ordered such that the `video` property comes before the `comments` property. As it is currently, the entire `comments` property of the JSON must be parsed and stored in memory before the correct video offset can be retrieved. Placing the `video` property before the `comments` property would allow processing the chat JSON as a stream, in situations where the file might be very large, and take up a lot of memory. Reordering the JSON properties can be done using the [[JsonPropertyOrder]](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonpropertyorderattribute) attribute, which was added in .NET 6. Sample usage of the attribute can be found [here](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/customize-properties?pivots=dotnet-6-0#configure-the-order-of-serialized-properties). The only changes necessary would be to add the `[JsonPropertyOrder]` attribute to the `ChatRoot` class properties in [ChatRoot.cs](https://github.com/lay295/TwitchDownloader/blob/611ae6a7e448709df627af0ef0dad9dfadb11586/TwitchDownloaderCore/TwitchObjects/ChatRoot.cs).

**Comment by ScrubN** [comment]
That seems pretty smart
