### ISSUE TITLE
VoD is delayed (audio is desync)

### ISSUE THREAD

**Issue by holeekebab** [lay295/TwitchDownloader#41]
hi! really love the program ! you are making my job as an editor so much easier and i really appreciate that!

i encountered 1 problem tho

recently when i start downloading vods it turns out the audio of the vods is desync

it wouldnt be a problem if the desync is even everywhere on the vod but turns out the desync gets higher and higher the longer the video gets, so you have to adjust video and sound every 10 minute .

https://www.twitch.tv/videos/634414213 
https://www.twitch.tv/videos/633443641 are the vods where i noticed that
i also tried it out with different random vods and same thing there

would appreciate help!

**Comment by lay295** [comment]
Yeah it's probably the same as #37, I just have to edit an argument when the mp4 is finalized. It should be fixed next release, which I'll probably release soon just for bug fixes.

**Comment by lay295** [comment]
Should hopefully be fixed in 1.25, feel free to reopen if its not including what program it gets desynced in. Thanks.
