### ISSUE TITLE
-bash: syntax error near unexpected token `1644029224'

### ISSUE THREAD

**Issue by TomGamerTV** [lay295/TwitchDownloader#411]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Describe your issue here

-bash: syntax error near unexpected token `1644029224'

**Comment by ScrubN** [comment]
Provide your input arguments. You likely made a typo
