### ISSUE TITLE
An error occurred while executing

### ISSUE THREAD

**Issue by weiweiiiiii** [lay295/TwitchDownloader#414]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Describe your issue here

![123456](https://user-images.githubusercontent.com/117614261/200214617-aec326bb-3c04-4339-a34e-6debfaece65c.PNG)
The first time I use the executive program, it runs like the above picture, How can I solve it?
thank you

**Comment by ScrubN** [comment]
That means you're using a version of windows that does not support system themes, and so the program will not automatically update its theme in accordance to windows. Besides that, the program should still work normally though. If it doesn't please tell me.

**Comment by weiweiiiiii** [comment]
Thanks for your reply, I look forward to program update 1.50.6 CLI <3

**Comment by Templayer** [comment]
How do I suppress this error? Where is a checkbox to suppress it?

**Comment by ScrubN** [comment]
> How do I suppress this error? Where is a checkbox to suppress it?

It should automatically be suppressed on older versions of windows in the next release after 1.50.6. If that's not the case please make a [new issue](https://github.com/lay295/TwitchDownloader/issues/new?assignees=&labels=bug&template=bug_report.yaml) about it and I will ask for more details
