### ISSUE TITLE
Output directory no longer being created

### ISSUE THREAD

**Issue by MitchellV3** [lay295/TwitchDownloader#417]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Describe your issue here

Using a script that was working correctly just days ago, I am now receiving errors when attempting to download chats as well as render them. If I manually create the output directory, everything still works fine. In the past, feeding the -o option a path would cause it to be created (if it did not already exist). I have tried multiple different scripts now and I am receiving this error every time. Thanks in advance.

> Unhandled exception. System.AggregateException: One or more errors occurred. (Could not find a part of the path 'E:\Video\DEMOLITION_D\Past-Broadcasts\2022-11\[Archive]\Chat\(2022-11-04) Halloween Day 16 SIGNALIS (Part 2) [v1643542670]-chat.json'.)
>  ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'E:\Video\DEMOLITION_D\Past-Broadcasts\2022-11\[Archive]\Chat\(2022-11-04) Halloween Day 16 SIGNALIS (Part 2) [v1643542670]-chat.json'.
>    at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String , FileMode , FileAccess , FileShare , FileOptions )
>    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
>    at System.IO.Strategies.OSFileStreamStrategy..ctor(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
>    at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 , Boolean )
>    at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 )
>    at System.IO.StreamWriter.ValidateArgsAndOpenPath(String , Boolean , Encoding , Int32 )
>    at System.IO.StreamWriter..ctor(String , Boolean , Encoding , Int32 )
>    at System.IO.StreamWriter..ctor(String , Boolean )
>    at System.IO.File.CreateText(String )
>    at TwitchDownloaderCore.ChatDownloader.DownloadAsync(IProgress`1 progress, CancellationToken cancellationToken)
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
>    at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
>    at System.Threading.Tasks.Task.Wait()
>    at TwitchDownloaderCLI.Program.DownloadChat(Options inputOptions)
>    at TwitchDownloaderCLI.Program.Main(String[] args)
>

**Comment by ScrubN** [comment]
>  In the past, feeding the -o option a path would cause it to be created (if it did not already exist).

Looking at the git history, ChatDownload should never have been able to create directories unless something was different in older versions of .NET

**Comment by MitchellV3** [comment]
Oh, that's strange, I'm not sure how I had it working before. Either way, thanks for the answer.
