### ISSUE TITLE
BTTV GIF emotes are rendered at unusual speeds

### ISSUE THREAD

**Issue by agenttud** [lay295/TwitchDownloader#42]
I've noticed some GIF emotes are rendered at abnormal speeds compared to their regular ones. Two examples I can give are monkaE and ABDULpls.

https://betterttv.com/emotes/5e10fd8c3267f72103fd4f25

https://betterttv.com/emotes/59a4ea2865231102cde26e9c 

You can see both examples within the first 30s of [this video](https://www.youtube.com/watch?v=IQP26vUR9k0). I could provide an example JSON as well, if you want.

**Comment by lay295** [comment]
Ahhhh, GIF frame times have always been kinda a pain. In this case they had some frames as 0 for some reason when I try and load them.

![](https://i.imgur.com/RtPD1ij.png)

By changing the 0 frame times to 10, it seems to be correct.  I'll try and get an update out within a day with this fix included.

![](https://i.imgur.com/mT9Iv1D.gif)

**Comment by lay295** [comment]
This should be fixed in the newest release 1.25, lemme know if it's not.
