### ISSUE TITLE
Word wrap problems (1.50.6)

### ISSUE THREAD

**Issue by HellbringerOnline** [lay295/TwitchDownloader#421]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Describe your issue here

Twitch
![image](https://user-images.githubusercontent.com/14059683/200747168-04820d5f-5aac-4c05-b161-229712b508f6.png)

TwitchDownloader
![image](https://user-images.githubusercontent.com/14059683/200747450-a649ee86-7701-4f3a-9260-99aed960c467.png)

**Comment by ScrubN** [comment]
I fixed this, however I wanted to ask if you care that it always splits at the end of the line rather than splitting at a `?` for URLs

**Comment by HellbringerOnline** [comment]
> I fixed this, however I wanted to ask if you care that it always splits at the end of the line rather than splitting at a `?` for URLs because that would require a slight rework
> 
> Also it **currently** does not respect right to left languages because it was getting pretty confusing to deal with both at the same time. Will probably modify to support RTL later

I think twitch adds a line break after the question mark if it's in a link, otherwise it adds a line break near the edge of the screen. Personally, I adhere to the idea that the render should be as similar as possible to the original chat

**Comment by ScrubN** [comment]
I've added `?` detection to wrap around. Twitch uses a link detection that must trigger before messages wrap at `?`s so non-link `???` spam messages with no spaces don't look weird but I don't want make a URL detector. This is a good enough compromise for me.
