### ISSUE TITLE
Video is 1 second late (1.50.6)

### ISSUE THREAD

**Issue by HellbringerOnline** [lay295/TwitchDownloader#422]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Describe your issue here

I tried to render the chat and found that the one second offset is still there

[Issue](https://github.com/lay295/TwitchDownloader/issues/384)

![image](https://user-images.githubusercontent.com/14059683/200748972-c865bc0d-8da1-4549-87e8-5e4001a8fe45.png)

**Comment by lay295** [comment]
Guess I should actually test my fixes huh
