### ISSUE TITLE
ERROR: Sequence contains no elements

### ISSUE THREAD

**Issue by KeyyBond** [lay295/TwitchDownloader#423]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Describe your issue here

I've got an error when trting to download a vod, I've literally been doing it for the past like like everyday and today i'm just getting a ERROR: Sequence contains no elements. 
Here is the vod if anything: https://www.twitch.tv/videos/1649167571

**Comment by ScrubN** [comment]
You need to provide the program with your Oauth token. Here's how to get it: https://www.youtube.com/watch?v=1MBsUoFGuls

**Comment by KeyyBond** [comment]
> e

Thank you so much

**Comment by ScrubN** [comment]
Personally I would keep the Oauth requirement to stay out of potential legal trouble
