### ISSUE TITLE
"1.xaml" not found crash

### ISSUE THREAD

**Issue by Templayer** [lay295/TwitchDownloader#425]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Describe your issue here

After updating to the latest version automatically (from 1.50.5 to 1.50.6) the application would not launch. It would tell me that it couldn't find "1.xaml", then it would tell me that it was unable to fetch the system theme... and then it would crash.

Not being able to fetch the system theme is not the source of the crash. The "1.xaml" file missing is.

To workaround the issue, I went to Themes, copied Dark.xaml and named the copy 1.xaml. Voila, the app now launches properly (but still bickers about the system theme fetching error, but that is already a different issue and doesn't cause the crash - but it didn't bicker about that in 1.50.5!).

And I seem to be able to download stuff just fine after the workaround:

![obrazek](https://user-images.githubusercontent.com/11728067/201493707-572ff3b6-0f02-4397-9088-7bf615b3cab2.png)

Operating system: Windows 7 64-bit Ultimate with pretty much everything customized. :^)

If needed, I can duplicate the problem and give any info you need... once I download that video, that is. ;)

**Comment by ScrubN** [comment]
This was just fixed in #415, please wait for the next release.
