### ISSUE TITLE
Fails to render video with JSON file from Twitch Chat Downloader

### ISSUE THREAD

**Issue by crackerbear** [lay295/TwitchDownloader#43]
I'm glad that you've added support for [Twitch Chat Downloader](https://github.com/PetterKraabol/Twitch-Chat-Downloader), however when I try to render a video, it fetches the required assets and renders the comments, but I only get a 1kb mp4 file and the output log shows: ```FINISHED. RENDER TIME: 0s SPEED: 0x```.

Even adding the [previous fix](https://github.com/lay295/TwitchDownloader/issues/28#issuecomment-622203625) to the tcd downloaded JSON file produces the same result.

Here's small example JSON file downloaded via tcd if you need to test for yourself: [642977658.zip](https://github.com/lay295/TwitchDownloader/files/4816238/642977658.zip)

**Comment by lay295** [comment]
Whoops, that's what I get for not testing I guess. I just made the fix and didn't test it because I was too lazy to download the program myself and download a chat, and didn't wanna do the long one you linked before.

Should be fixed in 1.26 (and I tested this time)

**Comment by crackerbear** [comment]
Thanks for the quick fix, I really appreciate it!
