### ISSUE TITLE
Ubuntu Inter Typeface Font Fallback Fails

### ISSUE THREAD

**Issue by goldbattle** [lay295/TwitchDownloader#432]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Command Line Interface

### Describe your issue here

Using ubuntu 18.04 with `-h 926 -w 274 --update-rate 0.1 --framerate 60 --font-size 15` as options.
[VOD 1651230100](https://drive.google.com/file/d/1cWXMmrPn_nh7Yl-Dh96q6O-rD64WCRJ9/view?usp=sharing)

1.40.7
![image](https://user-images.githubusercontent.com/2222562/202838158-717b07b4-2f09-49e2-9ba0-3fcfd8de94ca.png)

1.50.6
![image](https://user-images.githubusercontent.com/2222562/202838139-219867d4-b8c8-43ba-8aef-b41932611316.png)

**Comment by goldbattle** [comment]
The spaces seem to be much smaller, and the letters are not uniform / spaced correctly.

**Comment by ScrubN** [comment]
Used your exact inputs with 1.50.6 Win64 and it seems to be a Linux related issue. I wonder if `SkiaSharp Linux No Dependencies` has the issue too

![image](https://user-images.githubusercontent.com/72096833/202838789-00893e7e-f0c6-4cc2-8caf-87767f82aee9.png)

**Comment by goldbattle** [comment]
I ran `sudo apt-install fonts-inter` and it fixed it.
I don't think I had `sudo apt-get install fontconfig libfontconfig1` installed (should have read the updated readme).

**Comment by goldbattle** [comment]
Actually, I think there is support to use the internal font: https://github.com/lay295/TwitchDownloader/blob/cae9944710d26125c9cedac326f10668a75ca12f/TwitchDownloaderCore/ChatRenderer.cs#L125-L137

Will reopen as this might still be an issue (ie. fallback fails).

**Comment by ScrubN** [comment]
Inter embedded does not seem to work at all on Linux, which sucks on distros where Inter is not on the package manager like Debian. We probably have to extract it to a folder before reading it into memory, I'll do some testing

**Comment by ScrubN** [comment]
Fixed the issue. You can see both windows and linux render the same font and kerning now, the only difference is the subpixel rendering technique which is likely because ms has a copyright on the algorithm used in windows

Windows
![image](https://user-images.githubusercontent.com/72096833/202885912-8504c2c8-965c-4d30-b259-46e0b3d9a896.png)

Linux
![image](https://user-images.githubusercontent.com/72096833/202885921-24e84592-7e0d-49d6-a322-d69d6192daaf.png)

**Comment by ScrubN** [comment]
Correction: the fallback font on Linux is also different obviously but it seems to not support `:`s and probably several other chars. We should look into using a nerdfont instead and embed that just like we do with Inter
