### ISSUE TITLE
Emojis Causing Symbol Errors

### ISSUE THREAD

**Issue by goldbattle** [lay295/TwitchDownloader#433]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Command Line Interface

### Describe your issue here

Seeing that the dash `-` is not being rendered correctly using 1.50.6 compared to 1.40.7
On Ubuntu 20.04 with `-h 926 -w 274 --update-rate 0.1 --framerate 60 --font-size 15` as options.
[VOD 1651230100](https://drive.google.com/file/d/1cWXMmrPn_nh7Yl-Dh96q6O-rD64WCRJ9/view?usp=sharing)

Happens 1:01 into this VOD 1.40.7 render:
![image](https://user-images.githubusercontent.com/2222562/202837848-62435cbc-8cf5-4689-a3b0-d3e9c3dcb537.png)
5:46
![image](https://user-images.githubusercontent.com/2222562/202838451-ec212e2f-947d-42fe-b8e5-f661efa5cbd6.png)

But I get:
![image](https://user-images.githubusercontent.com/2222562/202837855-ef64b07b-8b56-454e-83bf-6f0640de61b5.png)
![image](https://user-images.githubusercontent.com/2222562/202838442-83920ce4-3056-4606-b560-ba68e382e752.png)

**Comment by goldbattle** [comment]
```
{"body":"Prediction Locked! 🔒 👀 - the choice with most wagered points is \"NOOOOOOO!!!!\" with 992513 points out of 1819471 points total. Good luck!","bits_spent":0,"fragments":[{"text":"Prediction Locked! 🔒 👀 - the choice with most wagered points is \"NOOOOOOO!!!!\" with 992513 points out of 1819471 points total. Good luck!","emoticon":null}],
```

```
{"body":"sodaNk 👍","bits_spent":0,"fragments":[{"text":"sodaNk","emoticon":{"emoticon_id":"emotesv2_6529543f7e344817a073ecf2f724e792","emoticon_set_id":""}}
```

Seems to be the emojis not being render properly.

**Comment by ScrubN** [comment]
You are correct, it is emojis not the dash.

Rendered on 1.50.6 CLI Win64
![image](https://user-images.githubusercontent.com/72096833/202838949-56751fd1-bfde-4bfc-a8f2-ff112e0cab2f.png)

**Comment by ScrubN** [comment]
Can you check if the folder `/tmp/TwitchDownloaderCLI/emojis` exists?

**Comment by goldbattle** [comment]
I forgot to add that I am using a temp folder with` --temp-path /tmp/tvc_render_segments/`

![image](https://user-images.githubusercontent.com/2222562/202839118-c4a08ea7-e185-4311-ada4-e4ae7ca85e6e.png)
![image](https://user-images.githubusercontent.com/2222562/202839127-fbfb6beb-f970-4969-ad31-8e45dd14fda7.png)
![image](https://user-images.githubusercontent.com/2222562/202839144-2a7fd9cb-b0dc-492c-b0d9-fff651b0a354.png)


`/tmp/TwitchDownloader/emojis`
![image](https://user-images.githubusercontent.com/2222562/202839217-a4f7fc62-e50d-48a1-98a5-7e7851d903af.png)


Both of these are empty (does it clear after render? I am *not* specifying --clear-cache).
I also was just testing on Windows, and it seems to work as expected, so seems to be related to my Linux machine.

**Comment by ScrubN** [comment]
No emojis are not cleared after render. I also just learned that the emoji extraction does not fully obey custom cache folders, I'll have to fix that. Can you check for me if your `/tmp/` directory contains a file named `tmp<randomchars>.tmp` with the MD5 `532479761d732e876c98ed03655acd62`? That's the emoji zip download that does not obey custom cache files and is not cleared after use.

**Comment by goldbattle** [comment]
Yes, that is getting downloaded (it isn't a full hash, but these have the twit emojis). I also have what I believe is from the older version `/tmp/emojis.zip`, but I am not sure if emojis have worked for me before in 1.40.7...
![image](https://user-images.githubusercontent.com/2222562/202839898-e7e1181e-30ef-494d-a67a-c335687f7c8d.png)
![image](https://user-images.githubusercontent.com/2222562/202839927-fb0e880d-e8ac-4169-8b2e-205a676df0ba.png)

**Comment by ScrubN** [comment]
> it isn't a full hash, but these have the twit emojis

That look like it's the correct zip. I wonder why it doesn't get extracted then.

Also you can get the MD5 hash of any file like so:
![image](https://user-images.githubusercontent.com/72096833/202839990-1d06d25f-3938-4ff4-9642-32c767d204f8.png)

**Comment by goldbattle** [comment]
I just deleted the whole cache folder, and now it seems to create some.
![image](https://user-images.githubusercontent.com/2222562/202840893-b8adaee4-b444-4b38-bd6d-a9feca3ffde4.png)
![image](https://user-images.githubusercontent.com/2222562/202840943-ecf9e96f-da2a-4658-87fd-538c2d96ef14.png)


But it doesn't seem to be in the `cache` directory.
Not sure why this directory is created....
![image](https://user-images.githubusercontent.com/2222562/202840930-f2d24fdf-9393-4328-a389-6595337d4ef7.png)

**Comment by ScrubN** [comment]
That's very weird. I was confused because my WSL test was populating the emojis folder

**Comment by goldbattle** [comment]
I just deleted the whole cache folder, and now it seems to create some.
![image](https://user-images.githubusercontent.com/2222562/202841037-3d0313e7-1d0d-47bc-b57c-53d6832e9b01.png)

But doesn't render correctly still
![image](https://user-images.githubusercontent.com/2222562/202841150-44dad593-9699-406f-9978-20e5046f865a.png)

**Comment by ScrubN** [comment]
That's very weird. I was confused because my WSL test was populating the emojis folder

**Comment by ScrubN** [comment]
Solved it. Patching now
