### ISSUE TITLE
Downloading highlight VOD's chat limits messages to 1 per second

### ISSUE THREAD

**Issue by aaronnuu** [lay295/TwitchDownloader#438]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Command Line Interface

### Describe your issue here

First of all, thanks for the great application. I'm just seeing an issue when downloading chat messages for `highlight` VODs only (the only ones I've tried besides `archive`, which work fine).

To be clear, when I say `highlight` I mean when I request chat for a VOD ID that I get back from the twitch API `https://api.twitch.tv/helix/videos` with `type=highlight` - this bug does not occur for `type=archive`.

An example of a command, with a valid VOD ID that I can see has the issue:

```
./TwitchDownloaderCLI --mode ChatDownload --output ./chat.json --id 1551067840
```

The problem is that the output of the `chat.json` file has a maximum of 1 chat message per second, even if the chat on the VOD has much many more messages than that.

I'm pretty sure the problem lies with this bit of code:

`TwitchDownloaderCore/ChatDownloader.cs:282`
```
SortedSet<Comment> commentsSet = new SortedSet<Comment>(new SortedCommentComparer());
```

Because this is defined as a `SortedSet` and has this corresponding `SortedSetComparer`:

`TwitchDownloaderCore/ChatDownloader.cs:553-559`
```
internal class SortedCommentComparer : IComparer<Comment>
{
    public int Compare(Comment x, Comment y)
    {
        return x.content_offset_seconds.CompareTo(y.content_offset_seconds);
    }
}
```

I think this is because it implements the `IComparer` interface, and is used as the `SortedSet` comparer, which automatically removes duplicate objects based on this comparison - i.e. only one object in this set can have each `content_offset_seconds` value.

This is how I understand it, I'm not too familiar with C# though so could be way off base.

I'm not totally sure why this doesn't affect the `archive` VODs, however it might be that one uses the old chat API and one uses the new one and they are handled differently? This is just a guess though.

Thanks!

**Comment by ScrubN** [comment]
> I think this is because it implements the IComparer interface, and is used as the SortedSet comparer, which automatically removes duplicate objects based on this comparison - i.e. only one object in this set can have each content_offset_seconds value.

You were pretty much on the mark. the `Compare(x, y)` method was being interpreted as a boolean value like `>0 == true`, `<=0 == false` when it should have been interpreted as `>= 0 == true`, `<0 == false` to allow for duplicates.

> I'm not totally sure why this doesn't affect the archive VODs, however it might be that one uses the old chat API and one uses the new one and they are handled differently? This is just a guess though.
Technically it did but archived VODs return comment offsets to 3 significant figures while highlights are rounded to an integer.
