### ISSUE TITLE
Failed VOD download leads to loss of hdd storage space

### ISSUE THREAD

**Issue by wetshrimp** [lay295/TwitchDownloader#44]
i had 40gb of storage and failed a vod download (9hrs, 720fps). I retried and it failed again (both led to ERROR). then i had no space left (65mb). 

Any way i can delete whatever is taking up space?

**Comment by lay295** [comment]
Yeah go to your windows explorer and type %temp%/TwitchDownloader and it should bring you here

![](https://i.imgur.com/2SduOuS.png)

There should be some folders which are just numbers containing .ts files, just delete those folders. I'll try and add better cleanup on errors in future versions.
