### ISSUE TITLE
Unable to save downloads to NTFS HDD

### ISSUE THREAD

**Issue by Frambooisier** [lay295/TwitchDownloader#443]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Command Line Interface

### Describe your issue here

```
[STATUS] - Downloading 100% (1/3)
[STATUS] - Combining Parts (2/3)
[STATUS] - Finalizing MP4 (3/3)
[NULL @ 0x557f7af8a2c0] Unable to find a suitable output format for '/mnt/WDJ/Recordings/'
/mnt/WDJ/Recordings/: Invalid argument

```

I was able to save file to main BTRFS ssd and to vFat pendrive but not to the NTFS HDD

**Comment by ScrubN** [comment]
Interesting, I'll do some testing on my Linux install. If it turns out to be NTFS not being supported then it's a .NET issue

**Comment by ScrubN** [comment]
![image](https://user-images.githubusercontent.com/72096833/203390301-04373aab-b490-442c-af1b-72cec151f6ea.png)

**Comment by Frambooisier** [comment]
The problem was something different, here is the command I used
```
flap@SFX:~> TwitchDownloaderCLI -m VideoDownload -u 12345678 -o /mnt/WDJ/Recordings/
[STATUS] - Downloading 99% (1/3)
[STATUS] - Combining Parts (2/3)
[STATUS] - Finalizing MP4 (3/3)
[NULL @ 0x55ce6092e2c0] Unable to find a suitable output format for '/mnt/WDJ/Recordings/'
/mnt/WDJ/Recordings/: Invalid argument
```

**I did not specify the name of the output file**, I may have gotten  confused while doing some testing and had only problems saving it to this drive while saving the same file to 3 different places without changing the name. Nevertheless it would be nice if CLI would assume default name and file format for the convenience of use. lets say with the output path /mnt/WDJ/Recordings/ the output would be VOD.mp4 if not specified also in the case of not providing the file format like /mnt/WDJ/Recordings/VOD the default assumed format would be .mp4
