### ISSUE TITLE
Recover cleared cache

### ISSUE THREAD

**Issue by dgSilver** [lay295/TwitchDownloader#446]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates

### Write stuff here

I foolishly cleared the cache trying to resolve the inability to fetch video data (was working fine just yesterday when I first ran it). Unbeknownst to me the "output" files on my external hard drive's twitchdownloader folder were the only functional ones (they were working despite downloader being forever stuck on finalizing). Is there any software to recover this sort of thing?

**Comment by ScrubN** [comment]
You can use [Recuva free](https://www.ccleaner.com/recuva) to recover recently deleted files on Windows. The longer you wait though, the more likely new files are written over the space that was previously the cache files
