### ISSUE TITLE
Segmentation Fault on Render

### ISSUE THREAD

**Issue by goldbattle** [lay295/TwitchDownloader#448]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Both

### Describe your issue here

I get a segmentation fault when rendering this VOD:
https://www.twitch.tv/videos/1657833950

https://drive.google.com/file/d/1MdDcFnE9zppHVhRT_7nyFdcMZvJ_LXYb/view?usp=sharing

Seems to fail here when I run through the editor:
![image](https://user-images.githubusercontent.com/2222562/204191452-91dc72fc-6868-4ec5-aad8-0c6e186f0dd5.png)

**Comment by goldbattle** [comment]
@ScrubN @lay295 do you think you could pull this bc9d09056c0331f20248ad150b4478d85757584f out into another PR so it can merge?
I have had to use a custom build instead of 1.50.7 because of this bug.

**Comment by ScrubN** [comment]
> @ScrubN @lay295 do you think you could pull this [bc9d090](https://github.com/lay295/TwitchDownloader/commit/bc9d09056c0331f20248ad150b4478d85757584f) out into another PR so it can merge? I have had to use a custom build instead of 1.50.7 because of this bug.

I'm pretty sure lay is reviewing the PR to merge it now
