### ISSUE TITLE
Prolly a dumb question, but, where's the .exe file?

### ISSUE THREAD

**Issue by DatDirectorGuy** [lay295/TwitchDownloader#45]
I extract the folder and open it but no .exe file. 

![Screenshot (55)](https://user-images.githubusercontent.com/56327178/87270372-c0f17c00-c484-11ea-990a-3a08062bab93.png)
![Screenshot (56)](https://user-images.githubusercontent.com/56327178/87270375-c4850300-c484-11ea-85e2-2bcca8f2e7a6.png)

**Comment by lay295** [comment]
https://github.com/lay295/TwitchDownloader/releases/

**Comment by DatDirectorGuy** [comment]
Thank you!
