### ISSUE TITLE
Any way to set time in file names and also set a default download folder?

### ISSUE THREAD

**Issue by fidorulz** [lay295/TwitchDownloader#450]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates

### Write stuff here

I finally got this to work and so far so good. 2 small questions

In settings you can change the name format for vods as per this picture

https://i.imgur.com/0wcZkuj.png

Is there any way to also have the time of the vod added to the name?

Also is there any way to set a default download folder or do you need to select every time?

**Comment by ScrubN** [comment]
> Is there any way to also have the time of the vod added to the name?

Do you mean the length of the vod or the stream date? If you mean date streamed, that's covered by `{date}` and `{date_custom}`

> Also is there any way to set a default download folder or do you need to select every time?

You have to select every time

**Comment by fidorulz** [comment]
I mean the time of the stream. So lets say the stream started at 21:00 you would see that time in the name along with the date

its a feature I used to use with twitchleecher which comes in handy if there are multiple streams with the same name on the same date

**Comment by ScrubN** [comment]
That is covered by `{date_custom="T"}`. You can see other formattings [here](https://learn.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings)
