### ISSUE TITLE
If one of the folders containing Downloader has a Semicolon, ";" in its name, downloader cannot open.

### ISSUE THREAD

**Issue by WaveSmashies** [lay295/TwitchDownloader#452]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

Title. It shows up in Task Manager for a bit, then closes. Moving it elsewhere fixes it, but that was annoying.

**Comment by ScrubN** [comment]
Can you explain better what the issue was? There are no semicolons in the release build process, nor the publish profiles

**Comment by WaveSmashies** [comment]
> e

If you place Twitch Downloader inside a folder which has ; in it's name, the software cannot open. I have a documents folder on one of my hard drives called "B; Documents" because Windows won't let you name folders with :. So I used a ;. When Twitch Downloader was in that folder, it wouldn't open. It's not the only program to have that issue as well.

**Comment by ScrubN** [comment]
> If you place Twitch Downloader inside a folder which has ; in it's name, the software cannot open. I have a documents folder on one of my hard drives called "B; Documents" because Windows won't let you name folders with :. So I used a ;. When Twitch Downloader was in that folder, it wouldn't open. It's not the only program to have that issue as well.

When you launch an application via its file, it creates a hidden console command that then executes the code of the file. The semicolon is used in the console to denote a new command on the same line. You should rename your folder.
