### ISSUE TITLE
Can't open the application

### ISSUE THREAD

**Issue by churrodude666** [lay295/TwitchDownloader#457]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates

### Write stuff here

Hi, first time user and I can't get the application to open. I tried release 1.50.6 and it was giving off the theme error message. So I've tried release 1.50.7 and aside from the known virus message, which i added as an exception in my antivirus, extracted ok. But then i can't open the application from the folder, I know I've probably done something wrong. Any help would be greatly appreciated, thanks.

**Comment by ScrubN** [comment]
1.50.7 will not be triggering any antivirus false positives. Additionally, I suspect this is probably a duplicate of #444. Please see if the build linked by qemjo works.

**Comment by churrodude666** [comment]
> As of 1.50.7, the application does not trigger antivirus false positives anymore.
> 
> I suspect this is probably a duplicate of #444. Please see if [1.50.8](https://github.com/lay295/TwitchDownloader/releases/tag/1.50.8) fixes your issue

Hi, pardon the late response. Issue is fixed, thank you for the help
