### ISSUE TITLE
Chat downloader only grabbing one message per second (VODs)

### ISSUE THREAD

**Issue by NovaPrima** [lay295/TwitchDownloader#458]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

This is similar to #438 I guess, but for full VODs, not highlights. I've been using it on Limmy's channel. He has 2.5-3k viewers so very frequently more than one message a second and these are being missed. It seems to happen on the vast majority of his VODs I try it on.

Example VOD: https://www.twitch.tv/videos/1660574480?filter=archives&sort=time

Chat from browser, first messages:

> 0:10 359_Ebin: what is going on....
> 0:11 fackinsteelz: !play
> 0:12 BeneathTheHeadphones: yep
> 0:12 mpceehammer: hey sexy
> 0:12 lew5150: morgign
> 0:13 SomeoneElseInChat: !play
> 0:14 aguywalkshomealoneatnight: EARLY
> 0:14 Leggsy: early :o
> 0:14 Dudsyyy: hello!
> 0:14 effsee_: awrite
> 0:14 BeaconDev: OLD MAN
> 0:15 Korean_Kangaroo: Hiyaaa
> 0:15 kracxl: christmas liggghts

From chat downloader:

> [0:00:10] 359_Ebin: what is going on.... 
> [0:00:11] fackinsteelz: !play 
> [0:00:12] BeneathTheHeadphones: yep 
> [0:00:13] SomeoneElseInChat: !play 
> [0:00:14] aguywalkshomealoneatnight: EARLY 
> [0:00:15] Korean_Kangaroo: Hiyaaa

**Comment by ScrubN** [comment]
Are you using 1.50.6 or 1.50.7?
