### ISSUE TITLE
CLI chat download returns 410 error but GUI works

### ISSUE THREAD

**Issue by crackerbear** [lay295/TwitchDownloader#459]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Command Line Interface

### Describe your issue here

When trying to download chat logs via the CLI I get the error message below:

```
>TwitchDownloaderCLI -m ChatDownload --id xxxxxxxxxx --timestamp-format Relative -o D:\Twitch\chat.txt

Unhandled exception. System.AggregateException: One or more errors occurred. (The remote server returned an error: (410) Gone.)
 ---> System.Net.WebException: The remote server returned an error: (410) Gone.
   at TwitchDownloaderCore.ChatDownloader.DownloadAsync(IProgress`1 progress, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at TwitchDownloaderCLI.Program.DownloadChat(Options inputOptions)
   at TwitchDownloaderCLI.Program.Main(String[] args)
```

It seems like [Twitch Chat Downloader](https://github.com/PetterKraabol/Twitch-Chat-Downloader) has the same problem and the reason is that the old twitch API is now gone and they've fully migrated to GraphQL.

However, using the GUI to download chat logs still works. Does the CLI and GUI use different methods of downloading?

**Comment by ScrubN** [comment]
The program uses both the old API and GQL, but prefers the old API while it's still available. The GUI and CLI both use the exact same function to download, it's more likely that it worked because some time had passed.

**Comment by crackerbear** [comment]
>it's more likely that it worked because some time had passed.

This definitely isn't the case for me. I have tried a dozen times consecutively with the CLI and it errors every time whereas the GUI works first try, I feel like the CLI doesn't use GQL at all.

Is there some way to show a log for the CLI or even force it to only use GQL?

**Comment by ScrubN** [comment]
> This definitely isn't the case for me. I have tried a dozen times consecutively with the CLI and it errors every time whereas the GUI works first try, I feel like the CLI doesn't use GQL at all.

The CLI does use GQL, I have debugged it many times. If CLI repeatedly does not work then I suspect you're not formatting the video id correctly.

> Is there some way to show a log for the CLI or even force it to only use GQL?

1.50.8 has removed v5.

**Comment by crackerbear** [comment]
Looks like I was using an old version of the CLI, I was under the impression I'd updated it, but apparently not. It works now, apologies for being dumb.
