### ISSUE TITLE
chat download in txt

### ISSUE THREAD

**Issue by Zetsssu** [lay295/TwitchDownloader#46]
can you add timestamps to txt? it's inconvenient without them

**Comment by lay295** [comment]
Yeah eventually, will be in the next release. I only really work on this in bursts every few weeks and is supported in the build I have currently.

**Comment by Zetsssu** [comment]
Thank you <3

**Comment by lay295** [comment]
In the 1.3 beta timestamps should be enabled by default for text chat downloads. I made the timestamp format the same as overrustlelogs. Let me know if it doesn't work for you.
