### ISSUE TITLE
No line breaks between messages in the latest version

### ISSUE THREAD

**Issue by Arhammahra** [lay295/TwitchDownloader#460]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

Chat messages don't have line breaks after downloading them using the latest version as of today, all the messages are in one continuous line.

**Comment by ScrubN** [comment]
Can you describe what you mean? Is this downloading? rendering? A picture would also be nice

**Comment by lay295** [comment]
It's with downloading plain chat's with the relative timestamps. Guessing it L42 was supposed to be sw.WriteLineAsync

https://github.com/lay295/TwitchDownloader/blob/2def0e91e5310cf641bd466131a8863d8bdee2ab/TwitchDownloaderCore/Tools/ChatText.cs#L33-L47
