### ISSUE TITLE
ERROR: Cannot access child value on Newtonsoft.Json.Linq.JValue.

### ISSUE THREAD

**Issue by Sadistic373** [lay295/TwitchDownloader#461]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

MOV/RLE
![Screenshot 2022-12-12 022739](https://user-images.githubusercontent.com/120340584/206985622-3aa4a4f3-13a5-4670-ae2d-c96e9d9c02ec.png)

**Comment by lay295** [comment]
Can you upload your json file here?

**Comment by Sadistic373** [comment]
> Can you upload your json file here?

[JSON FILE.zip](https://github.com/lay295/TwitchDownloader/files/10212346/JSON.FILE.zip)

**Comment by Sadistic373** [comment]
any updates? is it something on my end or some with the program

**Comment by ScrubN** [comment]
> any updates? is it something on my end or some with the program

I don't have time right now to check, but you can enable "verbose errors" in the settings for a more detailed error output to speed up diagnosing.

**Comment by Sadistic373** [comment]
> > any updates? is it something on my end or some with the program
> 
> I don't have time right now to check, but you can enable "verbose errors" in the settings for a more detailed error output to speed up diagnosing.

yeah sure i can do that brb

**Comment by Sadistic373** [comment]
> > > any updates? is it something on my end or some with the program
> > 
> > 
> > I don't have time right now to check, but you can enable "verbose errors" in the settings for a more detailed error output to speed up diagnosing.
> 
> yeah sure i can do that brb

![image](https://user-images.githubusercontent.com/120340584/207188893-8aaf97de-20d9-4772-9eba-7acde9e13a87.png)

here

**Comment by ScrubN** [comment]
The issue is something regarding 3rd party emotes. You can try turning off each of the providers individually to see if it works for now while we look further into it.

**Comment by Sadistic373** [comment]
> The issue is something regarding 3rd party emotes. You can try turning off each of the providers individually to see if it works for now while we look further into it.

turned off 7TV emotes, and its rendering now, maybe that helps?

**Comment by Sadistic373** [comment]
> The issue is something regarding 3rd party emotes. You can try turning off each of the providers individually to see if it works for now while we look further into it.

was half through rendering and then i got this 

![image](https://user-images.githubusercontent.com/120340584/207199036-c19973a7-6b1b-462b-a657-97bc29f06033.png)


any idea what it means??

**Comment by lay295** [comment]
Ffmpeg stopped working for some reason. Out of storage possibly? Just a guess

**Comment by ScrubN** [comment]
If not out of storage try the reset button in the ffmpeg tab

**Comment by ScrubN** [comment]
I've discovered the issue. Fix is nearly ready.

**Comment by lay295** [comment]
@ScrubN I fixed it in https://github.com/lay295/TwitchDownloader/commit/f795529ff41a738d1780c1e96a34dc4cbd6a498c unless you were thinking of doing something different

**Comment by ScrubN** [comment]
> @ScrubN I fixed it in [f795529](https://github.com/lay295/TwitchDownloader/commit/f795529ff41a738d1780c1e96a34dc4cbd6a498c) unless you were thinking of doing something different
> 
> I should really serialize these to actual objects one day since I don't really know how to use JObjects/JTokens well.

That works. I was going to separate the emote data functions so that the stacktrace shows who was at fault, up to you if you want that too

**Comment by lay295** [comment]
> > @ScrubN I fixed it in [f795529](https://github.com/lay295/TwitchDownloader/commit/f795529ff41a738d1780c1e96a34dc4cbd6a498c) unless you were thinking of doing something different
> > I should really serialize these to actual objects one day since I don't really know how to use JObjects/JTokens well.
> 
> That works. I was going to separate the emote data functions so that the stacktrace shows who was at fault, up to you if you want that too

Ye go for it if you want, I can wait on the merge

**Comment by ScrubN** [comment]
It's ready when you're ready
