### ISSUE TITLE
Can't download Clip Chat after 1.50.9

### ISSUE THREAD

**Issue by mohad12211** [lay295/TwitchDownloader#463]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Both

### Describe your issue here

![image](https://user-images.githubusercontent.com/51754973/207081489-0dceed78-1f50-42aa-8d2e-e09e0227e31c.png)
![image](https://user-images.githubusercontent.com/51754973/207081537-3b8c601c-d1ba-4775-a3c4-3de8d2aa482a.png)

**Comment by ScrubN** [comment]
Can you enable "verbose errors" in the settings?

**Comment by ScrubN** [comment]
It looks like the clip was deleted before you downloaded the chat.

**Comment by ScrubN** [comment]
Looks like this was fixed in 9ade1d3319fbe9e31698eaeeca1c708150fd6d0c
