### ISSUE TITLE
 ERROR: The pipe has been ended 

### ISSUE THREAD

**Issue by Sadistic373** [lay295/TwitchDownloader#465]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

![image](https://user-images.githubusercontent.com/120340584/207220771-9624463b-d676-431b-9ead-040f77b56259.png)

For more context ig, im downloading in to a 50 GB pendrive, i dont think it is possible because of  a lack of storage. it reaches 66% and ends the pipeline for me.

downloaded a much smaller chat mov in to the pendrive and that worked fine, idky there is a problem this time around. the only things that I really changed was the text size and maybe dimensions.

**Comment by ScrubN** [comment]
I think the 1.50.8/1.50.9 update caused an issue with the ffmpeg args tab of the chat render page.

Click the reset ffmpeg args button. If it crashes, keep trying until it doesn't crash.

**Comment by Sadistic373** [comment]
> I think the 1.50.8/1.50.9 update caused an issue with the ffmpeg args tab of the chat render page.
> 
> Click the reset ffmpeg args button. If it crashes, keep trying until it doesn't crash.
> 
> Also thank you for finding the verbose error output on your own!

than you! but i think i might need you to help me with this one lol, when you say reset ffmpeg args button, are you talking aobut chat render>ffmpeg>reset to default?

**Comment by ScrubN** [comment]
> than you! but i think i might need you to help me with this one lol, when you say reset ffmpeg args button, are you talking aobut chat render>ffmpeg>reset to default?

Yes

**Comment by Sadistic373** [comment]
> > than you! but i think i might need you to help me with this one lol, when you say reset ffmpeg args button, are you talking aobut chat render>ffmpeg>reset to default?
> 
> Yes

thanks

**Comment by ScrubN** [comment]
> I think the 1.50.8/1.50.9 update caused an issue with the ffmpeg args tab of the chat render page.

I have no clue. I ran into an issue while developing where the ffmpeg tab unloaded and crashed 3 times in a row (until clicking reset) and 2 other people have reported pipe errors. Just updated 1.50.7 -> 1.51.0 on my laptop and nothing happened.

**Comment by Sadistic373** [comment]
> > I think the 1.50.8/1.50.9 update caused an issue with the ffmpeg args tab of the chat render page.
> 
> I have no clue. I ran into an issue while developing where the ffmpeg tab unloaded and crashed 3 times in a row (until clicking reset) and 2 other people have reported pipe errors. Just updated 1.50.7 -> 1.51.0 on my laptop using the builtin updater and nothing happened.

been trying for like hours now, same problem, it just breaks, even got a new json file and it still has the same problem idky, kinda tempted to downgrade to an older version until this gets fixed lmao

**Comment by lay295** [comment]
Of the 50gb pen drive, how much is free when you're rendering?

It's not gonna be ffmpeg arguments related, because if it was it wouldn't get so far into the render. Unless something has changed with @ScrubN's PR I don't think there should be any difference between the previous version. Can give the old version a try.

**Comment by ScrubN** [comment]
> Of the 50gb pen drive, how much is free when you start rendering?
> 
> It's not gonna be ffmpeg arguments related, because if it was it wouldn't get so far into the render. Unless something has changed with @ScrubN's PR I don't think there should be any difference between the previous version. Can give the old version a try.

There should not have been any changes to the render pipeline that would cause a pipe end error. Ffmpeg disposal wasn't touched.

**Comment by Sadistic373** [comment]
> Of the 50gb pen drive, how much is free when you start rendering?
> 
> It's not gonna be ffmpeg arguments related, because if it was it wouldn't get so far into the render. Unless something has changed with @ScrubN's PR I don't think there should be any difference between the previous version. Can give the old version a try.

total is 57.6GB, iand there is 54.3 GB of free space left

**Comment by ScrubN** [comment]
> total is 57.6GB, iand there is 54.3 GB of free space left, it isnt a lack of storage issue

@lay295 is it possible that the thumb drive IO queue is full and we need to wait for it?

**Comment by lay295** [comment]
> > total is 57.6GB, iand there is 54.3 GB of free space left, it isnt a lack of storage issue
> 
> @lay295 is it possible that the thumb drive IO queue is full and we need to wait for it?

I really doubt.

@Sadistic373 

Give the "DebugIgnoreMe.zip" on the 5.10.0 release download page a go.

Made a change to just log the entire ffmpeg to the verbose output if the pipe has ended (not in an actual release).
I imagine since the crash it happening mid render the log will be quite large and won't fit in the message box. It should be copied to your clipboard and you can post it on like pastebin.

![image](https://user-images.githubusercontent.com/1060681/207247523-fe769971-27f6-4392-b027-c7a6d80749b8.png)

I always wanted a bit better logging for the pipe ended so this is as good an excuse as ever I guess to do it I guess. I'll probably make my own custom message box that has a scrollbar for the next release.

**Comment by lay295** [comment]
Also you mentioned that the Codec you're using is RLE right? Because yeah RLE shouldn't get massive, ProRes on the other hand... would be very believable

**Comment by Sadistic373** [comment]
> 

yeah im using rle, i give the debugignoreme zip a whirl and get back to you. brb

**Comment by Sadistic373** [comment]
@lay295 could you just send me the link to the zip, this taking sometime to get used to navigating github

**Comment by Sadistic373** [comment]
> > > total is 57.6GB, iand there is 54.3 GB of free space left, it isnt a lack of storage issue
> > 
> > 
> > @lay295 is it possible that the thumb drive IO queue is full and we need to wait for it?
> 
> I really doubt.
> 
> @Sadistic373
> 
> Give the "DebugIgnoreMe.zip" on the 5.10.0 release download page a go.
> 
> Made a change to just log the entire ffmpeg to the verbose output if the pipe has ended (not in an actual release). I imagine since the crash it happening mid render the log will be quite large and won't fit in the message box. It should be copied to your clipboard and you can post it on like pastebin.
> 
> ![image](https://user-images.githubusercontent.com/1060681/207247523-fe769971-27f6-4392-b027-c7a6d80749b8.png)
> 
> I always wanted a bit better logging for the pipe ended so this is as good an excuse as ever I guess to do it I guess. I'll probably make my own custom message box that has a scrollbar for the next release.

tried it twice, still doesnt work, turned on verbose errors to get a log, but a separate window doesnt pop up to show me a log like it did with the older ver.  dk if that was intentional or not. but yeah anything else i can do on my end or no?

**Comment by ScrubN** [comment]
> tried it twice, still doesnt work, turned on verbose errors to get a log, but a separate window doesnt pop up to show me a log like it did with the older ver. dk if that was intentional or not. but yeah anything else i can do on my end or no?

Weird. I'll make a different debug build and post it to my fork

**Comment by ScrubN** [comment]
Debug build is live at https://github.com/ScrubN/TwitchDownloader/releases. Make sure to enable verbose errors and it will popup with 2 message boxes. It will also create 'ffmpegerror.txt' in the execution directory and copy the error to your clipboard

**Comment by ScrubN** [comment]
I should have asked. Are you writing to a mask? Because lay forgot to add the log to the mask process

**Comment by Sadistic373** [comment]
> Debug build is live at https://github.com/ScrubN/TwitchDownloader/releases. Make sure to enable verbose errors and it will popup with 2 message boxes. It will also create 'ffmpegerror.txt' in the execution directory and copy the error to your clipboard

k im rendering rn

**Comment by ScrubN** [comment]
In the off chance that this new build *still* does not yield results I have made a few more changes to log *everything* in <kbd>MoreDetailedDebugBuild.zip</kdb>

**Comment by Sadistic373** [comment]
> I should have asked. Are you writing to a mask? Because lay forgot to add the log to the mask process

![image](https://user-images.githubusercontent.com/120340584/207275184-3e1227d0-66f5-4586-b953-c8e8140e7fb3.png)
 got it

**Comment by ScrubN** [comment]
> > I should have asked. Are you writing to a mask? Because lay forgot to add the log to the mask process
> 
> ![image](https://user-images.githubusercontent.com/120340584/207275184-3e1227d0-66f5-4586-b953-c8e8140e7fb3.png) got it

Upload ffmpegerror.txt too please

**Comment by ScrubN** [comment]
The file should have been created in the same folder as the application

**Comment by Sadistic373** [comment]
> The file should have been created in the same folder as the application

[ffmpegerror.txt](https://github.com/lay295/TwitchDownloader/files/10216273/ffmpegerror.txt)
 
found it

**Comment by ScrubN** [comment]
Here is what ffmpeg reported as the error:
```
av_interleaved_write_frame(): No space left on device
Error writing trailer of D:\[12-7-22] TommyKayLIVE - SPARTA IN CK 3 FINALLY NO CANCER LETS FIND OUT!  20 GIFTED = 1 PERSONAL CHRISTMAS CARD - Chat.mov: No space left on device
video:4194535kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!
```

In other words, it thinks there is no space left on the used drive. Once again, I suspect it may be the IO queue filling up and ffmpeg is interpreting it as a full drive

**Comment by Sadistic373** [comment]
> Here is what ffmpeg reported as the error:
> 
> ```
> av_interleaved_write_frame(): No space left on device
> Error writing trailer of D:\[12-7-22] TommyKayLIVE - SPARTA IN CK 3 FINALLY NO CANCER LETS FIND OUT!  20 GIFTED = 1 PERSONAL CHRISTMAS CARD - Chat.mov: No space left on device
> video:4194535kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
> Conversion failed!
> ```
> 
> In other words, it thinks there is no space left on the used drive. Once again, I suspect it may be the IO queue filling up and ffmpeg is interpreting it as a full drive, because there's no way a chat render can be 50gb unless your dimensions are more than 10x default for a 6+ hour chat

any advice on how to clear or even stop the IO queue filling up?

**Comment by ScrubN** [comment]
> any advice on how to clear or even stop the IO queue filling up?

Don't use a USB drive ¯\\\_(ツ)\_/¯

**Comment by Sadistic373** [comment]
> > any advice on how to clear or even stop the IO queue filling up?
> 
> Don't use a USB drive ¯\_(ツ)_/¯

https://tenor.com/view/esqueleto-gif-24452082

**Comment by Sadistic373** [comment]
> > any advice on how to clear or even stop the IO queue filling up?
> 
> Don't render directly to a USB drive ¯\_(ツ)_/¯
> 
> Lowering the framerate and/or dimensions may also help
> 
> Also keep in mind this is just my first guess and not a definite diagnosis

ye ye, take you time, but ill try confirming you suspicions, empty some of my files on to the the pen drive and the download the chat on the hardware instead

**Comment by Sadistic373** [comment]
ig this wont be that high up on the fix list, but pls

**Comment by ScrubN** [comment]
> ik this wont be that high up on the fix list, but pls

I honestly don't know if there's any way for us to do anything about this. We're piping directly into a separate ffmpeg process, so there might not be much that we can do.

**Comment by Sadistic373** [comment]
> > ik this wont be that high up on the fix list, but pls
> 
> I honestly don't know if there's any way for us to do anything about this. We're piping directly into a separate ffmpeg process, so there might not be much that we can do.
> 
> Edit: I just googled something and there might actually be a way to fix this. Are you able to test one more time? :)

cant rn, ill be able to run a test in a couple of hours tho

**Comment by ScrubN** [comment]
I've updated the debug build to potentially fix the IO queue issues. Please test it when you can, I don't have any slow thumb drives left in my house

**Comment by ScrubN** [comment]
So I tortured one of my thumb drives with a benchmark + 5 file copies at once and the renderer halted as expected. My theory has switch from the IO queue filling up to your drive briefly disconnects during writes. If that's the case, the updated debug build should still fix the issue.

**Comment by Sadistic373** [comment]
> So I tortured one of my thumb drives with a benchmark + 5 file copies at once and ffmpeg halted, so it is able to recognize a full IO queue. My theory is now that your drive briefly disconnects during writes. If that's the case, the updated debug build from yesterday should ideally still fix the issue or create a different custom error. The name of the zip is the same as the old build but it is different.

just tested it out and yeah you're rights it fixed

**Comment by Sadistic373** [comment]
> So I tortured one of my thumb drives with a benchmark + 5 file copies at once and ffmpeg halted, so it is able to recognize a full IO queue. My theory is now that your drive briefly disconnects during writes. If that's the case, the updated debug build from yesterday should ideally still fix the issue or create a different custom error. The name of the zip is the same as the old build but it is different.

one more thing tho, idk if this is a twitch downloader issue or my editing software issue, but when ever i render a vod that i got from the twitch downloader the audio sync is off by a couple of seconds, i would usually chalk it up the editing software, but this never really happened when i downloaded the vod through other sources

**Comment by ScrubN** [comment]
> just tested it out and yeah you're rights it fixed

Awesome. I'll make a PR to fix that.

> one more thing tho, idk if this is a twitch downloader issue or my editing software issue, but when ever i render a vod that i got from the twitch downloader the audio sync is off by a couple of seconds, i would usually chalk it up the editing software, but this never really happened when i downloaded the vod through other sources

Very likely your editing software. Try opening the vod in VLC and see if the audio is still desynced

**Comment by Sadistic373** [comment]
>
just tested it out and yeah you're rights it fixed

Awesome. I'll submit the changes in a PR.

one more thing tho, idk if this is a twitch downloader issue or my editing software issue, but when ever i render a vod that i got from the twitch downloader the audio sync is off by a couple of seconds, i would usually chalk it up the editing software, but this never really happened when i downloaded the vod through other sources

Very likely your editing software. Try opening the vod in VLC and see if the audio is still desynced

 looked in to it somemore, its was a frame issue, dw about it
