### ISSUE TITLE
Chat Render stops working/hangs after a while

### ISSUE THREAD

**Issue by Reimaginated** [lay295/TwitchDownloader#469]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

Currently running the Windows GUI version 1.51.0 and trying to render a chat from yesterday and today, but it eventually stops working. Both the Time Remaining and Elapsed Time stop moving. I use MP4 and have tried all the encodings (H.264, H.264 NVENC, H.265) and default ffmpeg values but the chat from today stops at around 28% and the one from yesterday stops at around 24%. 
I've also tried creating Highlights of the VODs and tried downloading Chat from those but it still won't work. It's most likely a problem on Twitch's end, but is there any way around this? I haven't tried turning off the emotes but I prefer to have those enabled.

![0FNNQmB](https://user-images.githubusercontent.com/20010408/207395629-32b8cc69-99c8-46b9-8475-91514dd37665.png)

![NG3REoP](https://user-images.githubusercontent.com/20010408/207395668-34de86a9-bfec-4731-958b-16e3f449dfe2.png)

![E2rr3pc](https://user-images.githubusercontent.com/20010408/207395688-33071968-ea91-4eba-baf2-a3fc403c930b.png)

**An example of it "freezing" at 28%**
![Dzfncw2](https://user-images.githubusercontent.com/20010408/207397618-5bd78565-d6eb-4b72-9b88-00e7ded5ac8e.png)

The JSONs were too large to upload but these were the VOD IDs used respectively:
2022-12-13: https://www.twitch.tv/videos/1677833097 `1677833097`
2022-12-12: https://www.twitch.tv/videos/1677580640 `1677580640`

#Edit:
Just found something very strange. I tried rendering the same JSON with 1.40.7 and it worked, but the 1.50.8, 1.50.9, and 1.51.0 GUIs all "froze".

**Comment by lay295** [comment]
Seems to be an edge case from #424 

https://github.com/lay295/TwitchDownloader/blob/6edf1070163b090ab67768cc10894ed9f63bb479/TwitchDownloaderCore/ChatRenderer.cs#L787-L791

'?' character is at index 0 of inputText so inputText is just an empty string, and we get an infinite loop. My fix would just to be adding a +1 to the index. Which is what I'll do later today unless @ScrubN has a different idea for the fix.

return inputText.Slice(0, delimiterIndex + 1).ToString();

**Comment by ScrubN** [comment]
> Seems to be an edge case from #424
> 
> https://github.com/lay295/TwitchDownloader/blob/6edf1070163b090ab67768cc10894ed9f63bb479/TwitchDownloaderCore/ChatRenderer.cs#L787-L791
> 
> '?' character is at index 0 of inputText so inputText is just an empty string, and we get an infinite loop. My fix would just to be adding a +1 to the index. Which is what I'll do later today unless @ScrubN has a different idea for the fix. The intention was to line break at '?' so it will stay on the same line, which I think still matches with the original intent.
> 
> return inputText.Slice(0, delimiterIndex + 1).ToString();

Change it to

`if (delimiterIndex > 0)`

**Comment by ScrubN** [comment]
> Seems to be an edge case from #424
> 
> https://github.com/lay295/TwitchDownloader/blob/6edf1070163b090ab67768cc10894ed9f63bb479/TwitchDownloaderCore/ChatRenderer.cs#L787-L791
> 
> '?' character is at index 0 of inputText so inputText is just an empty string, and we get an infinite loop. My fix would just to be adding a +1 to the index. Which is what I'll do later today unless @ScrubN has a different idea for the fix. The intention was to line break at '?' so it will stay on the same line, which I think still matches with the original intent.
> 
> return inputText.Slice(0, delimiterIndex + 1).ToString();

Yeah that seems good. I rewrote that method to be really fast because measuring is super slow and it seems I missed a thing
