### ISSUE TITLE
Error during Chat Render

### ISSUE THREAD

**Issue by Syvant** [lay295/TwitchDownloader#47]
Error happens during/after fetching emotes:
ERROR: Object reference not set to an instance of an object.

**Comment by lay295** [comment]
Can you upload a json you're trying to render along with a screenshot of the settings you're using?

**Comment by Syvant** [comment]
Here's the JSON file I'm trying to render:
[https://drive.google.com/file/d/19qSEe9pA4iU7m7HV4zI6JfbjJqv5V6oa/view?usp=sharing](URL)

and these are the settings I am using for the chat render:
![image](https://user-images.githubusercontent.com/40413279/89469764-c23e5d80-d73f-11ea-9953-ff3c922f2e44.png)

**Comment by lay295** [comment]
Well, I've never had a null comment before. I'll add a check in the next version so this error doesn't happen.

Here is a fixed version of the JSON if you want to render it before the new version is out.
https://drive.google.com/file/d/1E_YkCavnA4F7LRahYjRaqhDWdBTzlUq1/view?usp=sharing

![image](https://user-images.githubusercontent.com/1060681/89487659-106d5400-d774-11ea-83ca-94b7459027d9.png)

**Comment by lay295** [comment]
Should be fixed in [1.3 beta](https://github.com/lay295/TwitchDownloader/releases/tag/1.30-beta). Let me know if it's not, thanks for the report.
