### ISSUE TITLE
Cant Change update time to true 0 (old version's chat is faster)

### ISSUE THREAD

**Issue by Nutri626** [lay295/TwitchDownloader#473]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

Hello, so i have been still using old version because newer versions had problem with update time 0, by that i mean with old program chat moves really fast cos its true 0 i guess but in newer versions if you put 0 or 0.0 or anything i believe it still registers as 1 cos chat is "lagging" and is not so smooth as old versions (really noticeable with fast paced chats) , sadly you cant even download chat with old version anymore so i hope this problem is fixed in newer versions before old one competitively dies

**Comment by lay295** [comment]
Json files to compare would be nice :) if you put a 0 it should still register as 0. There were some internationalization parsing issues fixes with that number but 0 should have always worked I think.

It's possible Twitch is just less granular in the time they give back with the GQL API. It would probably be possible to "simulate" old behavior if that's the case and people would want that.

**Comment by ScrubN** [comment]
> as i said if we use exact same json file to render with old and new program the old one is much "faster" and smooth and newer has kinda 0.1 sec delay in it, its clearly visible with faster chats
> 
> idk you can test it yourself, here is json of like 10 second chat https://easyupload.io/cke0j6

Fixed it :)

**Comment by lay295** [comment]
Glad @ScrubN fixed it :D

Taking a quick peek at the GQL response though, they indeed only send back the comment offset to the nearest second now. So, while it will fix the rendering of old chat files new ones will continue to have the problem because Twitch no longer sends us that info (unless I'm missing something obvious here)

**Comment by ScrubN** [comment]
> Glad @ScrubN fixed it :D
> 
> Taking a quick peek at the GQL response though, they indeed only send back the comment offset to the nearest second now. So, while it will fix the rendering of old chat files new ones will continue to have the problem because Twitch no longer sends us that info (unless I'm missing something obvious here)

GQL only floors to the second on highlights, archives, and clips. VODs still return the full fractional seconds before expiring unless they changed something in the last 2 weeks.

**Comment by Nutri626** [comment]
> > Glad @ScrubN fixed it :D
> > Taking a quick peek at the GQL response though, they indeed only send back the comment offset to the nearest second now. So, while it will fix the rendering of old chat files new ones will continue to have the problem because Twitch no longer sends us that info (unless I'm missing something obvious here)
> 
> GQL only floors to the second on highlights, archives, and clips. VODs still return the full fractional seconds before expiring unless they changed something in the last 2 weeks.
> 
> Edit: it seems something has indeed changed in the last 2 weeks. Unfortunate.



hmm maybe you are right, i noticed it with old jsons but with new its almost same result ... thats really unfortunate if its twitchs problem ... fast paced chat seems so much better with old program/jsons
