### ISSUE TITLE
Control Over Frames

### ISSUE THREAD

**Issue by Sadistic373** [lay295/TwitchDownloader#478]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

I'm not sure if you are able to already do this but it would be nice to exercise some control over the frames when downloading the VOD.

**Comment by lay295** [comment]
You'd need to explain a bit more what you want, but considering we do not re-encode the video file downloaded whatever you're asking for we probably will not do.
