### ISSUE TITLE
More control over formatting and badge scaling

### ISSUE THREAD

**Issue by EricThePooh** [lay295/TwitchDownloader#480]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

I would love for there to be more controls over the text formatting. I'm currently trying to match the appearance of the chat to how the chat appears on stream, but the biggest issues I'm running into are the line spacing and kerning. I would also love for there to be a chat badge scaling option like the one for emotes.

Here's an example of what I mean. The rendered chat is on the left, and the on-stream chat is on the right.

[Example image](https://imgur.com/a/ShvfwNj)

**Comment by lay295** [comment]
I could probably expose options for scaling the badges and the vertical padding. 
I think the kerning mostly looks fine though? The font weight seems a bit bigger on the right one and the font size does seem a bit smaller on the left though. Which font are you using?

I do watch the coffee cow's YouTube videos every day though.

**Comment by EricThePooh** [comment]
Haha I'm actually one of his editors, so I'm using the same font (it's Segue UI Bold btw). Kerning isn't a big deal, just something I noticed was off between the 2. But really it's the line spacing that I would love to adjust, and that's not something I can change with a font.

Anyway, thanks for the app! I've found it very useful

**Comment by ScrubN** [comment]
> edit: actually, you're right about the font it is a bit different.... hmm

Twitch uses these fonts in descending priority depending on which are installed on your pc:
`Inter`,`Roobert`,`Helvetica Neue`,`Helvetica`,`Arial`,`sans-serif`

You can verify by using inspect element and viewing the computed for any chat message or by visiting the ['core' stylesheet](https://static.twitchcdn.net/assets/core-8596384aec2502e60a6e.css) and finding the `--font-base` variable
![Computed](https://user-images.githubusercontent.com/72096833/208354454-b765640e-43be-48c0-a992-16c0ff657588.jpg)

**Comment by EricThePooh** [comment]
I appreciate it! I might check that out, but idk if it's that relevant. The chat display he has on screen comes from a 3rd party site I can't recall the name of, but it had a limited number of fonts to pick from. I just went with the one that I thought most closely resembled it, but I guess I was just wrong.

I'm not too concerned about it though since it looks close enough.

**Comment by lay295** [comment]
@EricThePooh You can give this build a try which is from https://github.com/lay295/TwitchDownloader/commit/ca2ff0491564c66097ca181d9bf0db130acf7bfa
https://drive.google.com/file/d/1pkOba5rC8LwFbLYbDgsehqIvoZtSSX8r/view?usp=share_link

Or can wait a few more days until a release comes out with the scaling options.

**Comment by EricThePooh** [comment]
Sick! I’ll check it out From: Lewis PardoSent: Sunday, December 25, 2022 10:07 PMTo: lay295/TwitchDownloaderCc: EricThePooh; MentionSubject: Re: [lay295/TwitchDownloader] More control over formatting and badge scaling (Issue ***@***.*** You can give this build a try which is from ca2ff04https://drive.google.com/file/d/1pkOba5rC8LwFbLYbDgsehqIvoZtSSX8r/view?usp=share_linkOr can wait a few more days until a release comes out with the scaling options.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by ScrubN** [comment]
A public pre-release build with this will be coming out soon!

**Comment by EricThePooh** [comment]
Sick
________________________________
