### ISSUE TITLE
Arabic not rendering correctly

### ISSUE THREAD

**Issue by ScrubN** [lay295/TwitchDownloader#484]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Both

### Describe your issue here

Some or all Arabic may not be rendering correctly. 1.50.7 also has the problem but as far as I can tell 1.50.6 does not

Source
![image](https://user-images.githubusercontent.com/72096833/208596381-6015cfad-a499-465b-98f7-5901ff9a36c8.png)

1.50.7 - Master
![image](https://user-images.githubusercontent.com/72096833/208595533-a5dd9b44-525e-4746-bfcb-8f7886bea073.png)

1.50.6
![image](https://user-images.githubusercontent.com/72096833/208596288-80ce1a1d-43e3-490b-a5dc-0c3b161c1151.png)

**Comment by ScrubN** [comment]
I'm looking at the diff for ChatRenderer.cs 1.50.6 -> 1.50.7 and I honestly can't figure it out.

**Comment by ScrubN** [comment]
RTL is rendered as expected in #424

**Comment by ScrubN** [comment]
RTL is not rendered as expected in #437

**Comment by ScrubN** [comment]
Rendered using #437 as the base but using #424's ChatRenderer.cs and the RTL is rendered incorrectly. What..?

**Comment by ScrubN** [comment]
> RTL is not rendered as expected in #437. That PR didn't touch rendering at all though and the previous commit to ChatRenderer.cs was from #424

Just realized that the conflict merge commit was pushed to the branch along with everything from master up to then.

**Comment by ScrubN** [comment]
Found the problem. It doesn't seem like it should have, but this line change is what caused it all.
https://github.com/lay295/TwitchDownloader/blob/b5139e627baaad710181b107e4f68e1fb70b9316/TwitchDownloaderCLI/Modes/Arguments/ChatRenderArgs.cs#L47-L50
Yes, really. Fixing the CLI not using the embedded Inter font broke RTL rendering. I don't know why.

**Comment by ScrubN** [comment]
https://github.com/rsms/inter/issues/523#issuecomment-1345651926 It looks like it's official that Inter doesn't support Arabic and yet it has some Arabic glyphs.

**Comment by mohad12211** [comment]
while we are at it, the picture for 1.50.6 you posted has another problem.
this is what twitch shows
![image](https://user-images.githubusercontent.com/51754973/208712355-3cc420be-4c11-4f9a-a3e2-acbba53a7e79.png)
the spacing between words is not correct

**Comment by ScrubN** [comment]
![image](https://user-images.githubusercontent.com/72096833/208812764-3535095d-45c2-4b62-a987-9463b0776493.png)
So I fixed both block arts and arabic rendering, but in order to achieve this I had to give it an invalid font. Using any valid font produced this for arabic:
![image](https://user-images.githubusercontent.com/72096833/208812942-4ff8b33a-e837-49c0-82b5-56f751531f9d.png)

**Comment by ScrubN** [comment]
@mohad12211 can you compile that branch and see if Arabic renders correctly when given a font that properly supports it. I'm paranoid it's the fault of my system.

**Comment by mohad12211** [comment]
I used the github-actios binaries instead of compiling, assuming that it won't affect anything, let me know if you want me to actually compile it instead of using the github-actions.
I tried multiple fonts that supports Arabic, all rendered properly. but there's a couple of small problems.

rendered:
![image](https://user-images.githubusercontent.com/51754973/208844011-64ac7e4d-bbf3-414b-b2d6-3992fcb1f145.png)
message json:
![image](https://user-images.githubusercontent.com/51754973/208845914-94eab7e7-35a1-4cc9-944b-d4d46f21b80a.png)
there's an additional ♿ emoji and a "?" one, the Arabic text is rendered properly tho, I'm not sure if the Arabic text has anything to do with this problem.


rendered: 
![image](https://user-images.githubusercontent.com/51754973/208845170-d49c9ee5-8761-4069-b371-6202338d3f52.png)
message json: 
![image](https://user-images.githubusercontent.com/51754973/208845685-63a15473-4af1-4dc5-8e82-3e814ad20f8c.png)
note that this message has Arabic and directly after it the emojis, no space between the text and the emoji.

**Comment by ScrubN** [comment]
> I used the github-actios binaries instead of compiling, assuming that it won't affect anything, let me know if you want me to actually compile it instead of using the github-actions. I tried multiple fonts that supports Arabic, all rendered properly. but there's a couple of small problems.

Github-actions build works great

> there's an additional ♿ emoji and a "?" one, the Arabic text is rendered properly tho, I'm not sure if the Arabic text has anything to do with this problem.

This is probably an artifact of this change made in #464. Before it would advance by the amount of codepoints but 99.9% of emojis are handled as a single char in Substring's eyes so an index out of bounds was not uncommon. I personally would rather have the duplicate emojis than the ioob.

https://github.com/ScrubN/TwitchDownloader/blob/bf2f862091b049a860e96ebfaa1c745a8e9e3979/TwitchDownloaderCore/ChatRenderer.cs#L577-L579
 
> ![image](https://user-images.githubusercontent.com/51754973/208845170-d49c9ee5-8761-4069-b371-6202338d3f52.png)
> note that this message has Arabic and directly after it the emojis, no space between the text and the emoji.

I can see why this is a problem and how it occurs. My solution to this is would be a rewrite of ChatRenderer.cs in OOP because the structure of it as it stands can be a headache to work with and is very unoptimal. For example there is no reason to draw nonFont chars one-by-one and we could speed up rendering while also making it easier to read by drawing whole nonFont sections in one go, but doing this would require rewriting a few functions.

**Comment by mohad12211** [comment]
I see, it's a rare occurrence anyways, for now everything seems to be working.

**Comment by ScrubN** [comment]
I still don't understand why when using an invalid font the arabic is rendered correctly but the `GetFallbackFont()` font doesn't. On Windows both are Segoe UI and the rendering problem is present on my Debian WSL.

Also this may be wrong but I believe there is a lot of wasted memory because it looks like the font stored in the fallback cache for a given character contains the entire language.
![image](https://user-images.githubusercontent.com/72096833/208855378-1d2af3ca-fb12-4006-a3c1-8833df076d2e.png)

**Comment by mohad12211** [comment]
what do you mean by an "invalid font"?

**Comment by ScrubN** [comment]
> what do you mean by an "invalid font"?

In order for the arabic to render correctly in the image below, I passed `--font foo` as an argument to cause `SKTypeFace.FromFamilyName()` to return the system fallback because I do not have a font named `foo` installed.
![image](https://user-images.githubusercontent.com/72096833/208812764-3535095d-45c2-4b62-a987-9463b0776493.png)
https://github.com/lay295/TwitchDownloader/blob/e87319ad47288541643409fb666855469117c12c/TwitchDownloaderCore/ChatRenderer.cs#L60-L71

When I pass any other valid font, such as `--font 'Yu Gothic UI'`, or pass no font argument so `Inter Embedded` is the chosen message font, the arabic must render using the font provided by the function `ChatRenderer.GetFallbackFont()` which should be functionally identical to passing an invalid font as it is literally the exact same typeface but instead it renders incorrectly:
![image](https://user-images.githubusercontent.com/72096833/208812942-4ff8b33a-e837-49c0-82b5-56f751531f9d.png)

Both images had the exact same message input as the first message in this issue thread, I just copy-pasted it into a different chat for faster render times.

**Comment by mohad12211** [comment]
Ohhh now I see, in that case I have the same problem.
passing a font that supports Arabic works.
passing an invalid font (e.g. -f "foo") will also work. (will use my system font)
passing a font that doesn't support Arabic/Passing no -f argument will not work. Tested on Linux.

**Comment by ScrubN** [comment]
> Ohhh now I see, in that case I have the same problem.
passing a font that supports Arabic works. passing an invalid font (e.g. -f "foo") will also work. (will use my system font)
passing a font that doesn't support Arabic/Passing no -f argument will not work.

The thing is though, passing a font that doesnt support arabic/no -f argument goes and fetches your system font to render nonFont chars with, but only in the case of arabic (as far as i can tell) does it fail to render correctly in this specific scenario despite it fetching the same font as it would have had you passed `-f foo`.

**Comment by mohad12211** [comment]
> For example there is no reason to draw nonFont chars one-by-one

I think that this is the problem, maybe...
passing a font that doesn't support Arabic will actually use the fallback font, but the wrong form of the letter.
Arabic letter change shape depending on the letter before and after. 

> ![image](https://user-images.githubusercontent.com/72096833/208812764-3535095d-45c2-4b62-a987-9463b0776493.png)
>  ![image](https://user-images.githubusercontent.com/72096833/208812942-4ff8b33a-e837-49c0-82b5-56f751531f9d.png)

I can see that both of these images use the same font, the letters are drawn in the same way. but the letters are in the wrong form.

in Arabic, the shape of the letters changes depending on whether they occur alone, initially, medially, or finally within a word.
in the second image, where the letters are rendered incorrectly, all of the letters are rendered in the alone case, basically its assuming that there are no letters before it or after it.

so, I assume that you normally render word by word, but in the case of nonFont chars, you render them one by one.
this will cause the chat to be correctly rendered when passing an invalid font, because it's rendering word by word.
and will cause the chat to be incorrectly rendered when passing a valid font with no Arabic support, because you are rendering char by char, and Arabic depends on the previous and next chars.

is that the case? are you rendering word by word normally but in nonFont chars, char by char?

**Comment by ScrubN** [comment]
Y'know I never even thought of that. I'll test if that's the case and I guess also test my theory about the wasted memory.

**Comment by ScrubN** [comment]
![image](https://user-images.githubusercontent.com/72096833/208874817-a7f660ee-b65d-4e89-afe3-d1afbc737492.png)
Well, the answers are: true and true

**Comment by ScrubN** [comment]
And as a side effect, rendering nonFont got slightly faster somehow

Before: FINISHED. RENDER TIME: 15s SPEED: 3.81x
After: FINISHED. RENDER TIME: 7s SPEED: 8.42x

**Comment by ScrubN** [comment]
@mohad12211 
![image](https://user-images.githubusercontent.com/72096833/209410596-11a38c08-1f59-4fcb-a6c7-b016b833ea73.png)

**Comment by lay295** [comment]
> This is probably an artifact of this change made in #464. Before it would advance by the amount of codepoints but 99.9% of emojis are handled as a single char in Substring's eyes so an index out of bounds was not uncommon. I personally would rather have the duplicate emojis than the ioob.

Were ioob that common? Why weren't there more crashes reported because of this.

> 99.9% of emojis are handled as a single char in Substring's eyes

Aren't 99.9% of emojis multiple characters? Because the char in C# internally is UTF-16 and most emojis seem to be a high and low surrogate of these UTF-16 characters to make a UTF-32 character.

**Comment by lay295** [comment]
https://user-images.githubusercontent.com/1060681/209412025-6d1dbb08-49ee-4dfc-ab61-5ed0aa65ec76.mp4

Some old emoji testing I did, but it never resulted in an OOB exception for me.

**Comment by ScrubN** [comment]
> Were ioob that common? Why weren't there more crashes reported because of this.

I ran into them when someone sent the English flag 8 times in a row. Substring sees it as 1 char but it's made of 14 codepoints so before we would substring up 14 chars and IOOB.

> Aren't 99.9% of emojis multiple characters? Because the char in C# internally is UTF-16 and most emojis seem to be a high and low surrogate of these UTF-16 characters to make a UTF-32 character.

It's a mix of both. Working with Unicode has been a pain in my ass. There's technically another edge case that results in the wrong font being used for nonFont rendering because there is no way to get the Unicode range of a specific char.

**Comment by lay295** [comment]
> I ran into them when someone sent the English flag 8 times in a row. Substring sees it as 1 char but it's made of 14 codepoints so before we would substring up 14 chars and IOOB.

Do you still have an example JSON or could construct one that would crash on the older versions? I did testing with flags before and I didn't notice anything like that. 

I feel pretty strongly that we should not be decrementing just by 1.

**Comment by ScrubN** [comment]
> > I ran into them when someone sent the English flag 8 times in a row. Substring sees it as 1 char but it's made of 14 codepoints so before we would substring up 14 chars and IOOB.
> 
> Do you still have an example JSON or could construct one that would crash on the older versions? I did testing with flags before and I didn't notice anything like that.
> 
> I feel pretty strongly that we should not be decrementing just by 1.

I just changed it to using the length of the sequence string rather than incrementing by just 1. Before the patch we were incrementing by the number of codepoints.

**Comment by lay295** [comment]
Oh that works. I just don't see how it's functionally different than what was in before #464

https://github.com/lay295/TwitchDownloader/blob/2d04e08e88a3cb1bdca9f764cadb142f3458e8fd/TwitchDownloaderCore/ChatRenderer.cs#L564

https://github.com/lay295/TwitchDownloader/blob/59745469c2a5dcad090c120db26e6209ba9a7812/TwitchDownloaderCore/ChatRenderer.cs#L728

**Comment by ScrubN** [comment]
Oh. Guess I'll add the trim back. I swear at some point we were substringing by the amount of codepoints.

**Comment by ScrubN** [comment]
Ok I'm running it again and its not OOB anymore, what?? I'm so confused man. Did I accidentally change it to codepoints length and cause the OOB myself?

**Comment by lay295** [comment]
Well, I rendered it on 1.51.1 alright

**Comment by ScrubN** [comment]
Well I've re-added the trim but left the try-catch incase it happens again. In other words it's back to how it used to substring in a6dda93f48a92cbc503e53253543fefe36acee44
