### ISSUE TITLE
Banning words / emote only chat

### ISSUE THREAD

**Issue by Zaaif** [lay295/TwitchDownloader#486]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

Would be great if we could ban certain words so they wont appear on chat or whole massage that contains them will be entirely skipped. Option to make chat emote only :)

**Comment by ScrubN** [comment]
Yeah sure

**Comment by ScrubN** [comment]
> Option to make chat emote only :)

What does this mean? ban only emotes?

**Comment by Zaaif** [comment]
> 

Leave only emotes actually :D

**Comment by ScrubN** [comment]
Unfortunately that doesn't seem very practical
