### ISSUE TITLE
Upgrade to .NET 7

### ISSUE THREAD

**Issue by ScrubN** [lay295/TwitchDownloader#488]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

I would like to upgrade the project to .NET 7 for the better performance, new features, and some NuGet packages. Is this ok with you @lay295 ?

**Comment by lay295** [comment]
I was just going to wait until .NET 8 and just upgrade on their LTS releases, but if you want to upgrade them to .NET 7 go ahead :)

**Comment by ScrubN** [comment]
I figured you were waiting for .NET 8 but 7 fully came out like a month ago meaning its got 17 months of support from now, 5 of which will overlap with .NET 8 compared to an 11 month overlap from .NET 6

https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core
