### ISSUE TITLE
[advice/nonissue]Twitch.tv/gql VideoCommentsByOffsetOrCursor fetch in react

### ISSUE THREAD

**Issue by mwardlow** [lay295/TwitchDownloader#489]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates

### Write stuff here

Hi I used your app to get chat json data to make my app. I got the app working but while trying make the chat-download feature myself I ran into problems. when I fetch I get a readable stream im processing it like this. I receive a array of max 60 messages with a nextpage true. any tips on how i can take a entire vod worth of comments and save it to a variable that I can then filter I would be great.
![Screenshot_13](https://user-images.githubusercontent.com/47964395/210158277-31f7631e-1d61-4f51-83bb-55f0d7270724.png)
![Screenshot_10](https://user-images.githubusercontent.com/47964395/210158309-a46da2d9-7815-4e15-bbcc-0dbe1d872aa1.png)

**Comment by lay295** [comment]
I mean you can take a look at what this app is doing in this file if you want. Just have an infinite loop until hasNextPage in the response is false and use the cursor in the last comment edge to iterate over all the comments. 

https://github.com/lay295/TwitchDownloader/blob/master/TwitchDownloaderCore/ChatDownloader.cs

**Comment by mwardlow** [comment]
useEffect(() => {
    async function postData(cursor, videoID) {
      if(cursor) {
        fetch('https://gql.twitch.tv/gql', {
        method: 'POST',
        headers: { 'Content-Type': 'text/plain', 'Client-ID': 'kimne78kx3ncx6brgo4mv6wki5h1ko' },
        body: JSON.stringify([{
        "operationName": "VideoCommentsByOffsetOrCursor",
        "variables": {
          "videoID": "1685206724",
          "cursor": cursor
        },
        "extensions": {
          "persistedQuery": {
            "version": 1,
            "sha256Hash": "b70a3591ff0f4e0313d126c6a1502d79a1c02baebb288227c582044aa76adf6a"
          }
        }
      }])
      })
      .then(res => res.json())
      .then(res => {
        if(res[0].data.video.comments.pageInfo.hasNextPage === true) {
          setComments(prev => [...prev, res[0].data.video.comments.edges])
          const edgeLength = res[0].data.video.comments.edges.length
          const cursor = res[0].data.video.comments.edges[edgeLength-1].cursor
       
          postData(cursor)
        }
      })
    } else {
        fetch('https://gql.twitch.tv/gql', {
        method: 'POST',
        headers: { 'Content-Type': 'text/plain', 'Client-ID': 'kimne78kx3ncx6brgo4mv6wki5h1ko' },
        body: JSON.stringify([{
          "operationName": "VideoCommentsByOffsetOrCursor",
          "variables": {
            "videoID": "1685206724",
            "cursor": "eyJpZCI6IjI1MDFmN2Y2LWNiMDItNGVkOC1iNWI3LWM1ODUwMDIwNDRlNyIsImhrIjoiYnJvYWRjYXN0OjQxNjM0MTUyNDI3Iiwic2siOiJBQUFBRGhoM0Z3QVhNdUtuWWdoRUFBIn0"
          },
          "extensions": {
            "persistedQuery": {
              "version": 1,
              "sha256Hash": "b70a3591ff0f4e0313d126c6a1502d79a1c02baebb288227c582044aa76adf6a"
            }
          }
        }])
      })
      .then(res => res.json())
      .then(res => {
        console.log(res[0].data.video.comments.edges[3].node.message)
        if(res[0].data.video.comments.pageInfo.hasNextPage === true) {
          setComments(res[0].data.video.comments.edges)
          const edgeLength = res[0].data.video.comments.edges.length
          const cursor = res[0].data.video.comments.edges[edgeLength-1].cursor
         
          postData(cursor)
        }
      })
    }
  }
 
  postData()
  }, [])

**Comment by ScrubN** [comment]
If you need further help you can ask again here or create a new issue
