### ISSUE TITLE
Video audio desync

### ISSUE THREAD

**Issue by xaolin** [lay295/TwitchDownloader#49]
This is a problem I didn't have before. I always had version 1.24 installed, but since I tried the newest version this happened. When I drag and drop the file in Vegas Pro, the audio is longer than the video and I have to sync it myself.

**Comment by lay295** [comment]
Yeah when I tried to fix other desync issues I think I messed up some stuff up. Messed around with parameters in ffmpeg for a few hours and think I have something that works well. Within a few days a new version should be up.

**Comment by lay295** [comment]
Should be fixed in [1.3 beta](https://github.com/lay295/TwitchDownloader/releases/tag/1.30-beta). Let me know if it's not, thanks for the report.
