### ISSUE TITLE
Video Chapters

### ISSUE THREAD

**Issue by TheMadog24** [lay295/TwitchDownloader#491]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

I would love to be able to have chapters in one way or another, whether it be generating a chapter file, or embedding chapters into the mp4 metadata with ffmpeg.

**Comment by ScrubN** [comment]
As far as I can tell none of the current requests that we make return stream chapters and I have no clue where to begin looking. If @lay295 can figure out the request then I would easily be able to implement the metadata to downloaded videos.

**Comment by TheMadog24** [comment]
I'm not sure if it helps at all, but the reason I suggest it is because [Tartube](https://github.com/axcore/tartube) has it, but it's meant for youtube and uses [yt-dlp](https://github.com/yt-dlp/yt-dlp/). The download speed is pretty terrible (1-3Mbps), but it does work with twitch, and can embed chapters.

**Comment by ScrubN** [comment]
Oh interesting. On the one hand, yes that is helpful, but on the other hand, the mainapp.py script (where I assume the queries are made) is fucking 27,000 lines. I'll try looking through it.

**Comment by lay295** [comment]
I dunno if they've changed their GQL call but this is what I've used before

![image](https://user-images.githubusercontent.com/1060681/210308092-85cbbbee-9cd4-4e62-a34d-430db9450b61.png)

**Comment by ScrubN** [comment]
Tartube does not handle chapters, it is merely a glorified yt-dlp GUI frontend. [Here](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/twitch.py) is the script responsible for all of the metadata scraping in yt-dlp. It looks like there's a lot of other metadata we could grab as well so I may look into that too.

**Comment by lay295** [comment]
Personally, I'd be in favor of storing whatever metadata we gather inside the chat json instead of somehow in the mp4 file. 

I am a little afraid Twitch is gonna crack down more on these GQL calls with the integrity endpoint check... But we'll cross that road when we get there.

**Comment by TheMadog24** [comment]
Storing the chapters and other metadata in the chat file would actually make it much easier to work with for me, since Mediainfo.js can't be a local file, and doesn't work offline.

I am also surprised that you guys haven't asked what I'm working on that uses TwitchDownloader.
You have all been very nice and willing to help, despite all of my odd requests, lol.

**Comment by ScrubN** [comment]
I assumed you just wanted the chapters for playback purposes. If you're going to be actually using the information then we should add it to both video and chat files. It could be practical in the future for chats anyways.

Also VLC, MPV, Handbrake, XMedia, and Gnome Videos are all able to read chapter data.
![image](https://user-images.githubusercontent.com/72096833/210415220-a51399b0-2f48-4916-90dc-26d8b0fae2ca.png)
![image](https://user-images.githubusercontent.com/72096833/210415311-d6dc642e-90b1-49bc-af50-bfa7810e9e96.png)
![image](https://user-images.githubusercontent.com/72096833/210415655-5e852295-7725-4586-9955-911fa1d57881.png)

**Comment by TheMadog24** [comment]
> If you're going to be actually using the information then we should add it to both video and chat files. It could be practical in the future for chats anyways.

For my application of it, either is fine, and both is also fine. Having the chapter data stored in the video file is how it works now, but that system doesn't work if you have no internet (since it relies on web resources). Having it stored in the chat file would allow me to always make it work, but that also relies on the people pairing the correct video and file together.



> Also VLC, MPV, Handbrake, XMedia, and Gnome Videos are all able to read chapter data.

AH, I forgot about Handbrake, but I'm not familiar with the other two.

**Comment by ScrubN** [comment]
As far as I can tell chapters are not standardized as a whole, they're standardized per encoding format/tool

**Comment by ScrubN** [comment]
https://twitch.tv/videos/1694846567

![image](https://user-images.githubusercontent.com/72096833/210932714-ac1aabd5-cf6d-4611-85f6-9e2577e4f191.png)
![image](https://user-images.githubusercontent.com/72096833/210933429-10973356-6e9c-41aa-bf89-22bd4e346a1f.png)

**Comment by ScrubN** [comment]
I'm torn between directly embedding the GQL chapter response or beautifying it in ChatRoot. Any opinions?

**Comment by ScrubN** [comment]
Here's the current chatdownload version. Any objections/suggestions? I assume there's more chapter types than just `GAME_CHANGE`, probably stream markers, that would fill in the empty strings but I'm having trouble with EditThisCookie so I can't verify this.

![image](https://user-images.githubusercontent.com/72096833/210954618-389cff5d-1703-4b0f-ab74-11f584625ada.png)

**Comment by TheMadog24** [comment]
I'm not sure if I'm the one you're asking, but it looks great to me!

**Comment by ScrubN** [comment]
> I assume there's more chapter types than just `GAME_CHANGE`, probably stream markers, that would fill in the empty strings but I'm having trouble with EditThisCookie so I can't verify this.

By using cookie quick manager with firefox, I was able to get my token and confirm that stream markers are not returned in the chapter response. Not sure if there really is any chapter type other than `GAME_CHANGE`, though I will still keep the check in videodownload just in case.

**Comment by TheMadog24** [comment]
Feel free to correct me if I am wrong, but I thought the stream markers were only visible by the streamer.

**Comment by ScrubN** [comment]
If a user has editor permissions then they can also see stream markers.
