### ISSUE TITLE
Unlisted 7TV emotes

### ISSUE THREAD

**Issue by grips199** [lay295/TwitchDownloader#495]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

In the latest version,  7TV emotes marked as " unlisted emote "  do not work.
In old version 1.40.2 they work.
For exampe this emote:
https://7tv.app/emotes/6287c2ca6d9cd2d1f31b5e7d

**Comment by ScrubN** [comment]
This is intentional behaviour

**Comment by lay295** [comment]
When you have 7TV installed and someone uses that emote is it visible?

From the description on the 7TV website it sounds like unlisted just means like, not on the public emote list. It sounds like we maybe should be showing it if "unlisted" means from like the emote directory list and not "unlisted" from a channel.

![image](https://user-images.githubusercontent.com/1060681/210640894-a4929c68-4c13-40f9-a7f7-1c63c35b2c80.png)

**Comment by grips199** [comment]
> When you have 7TV installed and someone uses that emote is it visible?
> 
> From the description on the 7TV website it sounds like unlisted just means like, not on the public emote list. It sounds like we maybe should be showing it if "unlisted" means from like the emote directory list and not "unlisted" from a channel.
> 
> ![image](https://user-images.githubusercontent.com/1060681/210640894-a4929c68-4c13-40f9-a7f7-1c63c35b2c80.png)

It is not on the public emote list, true.
On the Twitch site with 7TV it is visable like many more " unlisted " emotes, but in rendered chat it's just text.
In version 1.40.2 it works like it should, in latest nope

**Comment by ScrubN** [comment]
Well then in that case lay feel free to remove the listed check. It's at the bottom of `GetStvEmoteData()`.

**Comment by goldbattle** [comment]
The original interpretation is that unlisted are ones that have not been moderated yet by the 7tv team. It seems they are shown by default in the chrome extension (or maybe I unchecked?). It would still be nice to have, and I would rather match the 7tv functionally (whatever their default is), but leave the option to toggle it...
![image](https://user-images.githubusercontent.com/2222562/212595002-5802a796-2097-431c-98cc-39ee998d2667.png)

**Comment by ScrubN** [comment]
> The original interpretation is that unlisted are ones that have not been moderated yet by the 7tv team. It seems they are shown by default in the chrome extension (or maybe I unchecked?). It would still be nice to have, and I would rather match the 7tv functionally (whatever their default is), but leave the option to toggle it...

They are shown by default in the chrome extension, and I believe an emote uploader can unlist an emote that was verified by a moderator.

Do you want the toggle on both downloads and renders or just renders?

**Comment by goldbattle** [comment]
I think it would be safe to always download all emotes, then toggle on render.

**Comment by ScrubN** [comment]
I added it as an option to the CLI because the GUI is a little crowded. If you think I should add it to the GUI anyways then I can
