### ISSUE TITLE
Slow/Stuttery Chat Flow After v1.50

### ISSUE THREAD

**Issue by MTeelul** [lay295/TwitchDownloader#496]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

Noticed that after the v1.50 update, the chat is rendered differently.

In version 1.40, the chat would flow smoothly and render message by message. However, in version 1.50, the chat render jumps messages not show them one at a time.

![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/121988359/210677337-978e52d7-5d0d-4a8d-a68f-4e91c617c9b7.gif)

Render settings are the same on both versions:
![image](https://user-images.githubusercontent.com/121988359/210678288-edbc0054-c0c3-4f90-83ae-a3cda6672031.png)

Is there anything I can do on my end to fix this? bug? or does it have to do with Twitch's API?

Thanks in Advance :D

**Comment by ScrubN** [comment]
https://github.com/lay295/TwitchDownloader/actions/runs/3860393811 Try this build with a recent chat and make sure "dispersion" is enabled, it will artificially add some assumed offset to make the chat flow smother.

**Comment by MTeelul** [comment]
Yes!!!!
it's identical to how it previously rendered the old chat flow

Thanks again!! <3
