### ISSUE TITLE
1.30 problem

### ISSUE THREAD

**Issue by xaolin** [lay295/TwitchDownloader#50]
So, I wanted to try the newest update and when I try downloading a VOD, the program closes all of a sudden. This only happens with 24h+ VODs.

**Comment by xaolin** [comment]
Also, the delay is still there, but now the audio is shorter than the video.

**Comment by lay295** [comment]
Could you give me a VOD URL for both the 24hr problem and the delay? Thanks

**Comment by xaolin** [comment]
I think the desync problem might have been on my end. A Vegas Pro setting might have caused it. I'll report it if it will happen again.

**Comment by lay295** [comment]
I've updated the 1.30 release.zip, should fix your problems.
