### ISSUE TITLE
Trying to render chat, got hexadecimal error - (Parameter 'hexString')

### ISSUE THREAD

**Issue by JaredBBraun** [lay295/TwitchDownloader#500]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

![image](https://user-images.githubusercontent.com/28907305/211171634-fc18a109-0051-4ed5-bef9-b41e9c7c7c71.png)
ERROR: Invalid hexadecimal color string. (Parameter 'hexString')

json: https://drive.google.com/file/d/1rpE5JNBtdr7QXOMcCf-Us1NrHp7k_c2V/view?usp=share_link

**Comment by ScrubN** [comment]
Looks like twitch changed their API again and now users without custom colors are blank instead of null.

**Comment by ScrubN** [comment]
Did you modify the chat at all? Your chat looks super messed up and when redownloading the chat they don't look the same in any way AND user colors are null instead of blank, meaning the crash doesn't occur.

**Comment by JaredBBraun** [comment]
> Did you modify the chat at all? Your chat file looks super messed up and when redownloading the chat they don't look the same in any way AND user colors are null instead of blank, meaning the crash doesn't occur and twitch didn't actually change their API.

I only changed the other of the chat messages alphabetically I did not modify the messages themselves, or add or remove any just sorted them.

**Comment by ScrubN** [comment]
So firstly, your sorter removed all null values, causing the crash.
![image](https://user-images.githubusercontent.com/72096833/211179735-36b1236b-c333-4e9c-a5ee-ce791357351a.png)
![image](https://user-images.githubusercontent.com/72096833/211179729-91ee3841-2381-4fa0-b28a-808216d7db81.png)

Secondly, the renderer relies on the chat being ordered by comment offset or you get a memory leak and comments get drawn in the wrong order.
![image](https://user-images.githubusercontent.com/72096833/211179754-42883ff2-f2b3-4718-8703-15ef2468917a.png)

**Comment by JaredBBraun** [comment]
Thanks! it looks like `content_offset_seconds` has to be in the order of the "comments" list even if modified? Maybe there could be json data validator? I find out that my json parser made nulls to just "".  example  `"bio":null`  changed it to`"bio":""` So when Commenter doesn't have all complete fields that breaks the renderer as well?

**Comment by JaredBBraun** [comment]
Also I tried to render the original json untouched and it just crashes, IM assuming due to the large amount of Comment objects?

**Comment by ScrubN** [comment]
> Also I tried to render the original json untouched and it just crashes, IM assuming due to the large amount of Comment objects?

It rendered just fine for me? Try redownloading it: 1697567799

**Comment by ScrubN** [comment]
> Thanks! it looks like `content_offset_seconds` has to be in the order of the "comments" list even if modified? Maybe there could be json data validator?

Yes the comments list must be ordered by `comment_offset_seconds`. A json validator would be good for users who modify the chat json, you aren't the first, but in my opinion it's low priority.

> I find out that my json parser made nulls to just "". example `"bio":null` changed it to`"bio":""` So when Commenter doesn't have all complete fields that breaks the renderer as well?

Doing `null` check is as easy as:
```cs
CheckBio(comment.bio ?? "foo");
```
or
```cs
comment.bio ??= "foo";
CheckBio(comment.bio);
```

Meanwhile null + empty string checks are:
```cs
if (string.IsNullOrWhitespace(comment.bio))
{
    comment.bio = "foo";
}
CheckBio(comment.bio);
```

Not to mention null + empty checks are also most costly than null checks.

**Comment by JaredBBraun** [comment]
> if (string.IsNullOrWhiteSpace(comment.bio))
> {
>     comment.bio = "foo";
> }
> CheckBio(comment.bio);
> ```
> 
> Not to mention `null + empty` checks are also more costly than `null` checks.

so you can get a successful render by just going into any fields that were left null and if they were "changed" to "" you can just insert anything back into that field and it will work?

**Comment by ScrubN** [comment]
> so you can get a successful render by just going into any fields that were left null and if they were "changed" to "" you can just insert anything back into that field and it will work?

So in the case of parsing the hexString if the value is `null` then it will generate a new random hexString based on the user's name. If it is not `null` then it will assume it is not garbage and parse it as-is, throwing an exception if it fails.

```cs
SKColor userColor = SKColor.Parse(comment.message.user_color ?? defaultColors[Math.Abs(comment.commenter.display_name.GetHashCode()) % defaultColors.Length]);
```

**Comment by JaredBBraun** [comment]
So I understand that the JSON parsers I have used were the problem it would take nulls and convert them to empty strings when deserializing objects that were null. The solution that fixed my issue when loading and editing the data is that I had to use Newtonsoft.Json. A good FYI to anyone editing the JSON I guess. This bug for me is resolved and I can move forward and use chat rendering as intended successfully.

**Comment by ScrubN** [comment]
I decided to write the integrity check now rather than later. I'm quite curious, which JSON parser were you using that caused the default values instead of null?

**Comment by JaredBBraun** [comment]
> I decided to write the integrity check now rather than later. I'm quite curious, which JSON parser were you using that caused the default values instead of null?

https://docs.unity3d.com/2020.3/Documentation/ScriptReference/JsonUtility.html first then I tried https://github.com/Bunny83/SimpleJSON, First time trying Newtonsoft.Json, didn't know nulls could literally just be null

**Comment by ScrubN** [comment]
I didn't know Unity supplied a json reader. If you don't want to use Newtonsoft then you can use System.Text.Json, though that requires .NET Core 3.0+
