### ISSUE TITLE
Download/Network Speed limit.

### ISSUE THREAD

**Issue by TheMadog24** [lay295/TwitchDownloader#502]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

 Allow the user to limit the speed of downloads.

Probably not very practical for most people, and I can only assume it's extremely difficult to implement, but it would be very nice to have.

___

For instance, when I download longer videos (5+ Hours), the program likes to use up 100% of my network, and I sometimes struggle to open webpages or videos until it finishes downloading (also no pause feature).

**Comment by ScrubN** [comment]
I understand and share your problem. I wish this was an easy fix but as far as I can tell, HttpClient does not natively support speed limiting and I can't find *anything* online. My suggestion is use 1 download thread since that seems to hover around 15-20mbps on my connection if task manager is to be trusted.

**Comment by ScrubN** [comment]
On second thought maybe this is possible? We could take note of how large the download was and do some math against the requested mbps to determine how long to sleep for before the next download?

**Comment by TheMadog24** [comment]
> My suggestion is use 1 download thread since that seems to hover around 15-20mbps on my connection if task manager is to be trusted.

For me, 1 download Thread is 300MB/s, which is 100% of my download speed.

**Comment by ScrubN** [comment]
> > My suggestion is use 1 download thread since that seems to hover around 15-20mbps on my connection if task manager is to be trusted.
> 
> For me, 1 download Thread is 300MB/s, which is 100% of my download speed.

Interesting. Maybe someone else in my household was downloading something while I was testing.

**Comment by TheMadog24** [comment]
> > > My suggestion is use 1 download thread since that seems to hover around 15-20mbps on my connection if task manager is to be trusted.
> > 
> > 
> > For me, 1 download Thread is 300MB/s, which is 100% of my download speed.
> 
> Interesting. Maybe someone else in my household was downloading something while I was testing.

Lol, even with only 1 download thread, while I am downloading, everyone else basically loses internet access, since I am using 100% of the bandwidth. I can't even watch videos on the same PC that is downloading.
