### ISSUE TITLE
ERROR: A connection attempt failed ...

### ISSUE THREAD

**Issue by Teknoist** [lay295/TwitchDownloader#504]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

ERROR: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (dgeft87wbj63p.cloudfront.net:443)

![image](https://user-images.githubusercontent.com/37031361/211976482-55f47459-629f-442b-85cb-858f759ebd6c.png)

**Comment by ScrubN** [comment]
You might just have to wait, you might have to connect to a vpn, or you might have to reset your computer's network settings

**Comment by Teknoist** [comment]
I will try it on my work computer in a few hours, sometimes the isp I use at home can block some sites.

**Comment by goldbattle** [comment]
Were you able to resolve this issue?

**Comment by Teknoist** [comment]
Problem my ısp problem solve
