### ISSUE TITLE
Having Issue inside Terminal On Mac

### ISSUE THREAD

**Issue by masonkt** [lay295/TwitchDownloader#507]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

I have downloaded and extracted the file. Originally Mac wouldn't allow it to open since it wasn't on the app store, so I gave it exceptional permission to do so. I was then able to open the terminal, but inside the terminal, I get: Last login: Fri Jan 13 11:33:32 on ttys000
/Volumes/Backup\ Plus/Youtube/Raw\ Files/TwitchDownloaderCLI ; exit;
Macs-MBP-2:~ (REDACTED)$ /Volumes/Backup\ Plus/Youtube/Raw\ Files/TwitchDownloaderCLI ; exit;
Usage: TwitchDownloaderCLI [VERB] [OPTIONS]
Try 'TwitchDownloaderCLI help' for more information.
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

Then after that runs, I'm not able to type in the terminal to continue the installation process. Any help would be great.

**Comment by ScrubN** [comment]
Did you follow the instructions in the README?

**Comment by masonkt** [comment]
> Did you follow the instructions in the README?
Yea, the mac instructions have me extract the downloader, then I'm supposed to give it executable rights inside the terminal. However, when I try to type in the terminal I can't.

**Comment by ScrubN** [comment]
Just to be clear, you're not double clicking the program in finder right? The program is operated by using a terminal window spawned by the user.

**Comment by masonkt** [comment]
> Just to be clear, you're not double clicking the program in finder right? The program is operated by using a terminal window spawned by the user.

I was at first, then I figured out that part and used the terminal. I finally THINK I got the terminal to give the program executable rights, but now I am getting: -bash: syntax error near unexpected token '(Here is the VOD ID that I entered to download)'. This is where I am now confused

**Comment by ScrubN** [comment]
sounds like you have a double space or & causing a new command

**Comment by goldbattle** [comment]
Feel free to reopen if you still have troubles running the CLI with specific errors it gives you.
