### ISSUE TITLE
Why are the size of video smaller with Your Downloader than other Downloaders and Websites? + Missing Frames

### ISSUE THREAD

**Issue by George620** [lay295/TwitchDownloader#51]
If I download the same video with the same quality with other downloader or website, file is bigger, but if I use your downloader, file is smaller. Not that I mind, but why are the video smaller?
Missing Frames Issue?: If I open both videos from your downloader and other sites/downloaders in cutting program, the video using your downloader tells me the video is variable frame rate. And if I look at both videos length, first (Your Downloader) is 6:21 seconds and 23 frames and "Others" is 6:21 seconds and 25 frames. So with your downloader two frames missing. Why?
[I did this above as an second experiment and maybe issue on TD 1.3 Predownload, because month ago on older version (v. 1.25 I think) when I download 6 hour video (even here is video 200 MB smaller than "others") I notice extra 8 secs of video (Tw. D), so I download the same video with the "Others" and that extra 8 secs isn't there. Exactly: 6:08:10 secs and 1 frame with your downloader (tells me variable frame rate, I look depthly in cutting program and... frames missing?! {"only" 29 frames instead of 30 in some seconds} {that's exactly how i came up with the problem above, but idk if this have connection}) and 6:08:02 secs and 0 frames with "others", which is true length. Maybe this (longer video than true length) is patched because of older version, but I let you know what happened in my unexpected first experiment, because it can have a connection with frame "issue" above that I'm asking.]

**Comment by lay295** [comment]
I'll be honest, the main point of the tool is just the chat render, and the VOD downloader was mostly an afterthought. A reason why the files might be different is because audio is being re-encoded, as for missing frames, unless you're cropping I don't see why it would be missing frames.

I won't be providing much support in debugging the VOD downloader besides fixing if it breaks, or there are desync issues.
