### ISSUE TITLE
Show estimated file size before downloading

### ISSUE THREAD

**Issue by WolfRider3000** [lay295/TwitchDownloader#514]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

Is it possible to add a feature to display the estimated file size before downloading the VoD? Something like UnTwitch does where you can see the file size in the resolution selection bar. It will be very useful to people like me with limited disk space. It would also be great if the program calculated how much the selected part of the VoD will weigh (for example, one VoD of a subathon weights about 100 GB, but most of the VoD is sleeping anyway, so you only need to download the useful 10-11 hours parts, which usually weight about 35 GB).
![Screenshot_517](https://user-images.githubusercontent.com/67225704/212628937-d5cfc143-082e-4822-a38b-af6e2734972a.png)

**Comment by ScrubN** [comment]
This is a complicated one because specifically vod downloads require about 2x the disk space because of the way we re-encode the result. If we were to put a truthful estimate then people would question why the estimation is double the real download size and start doubting it.

**Comment by ScrubN** [comment]
On the other hand I did just think of a way we could possibly not require 2x the disk space. I might look into that at some point and if it turns out it does work then I will also see about implementing a size estimation.

**Comment by ScrubN** [comment]
Thought on this again and I've changed my mind. I'll just throw an error before downloading if there isn't enough space.

**Comment by ScrubN** [comment]
In order to estimate the file size we would need to check the data rate of the VOD, which means downloading a video single part beforehand. Unfortunately the code for downloading even a single part is coupled to the video downloader process so tightly that this isn't currently possible, meaning a partial rewrite is required to decouple it and make file size estimation possible. I would like to do this eventually for maintainability reasons as well but for now that means estimation isn't currently possible :(

**Comment by WolfRider3000** [comment]
> I would like to do this eventually for maintainability reasons as well but there are several changes to the downloader waiting as pull requests so for now that means estimation isn't currently possible :(

Thank you for looking into it. I guess for now I will just use UnTwitch to estimate file size and wait for new versions.

**Comment by ScrubN** [comment]
Lay let me know that apparently there is a field in the info response that contains the video data rate, meaning it was trivial to implement. It's even better than UnTwitch too because it reacts to cropping!

**Comment by jafrizzell** [comment]
Sorry for resurrecting a dead thread. In a similar vein, could a chat download show the total # of chat messages prior to downloading? Maybe not necessary to have the number account for start & end times, but this way I can estimate how large & how long it will take to download the vod chat.

**Comment by ScrubN** [comment]
> Sorry for resurrecting a dead thread. In a similar vein, could a chat download show the total # of chat messages prior to downloading? Maybe not necessary to have the number account for start & end times, but this way I can estimate how large & how long it will take to download the vod chat.

Sorry for not seeing this comment earlier, but as far as I can tell there isn't an API request to get the chat message count.
