### ISSUE TITLE
Running downloader on Linux

### ISSUE THREAD

**Issue by MashaGaming** [lay295/TwitchDownloader#52]
Unable to use the TwitchDownloader on linux either by using wine or through source

**Comment by lay295** [comment]
The GUI part of this program isn't supported on Linux. As it was made in .NET Framework, it was meant to work under Windows. Soon there will be a TwitchDownloaderCLI that will be Linux compatible, but with no user interface like the windows version.

**Comment by lay295** [comment]
I've just released 1.30 which has a command line version that can run on Linux. In my free time I can see if I can get it running under wine, but no guarantees.
