### ISSUE TITLE
stuck at "finalizing mp4" NEVERMIND - ARCHIVE

### ISSUE THREAD

**Issue by mandrewslol** [lay295/TwitchDownloader#524]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

When I try to download a vod it gets stuck at "finalizing mp4". Any known fixes?

EDIT: NEVERMIND - ARCHIVE

**Comment by ScrubN** [comment]
Finalizing can take a long time on slower machines. Soon there will be a progress bar during video finalization to give the user a better idea of what is happening.

You may close this issue as completed.
