### ISSUE TITLE
Will it be possible to download a VOD with a rendered chat so that it is one video?

### ISSUE THREAD

**Issue by JessieKr** [lay295/TwitchDownloader#527]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates

### Write stuff here

Will it be possible to download a VOD with a rendered chat so that it is one video?

**Comment by goldbattle** [comment]
Tracking this request in issue: https://github.com/lay295/TwitchDownloader/issues/249
