### ISSUE TITLE
Animated emotes freezing after certain message count

### ISSUE THREAD

**Issue by Valkyprin** [lay295/TwitchDownloader#529]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

When rendering chat, even with a partial render of say 1000 messages, if it goes beyond around the 80000 messages point from the json file, all animated emotes will be frozen.

Not to mention rendering a chat with over 80000 at least with prores and importing into premiere pro gives a blank video.

Is anyone else having this issue? The streams I've downloaded these from have been deleted at this point but if it's an issue with the chat download settings it'd be great to know for future reference. Thanks.

**Comment by ScrubN** [comment]
Can you please provide your chat json? You eill have to zip it or rename to .txt for github to allow uploads

**Comment by ScrubN** [comment]
I rendered your chat with 1.51.1 and 19:21:40 in animated emotes are still working as expected. If you can provide a timestamp of where you saw the frozen animated emotes then that would be appreciated

**Comment by Valkyprin** [comment]
I have the render split in two but it'd be around 19:53:03 there's some animated emotes on screen that are working that you can see freeze at that timestamp, then everything beyond that is still frozen.

**Comment by ScrubN** [comment]
I can confirm the animated emotes stop playing. They did not stop playing on a frame where new comments were drawn so it is likely unrelated to that.

**Comment by Valkyprin** [comment]
I just checked with another file and it freezes at the same time.

**Comment by ScrubN** [comment]
So this is the second that the animated emotes stop animating.
![image](https://user-images.githubusercontent.com/72096833/215620531-83879c9d-b77e-461c-8636-39f2b7770c0f.png)
I was wondering what significance the number had in relation to how computers handle numbers until I multiplied it by the FPS to find the render tick that they stopped animating and low and behold 71582 * 30fps = integer overflow. I'm honestly surprised only animated emotes broke.
![image](https://user-images.githubusercontent.com/72096833/215620765-6a388a78-c82b-4560-8c9a-bd109f5d0621.png)

**Comment by Valkyprin** [comment]
Interesting, so I'll just have to render it at a lower framerate. Thanks so much for all the help! Unless there's anything you'd recommend instead?

**Comment by ScrubN** [comment]
No, unfortunately there is nothing you can do you with 1.51.1 to fix the overflow due to the order of operations. If you want to build my fix PR from source instructions can be found in the [README](https://github.com/lay295/TwitchDownloader#building-from-source)

**Comment by lay295** [comment]
> No, unfortunately there is nothing you can do you with 1.51.1 to fix the overflow due to the order of operations. If you want to build my fix PR from source instructions can be found in the [README](https://github.com/lay295/TwitchDownloader#building-from-source)

Would you want [maintain access](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/repository-roles-for-an-organization) to this Github repo? I don't really have time to look over all the PRs truthfully and currently in the mode where I was just going to fix stuff if Twitch breaks stuff.

**Comment by ScrubN** [comment]
You can somewhat see in the screenshot that the currentTick is being multipled by 1000 before offscreen being divided by the framerate. If it was divided before being multiplied then the overflow wouldn't happen at 30fps, but would instead be tied to the fps, making 1fps overflow at 19:53:03, 2fps overflow at 39:46:06, and so on. The solution is to just use a bigger integer.

**Comment by ScrubN** [comment]
> Would you want [maintain access](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/repository-roles-for-an-organization) to this Github repo? I don't really have time to look over all the PRs truthfully and currently in the mode where I was just going to fix stuff if Twitch breaks stuff.

Sure, that would be very helpful!

**Comment by lay295** [comment]
> > Would you want [maintain access](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/repository-roles-for-an-organization) to this Github repo? I don't really have time to look over all the PRs truthfully and currently in the mode where I was just going to fix stuff if Twitch breaks stuff.
> 
> Sure, that would be very helpful!

Was a little wrong in the permissions since that was for organizations only (whoops). But I added you and @goldbattle as collaborators if you two want to make changes.

**Comment by ScrubN** [comment]
Sounds good. You don't mind if I close old resolved issues do you? For example the original RTL feature request is still open

**Comment by lay295** [comment]
> Sounds good. You don't mind if I close old resolved issues do you? For example the original RTL feature request is still open

Ye go for it, a lot of the issues are stale :'(

**Comment by lay295** [comment]
> Sounds good. You don't mind if I close old resolved issues do you? For example the original RTL feature request is still open

Can also add me on Discord Mr.Derp#9333 if you ever wanna talk about stuff
