### ISSUE TITLE
Export transparent files with webM?

### ISSUE THREAD

**Issue by NicolasJMendez** [lay295/TwitchDownloader#53]
Hello, I just was using your program and noticed that you had different different file formats for rendering but when it came to transparency you choose to go with /MOV files. These are massive, mine was like 80GB for a 2 hour VOD. Any reason you don't support using WebM? I do motion graphics and I always use .WebM file formats (VP8 is what I usually export in but VP9 doesn't seem to support transparency from my experience). Just wondering what the reasoning is.

Also, for some reason I get big emotes for certain emotes. here is an example:
https://imgur.com/Co5Q4oZ

Would love to hear back! thanks for your work!

**Comment by lay295** [comment]
Transparency with webm is supported, with vp8/vp9 encoding being super slow. Can you tell me what emotes are big?

**Comment by NicolasJMendez** [comment]
That's weird. Whenever I import the .webm file into premiere pro it does not retain the transparency, I still get the black background. 

I managed to track down the emote used in the chat that is in the image. I guess it's reckBaka? I've tried to do some googling around but didn't find anything on it. but it's obviously in betterttv or frankerfacez's api cuz your program was able to pull that lol. Here is the JSON for the comment:

`{"_id": "f42f97bf-0261-4ec0-9c4d-193325ced116", "created_at": "2017-07-28T13:31:39.289Z", "updated_at": "2017-07-28T13:31:39.289Z", "channel_id": "9072112", "content_type": "video", "content_id": "162591866", "content_offset_seconds": 3123.789, "commenter": {"display_name": "AstroDinger", "_id": "89093413", "name": "astrodinger", "type": "user", "bio": null, "created_at": "2015-04-20T21:23:42.398102Z", "updated_at": "2020-04-19T03:38:55.85093Z", "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/astrodinger-profile_image-174a66b8b0808610-300x300.png"}, "source": "chat", "state": "published", "message": {"body": "GO TO TAIWAN WITH RIN reckBaka GO TO TAIWAN WITH RIN reckBaka GO TO TAIWAN WITH RIN reckBaka GO TO TAIWAN WITH RIN reckBaka GO TO TAIWAN WITH RIN reckBaka GO TO TAIWAN WITH RIN reckBaka ..", "emoticons": [{"_id": "340688", "begin": 22, "end": 29}, {"_id": "340688", "begin": 53, "end": 60}, {"_id": "340688", "begin": 84, "end": 91}, {"_id": "340688", "begin": 115, "end": 122}, {"_id": "340688", "begin": 146, "end": 153}, {"_id": "340688", "begin": 177, "end": 184}], "fragments": [{"text": "GO TO TAIWAN WITH RIN "}, {"text": "reckBaka", "emoticon": {"emoticon_id": "340688", "emoticon_set_id": ""}}, {"text": " GO TO TAIWAN WITH RIN "}, {"text": "reckBaka", "emoticon": {"emoticon_id": "340688", "emoticon_set_id": ""}}, {"text": " GO TO TAIWAN WITH RIN "}, {"text": "reckBaka", "emoticon": {"emoticon_id": "340688", "emoticon_set_id": ""}}, {"text": " GO TO TAIWAN WITH RIN "}, {"text": "reckBaka", "emoticon": {"emoticon_id": "340688", "emoticon_set_id": ""}}, {"text": " GO TO TAIWAN WITH RIN "}, {"text": "reckBaka", "emoticon": {"emoticon_id": "340688", "emoticon_set_id": ""}}, {"text": " GO TO TAIWAN WITH RIN "}, {"text": "reckBaka", "emoticon": {"emoticon_id": "340688", "emoticon_set_id": ""}}, {"text": " .."}], "is_action": false, "user_badges": [{"_id": "subscriber", "version": "0"}], "user_color": "#0000FF"}}`

**Comment by lay295** [comment]
I'll look into the big emote issue soon, and in the 1.30 beta there is an issue with emojis being cut off as well.

I assume you're using this for webm support.
https://www.fnordware.com/WebM/
It seems other people have similar issues importing alpha? But it can export alpha.

https://github.com/fnordware/AdobeWebM/issues?q=alpha

FFProbe is also telling me there is an alpha channel.
![image](https://user-images.githubusercontent.com/1060681/90296926-f9f18780-de5a-11ea-8aa6-714d3e047563.png)

A while ago when I implemented transparency support I verified the webm had transparency by using a webpage with a background and loading the webm. I haven't tried it in Premiere before, but I do the the back background and it saying there is no alpha channel, even though I know there is one. (same with VP8)

![image](https://user-images.githubusercontent.com/1060681/90297052-52c12000-de5b-11ea-9e08-2a7b9f81df5f.png)

So, I know huge file sizes suck, but it's just most codecs that support alpha channel are usually intermediary formats which are huge :/ a few people have suggested that instead I can generate 2 H264 mp4's and have one of them being a mask, and to just combine them in the video editor. I haven't had time to try that, but other than that I have no clue. Open to suggestions.

**Comment by lay295** [comment]
For example, this is one of the test files I was using, trying to get working in Premiere which I couldn't.
https://twitcharchives.com/temp/1min.webm

Here is an example webpage which shows it does have a transparent background
https://twitcharchives.com/temp/test.html

**Comment by NicolasJMendez** [comment]
Man, that's weird. I've tried that file you've uploaded and still no transparency, even though you obviously have it export as alpha. It says "Alpha: None" in PP:
https://imgur.com/2wdH3SF

It says that for your video file as well as any file I export from your program. I don't like using chromakey because you get bad edges and you never know what color to choose because users have all types of colors for names and emotes. I've done a little more research and it seems that this is a problem in PP that some people are getting. I'll do some more research and report back here if there is anything new. Thanks for your work on the project, I really appreciate it!

**Comment by lay295** [comment]
I remember someone mentioned blue worked ok for them. I actually don't use my program to edit videos so I don't really have a great solution besides the huge mov files. I'll probably end up doing the 2 video solution with a mask video for the transparency until some code.

Someone could also update the adobe webm extension to support alpha channels, but I am not experienced enough in C/C++ to attempt it.

Gifs could work? But it doesn't look like it actually has an alpha channel like you said, it just picks a color to be transparent instead, which I would assume have the same downfalls as just chromakeying out a color.

**Comment by lay295** [comment]
I experimented with 2 separate videos, one being a mask for the actual chat file. Since you do graphics I wonder if you could tell me how you can combine these in adobe premiere so I can do testing of my own? I've tried for like 30 minutes but can't get it to work. If not I'll keep trying at it later.

https://drive.google.com/file/d/1jzm6vQumOYmT6gutIk-mH1YWCgIbf-HQ/view?usp=sharing

If it works and can be blended together in a video editor I think this would be the best solution going forward. Pretty quick at encoding too compared to VP8/VP9.

**Comment by NicolasJMendez** [comment]
I have successfully utilized the track matte file. Although for some reason the scaling is off when track matte key is applied; which is weird because both of the files are actually the same dimensions. 

Here are some pictures to help aid you in replecating this: https://imgur.com/a/MZ924kT

In PP I imported just a video file (a random one that I am working on for a client) and both the original chat and masked chat. Make sure to have the masked video above (1min_mask.mp4)(Picture 1). Then, select both clips and make a Nested Sub sequence (Picture 2) I named it Chat. Enter the sub sequence by double clicking on it in the timeline (Picture 3). Go into your effects list and search for Track Matte Key(Picture 4). Once you find that, drag that onto your original chat (1min.mp4). Click 1min.mp4 in the timeline(the original chat that you just applied a track matte key to) and go to the effects control panel and scroll down until you are in the Track Matte Key FX, drop down the Matte: and select Video 3, the name may differ for you but it should be the only other option in there because this is within a nest sequence with only 1 other video (Picture 4.5). Once you do that it will look something like this (Picture 5). It doesn't work because the type of mask that you provided is a luma-based mask (white allows the underlying video through, black makes everything behind it transparent). Once that is done it would look like this (Picture 6), kinda messed up. This is because for some reason PP re-scaled the mask file, I have no idea why. So to fix this just scale up the mask's "scale" option. Do that by clicking the mask layer (1min_mask.mp4) in the timeline and go to the effects control page, scale the "scale" option from under the "Motion" drop down up from 100% to 533% (Picture 8). Now you get this (Picture 9). Head back over to the main comp we started with (outside the nested sequence)(Picture 10) and you should get something like this (Picture 11).

Scaling the mask video only works for that file resolution, I'd assume. Maybe it works with other ones but I haven't tried it. I'd advise playing with the scale and see how it works because 533% was pretty crude and may not of been exactly perfectly lined up. Also, my PP layout is for 3 monitors so the location at which you find things like the effect control may differ.

Sorry if I went too in depth with the explanation, not sure of your level of proficiency in PP

**Comment by NicolasJMendez** [comment]
I'm actually stupid. When you make your nested sequence and double click into it, go to your sequence settings (Sequence->Sequence Settings) and set the dimentions to what your video file is. For instance your video file is 720 x 1440. So change it to that. Then apply your track matte key to the 1min.mp4, select video 3 as your Matte, and change "Composite Using" "Matte Luma" then head back over to your main comp and it'll be fine. 

Can't believe that wasn't the first thing that I did. So if you export your file from your program as 1920x1080 (hypothetically speaking) then you need to set your comp settings for your nested sequence "chat" to 1920x1080. I can make a video on how to do this if you'd like. That can be shared for people to follow. It's very simple.

**Comment by lay295** [comment]
Sure, a video would be appreciated if you wouldn't mind. My proficiency in premiere is basically none. I plan to make a simply tutorial on how to do it in premiere and in sony vegas once I figure out how to do it myself and do some more testing for others to follow. Thanks for the help :)

**Comment by NicolasJMendez** [comment]
Alright I've uploaded a short vid on how to get the track matte working within Premiere Pro. 
https://drive.google.com/file/d/1oeF0rKNP6PbCGt8PFEcLrN4RucRD_FAx/view?usp=sharing

**Comment by lay295** [comment]
Added it to 1.31, lemme know if any problems with it. But thanks again for your help!
