### ISSUE TITLE
ERROR: Cannot access child value on Newtonsoft.Json.Linq.JValue.

### ISSUE THREAD

**Issue by z1qqy** [lay295/TwitchDownloader#530]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Unsure

### Describe your issue here

when I try to download my most recent VOD, I get this error. It's pretty fucking annoying, please fix whatever is wrong with this dogshit! thanks!

**Comment by lay295** [comment]
Thanks for your very informative bug report with information on to reproduce the issue



> ### Edition
> Unsure

And apparently cannot read version numbers at the top of the application
![image](https://user-images.githubusercontent.com/1060681/215850395-66f2811f-1dc2-469e-93bb-a4e49bb4e1da.png)
