### ISSUE TITLE
ERROR: Data error (cyclic redundancy check)

### ISSUE THREAD

**Issue by BOU4EYT** [lay295/TwitchDownloader#534]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

When i try to download a VOD i get a ERROR: Data error (cyclic redundancy check)

**Comment by ScrubN** [comment]
Can you enable 'Verbose Error Output' in the settings and send a screenshot of the output?

**Comment by ScrubN** [comment]
Looking around online it seems likely the error is a result of your hard drive failing or is about to fail. You should [follow the steps for repairing the drive in this article](https://www.drivereasy.com/knowledge/solved-data-error-cyclic-redundancy-check/#drive) just don't buy the crappy software at the top.

If you continue to receive CRC errors then you should probably purchase a new drive as soon as possible and copy important files to the new drive.

In the event that the failing drive no longer appears in file explorer and disk management thinks it's raw or unformatted then you will need to use a tool like [Recuva](https://www.ccleaner.com/recuva) to recover important files. You DON'T need to purchase a license for Recuva to use it to recover any lost files, and most other recovery programs are hot garbage that want to make a quick buck off of you.

**Comment by BOU4EYT** [comment]
thanks! i didnt know my hard drive was failing
