### ISSUE TITLE
The status bar doesn't adjust based on font size, which can render it unreadable

### ISSUE THREAD

**Issue by Templayer** [lay295/TwitchDownloader#536]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

Try reading the status bar info from this screenshot (it gets even worse when downloading):

![image](https://user-images.githubusercontent.com/11728067/216819555-53e32e99-fdaf-4ef9-82ec-de5835497b2e.png)

**Comment by ScrubN** [comment]
Basically nothing in the GUI is made to to adapt to font size changes. It's a huge pain in the ass to do that while still having it look appealing at the regular font size. There are a few places that will get better with the localization update but that's not ready yet.

**Comment by Templayer** [comment]
> Basically nothing in the GUI is made to to adapt to font size changes. It's a huge pain in the ass to do that while still having it look appealing at the regular font size. There are a few places that will get better with the localization update but that's not ready yet.

True, but other elements in the GUI can be enlarged by making the window larger.

The height of the status bar, however, can not. Plus the text on the left in the status bar is unnecessarily cropped from the bottom. (I think? It's hard to tell if that isn't just where the status bar really ends...)

**Comment by ScrubN** [comment]
That's a fair criticism. I'll see if there's anything I can do

**Comment by ScrubN** [comment]
Try the workflow build of #538 when it finishes and see if it helps at all. It's the best I can do, I can't make the status bar dynamically get bigger

**Comment by Templayer** [comment]
Much better in the new version:

![image](https://user-images.githubusercontent.com/11728067/223407864-57bc6d1d-8b11-4aa4-9ff8-e22f13f2653e.png)

Thank you!
