### ISSUE TITLE
Fatal Error on Chat Render (chat.json is not a valid chat format)

### ISSUE THREAD

**Issue by tolekk** [lay295/TwitchDownloader#539]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

When trying to render chat the app throws a Fatal Error. App version 1.51.2
Downloaded the json as queued alongside VODS, both new and old version json files cause this. 

![image](https://user-images.githubusercontent.com/48994738/217784901-de24f7b6-5f63-41d6-8e6c-5c5cc01dfd49.png)
![image](https://user-images.githubusercontent.com/48994738/217785963-e7d50e88-c72f-410e-a76d-59d7e8d3998a.png)
![image](https://user-images.githubusercontent.com/48994738/217786011-d7d25534-f038-4943-bf36-ab659b291737.png)

Scaling at 1.0, encoding an mp4 h264 video at 60fps with a mask. Ffmpeg args set to default.

**Comment by ScrubN** [comment]
I changed up the json parsing. Seems I forgot to make the file format check case insensitive. Rename it from `Chat.Json` to `chat.json` and it should work
