### ISSUE TITLE
Timestamps ver. 2

### ISSUE THREAD

**Issue by George620** [lay295/TwitchDownloader#54]
Can you please add timestamps in txt same as the video time like the rendered json file if possible? Example: (1:20:05) this is my first message; (1:20:06) this is my second message etc.

**Comment by lay295** [comment]
Hmmm I could, but I think for most people they would prefer the current format (which I took from overrustlelogs) since it shows the exact time the message was sent, and not relative to when the VOD was started. I'll probably will add a formatting setting in the next version.

**Comment by George620** [comment]
Yeah, I prefer it too, but some option will be cool.
