### ISSUE TITLE
FFMPEG threads in GUI

### ISSUE THREAD

**Issue by gazwilliams** [lay295/TwitchDownloader#540]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

Add customisation for number of threads in FFMPEG. I have 24 cores I could use to render video output faster but GUI version only uses single thread?

**Comment by ScrubN** [comment]
The FFMPEG used for rendering should be set to auto threads, only the chat renderer itself is single threaded.

**Comment by gazwilliams** [comment]
![image](https://user-images.githubusercontent.com/31708687/217955917-1369878e-fb22-46df-a597-03a3b261ca7d.png)
I cant see any configuration to alter the behaviour. From what youve said it should be using autothreads but it doesn't seem to scale beyond one? Attached screencap as evidence AMD 5900x CPU for reference.

**Comment by ScrubN** [comment]
VOD Downloads can only use 1 thread. It is a limitation of `-c:v copy`.
