### ISSUE TITLE
Supporting Arabic language.

### ISSUE THREAD

**Issue by TehUnreal** [lay295/TwitchDownloader#545]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

When rendering chat replay in the arabic language, there are no spaces between the words? I attached a picture.
![problem](https://user-images.githubusercontent.com/15260258/219675814-85b92d4f-3b1a-4bc4-864d-b9fc44b0c2ef.png)

**Comment by ScrubN** [comment]
I assume you are using the 1.51.2 pre-release. Please try increasing word scaling in the scaling options.

**Comment by TehUnreal** [comment]
> The 1.51.2 pre-release has further improvements to arabic rendering, if you are not using it please try it. Otherwise please try increasing `Word Spacing Scale` in the scaling options.

I will try that, thank you so much for the reply!

**Comment by ScrubN** [comment]
Glad it was able to work. For reference, this is the default word spacing currently implemented in the master branch.
![image](https://user-images.githubusercontent.com/72096833/219904953-1ac288ec-85db-4553-9048-8789936721f4.png)
I can spot a few spots where its a bit lacking but that would be the fault of the text library not accurately reporting the width of the words :( hence why a word spacing multiplier is exposed to the user.
