### ISSUE TITLE
Pepper Emoji render bug?

### ISSUE THREAD

**Issue by sunkhaskasis** [lay295/TwitchDownloader#548]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

It appears that the pepper emoji (🌶) is rendered incorrectly.

Twitch:
![image](https://user-images.githubusercontent.com/19194315/219944386-1a6e7060-619b-48d3-8c1a-a56a24735adb.png)

Twitch Downloader:
![image](https://user-images.githubusercontent.com/19194315/219944396-ac903b07-4026-424a-9024-22c1947b46a2.png)

JSON:
https://www.dropbox.com/s/ogfkf02o4rxjsvq/%5B2-18-23%5D%20forsen%20-%20Games%20and%20shit%21%20-%20Chat.json?dl=1

**Comment by ScrubN** [comment]
This seems to be an issue regarding specific high surrogate emojis

**Comment by ScrubN** [comment]
So I've realized that if we do a second pass when no emoji was found, the quick and dirty solution works and also doesn't break other emojis like flags.
