### ISSUE TITLE
Migrate to other emoji vendor

### ISSUE THREAD

**Issue by sunkhaskasis** [lay295/TwitchDownloader#551]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

In case you've not heard, the fate of Twemoji is rather uncertain for the near future: 
https://github.com/twitter/twemoji/issues/570

TL;DR: Many people responsible for the project were laid off and nobody knows what's going to happen to it now. The Unicode 15.0 update was supposed to be dispatched sometime around last year, but wasn't because of the aforementioned reasons. 

If Twemoji is not going to receive new updates, it might be a good idea to choose a different emoji vendor. One option I've explored was Google Noto Color Emoji, another open-source emoji project available here: 
https://github.com/googlefonts/noto-emoji

It receives regular updates and is compliant to the Unicode 15.0 standard. One major problem it has, however, is the lack of pre-made flag emoji which are available in Twemoji.

Of course, this is far from being a priority and Noto isn't the only open-source emoji vendor, but with Unicode being annually updated, Twitch Downloader would benefit from migrating as to not miss out on the Unicode updates.

**Comment by sunkhaskasis** [comment]
A little update: I've messed around with it and have a small proof of work:
![image](https://user-images.githubusercontent.com/19194315/220464481-10005d65-db66-437b-b6d5-369e0d0d04a8.png)

As you can see, Noto emoji do work well, but many of them would have to be checked for having "FE0F" in the filename to render properly.

**Comment by ScrubN** [comment]
> but many of them would have to be checked for having "FE0F" in the filename to render properly.

This should have been fixed in #547. Apparently `String.StartsWith()` and `Span<T>.StartsWith()` don't treat emojis the same which is why the FE0F (and #548) issues appeared

**Comment by ScrubN** [comment]
Also I'm not opposed to switching to the Noto color emojis. It looks like we should be able to reliably fetch the zip at runtime too instead of embedding it which means making the application file size 8MB smaller. *~~Also by not attributing twemoji in the readme we've been violating the license~~*
