### ISSUE TITLE
Chat mask is just a white video

### ISSUE THREAD

**Issue by Aquil100** [lay295/TwitchDownloader#557]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

Since I updated to the most recent version the chat mask has been generating as just a full white video. The chat still renders fine. Previously this function always worked fine for me, but now I tried to download an older version and the problem persists. I also already tried clearing the cache and using a different codec. Unfortunately it doesn't give me any error message for further details.

**Comment by ScrubN** [comment]
You need to set the alpha of the background color to 0. The mask generator reads directly from the alpha of background color.

**Comment by Aquil100** [comment]
Welp I'm dumb
Maybe the update reset the alpha channel values and I completely forgot about that step.
Thank you!
