### ISSUE TITLE
Possible to render transparent chat?

### ISSUE THREAD

**Issue by catches** [lay295/TwitchDownloader#558]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

Hey, so I noticed in most of xQc's youtube videos, there's this transparent chat with some shading and shadow, is it possible to get this?
![image](https://user-images.githubusercontent.com/105005455/221261585-4fb3e4cf-4cd3-4ea1-acd6-975a4c98caaf.png)

**Comment by ScrubN** [comment]
Enable generate mask, set background alpha to 0, and then use the mask output as a transparency override in your video editing software.

Or set background alpha to 0 and use a codec that supports transparency like ProRes.
