### ISSUE TITLE
Problem when downloading in 'task queue'

### ISSUE THREAD

**Issue by spiki12345** [lay295/TwitchDownloader#561]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

The problem is with the "task queue" when the streamer records multiple live streams with the same title on the same day. When the files are saved, only one is saved and the others are lost because they are overwritten by the last one downloaded. The solution would be for the program to detect if there is already a file with that name, and to add a number or something to the name of the next file so that it is not overwritten. For example, in the image, only one of the two videos would be saved. Both would be downloaded, but the last one downloaded would overwrite the first one. Is this an error in the program, or is there another way to do it that I don't know?

![Captura-de-pantalla-313-](https://user-images.githubusercontent.com/68424969/221753132-65422edc-6259-4877-87da-5e453ead3df9.jpg)

**Comment by ScrubN** [comment]
For now just use the `{id}` or `{random_string}` options in the filename template settings.

**Comment by spiki12345** [comment]
Thanks for the quick reply
