### ISSUE TITLE
Wrong portion downloaded

### ISSUE THREAD

**Issue by indeboss** [lay295/TwitchDownloader#562]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

Tried to download a portion of [this](https://www.twitch.tv/videos/1737199401) vod - from the beginning till 1:06:58, but instead it only downloaded it till ~46 min. The app didn't show any errors.
The only thing I can think of is that this vod was created after the streamer disconnected, so it shares the same name as a vod I downloaded before (but I saved them with different names).

So what I did for a workaround, to get the actual part I needed, is I set the end mark for 1:30:30 and it downloaded a part till 1:08:38, even after I cleared cache.

**Comment by indeboss** [comment]
Tried it on a different abrupted stream with a name **different** from the original one - this time, this time there was no issue. So maybe it does have something to do with abrupted streams of the same name specifically.

**Comment by ScrubN** [comment]
I'm unable to reproduce.

Also stream names are never utilized, they're only displayed for the user's convenience.

**Comment by ScrubN** [comment]
Closing due to stale, and the video downloader has been significantly rewritten since this issue was made. If it occurs again, please make a new issue.
