### ISSUE TITLE
Error message when trying to download VOD: Could not find a part of the path

### ISSUE THREAD

**Issue by Racoon8** [lay295/TwitchDownloader#565]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates

### Write stuff here

I'm new to the app, pretty much just downloaded and I'm not sure I set it up properly. But this is the error message I'm currently getting when trying to download a video: 

https://ibb.co/znQCbsT

**Comment by ScrubN** [comment]
That was a bug regarding video downloading in the 1.51.2 pre-release, it has since been fixed for upcoming 1.51.3.
To fix it, you can either manually create the directory or do a chat download/update/render with images enabled and the directory will be created.

**Comment by madaios** [comment]
easy fix, just go to C:\Users\name\AppData\Local\Temp and create a folder named TwitchDownloader

**Comment by ScrubN** [comment]
Oh this is fixed by the way
