### ISSUE TITLE
Sequence Contains No Elements

### ISSUE THREAD

**Issue by SgtPig52** [lay295/TwitchDownloader#569]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

When downloading a bod it just says ERROR: Sequence contains no elements

**Comment by ScrubN** [comment]
Please provide the VOD ID and application version

**Comment by SgtPig52** [comment]
Fixed it now its just not showing finished downloads

**Comment by ScrubN** [comment]
- Continue in #541
