### ISSUE TITLE
Problem rendering out chat with Generate Mask

### ISSUE THREAD

**Issue by NicolasJMendez** [lay295/TwitchDownloader#57]
Hey, sorry to keep bothering you but with the latest build (1.31) the program keeps crashing. [Here is a video.](https://drive.google.com/file/d/1HHtLMDwBpSRVEOxkCT1Fn_uLAIHC2ksV/view?usp=sharing)

I've selected the MP4 container with h.264 encoding (also tried 265) and it just crashes right when you get to "Rendering Video". I get 2 videos made but they are just empty. I tried looking in the program root for some error log files but didn't find any, maybe you don't have error logging in your program? or I just missed it? 

Regardless I thought that this was a pretty significant issue to justify opening another issue ticket. Also, I did however try rendering it out with a regular background color using MP4/H.264 and that worked as usual. It must be something with the mask generation. Unless of course I am doing something wrong lol

Thanks!

**Comment by lay295** [comment]
Hmmm, I replicated your settings and same chat and I'm unable to reproduce the crash.
![image](https://user-images.githubusercontent.com/1060681/90808655-5f77c500-e2ee-11ea-857a-fafe90d92c56.png)

But yeah my program needs more logging... My only guess it maybe you changed the ffmpeg arguments? I think it resets when you select the format/codec though so probably not. You can try and delete everything in %TEMP%/TwitchDownloader and try again. If still not i'll try and add more logging.

**Comment by NicolasJMendez** [comment]
I've not changed any ffmpeg parameters and have just tried deleting your folder in TEMP but the problem still persists. 

I've tried a few different things while keeping the render settings the same (keeping generate mask on). I've tried with chatlogs(not embedded emotes) and chatlogs (embedded emotes) from the chat downloader, still crashes. I've also tried to turn off emotes both FFZ and BTTV on the rendering but still crashes. Kind of all I can think of.

Still everything works if I don't render out a mask.

Thanks!

**Comment by NicolasJMendez** [comment]
I had a friend try it out, who doesn't live with me and on a different setup. He gets the same crashing. Also, I tried it again just now and it rendered a little longer (like, 2 seconds total) and it managed to render 5 chat entries on the video that was exported. Hope that info is of any use.

**Comment by lay295** [comment]
Sent it to my roommate and it crashes in theirs which is good, so later when their not on it I'll debug it on their computer.

**Comment by lay295** [comment]
Well it was a memory access error, and disabling compiling optimizations for a part of the code fixed it, still no idea why it happened.

Working on my computer in release mode and works on my roommates computer too.

**Comment by NicolasJMendez** [comment]
Problem solved and is working! Awesome tool thanks for your service!
