### ISSUE TITLE
ERROR: Sequence contains no elements

### ISSUE THREAD

**Issue by k1omsu** [lay295/TwitchDownloader#570]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

When I try to download the VOD https://www.twitch.tv/videos/1750033696 it gives me ERROR: Sequence contains no elements
And also I can't choose quality. I've tried with Oauth but it also doesn't work
![image](https://user-images.githubusercontent.com/126907186/222794656-7bc780d1-83b7-469f-98de-3a2414e3580d.png)
.

**Comment by ScrubN** [comment]
Not our fault. I'll add a custom error message.

![image](https://user-images.githubusercontent.com/72096833/222813355-9ac1caf5-89ba-4097-afb4-a64c4d02f88b.png)
