### ISSUE TITLE
Reduce Embedded Emotes to Minimum

### ISSUE THREAD

**Issue by goldbattle** [lay295/TwitchDownloader#571]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

It would be nice to have just the emotes that are contained in the chat file retained in the embedded data. This would reduce the size by a lot since not all first or thirdparty emotes are used over a stream or clip. Would require on download the parsing of emotes, but if this logic is factored out so both the rendering and download use it, I think it could be doable.

**Comment by ScrubN** [comment]
I've got it working. I'll try to see about bits and badges too in the same PR

**Comment by ScrubN** [comment]
Before:
![image](https://user-images.githubusercontent.com/72096833/222831463-05759d13-8cdb-42cf-8237-2137630e20d2.png)
After:
![image](https://user-images.githubusercontent.com/72096833/222831483-9457fdc6-a088-4330-bcc2-71a0ff368bcf.png)

Relatively smaller streamer but point still stands, it's a huge reduction in size.

**Comment by ScrubN** [comment]
Let me know what you think of the PR
