### ISSUE TITLE
Invalid Clip ID Parsing Error

### ISSUE THREAD

**Issue by goldbattle** [lay295/TwitchDownloader#573]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Both

### Describe your issue here

Both these seem to break for me on parsing:
- https://clips.twitch.tv/CorrectGoodCrocodileDerp-GoIV29dcyU_WKEOC
- https://clips.twitch.tv/DistinctBoxyInternPMSTwin-IX-tAqSy0d098iZL

```
CorrectGoodCrocodileDerp-GoIV29dcyU_WKEOC
DistinctBoxyInternPMSTwin-IX-tAqSy0d098iZL
```

Likely the underscore? `_` and dash `-`?
https://github.com/lay295/TwitchDownloader/blob/7ce73828d9a05d585cb62673d2620f38d55e6e8b/TwitchDownloaderWPF/PageClipDownload.xaml.cs#L108-L122

And here for the CLI?
https://github.com/lay295/TwitchDownloader/blob/7ce73828d9a05d585cb62673d2620f38d55e6e8b/TwitchDownloaderCLI/Modes/DownloadChat.cs#L33-L34

**Comment by ScrubN** [comment]
CLI regex finds both of them
![image](https://user-images.githubusercontent.com/72096833/222872286-21e3c82b-d77c-43ff-b723-daaae26aceb9.png)

**Comment by goldbattle** [comment]
Oh it seem to work in the GUI if I specify the whole URL, oops. Let me double check the CLI.

**Comment by ScrubN** [comment]
Can confirm just the ID breaks. I swear I tested all combinations. Will fix
![image](https://user-images.githubusercontent.com/72096833/222872436-b5dd9b82-423b-40ab-8b84-26b9fd15faff.png)
![image](https://user-images.githubusercontent.com/72096833/222872454-0208a40b-b548-4684-b6ab-25fb26ab1558.png)

**Comment by ScrubN** [comment]
> Oh it seem to work in the GUI if I specify the whole URL, oops. Let me double check the CLI.

The issue was probably a spacebar because we current aren't running string.Trim.

**Comment by goldbattle** [comment]
If I use the full url in the CLI it also works for me, but these do not:
Worst:
```
TwitchDownloaderCLI clipdownload --id https://clips.twitch.tv/DistinctBoxyInternPMSTwin-IX-tAqSy0d098iZL -o /tmp/video.mp4
TwitchDownloaderCLI clipdownload --id https://clips.twitch.tv/CorrectGoodCrocodileDerp-GoIV29dcyU_WKEOC -o /tmp/video.mp4
```
Broken:
```
TwitchDownloaderCLI clipdownload --id DistinctBoxyInternPMSTwin-IX-tAqSy0d098iZL -o /tmp/video.mp4
TwitchDownloaderCLI clipdownload --id CorrectGoodCrocodileDerp-GoIV29dcyU_WKEOC -o /tmp/video.mp4
```

**Comment by ScrubN** [comment]
> If I use the full url in the CLI it also works for me, but just the ID doesnt seem to work.
> 
> Works:
> 
> ```
> TwitchDownloaderCLI clipdownload --id https://clips.twitch.tv/DistinctBoxyInternPMSTwin-IX-tAqSy0d098iZL -o /tmp/video.mp4
> TwitchDownloaderCLI clipdownload --id https://clips.twitch.tv/CorrectGoodCrocodileDerp-GoIV29dcyU_WKEOC -o /tmp/video.mp4
> ```
> 
> Broken:
> 
> ```
> TwitchDownloaderCLI clipdownload --id DistinctBoxyInternPMSTwin-IX-tAqSy0d098iZL -o /tmp/video.mp4
> TwitchDownloaderCLI clipdownload --id CorrectGoodCrocodileDerp-GoIV29dcyU_WKEOC -o /tmp/video.mp4
> ```

Looks like I forgot to add a carat to the CLI clip downloader regex, whoops.

**Comment by ScrubN** [comment]
Tested it against 12 or so different videos/clips and it seems to work 100% of the time.
