### ISSUE TITLE
Add animated FrankerFaceZ emotes

### ISSUE THREAD

**Issue by sunkhaskasis** [lay295/TwitchDownloader#577]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

So FFZ released quite a big update recently, which includes support for animated emotes. From what I gathered, when you upload an animated emote, it creates two versions: animated and static. Here's an example of an animated emote:
https://cdn.betterttv.net/frankerfacez_emote/720546/animated/4

And here's the same emote, but static:
https://cdn.betterttv.net/frankerfacez_emote/720546/4

Any emote that was uploaded prior to the update doesn't have an animated version (naturally), so if you try adding "animated" to the url, it'd result in error 404. I guess what could be done is when channel emotes are fetched, prefer the animated version and if it's not found, skip it and look for the static one.

**Comment by ScrubN** [comment]
I guess I'm waiting a few days to work on this, because this emote is indeed animated but the API response says it isn't
![image](https://user-images.githubusercontent.com/72096833/222984323-c4d9aa08-c843-4b31-8f55-0ead2a23917b.png)

**Comment by sunkhaskasis** [comment]
> I guess I'm waiting a few days to work on this, because this emote is indeed animated but the API response says it isn't ![image](https://user-images.githubusercontent.com/72096833/222984323-c4d9aa08-c843-4b31-8f55-0ead2a23917b.png)

Actually, that's only on BTTV's side. FFZ's native API has it exposed, as you can see here:
https://api.frankerfacez.com/v1/room/id/26964566
