### ISSUE TITLE
Error while trying to render chat

### ISSUE THREAD

**Issue by Ashdemai** [lay295/TwitchDownloader#578]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Command Line Interface

### Describe your issue here

Downloading the JSON file is fine, but trying to render it out gives me this error
```
[STATUS] - Fetching Images [1/2]Unhandled exception. System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean )
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at TwitchDownloaderCLI.Modes.RenderChat.Render(ChatRenderArgs inputOptions)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at TwitchDownloaderCLI.Program.Main(String[] args)
--- End of stack trace from previous location ---

   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at TwitchDownloaderCLI.Modes.RenderChat.Render(ChatRenderArgs inputOptions)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at TwitchDownloaderCLI.Program.Main(String[] args)
Aborted (core dumped)
```

I use these flags `-h 1080 -w 422 --framerate 30 --update-rate 0 --font-size 18 --timestamp -o` if that helps any bit.

**Comment by Ashdemai** [comment]
I use these flags `-h 1080 -w 422 --framerate 30 --update-rate 0 --font-size 18 --timestamp -o` if that helps any bit.

**Comment by ScrubN** [comment]
Are you double-clicking? The cancel button appears right under the render button.

**Comment by Ashdemai** [comment]
> Are you double-clicking? The cancel button appears right under the render button.

What do you mean? I'm using the command line.

**Comment by ScrubN** [comment]
Oh my bad, I was reading the email and missed the part about CLI.

**Comment by ScrubN** [comment]
I'm unable to reproduce using your exact args. Are you able to share the json file?

**Comment by Ashdemai** [comment]
> I'm unable to reproduce using your exact args. Are you able to share the json file?

Here you go https://files.catbox.moe/d0fj9c.json

**Comment by ScrubN** [comment]
I'm very confused because I am able to render the chat just fine, and there are no exposed cancellation token sources in CLI so canceling should be impossible.

**Comment by Ashdemai** [comment]
It's just stuck on Fetching Images for like a minute and then dumps the error. I'm not doing anything more. I even tried it with a known file that I knows rendered in the past. It was working fine a week ago. I'm using this feature quite extensively so it's really hurting my workflow.

**Comment by ScrubN** [comment]
Are you using 1.52.0?

**Comment by Ashdemai** [comment]
Yes.

**Comment by Ashdemai** [comment]
Problem fixed itself, might as well close this issue.

**Comment by ScrubN** [comment]
@Ashdemai do you happen to be using IPv6? Someone had the same issue and they suspect that might have been the cause.

**Comment by Ashdemai** [comment]
I never figured out what the issue was, AFAIK I was still using IPv4 and while it happened, it still worked on my laptop on the same router.
