### ISSUE TITLE
"ERROR: Unable to Find Thumbnail"

### ISSUE THREAD

**Issue by Sadris** [lay295/TwitchDownloader#58]
Not 100% sure to what this entails for the software itself, but I try downloading a vod and when I try that, the software keeps saying "Idle" in the corner. Not just that, but, it spits out an error message saying it cannot find the video information. I tried the 1.3.1 and 1.3 versions for reference, with this vod: https://www.twitch.tv/videos/713799008

**Comment by lay295** [comment]
Perhaps you're having internet issues or maybe a problem with the twitch api? Downloading fine here on 1.31, and gets the thumbnail.
