### ISSUE TITLE
Video quality selection when using mass downloads

### ISSUE THREAD

**Issue by zeaki** [lay295/TwitchDownloader#581]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

Please add the option when using the mass downloads tab to select video quality like in VOD download tab. Downloaded over 40gb for 2 videos overnight because I didn't recognize there wasn't the option. On top of it all both ended up failing at 99%.

**Comment by Daniele1926** [comment]
up, i need too
