### ISSUE TITLE
"Object reference not set to an instance of an object." error when downloading chats and VODs

### ISSUE THREAD

**Issue by agenttud** [lay295/TwitchDownloader#583]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

When I try to download certain chats (and sometimes VODs as well), I get "ERROR: Object reference not set to an instance of an object.". I'm not sure what causes this issue, since it occurs pretty irregularly.

The only thing I managed to isolate is that it started happening with 1.51.2, since downgrading to 1.51.1 could successfully download problematic items. I thought 1.52.0 would solve it, but it's still happening. An example is the following VOD:

https://www.twitch.tv/videos/1756335644

If I try to download it with version 1.52.0, I get that error for both VOD and chat. If I do with 1.51.1, it works successfully.

**Comment by ScrubN** [comment]
Can you please enable "Verbose Errors" in the application settings? It will generate a pop-up to tell me where the issue is.

**Comment by ScrubN** [comment]
Never mind, I was able to reproduce the error locally
