### ISSUE TITLE
Chat downloader shows different time compared to VOD download time. (Compared Version 1.51.1 against 1.52.0)

### ISSUE THREAD

**Issue by DieHardjagged** [lay295/TwitchDownloader#585]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

I compared version 1.51.1 against 1.52.0 and noticed this slight timebug (I cant say if simply the 12 got squished and only shows up as 1 or if its legit a bug), same vod link, but different time, its not a problem on the VOD download tab.
![Screenshot 2023-03-07 012407](https://user-images.githubusercontent.com/62212036/223286955-47dce8b4-9fe5-425b-8256-d5fd2622cb29.png)

**Comment by ScrubN** [comment]
This is intentional, I added a conversion from UTC to local time for most of the pages, though it seems I forgot to add it to the VOD page too. I guess I could make it an application wide setting if you would prefer that

**Comment by DieHardjagged** [comment]
> This is intentional, I added a conversion from UTC to local time for most of the pages, though it seems I forgot to add it to the VOD page too. I guess I could make it an application wide setting if you would prefer that

I basically personally always prefer the UTC time because i actually date the files by when the stream originally happened acccording to my local time zone and not the time zone of the Streamer.

**Comment by ScrubN** [comment]
"Local time" should be defined by the current time zone set on your PC, not the streamer's

**Comment by DieHardjagged** [comment]
> "Local time" should be defined by the current time zone set on your PC, not the streamer's

I really thought it was a bug, because the time on the VOD download page is still correct, but its labeled as 12:00:21 instead of 00:01:21, thats why i mentioned it in the first place.
