### ISSUE TITLE
ERROR: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by SellPL** [lay295/TwitchDownloader#588]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

When i try to download a valid VOD i get "ERROR: Object reference not set to an instance of an object." Is there any fix for this? The only thing i could find in issues was  this https://github.com/lay295/TwitchDownloader/issues/521 but in their case video wasnt avaliable (mine is pretty much the opposit)
![Screenshot 2023-03-07 111528](https://user-images.githubusercontent.com/76593292/223363445-c4a48372-8cfd-4bd7-8c21-3c76f99c7a7c.jpg)

**Comment by ScrubN** [comment]
When you go to the VOD page, are any of the chapters missing artworks/are labeled as "chapter #"?
![image](https://user-images.githubusercontent.com/72096833/223364207-f7c98d2c-b51a-4781-8aaf-8b2e70fca3eb.png)

**Comment by SellPL** [comment]
> When you go to the VOD page, are any of the chapters missing artworks/are labeled as "chapter #"? ![image](https://user-images.githubusercontent.com/72096833/223364207-f7c98d2c-b51a-4781-8aaf-8b2e70fca3eb.png)
> 
> If no, I will need you to enable "Verbose Errors" in the settings and take a screenshot. Getting the VOD url would also help a lot.

so i turned on "Verbose Errors" (dont know what it does) and here is a link https://www.twitch.tv/videos/1757314368 Still get same error :\

**Comment by SellPL** [comment]
also no chapters
