### ISSUE TITLE
[Request] Outline options for usernames and emotes

### ISSUE THREAD

**Issue by Dry4Haz** [lay295/TwitchDownloader#59]
I tried out the new transparency mask feature and it's great, but I do think it looks a bit weird when the usernames and emotes don't have an outline like the message text. It's mostly the usernames that look weird but it would be nice to have some sub-option to add an outline to everything.

Another small thing that you might call an issue. I watched your video showing how to use the mask and I noticed your update time for the render was set on 0.2 which I assumed made it so the chat video renders chat messages 5 times a second and not once a second. But when I enter the same value I just get an error. Anything under 1 does this.

**Comment by Dry4Haz** [comment]
Okay, so about my issue, it seems like it works by changing it to 0,2 with a comma instead of 0.2. But I noticed on highlighted vods it doesn't really work, but that's probably on twitch's end.

**Comment by lay295** [comment]
Fixed in 1.32, no emoji outlines but I feel the contrast in images should be enough.
