### ISSUE TITLE
Quality Video Selection is empty.

### ISSUE THREAD

**Issue by Gitphex** [lay295/TwitchDownloader#594]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

The quality video selection is empty when i try to select one, the VOD is recognized but the list for different quality videos is totally empty.

I hope you can fix it as soon as possible, and thanks a lot for this amazing program.

Greeting.

Edit: I think i have another problem here, the streamer never set the VOD only for subscribers before, can this be the issue?

When i try to download i got this. "ERROR: Insufficient access to VOD, OAuth may be required."

Greetings.

**Comment by ScrubN** [comment]
If you go to the VOD link, it looks like this in the browser, yes? The error you got and the lack of a quality selector are consequences of this. 
![image](https://user-images.githubusercontent.com/72096833/223925041-cccc969b-c3f2-4cca-9f2f-7c9a3aae5630.png)

**Comment by Gitphex** [comment]
Yes, i think it was that, so not a problem / issue of the program, instead the authorization to view the video.

Thanks for the answer!... Greetings.
