### ISSUE TITLE
System.InvalidOperationException: The stream is currently in use by a previous operation on the stream.

### ISSUE THREAD

**Issue by jaycade** [lay295/TwitchDownloader#598]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

When downloading the VOD located at https://www.twitch.tv/videos/1704000036 the app seemingly fails to finalize the VOD, errors with a .NET Runtime error **_System.InvalidOperationException: The stream is currently in use by a previous operation on the stream._**, and then the GUI app completely crashes.

![image](https://user-images.githubusercontent.com/5213393/224312703-606cb19e-6f7c-42b8-90fe-6465318cc9db.png)
![image](https://user-images.githubusercontent.com/5213393/224312729-4c4e1f34-efe5-4315-b874-71b8fdb12675.png)

[ffmpegLog.txt](https://github.com/lay295/TwitchDownloader/files/10941908/ffmpegLog.txt) shows numerous lines of **_output.ts: corrupt input packet in stream 1_** which correspond with the muted segments of the VOD when I view the output.ts file.
Despite crashing during finalizing of the VOD, the app completes the .mp4 file, and when I skim
through the video and view the parts in and around the muted areas, the video itself appears to be fully intact, and muted parts of the VOD by Twitch are to be expected, so I'm unsure what exactly what the problem is.

**Comment by ScrubN** [comment]
I believe I have found the source of the issue, however I am more interested in how the hell it caused the GUI to crash despite being in a try-catch block.

**Comment by jaycade** [comment]
Edit: The GUI seems to crash with every VOD download, not just the one linked above.
Here's the accompanying app error from Windows Event Log if it helps.

![image](https://user-images.githubusercontent.com/5213393/224452443-c9dff17d-480c-4f1f-9230-c383c717068b.png)

**Comment by ScrubN** [comment]
You can test if the issue is resolved on your end with a PR build artifact: https://github.com/lay295/TwitchDownloader/actions/runs/4390473161

**Comment by RealityRipple** [comment]
This issue occurs if Windows Defender's Real Time Protection is on, even on a solid state drive.
Tested the linked build on a 100%-reproducible-behavior system, issue confirmed as patched. Thank you for your hard work!
