### ISSUE TITLE
RTL languages support?

### ISSUE THREAD

**Issue by Adam-Saeed** [lay295/TwitchDownloader#6]
Will there be an upcoming support for languages such as Arabic? I mean in chat rendering. The Arabic characters do show up but they are separated when they should be connected to each other.

something like "ب ا ب ش" should be "شباب"

Thank you.

**Comment by lay295** [comment]
Uhhh, maybe? There's a good chance I won't support it because I'm not very knowledgeable about RTL languages. Could you link me a VOD that has RTL in the chat so I can try and get it to work and compare it to how twitch is displaying it? If you do I'll try and get it to work in my free time.

**Comment by Adam-Saeed** [comment]
yeah, 506214459
Thank you again
