### ISSUE TITLE
TwitchDownloader Downloads Vods MUCH Faster Than TwitchDownloaderWPF.

### ISSUE THREAD

**Issue by shini07** [lay295/TwitchDownloader#601]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

I have both set to 10 Threads but for some reason TwitchDownloaderWPF is only using around 250 Mbps while TwitchDownloader will use my full bandwidth.

**Comment by 1011025m** [comment]
Can confirm this behavior. Also, before 1.52.0 I was able to set the download threads to 50 and a 3 hour stream would be done downloading in about 2 minutes, whereas after the update the download threads is capped to 10 and is unable to use the full capability of my network.

**Comment by ScrubN** [comment]
Increase bandwidth cap in the settings.
![image](https://user-images.githubusercontent.com/72096833/224504225-c77b9ea0-fe7e-48e3-a9b2-1c2602229def.png)

**Comment by 1011025m** [comment]
> Increase bandwidth cap in the settings.

Huh, this was mentioned nowhere in the release notes.

**Comment by ScrubN** [comment]
![image](https://user-images.githubusercontent.com/72096833/224504485-fa53b68d-e7d6-4da6-b056-aac2f8da4d5c.png)
