### ISSUE TITLE
No file is present when download completes

### ISSUE THREAD

**Issue by swiffy22** [lay295/TwitchDownloader#603]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

During the process of downloading a vod, I can see the many separate, unmerged files populate the folder I've selected, but when the process is finished, the vod is nowhere to be found. I first downloaded and tried this program with 1.51.1 and had the same issue. I decided I'd wait for an update to see if it was resolved, but no luck. Have I missed a step with the installation?

**Comment by ScrubN** [comment]
Are you using 1.51.2? If so did you get a log message saying that the cache was not cleared and there is a log file inside the cache? If yes, can you please send the log file?

**Comment by swiffy22** [comment]
I'm not sure what caused the issue, but I seem to have found a solution. I had the application pinned to my taskbar and have been opening it that way. Opening it this way would always cause v1.51.2 to open. I checked the program folder to look for any error log files that the program might have generated, and I noticed there was a second executable, v1.52.1. This version works as expected.

Unfortunately v1.51.2 doesn't appear to give any information in the program itself when it fails to produce a file, but if it also generates an error log file somewhere, I'd be happy to send it over if you can direct me to where it should be (if it even produced one at all). In any case, the problem appears to be resolved on the newest version. Thanks for your quick response!

**Comment by ScrubN** [comment]
I made a mistake, you should be using 1.52.1 (TwitchDownloaderWPF.exe), not 1.51.2 (TwitchDownloader.exe).

When a download fails with 1.52.1:

The log file will be located at the cache directory inside a folder that is a bunch of numbers `##########_############`. The folder should contain `output.ts`, `metadata.txt`, and `ffmpegLog.txt`. I will need ffmpegLog.txt.
If your cache is at the default location, then you can find it by entering `%temp%\TwitchDownloader` inside the start menu, file explorer, or the run dialogue.

**Comment by ScrubN** [comment]
This will continue to be tracked in #541. Further discussion can occur there.
