### ISSUE TITLE
Struggling to even run the application

### ISSUE THREAD

**Issue by rolfdansl** [lay295/TwitchDownloader#604]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates

Why is the WPF Exe not even loading...

so i ran an older version of twitchdownloader.exe when suddenly i got this error i believe it was 403 and that i wouldnt have access or content was blocked. I got on this page and saw that all the other users of old systems should switch to this WPF system, so I did. as im trynna launch the 103 MB package that was linked under a post, im trying to run this TwitchDownloader.WPF but it doesnt even open...

anyone care to help or explain why im facing this issue...

https://user-images.githubusercontent.com/127673733/224677769-44961409-4644-4217-8a48-9c2def86538a.mp4

**Comment by MeisterLuchs** [comment]
It seems you have the .exe on your desktop. When you download the 103 MB .zip file, you have to extract all of its contents in one folder. You can then create a desktop shortcut on the .exe. 
![image](https://user-images.githubusercontent.com/37845513/224753479-bc40b416-1702-4da3-aa1d-d784879ba932.png)

**Comment by rolfdansl** [comment]
> It seems you have the .exe on your desktop. When you download the 103 MB .zip file, you have to extract all of its contents in one folder. You can then create a desktop shortcut on the .exe. ![image](https://user-images.githubusercontent.com/37845513/224753479-bc40b416-1702-4da3-aa1d-d784879ba932.png)

i got it to work with a help of a friend, told me to download https://dotnet.microsoft.com/en-us/download/dotnet/6.0 and sent me this zip archive: https://drive.google.com/file/d/1NqkffJR3o56CTKqBe0RaSsHvnNfpvu_7/view?usp=sharing (too big to link it on github) and then it worked, i really dunno where the problem was, didnt have second .exe on my desktop but glad that its fixed now...

**Comment by rolfdansl** [comment]
yes ty
