### ISSUE TITLE
Don't know how to run the app

### ISSUE THREAD

**Issue by Lynokz** [lay295/TwitchDownloader#607]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

Hello, English is not my native language sorry, I'm desperately trying to install the application, I've read the "where is the EXE" but I can't quite understand what I should do to find it. I downloaded the latest version available and it's the first time I've used the site so I'm a bit lost, is it possible to have a quick explanation? Thank you very much for your work !

**Comment by MeisterLuchs** [comment]
Welcome to GitHub! 😃 
In the "where is the EXE" file should be a link. When you open that page there is a list of releases. 
The release labelled "Latest" is the recommended one for most users. On the bottom of each release you can find "Assets". 
You need to download the appropriate asset there, the names should be descriptive enough.

**Comment by ScrubN** [comment]
You can either follow the link in the "Where is the EXE" file or you can click on the "download here" in second checklist item at the top of your issue post.
From there you should see a post with a green "Latest" tag. You'll want to scroll down to the "Assets" section of the post and download TwitchDownloader**GUI**.
Once downloaded, you can unzip the program and you're golden!

**Comment by ScrubN** [comment]
Closing as stale. If you need more help, don't be afraid to ask!
