### ISSUE TITLE
ERROR: Invalid pattern

### ISSUE THREAD

**Issue by dro41la** [lay295/TwitchDownloader#612]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

Hi, can you help with an error? When I try to render the chat, I get the following error: "ERROR: Invalid pattern '(?<=^| )))(?=$| )' at offset 9. Too many )'s." This error only occurs on certain channels. What could be the cause?

**Comment by ScrubN** [comment]
Can you enable "Verbose Errors" in the application settings an send a screenshot of the output? I know what the error is but I don't recall having hat specific pattern anywhere.
