### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by rolfdansl** [lay295/TwitchDownloader#617]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates

### Write stuff here

Trynna get my Chat Log as usual, got my JSON File here and this happens as im trynna render it, what does it mean?

https://user-images.githubusercontent.com/127673733/226103626-4f959ad6-6293-4c05-9978-6c9aa970d7e3.mp4

@ScrubN

**Comment by ScrubN** [comment]
The error message says it is not a valid chat format. The file extension is probably incorrect.
I will fix the crash though.
