### ISSUE TITLE
Crash when multiple queued VOD downloads finish at the same time

### ISSUE THREAD

**Issue by Rhodan81** [lay295/TwitchDownloader#618]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

GUI version crashes when multiple queued VOD downloads finish at the same time. I was downloading highlight videos that are all roughly the same length (about 30 minutes of video each). I had left the default setting of 6 paralell downloads. Apperently ffmpeq was still running after the crash and the downloaded files did finalize correctly. Had to reopen the Downloader and requeue the rest of my downloads.

This happened twice, so it seems to be repeatable. After that I changed it to download just 1 at a time and the issue went away.

Screenshot of the crash. Got multiple of these error windows:
![Error](https://user-images.githubusercontent.com/549421/226120699-18025065-7d33-45a8-90f0-17db89249a25.png)

**Comment by ScrubN** [comment]
Duplicate #598. Has been fixed for next release
