### ISSUE TITLE
Cant render this .json

### ISSUE THREAD

**Issue by HellbringerOnline** [lay295/TwitchDownloader#619]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

Cant render this .json
![image](https://user-images.githubusercontent.com/14059683/226129314-7295ce6a-34f2-46b3-bd9e-df7170dc31cb.png)

![image](https://user-images.githubusercontent.com/14059683/226129411-211d1646-d70f-4386-af98-f43928bd201b.png)
![image](https://user-images.githubusercontent.com/14059683/226129399-0d04471b-71be-437e-8685-0d0fdac22c46.png)
![image](https://user-images.githubusercontent.com/14059683/226129478-3d67e0f2-5f14-4de1-8252-505ad39b7db9.png)
![image](https://user-images.githubusercontent.com/14059683/226129492-4489419b-78cd-4a6a-ba25-e6f2b0d5d5a5.png)
![image](https://user-images.githubusercontent.com/14059683/226129507-0267721f-b494-4b63-a8f6-87e25258c165.png)

(https://github.com/lay295/TwitchDownloader/files/11009294/2022.06.30.koshkamoroshka.-.-.Chat.zip)

**Comment by ScrubN** [comment]
Fixed it. Surprised I didn't run into that issue myself given the large amount of chats I've tested since #518

**Comment by ScrubN** [comment]
Yeah, looking at the image comparison I made, there are messages that should have resulted in this occurring. I don't get it..
