### ISSUE TITLE
No .mp4 file from VOD

### ISSUE THREAD

**Issue by Catherdaz** [lay295/TwitchDownloader#62]
I have tried downloading a VOD numerous times in the last few days, it never shoes up in the directory i save it.

The program goes through the download, combines parts and finalizes .mp4 without an issue and says "done" without any log messages. But the file is not in the folder. (it works with .json however)

Any solutions to this issue?

**Comment by Opengreen-xd** [comment]
Same thing here. Croped VOD - cant see the file in end directory

**Comment by Dakiller1234** [comment]
I have the same exact problem , the video finishes download but you cannot find it anywhere on your pc ! i dont understand quite why !

**Comment by SanderToni** [comment]
same here

**Comment by goldbattle** [comment]
Closing due to old age, feel free to reopen if this is still an issue with the current release.
