### ISSUE TITLE
BTTV Emotes Download Issue

### ISSUE THREAD

**Issue by LegendaryWolfeh** [lay295/TwitchDownloader#625]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

When trying to download the chat with BTTV emotes checked, get null value error. Effects JSON and HTML options, if BTTV unchecked everything works fine. I've attempted after clearing cache, as well as just deleting and retrying after deleting cache as well.
![image](https://user-images.githubusercontent.com/39720000/226208703-23d7a12c-026a-4f79-b9bf-0c9f19678e85.png)
![image](https://user-images.githubusercontent.com/39720000/226208378-1a25a6f9-214e-43ca-8684-b69c9396e759.png)

**Comment by ScrubN** [comment]
This was fixed in 561277a for the next release. Until that releases just disable BTTV when downloading from a channel which does not have BTTV emotes.
