### ISSUE TITLE
ERROR: The decryption operation failed, see inner exception.

### ISSUE THREAD

**Issue by Gangfat** [lay295/TwitchDownloader#626]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Unsure

### Describe your issue here

Trying to download VOD for 99% gives an ERROR: the decryption operation failed, see innerexception.
![Screenshot_20](https://user-images.githubusercontent.com/99077168/226381267-5d775c45-fa71-47d6-a532-a5771fe2f32b.png)
Inscription in Russian: The specified data cannot be deciphered

**Comment by Gangfat** [comment]
> Hmmm. How much time was spent downloading the video?

30 minutes

**Comment by cabcallaway** [comment]
I am expderiencing the same issue

**Comment by N0itx** [comment]
I have the same problem in version 1.52.2 but it works fine in 1.52.1
