### ISSUE TITLE
Error rendering chat mask

### ISSUE THREAD

**Issue by Zaltoman** [lay295/TwitchDownloader#632]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates

### Write stuff here

I'm running into an issue where I want a mask for my chat, and supposedly have the right encoder selected, yet I am still getting the same error as before. Is there anything I'm missing?

(ERROR: You've selected an alpha channel (transparency) for a container/codec that does not support it.\nRemove transparency or encode with MOV and RLE/PRORES (file size will be large))

![Screenshot_746](https://user-images.githubusercontent.com/25019139/227381720-3ef71b85-8a9e-42d8-8787-e07622ba707b.png)

**Comment by ScrubN** [comment]
There was an error in the logic for determining supported codecs for transparency which was fixed in 4cebb655eda5a14d58f9a69dd465fb8c2e1a761d for next release. The issue may go away if you use a codec other than ProRes/RLE.

**Comment by lay295** [comment]
I assume it's just the wrong error is showing right? In this and #627 should be displaying "ERROR: You've selected generate mask with an opaque background. Reduce the background color alpha or disable generate mask."

@Zaltoman basically, if you want a mask you probably should be using H264/MP4 and setting an alpha channel in the background color

OR if you don't want to generate a mask and instead have the transparency in the video file itself you can use ProRes. AKA uncheck the mask button but you still have to set transparency in the alpha channel. No real reason to have ProRes _and_ a mask.

**Comment by ScrubN** [comment]
> I assume it's just the wrong error is showing right? In this and #627 should be displaying "ERROR: You've selected generate mask with an opaque background. Reduce the background color alpha or disable generate mask."
> 

Both the error message was incorrect and there was an error in the logic, I did some pretty thorough testing.

> @Zaltoman basically, if you want a mask you probably should be using H264/MP4 and setting an alpha channel in the background color

Yes I agree with this, though I figured they were using ProRes for the really high quality

**Comment by lay295** [comment]
> Yes I agree with this, though I figured they were using ProRes for the really high quality

I imagine they just had the defaults and wanted a mask, then the misleading error had them change to ProRes/RLE to correct the error, and it still didn't work. Just a guess though ¯\\\_(ツ)_/¯ since I imagine most users don't know how the codecs/containers actually work.
