### ISSUE TITLE
Chat rendering error

### ISSUE THREAD

**Issue by jorgeconstantini** [lay295/TwitchDownloader#633]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

Whenever I try to render chat in any setting and on any codec, I get the error "ERROR: Value cannot be null. (Parameter 'collection')
" and can't do it.

**Comment by ScrubN** [comment]
Duplicate #622.
