### ISSUE TITLE
Expose outline scale in GUI

### ISSUE THREAD

**Issue by matter1770** [lay295/TwitchDownloader#639]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates

Switched to latest version after using the 1.4 version for a long time due to it not properly rendering the chat anymore however on my new rendered files, the outline is way too thin and there isn't an option to increase it

**Comment by ScrubN** [comment]
I didn't realize outline scaling was only exposed in the CLI. I'll add it to the GUI.

**Comment by ScrubN** [comment]
e990afc8f549517794a05cabe808dfa8e0be25ac There will be an option to change outline thickness in the next release.
