### ISSUE TITLE
Last used download folder is not remembered

### ISSUE THREAD

**Issue by Azarien** [lay295/TwitchDownloader#640]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

The last used download folder when using Enqueue Download is not remembered.
Instead the "Download Folder" field in Enqueue Options dialog is empty the next time the dialog is shown.

This worked fine in 1.51.x. When downloading multiple VODs to the same folder, there was no need to browse for the folder each time.

**Comment by Azarien** [comment]
Well, it started working after several times. So I don't know what's going on.

**Comment by ScrubN** [comment]
When updating the app, user preferences usually get reset. I'm looking into this but for now it is a quirk we must deal with.
The download folder is saved when successfully setting the path using the `Browse` button.
