### ISSUE TITLE
"Required option 'o, output' is missing." depsite specifying it with other options.

### ISSUE THREAD

**Issue by YousufSSyed** [lay295/TwitchDownloader#642]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Command Line Interface

### Describe your issue here

I'm using an M1 MacBookAir with `TwitchDownloaderCLI-1.52.2-MacOS-x64`. This is the command that returns an error:

```
./TwitchDownloaderCLI chatrender -i QuickDevStream.txt --background-color #18181C --font-size 18 -w 426 -h 1080 --timestamp --output-args='-c:v libx264 -crf 25 "{save_path}"' -o QuickDevStreamChat.mp4
```

I also tried the following commands but they didn't work either:
`./TwitchDownloaderCLI chatrender -i QuickDevStream.txt --background-color #18181C --font-size 18 -w 426 -h 1080 --timestamp --output-args='-c:v libx264 -crf 25 "{save_path}"' -o QuickDevStreamChat.mp4`
`./TwitchDownloaderCLI chatrender --input QuickDevStream.txt --background-color #18181C --font-size 18 -w 426 -h 1080 --timestamp --output QuickDevStreamChat.mp4`

I also tried changing `--timestamp` to `--timestamp=true` but that didn’t work too. 

I did this command and got a different error message: `./TwitchDownloaderCLI chatrender --input QuickDevStream.txt --output QuickDevStreamChat.mp4` and opened another issue [here](https://github.com/lay295/TwitchDownloader/issues/643).

But Ideally, I'd want to write the input and output files names in quotes and spaces:

```
./TwitchDownloaderCLI chatrender -i "Quick Dev Stream.txt" --background-color #18181C --font-size 18 -w 426 -h 1080 --timestamp --output-args='-c:v libx264 -crf 25 "{save_path}"' -o "Quick Dev Stream Chat.mp4"
```

**Comment by YousufSSyed** [comment]
@ScrubN I still get this problem even with the patched version you showed me.

**Comment by ScrubN** [comment]
I am able to reproduce on both mac and windows. The issue is that the shell thinks your specification of the background color is a comment.
![image](https://user-images.githubusercontent.com/72096833/229250072-2673c739-6fc4-46af-916a-95a1ce4d3af7.png)
Notice how everything after the '#' is greened out until I wrap it in quotation marks
![image](https://user-images.githubusercontent.com/72096833/229250124-fe9c5c5c-85df-44b2-9967-608e923353a5.png)
