### ISSUE TITLE
Download Speed Limiter

### ISSUE THREAD

**Issue by KiraaQueen** [lay295/TwitchDownloader#645]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

I would really like to see an option to set the download speed limit. It is very unpleasant when all traffic is filled only with downloading the VOD

**Comment by ScrubN** [comment]
Duplicate #502. This has been a feature for the last 3 releases.

**Comment by KiraaQueen** [comment]
Ah, sorry, turned out that I checked only opened issues. I read #502 , I'll try to change download threads number, Thank you.
