### ISSUE TITLE
Always not all badge images when saving a chat.

### ISSUE THREAD

**Issue by HellbringerOnline** [lay295/TwitchDownloader#646]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates

### Write stuff here

When I download any chat and then immediately update it, there are always not enough badge images.

![image](https://user-images.githubusercontent.com/14059683/229167242-ead85b58-d3e6-470a-be5e-87d4348b5ba0.png)

**Comment by ScrubN** [comment]
Yeah I noticed that too. I'm not what the cause is, I'll have to look into it

**Comment by ScrubN** [comment]
1d3ce01fadac2c8921e8064dde9120ebca1d7419 Fixed
