### ISSUE TITLE
Chat Relative Timestamps reset after 24 hours

### ISSUE THREAD

**Issue by KamasamaK** [lay295/TwitchDownloader#647]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

For VODs that are longer than 24 hours, the relative timestamp for Chats resets after 24 hours back to 0:00:00 instead of 24:00:00.

**Comment by ScrubN** [comment]
The issue is caused by the `TimeSpan.ToString()` [format string](https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-timespan-format-strings) not supporting total hours; only hours. I will do my best to fix this as it also affects another feature I am trying to add.
