### ISSUE TITLE
Bttv issue: ImagesUnhandled exception. System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'collection'))

### ISSUE THREAD

**Issue by cyperdark** [lay295/TwitchDownloader#648]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Command Line Interface

### Describe your issue here

Command:
```
TwitchDownloaderCLI.exe ChatDownload --id 1773421917 --embed-images --bttv true --ffz true --stv true --temp-path "C:/Users/user/Documents/cache" -o "C:/Users/user/Downloads/1680364027_1773421917.json" -b 6023 -e 6498
```

![image](https://user-images.githubusercontent.com/21735205/229300805-76e616d0-1d4d-4b69-b329-1d2c290538f4.png)

**Comment by cyperdark** [comment]
![1680364826_ZP7bZfyjP1](https://user-images.githubusercontent.com/21735205/229301542-0d234ca1-fa23-47c1-8eba-5e57e8a48430.png)

**Comment by ScrubN** [comment]
Duplicate #622. This has been fixed for the next release, though you can use a workflow build in the meantime https://github.com/lay295/TwitchDownloader/actions/runs/4580082135
