### ISSUE TITLE
No queue possible if it is the same VOD

### ISSUE THREAD

**Issue by xRangerDE2** [lay295/TwitchDownloader#649]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates

### Write stuff here

Hi guys, when you want to download the first 60 minutes of a VOD and then the second 60 minutes (with the same VOD URL) it is not possible to put both in the queue because you have to wait because if you try that only one file with the same name is downloaded.

So 2 parts are downloaded and the first part is replaced by the second. How about a part function so that at the end of the mp4 somehow a _1 _2 etc ?

**Comment by ScrubN** [comment]
You can add a `{random_string}` parameter to your filename template in the settings. There may also be several more filename parameters in the upcoming 1.52.3.

**Comment by xRangerDE2** [comment]
Perfect, thank you! This will definitely reduce some problems.

For the 1.52.3 it would be cool to add a parameter which creates a "download order" with the endings _1 _2 _3 etc. so that you have directly a number order as filename.

**Comment by ScrubN** [comment]
I plan on overhauling a lot of the core functionality such as filenames to allow for better compatibility, such as automatically applying `(1)`, `(2)`, as well as supporting templates in the CLI version; not just the GUI.

**Comment by indeboss** [comment]
You can still queue multiple parts, just keep them in separate folders

**Comment by ScrubN** [comment]
> I plan on overhauling a lot of the core functionality such as filenames to allow for better compatibility, such as automatically applying `(1)`, `(2)`, as well as supporting templates in the CLI version; not just the GUI.

This now exists in the task queue.
