### ISSUE TITLE
TwitchDownloaderCLI does not accept certain valid clip IDs

### ISSUE THREAD

**Issue by aidan-walden** [lay295/TwitchDownloader#65]
For example, the clip ID AnimatedCoweringDinosaur4Head is rejected because of the 4, but it is completely valid (link to clip [here](https://clips.twitch.tv/AnimatedCoweringDinosaur4Head))

**Comment by lay295** [comment]
Whoops, will fix soon.

**Comment by lay295** [comment]
Should be fixed in 1.33, feel free to comment again if it's not. Thanks for the reporting the issue.
