### ISSUE TITLE
Video Encoding Details in the GUI

### ISSUE THREAD

**Issue by Deathman451** [lay295/TwitchDownloader#651]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

I am aware of ffmpeg allowing hardware acceleration on supported GPUs. Unfortunately the GUI does not have an easy way to see, whether any hardware acceleration is being used. A simple way to see if the video is software or hardware processed during the finalization command would really help in my opinion. Of course, permitting hardware acceleration would also be really nice but that is beyond the scope of the project potentially.
For the record, I attempted to detect hardware acceleration via the Process Monitor and Process Explorer from the SysInternals Suite which can be found here: https://learn.microsoft.com/en-us/sysinternals/
I also utilized HWInfo which can be found here: https://www.hwinfo.com/
I also used the normal Task-Manager as it more easily shows video encode and decode usage of the specific video units, if the GPU has those. 
In all instances up-to-date Software was used on Windows 10 Pro, OS build 19045.2788.
The ffmpeg version used is the full version, pre-built by Gyan Dev, which I put into the folder and overwrote the bundled ffmpeg executable on my second try and simply left no binary in the folder, so whatever it downloads, for the third attempt. 
Specifics about the ffmpeg build can be found here: https://www.gyan.dev/ffmpeg/builds/

**Comment by ScrubN** [comment]
Does this help?

![image](https://user-images.githubusercontent.com/72096833/229384671-c17f24d9-6bb4-47db-b64b-d745818a06f8.png)

**Comment by Deathman451** [comment]
But that is under Chat Render, no? Does this also apply for VOD Download or Clip Download? Cause to me that looks like the Encoding setting when also downloading chat but I might be wrong. Additionally, maybe move that part to the settings window or show it in the other sections too, if it's application wide, which Codec you select. And sorry for the trouble cause I didn't look in the Chat Render settings as I was not interested in having the chat personally.

**Comment by lay295** [comment]
Yes, the hardware encoding option it just for rendering a chat.

Considering that the "finalizing" step in downloading a VOD is just re-muxing the .ts file into an MP4 and we're not re-encoding anything, there would be basically 0 benefit to using hardware acceleration so I don't really see a point in doing it. It's basically just an I/O bound operation.

**Comment by Deathman451** [comment]
Ohhh. I completely misunderstood the premise of the "finalizing video" step then. I thought it does more than just muxing the parts into one MP4 stream because it utilizes ffmpeg.
Completely my fault and that makes a lot of sense then. Thank you for the time you two took to respond to my questions. This case is closed then and I hope you enjoy the remainder of the easter holidays. :)
