### ISSUE TITLE
VOD Downloader

### ISSUE THREAD

**Issue by GoodNames18** [lay295/TwitchDownloader#652]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates

### Write stuff here

Why the quality of this vod can't find the  quality, I can't downlload tho [Image](https://i.imgur.com/P64aWJM.jpeg)

**Comment by ScrubN** [comment]
The video is subscriber only. You must subscribe with your account and then provide the OAuth to the downloader.
![image](https://user-images.githubusercontent.com/72096833/229556187-0806b69a-7a1d-4286-a160-c758b7ffbe23.png)
![image](https://user-images.githubusercontent.com/72096833/229556597-99f2249c-8262-4b5a-a75f-5e7a6937d608.png)
