### ISSUE TITLE
Can't render chat when using Russian language

### ISSUE THREAD

**Issue by seekomann** [lay295/TwitchDownloader#653]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

Error "ОШИБКА: Input string was not in a correct format." will appear if you click the "Render chat" button when using the Russian language.
There is no problem if you using English language.

**Comment by ScrubN** [comment]
Go to the scaling page, the values must be corrected. I will see if I can automate this but for now they must be manually fixed.
