### ISSUE TITLE
ERROR: Invalid Crop Inputs

### ISSUE THREAD

**Issue by XmarkCombo** [lay295/TwitchDownloader#654]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Select an Option

### Describe your issue here

![image](https://user-images.githubusercontent.com/129814866/229671895-4fd029a1-cd76-4de7-8a71-ac9723dc2195.png)

**Comment by ScrubN** [comment]
c4c4a6f124887ddc9de10068120e1049e9d23689

**Comment by XmarkCombo** [comment]
thank you <3
