### ISSUE TITLE
ERROR: Invalid Crop Inputs

### ISSUE THREAD

**Issue by TheSidh** [lay295/TwitchDownloader#657]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

any custom inputs in 'Crop Video' result in 'ERROR: Invalid Crop Inputs' message. Only a full VOD download is possible. (v1.52.3)

**Comment by SalvaDope** [comment]
I am getting the same exact error. If I change the value 1/10 times it will work but I end up downloading an extra hour or two of the VOD :(

**Comment by fidorulz** [comment]
Same issue here running windows 11 and version 1.52.3

Worked fine last night and version was same so suspect twitch may have changed something on their end

**Comment by Ericular** [comment]
Same issue here, Windows 11 and 1.52.3
Setting only a start crop time or end crop time works for me, just not when I specify both.

**Comment by ScrubN** [comment]
This was fixed last night just after the release of 1.52.3. I will release 1.52.4 as a hotfix soon.
