### ISSUE TITLE
Chat Downloader: always Downloads full VOD instead of clip

### ISSUE THREAD

**Issue by C4DL3R** [lay295/TwitchDownloader#66]
no idea what could cause this but I tried it with a few different clips and it always happens.

The created JSON file always contains the full VOD, same goes for the .txt file.

**Comment by lay295** [comment]
An example vod and screenshot of crop settings would be helpful

**Comment by lay295** [comment]
Should be fixed in 1.33, feel free to comment again if it's not. Thanks for the reporting the issue.
