### ISSUE TITLE
Twitch Downloader 1.52.4 bug - Chat render sometimes adds a whole second to the total runtime of a rendered Chat.

### ISSUE THREAD

**Issue by DieHardjagged** [lay295/TwitchDownloader#660]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

Hy there, 
i tried out Twitch Downloader 1.52.3 and wanted to use the Chat Updater tab, but when i load the Json it refuses to show me the correct info, as in Length, Created and Title, it simply states these 3 as "Unknown". 
Json files that were created starting December 2022 are being read correctly though.
I will add an example Json file in Zip form that gives me the bugged attributes mentioned above and a Screenshot which shows the named Errors.
[[11-19-22] EarsOfKittyness - I don't care what you say, it's still caturday - Chat.zip](https://github.com/lay295/TwitchDownloader/files/11153756/11-19-22.EarsOfKittyness.-.I.don.t.care.what.you.say.it.s.still.caturday.-.Chat.zip)

![Screenshot 2023-04-05 003044](https://user-images.githubusercontent.com/62212036/229937657-e964e394-ccd9-43cc-afa2-6a9051f47feb.png)

**Comment by ScrubN** [comment]
As far as I can tell, it is working correctly, your chat json does not contain a length, title, or creation date property.
![image](https://user-images.githubusercontent.com/72096833/229942987-9dea361f-edbd-4f37-b943-93b8d7d22452.png)
Compared to a json made on December 9th which does have a length property along with some other information.
![image](https://user-images.githubusercontent.com/72096833/229943179-acce894b-8ad4-48e9-ae88-c1ddcfa5a5ee.png)

Maybe if the start crop is 0 then I can implement guessing the creation date using the first chat message, but I do not want to guess the length of the chat because it is possible the end crop was not the full length of the video, hence the "video.length" property.
![image](https://user-images.githubusercontent.com/72096833/229943827-b237e847-ae51-403d-b100-aaf97503edb4.png)

**Comment by DieHardjagged** [comment]
> As far as I can tell, it is working correctly, your chat json does not contain a length, title, or creation date property. ![image](https://user-images.githubusercontent.com/72096833/229942987-9dea361f-edbd-4f37-b943-93b8d7d22452.png) Compared to a json made on December 9th which does have a length property along with some other information. ![image](https://user-images.githubusercontent.com/72096833/229943179-acce894b-8ad4-48e9-ae88-c1ddcfa5a5ee.png)
> 
> Maybe if the start crop is 0 then I can implement guessing the creation date using the first chat message, but I do not want to guess the length of the chat because it is possible the end crop was not the full length of the video, hence the "video.length" property. ![image](https://user-images.githubusercontent.com/72096833/229943827-b237e847-ae51-403d-b100-aaf97503edb4.png)

I used this "broken" (Well broken as in it cant be used with the current Downloder) Json with an earlier version to render a chat back then, its length is supposed to be 07:09:58.

**Comment by ScrubN** [comment]
As it stands, the renderer only looks at the start and end crops and only the updater utilizes the video.length property (if it is available)

**Comment by DieHardjagged** [comment]
> As it stands, the renderer only looks at the start and end crops and only the updater utilizes the video.length property (if it is available)

I could manually fix this by adding the missing information myself to the Json, it would work that way i can assume?

**Comment by DieHardjagged** [comment]
There is another bug that i noticed with this version, whenever i render a chat, the program adds +1 second to the total runtime, meaning i have to update the json through the Chat updater by subtracting a whole second so that the rendered file matches the runtime of the vod, why is that? 
I cant also find a way to spot this beforehand so i basically have to render the chat twice in case it adds that whole second.

**Comment by ScrubN** [comment]
> Could i still fix this by adding the missing information to the json myself?

Yes

> There is another bug that i noticed with this version, whenever i render a chat, the program adds +1 second to the total runtime, meaning i have to update the json through the Chat updater by subtracting a whole second so that the rendered file matches the runtime of the vod, why is that?

I am unable to reproduce. If you could provide a chat file that it occurs with, that would help a lot.

> Theres also another question regarding the Chat Downloader, because when i download a json and then decide to download it again the next day, the file gains +1 kb, i assume this is Twitchs doing?

It should be the same size every time, maybe windows is just rounding differently? Check the exact file size in the file properties window. You can also try hashing or diffing both of the files. I would recommend using WSL for either for those with the `sha256sum` and `diff` commands respectively.

> Im also a bit confused about the Chat Updater settings, if i want to update the timing issue and still want to keep the default emotes that were coded into the file when i originally downloaded it (as in Embed Images +BTTV +FFZ + 7TV) , should i just keep the Embed and Replace options unchecked?

Yes

**Comment by DieHardjagged** [comment]
I still wouldnt know how to add this missing second to the Json though, since i never tried something like this before.

I am still in the process of rendering the last 10 Jsons to see which of them comes with a time difference and i noticed something strange,  
This Stream (https://www.twitch.tv/videos/1781869688) runs for 07:00:38 Hours but the VOD i ripped only runs for 07:00:37 despite showing the "Length" of it as 07:00:38, i rendered the Json of the chat and got the exact time of 07:00:37, i then copied the Json, put it in a different folder and then rendered it again but this time the Chat Render has the exact runtime of 07:00:38, i did not change anything on the file, so i dont understand why it changed or how. 

[Backup of Original Json file rendered into a 07.00.38 Chat Render.zip](https://github.com/lay295/TwitchDownloader/files/11182084/Backup.of.Original.Json.file.rendered.into.a.07.00.38.Chat.Render.zip)
[Original Json file rendered into a 07.00.37 Chat Render.zip](https://github.com/lay295/TwitchDownloader/files/11182085/Original.Json.file.rendered.into.a.07.00.37.Chat.Render.zip)

**Comment by DieHardjagged** [comment]
I still wouldnt know how to add this missing second to the Json though, since i never tried something like this before.
I also cant replicate the +1kb problem anymore, all json files are now the same size each redownload.

But lets get back on this timing problem with rendered chats that i have sometimes.
This Json that i added to this post was just used to render a Chat, its from a Stream that ran for 07:17:17 Hours but the rendered File will always be 07:17:18 Hours long (I used Twitchdownloader 1.52.4 to render the Chat), i had to fix the length manually by subtracting a second from the json in the Chat updater, after this, the Chat render came out in the correct length.
This is also a inconsistent problem, sometimes it happens with a json i downloaded from a Vod and sometimes the next different Vod i download a json from comes out with the correct length.
[[3-11-23] EarsOfKittyness - Time to finish this caturday disaster - Chat.zip](https://github.com/lay295/TwitchDownloader/files/11184055/3-11-23.EarsOfKittyness.-.Time.to.finish.this.caturday.disaster.-.Chat.zip)

**Comment by ScrubN** [comment]
After some investigation I believe the issue is due to the Twitch API rounding the stream length to the nearest whole number. Without downloading the whole video there is no way for the chat downloader to know the precise millisecond length of the VOD, so unfortunately there is probably no way to solve this problem for you.

If the extra second is annoying because the video timecodes in your media player windows don't match, then I _might_ have a solution for that in a few months. No guarantees though.

**Comment by DieHardjagged** [comment]
> After some investigation I believe the issue is due to the Twitch API rounding the stream length to the nearest whole number. Without downloading the whole video there is no way for the chat downloader to know the precise millisecond length of the VOD, so unfortunately there is probably no way to solve this problem for you.
> 
> If the extra second is annoying because the video timecodes in your media player windows don't match, then I _might_ have a solution for that in a few months. No guarantees though.

Its alright, i was just wondering why sometimes there was a whole second missing from ripped vods compared to the rendered chats, thats all, but still would be nice to not have that happen, either way thanks for giving an outlook that there "might be a solution" for this.
