### ISSUE TITLE
Chatrender - Value cannot be null. (Parameter 'asset')

### ISSUE THREAD

**Issue by nguyend24** [lay295/TwitchDownloader#663]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Command Line Interface

### Describe your issue here

Previously mentioned here: #622

I ran into this issue last week and I've been following it since. Not sure if what I'm seeing now should be a new issue or not. It's a slightly different error from before. 

Happens when using the latest version of Ganymede, but rendering outside ganymede with **v1.52.3** works. Mentioned it in Zibbp/Ganymede#153, and referred here by @Zibbp but I'm not sure on which side the error lies since it renders fine on the CLI.

Here's a vod where this occurs. 

https://www.twitch.tv/videos/1652395872

And this is the JSON for the chat. Changed the extension to txt so it would upload.
[1652395872_fb1e4c92-bb1a-11ed-b463-0242ac130002-chat.txt](https://github.com/lay295/TwitchDownloader/files/11154809/1652395872_fb1e4c92-bb1a-11ed-b463-0242ac130002-chat.txt)

This is for chatrender.

[STATUS] - Fetching Images [1/2]
[LOG] - No valid typefaces were found for some messages.

[STATUS] - Rendering Video: 0% (0h0m12s Elapsed | 2h31m10s Remaining)Unhandled exception. System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter '**asset**'))

_Originally posted by @nguyend24 in https://github.com/lay295/TwitchDownloader/issues/622#issuecomment-1496863153_

**Comment by nguyend24** [comment]
Full stacktrace:
[stacktrace.txt](https://github.com/lay295/TwitchDownloader/files/11154896/stacktrace.txt)

**Comment by ScrubN** [comment]
So it looks like the system running Ganymede lacks a fallback font, specifically for right-to-left characters. In this scenario we recommend [installing Google Noto fonts](https://github.com/lay295/TwitchDownloader/blob/master/TwitchDownloaderCLI/README.md#additional-notes). If the machine is running Alpine, there is a doc page specifically or that linked in the CLI readme.

**Comment by nguyend24** [comment]
Thanks! fonts were installed, but I guess it needed a `fc-cache -f` to find them. Working now.
