### ISSUE TITLE
infinte 100% running

### ISSUE THREAD

**Issue by luckzzw** [lay295/TwitchDownloader#665]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Select an Option

### Describe your issue here

I have a bug in "Task Queue", When the download go to "100%" in Running, just stuck and dont finish
![image](https://user-images.githubusercontent.com/130003930/230225184-3d3dcedd-9e2d-422c-aa8f-322293fbce21.png)

**Comment by lay295** [comment]
how long is "infinite"?  how long did you actually wait?

I imagine it's just finalizing the VOD which it basically has to copy it completely again. So if you have a slow drive or it's a large VOD it can take a while.

**Comment by kuviman** [comment]
happens to me too. I think it only happens when using the task queue and not regular vod download

task manager reports 0% cpu usage, 0% disk usage, 0% network usage once app gets to this stuck state, so i dont think its finalizing the vod (theres no ffmpeg subprocess)

hangs on 99% for me tho, not on 100%

**Comment by ScrubN** [comment]
> happens to me too. I think it only happens when using the task queue and not regular vod download
> 
> task manager reports 0% cpu usage, 0% disk usage, 0% network usage once app gets to this stuck state, so i dont think its finalizing the vod (theres no ffmpeg subprocess)
> 
> hangs on 99% for me tho, not on 100%

Your issue sounds like #265 

It's hard to tell if luckzzw's issue is also #265, though I'm leaning towards it.

**Comment by cursdgmr** [comment]
I've been having this issue with the task queue too, and what I've found is that it seems to happen on VODs that are over about 5 hours. I wasn't able to replicate it with a 4hr 37m VOD, and the ones I tried to download and couldn't were all at least over 5 hours. It took about 20-30 mins to get to 100%, and it stayed there running for hours. The video files wouldn't open when I tried either.

**Comment by ScrubN** [comment]
> I've been having this issue with the task queue too, and what I've found is that it seems to happen on VODs that are over about 5 hours. I wasn't able to replicate it with a 4hr 37m VOD, and the ones I tried to download and couldn't were all at least over 5 hours. It took about 20-30 mins to get to 100%, and it stayed there running for hours. The video files wouldn't open when I tried either.

Did you try the cancel button, and if so did it work?
If the cancel button does indeed work then the problem is more than likely the video downloader at fault instead of the task queue, which would probably make it related to #772.

**Comment by cursdgmr** [comment]
> 
> Did you try the cancel button, and if so did it work? If the cancel button does indeed work then the problem is more than likely the video downloader at fault instead of the task queue, which would probably make it related to #772.

The cancel button worked, yes. It stopped the download and cleared out the temporary files. I was able to successfully download the VODs one at a time, though.
