### ISSUE TITLE
ERROR: Width and Height must be even

### ISSUE THREAD

**Issue by Nutri626** [lay295/TwitchDownloader#666]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Select an Option

### Describe your issue here

i changed width and height of the chat and now it says ERROR: Width and Height must be even when im trying to render ... 

okay problem is only for some settings i guess, for example 375 width and 580 height cant be rendered, not sure if its a bug or it has problem with some resolutions only

**Comment by lay295** [comment]
The width and height must be even, the number 375 isn't even. 

Some codecs such as H264 don't support odd resolutions.
