### ISSUE TITLE
VODs longer than 24 hours causes fatal error in finalizing stage

### ISSUE THREAD

**Issue by blomsterpistolen** [lay295/TwitchDownloader#668]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

24:05 hour VOD downloads successfully, and merging parts looks OK.

When the video begins to finalize (0% [4/4] parts), it causes a fatal error. See attached.
VOD is then stuck finalizing at 0% forever, and a 0 byte mp4 is created my vod directory.

![image](https://user-images.githubusercontent.com/130615540/231608721-478a6cef-3013-4349-89bb-2cf51f10214b.png)
![image](https://user-images.githubusercontent.com/130615540/231608324-09c875d8-b098-4a8e-93d1-b1cdcc4f6749.png)

**Comment by ScrubN** [comment]
I hate working with TimeSpan.Parse. Until 1.52.5 is released, you can either just ignore the popup (don't click OK) and it will complete the download or you can use a workflow build from after it has patched: [github.com/lay295/TwitchDownloader/actions/runs/4695747656](https://github.com/lay295/TwitchDownloader/actions/runs/4695747656?pr=670)

**Comment by blomsterpistolen** [comment]
Thank you, the build works perfectly
