### ISSUE TITLE
Mass Download MOV+RLE/PRORES Chat Render Error

### ISSUE THREAD

**Issue by TheInevitableBug** [lay295/TwitchDownloader#669]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

I am trying to mass download chat renders with a transparent background. When using the 'Chat Render' tab, using MOV+RLE and PRORES, it downloads successfully downloads the video. When using the same clip in the 'Task Queue' tab URL List, I get the error:

![image](https://user-images.githubusercontent.com/98386739/231636569-8f35e4f8-4e56-4db5-a869-27a1cc15198a.png)
![image](https://user-images.githubusercontent.com/98386739/231636592-aeb1eb29-7e23-4e7a-b647-e98f379de86a.png)

Aside from the encoding, all the other settings in the chat render settings are the default.

**Comment by ScrubN** [comment]
Can you try rendering the chat jsons in the regular chatrender tab?

**Comment by ScrubN** [comment]
The issue is that the enqueue button in that specific scenario assumes the output is an MP4. I'll try to fix it but the task queue system doesn't have much information available to it. It needs a rewrite pretty badly.

**Comment by ScrubN** [comment]
Until 1.52.5 releases, you can use a workflow build from after it has been patched: https://github.com/lay295/TwitchDownloader/actions/runs/4711439614

**Comment by TheInevitableBug** [comment]
> Until 1.52.5 releases, you can use a workflow build from after it has been patched: https://github.com/lay295/TwitchDownloader/actions/runs/4711439614

Thanks, that works perfectly
