### ISSUE TITLE
ERROR: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (usher.twitch.tv:80)

### ISSUE THREAD

**Issue by 5a2m** [lay295/TwitchDownloader#676]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

this just happened on both versiosn (NEW and OLD) i've tried.

2 hours before this was just fine (and i've been using this for months..) then this just suddenly happened, now i can't download ANY vod (only chat and clips)

last time my friend had this issue and apparently the "update prompt" where everytime you guys issue a new update theres a prompt that we can click : FIXES this bug

bug: ERROR: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (usher.twitch.tv:80)
![f32](https://user-images.githubusercontent.com/131043389/232598118-d5d90258-e7de-4ec9-af61-276547e9e61f.PNG)

is it possible for you to do a minor update so it kinda "refreshes" the app? or is there a solution to this issue? thanks in advance!

**Comment by indeboss** [comment]
Same issue here, except no buttons become active when I click "Get info", only the thumbnail shows up

**Comment by erichsangg** [comment]
Same error here

**Comment by Chrisos02** [comment]
> Same issue here, except no buttons become active when I click "Get info", only the thumbnail shows up

Same

**Comment by damashki** [comment]
Just started happening for me as well

**Comment by RecoN12803** [comment]
Okay so i thought it was a me problem when I couldn't find the problem before you posted this

**Comment by lay295** [comment]
Can give 1.52.5 a try, should hopefully fix it

**Comment by adsa95** [comment]
Works for me now, thanks!

**Comment by XmarkCombo** [comment]
Works for me now too, thanks!

**Comment by damashki** [comment]
1.52.5 is working ok for me
