### ISSUE TITLE
refuses to open/malware warnings

### ISSUE THREAD

**Issue by qwertyui6** [lay295/TwitchDownloader#677]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

when i try to open it wont let me open the exe and or extract. it could be my windows defender is deleting the file after i open it. avast is putting it in quarantine. all other versions are not working at all.. ive tried on separate computers. yesterday all versions were working fine until the new update came out. i also tried updating it and its in a update loop. why wont any of the other versions work? why is the latest version not opening. the other versions open and when i put in the link to download vod it wont download anything and it says wont fetch link id for every versionn. please fix fix fix when i redownlaoded other versions my pc isnt freaking out about malware but only the newest version is. it wont opening and stuff:((( 
can you make another version but with no malware thanks:)

**Comment by ScrubN** [comment]
It's a false positive from Avast (and AVG, they're the same program under the hood) https://www.virustotal.com/gui/file/9bcd1c491c87f3b4796a2cb07fabd259f7e648c0a099b2ee44d9da7fc072e227

**Comment by qwertyui6** [comment]
w
