### ISSUE TITLE
Does the Embedding Emotes to Simple Text do something in the previous update?

### ISSUE THREAD

**Issue by George620** [lay295/TwitchDownloader#68]
I'm asking because in the new update (1.33) all files I had in Temp folder are deleted. Are EE to Simple Text (or whole Temp folder from previous versions before the bug fix) completely useless in previous updates?

**Comment by lay295** [comment]
Embedding Emotes was only intended for .json files not text files because json files are the only ones used for rendering. The temp folder is simply a cache when emotes are downloaded, either by embedding emotes or with a chat render. The temp folder existed even before embedding emotes was an option.

**Comment by George620** [comment]
So when I have .json file and EE+Simple Text from video that doesn't exist now, does that mean I can't render the chat correctly if emote is deleted from Twitch servers?

**Comment by lay295** [comment]
There is no EE+Simple text, like you said earlier it was a bug and it's supposed to only be EE+json. If you have EE+json, it'll store all emote data in the json file like I mentioned earlier, so if an emote is deleted on Twitch, when the program tries to download the emote and it fails, it'll find the emote data inside the json file.

**Comment by George620** [comment]
(I know there is no Simple Text+EE and this is a bug, I thought of checking this "options". I don't write it correctly.)
So EE in previous versions do nothing to save potential deleted emotes from Twitch?

**Comment by lay295** [comment]
Correct, only EE+json with version 1.32 or above will store the emote data correctly.
