### ISSUE TITLE
Twitch updated URL to video link

### ISSUE THREAD

**Issue by TecWiz12** [lay295/TwitchDownloader#682]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

Attempted to manually pull the file and tried to use the GUI, the URK to the file is now showing "production.assets.clips." 

it looks to me the Auth locked the downloading now and no longer to access this. 

`https://clips.twitch.tv/LaconicInspiringFlamingoPJSalt-T1L5J36c4Y0lC9bg`

`<video playsinline="" webkit-playsinline="" src="https://production.assets.clips.twitchcdn.net/Ozjkn09S-Sd-nOGNJQvW4A/48338483133-offset-1852.mp4?sig=173d4f64ac5c779e176af5e7225b9fa1388d6300&amp;token=%7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22clip_uri%22%3A%22https%3A%2F%2Fproduction.assets.clips.twitchcdn.net%2FOzjkn09S-Sd-nOGNJQvW4A%2F48338483133-offset-1852.mp4%22%2C%22device_id%22%3A%22T5VT1jXzwQBfQBjFQtn2t2JEOvBdweOT%22%2C%22expires%22%3A1681941249%2C%22user_id%22%3A%22202664482%22%2C%22version%22%3A2%7D"></video>`

**Comment by ScrubN** [comment]
I don't exactly understand what you're trying to say, however I can tell you that the clip is expired/deleted.

**Comment by TecWiz12** [comment]
my apologies, it totally was there when i was looking for it..... welp nvm then process still works. oops 
thank you for looking at it quickly
