### ISSUE TITLE
frozen

### ISSUE THREAD

**Issue by qwertyui6** [lay295/TwitchDownloader#683]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

when you crop a vod using the start optiion. the first 1-3 second is frozen. is there a way to fix that

https://user-images.githubusercontent.com/131138777/232987820-04cb111d-2aef-47dc-9e68-8c5167f58cab.mp4

**Comment by ScrubN** [comment]
The way we apply cropping does not re-encode the video. Most video players or editors are fine with that but some (namely chromium, firefox, and VLC) don't like it. You can just re-encode the video with handbrake to fix it.
