### ISSUE TITLE
middle crop

### ISSUE THREAD

**Issue by qwertyui6** [lay295/TwitchDownloader#684]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

can you add a more than 2 crop option. need it to cut out segments of copyright between start and end with out importing into a video editor. i made a quick idea of it
![please](https://user-images.githubusercontent.com/131138777/232990193-07ef6f0f-585b-4509-a0c3-f65d7af7d4cd.PNG)

**Comment by ScrubN** [comment]
As mentioned in https://github.com/lay295/TwitchDownloader/issues/683#issuecomment-1514221063, we do not re-encode the video when cropping. If we were to add a middle crop that would require re-encoding or 2-pass finalization. Using a video editor to remove it should only take you a few seconds, and if you do not own a video editor you can use [Blender](https://blender.org/download)

**Comment by qwertyui6** [comment]
w
