### ISSUE TITLE
Last version 1.52.5 has malware.... Explain this.

### ISSUE THREAD

**Issue by MrDummyNL** [lay295/TwitchDownloader#685]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

Got warnings from Avast. So, explain this, because older versions have no warnings.
What did you there on last version?
Is your PC safe and virus free?
Is your PC not infected with malware lately?
If you are sure it's not infected, report to Avast.

![2023-04-19_130645](https://user-images.githubusercontent.com/37593786/233058241-561356a6-9833-4ebc-b52d-04ea4fbd3bcb.png)

**Comment by ScrubN** [comment]
See #677. Avast/AVG are notorious for false positives like this.
You should honestly just use win defender :p

**Comment by MrDummyNL** [comment]
Allright. I will add it to whitelist. Thanks for the answer.
