### ISSUE TITLE
the vod wont download

### ISSUE THREAD

**Issue by vchompys** [lay295/TwitchDownloader#692]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

there was a new update i pressed no on accident and it started not downloading and before you call me a idiot after that i downloaded the latest version and still wont download it says ''ERROR: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (usher.twitch.tv:80)''

**Comment by ScrubN** [comment]
Update the app
