### ISSUE TITLE
OAuth Token Fail

### ISSUE THREAD

**Issue by NinaCal** [lay295/TwitchDownloader#693]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

Hello

I am quite new at this, so pardon me if my struggle sounds ridiculous
I've been trying to dowload a VOD but the same error message kept appearing : ERROR: Insufficient access. OAuth may be required.

I figured I needed to get the OAuth Token, which I think I found a way to get. But when I enter it and try again, another error message appears : ERROR: Response status code does not indicate success: 401 (Unauthorized).

I can't seem to get a way around it.

Thank you for your help

**Comment by ScrubN** [comment]
Does your twitch account have access to play the video on the website?

**Comment by NinaCal** [comment]
Do you mean to ask me if I am subbed to the channel ? The answer is no, that's why I'm trying to recover to VOD, it's for subs only.
The live is very recent as well and is not archived

**Comment by ScrubN** [comment]
Only subscribed channels can download subscriber only vods.

**Comment by NinaCal** [comment]
Okay ... then I don't really understand the point of it?

**Comment by ScrubN** [comment]
The point is to allow subscribers or channel video editors to download the videos without enabling piracy. As a comparison, Patreon allows paying users to download files too.
