### ISSUE TITLE
Chat compression not working in CLI

### ISSUE THREAD

**Issue by Tristar7** [lay295/TwitchDownloader#694]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Command Line Interface

### Describe your issue here

Filesize remains identical to uncompressed and content is still in plain text.

**Comment by ScrubN** [comment]
I'm unable to reproduce. Could you provide your download command?

**Comment by Tristar7** [comment]
found the isue:

using 
-o "test.json"
fails, despite the tool adding .gz at the end

using 
-o "test.json.gz"
works, filename ends up as test.json.gz.gz though

however that file cannot be opened with a compression tool, which works for files created with the GUI.

**Comment by ScrubN** [comment]
I found the issue. Whoops.

**Comment by ScrubN** [comment]
It has been fixed. You can either wait for an update or use a workflow build: https://github.com/lay295/TwitchDownloader/actions/runs/4825442349

**Comment by Tristar7** [comment]
remains the issue that using

-o "test.json.gz"

creates corrupted, unusable files

**Comment by ScrubN** [comment]
The CLI is now smarter and more strict about file extensions
