### ISSUE TITLE
Generate mask for a chat

### ISSUE THREAD

**Issue by Windyishere** [lay295/TwitchDownloader#698]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates

### Write stuff here

Hello!
I ran in to a problem which bothers me a lot, i wanna have a mask on my chat like this guy have in a video -https://youtu.be/xpRhvTGMtnE?t=121

But i end up with this error, someone knows how to fix it please? 
https://prnt.sc/X7GGUBWinzmS

**Comment by Windyishere** [comment]
Also, is there a way to see a preview of it? I can see that from older versions you had a preview button there but i dont see it at all

**Comment by ScrubN** [comment]
> But i end up with this error, someone knows how to fix it please?

You set the font to transparent, not the background.

> Also, is there a way to see a preview of it? I can see that from older versions you had a preview button there but i dont see it at all

The old renderer would generate each frame to the disk as a png and then combined them with ffmpeg, and the preview button would simply read the latest png in the disk cache. The current renderer sends the frames directly to ffmpeg which means a preview button is impractical, although not impossible.

**Comment by Windyishere** [comment]
Oh my god thank you! I'm so stupid haha!
