### ISSUE TITLE
Fix "bad" twitch emotes

### ISSUE THREAD

**Issue by MiracleBlessing** [lay295/TwitchDownloader#7]
As you may know, some of the very early global emotes look terrible. They either have a white background or a white outline, which isn't really pleasant to look at with the dark background. FrankerFaceZ has a feature where it'd substitute them with their own images instead of the ones on twitch's cdn. Could you possibly implement a similar system? Here's the list of the known bad emotes and their id's:
`DansGame - 33`
`RedCoat - 22`
`OptimizePrime - 16`
`StoneLightning - 17`
`JKanStyle - 15`
`JonCarnage - 26`
`TheRinger - 18`

And here are the replacement images from ffz's cdn:
https://cdn.frankerfacez.com/static/replacements/15-JKanStyle.png
https://cdn.frankerfacez.com/static/replacements/16-OptimizePrime.png
https://cdn.frankerfacez.com/static/replacements/17-StoneLightning.png
https://cdn.frankerfacez.com/static/replacements/18-TheRinger.png
https://cdn.frankerfacez.com/static/replacements/22-RedCoat.png
https://cdn.frankerfacez.com/static/replacements/26-JonCarnage.png
https://cdn.frankerfacez.com/static/replacements/33-DansGame.png

**Comment by lay295** [comment]
This was an issue I was thinking of doing earlier, but a lot of people render large chats so I try and get larger emote sizes. The "fixed" emotes from what I can tell are only on 1x scale and would look not great compared to the original when scaled up.

That and I don't think the work is worth the benefits too much.
