### ISSUE TITLE
Clip Mass Downloader Fatal Error

### ISSUE THREAD

**Issue by Seguran2311** [lay295/TwitchDownloader#705]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

I receive this error when trying to use the search clips function in Task Queue. I am able to enqueue clips and download them outside of the Task Queue section. I do not receive this error in the Search VoDs section. 

![image](https://user-images.githubusercontent.com/104663801/236350799-69b2acfe-74ae-41ec-bbf6-671d44d7be3e.png)

**Comment by ScrubN** [comment]
Download the 1.52.6 preview build. The first page of clips and vods should work as expected.
