### ISSUE TITLE
Audio out of sync when using crop function

### ISSUE THREAD

**Issue by MistarBeanz** [lay295/TwitchDownloader#706]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

When downloading a VOD and using the crop function (rather than downloading the entire VOD by default), the audio is significantly out of sync.

**Comment by ScrubN** [comment]
Duplicate #556. VLC is the issue, not the video file. Just re-encode it with handbrake or something

**Comment by TheMadog24** [comment]
> Just re-encode it with handbrake or something

Hey, sorry to comment on an old issue, but do you know of a way to fix this without re-encodeing?
This issue shows itself on more than VLC, for me, the only thing that doesn't have the audio sync issue is Windows Media player.
When using an HTML5 video player, or even when uploading to youtube it has the audio sync issue.
