### ISSUE TITLE
Download chat from unlisted vod

### ISSUE THREAD

**Issue by gatsuslayer** [lay295/TwitchDownloader#708]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates

### Write stuff here

I tried to download the chat of an unlisted vod using the id provided by twitch tracker but the program gives me an error, is there any way to get the "real" id of a private vod?

**Comment by ScrubN** [comment]
See https://github.com/lay295/TwitchDownloader/issues/680#issuecomment-1513868769. Not even the twitch web player is able to show chats, so sadly there is nothing we can do.
