### ISSUE TITLE
--ffmpeg-path CLI argument doesn't work

### ISSUE THREAD

**Issue by crackerbear** [lay295/TwitchDownloader#71]
My bat file contains the line `"F:\Twitch Downloader\TwitchDownloaderCLI.exe" -m ChatDownload --ffmpeg-path "F:\Twitch Downloader\ffmpeg.exe" --id 683368263 -o F:\Twitch\683368263_chat.json` however, I get this error: 

`[ERROR] - Unable to find ffmpeg, exiting. You can download ffmpeg automatically with the argument --download-ffmpeg`

The bat file only works if I place it within the Twitch Downloader folder, where the ffmpeg.exe resides. So in other words, the bat file expects the ffmpeg.exe to be in the same directory to which it is ran from and ignores the --ffmpeg-path argument.

Running the same command straight in CMD returns no errors, but I suspect that's because it's still ignoring the --ffmpeg-path argument, however I have ffmpeg set up in my PATH as a environment variable.

**Comment by lay295** [comment]
Oh whoops... yeah that's a mistake on my end. I've made some changes and tested it on my end and it seems to work. Should work without having to include --ffmpeg-path if it's in your PATH now as well.

https://drive.google.com/file/d/1UnEjpSZIDp8YgsgOYrOzpIg-4H6sGOVn/view?usp=sharing

Give it a try, and if it works I'll push it as an update soon

**Comment by crackerbear** [comment]
That works great. Thanks a lot for the speedy fix!
