### ISSUE TITLE
Video Download Exceeding 100%

### ISSUE THREAD

**Issue by TheMadog24** [lay295/TwitchDownloader#711]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

![image](https://github.com/lay295/TwitchDownloader/assets/12008758/2ccc1718-cc6c-4dde-b445-ffd9f5da5878)

Video Downloaded, but has been taking a very long time to finalize (it's a very large video), but I noticed it did not stop at 100%.

I have no idea if this video will finish or not now.

**Comment by TheMadog24** [comment]
![image](https://github.com/lay295/TwitchDownloader/assets/12008758/b7703d78-9b89-4f91-a30f-c3ad9c45ad83)
It has now Exceeded 200%

**Comment by ScrubN** [comment]
I never thought this was possible. If I had to guess, I'd say ffmpeg probably returned some form of default video length during the initial metadata output.

If you could recreate it and send `%temp%\TwitchDownloader\###_###\ffmpegLog.txt` that would help solve it.

**Comment by TheMadog24** [comment]
> If you could recreate it and send `%temp%\TwitchDownloader\###_###\ffmpegLog.txt` that would help solve it.

No such file/directory exists, I have `%temp%\TwitchDownloader\`, but only these folders:
![image](https://github.com/lay295/TwitchDownloader/assets/12008758/312fe034-4385-4e57-a469-10107cdc0c55)

I can try and download it again because I assume it cleans out any old files, but it may be a while, since it's a 48h long VOD, and it was 128GBs. It will be a while though.

let me know at what point I need to check for that file

**Comment by ScrubN** [comment]
You can probably download at 160p to cut down the file size without hurting reproducibility.

> I can try and download it again because I assume it cleans out any old files

Correct, it would have been cleaned up.

> Let me know at what point I need to check for that file

Look for it when finalizing goes over 100%. Maybe around 105% to allow for some leeway.

**Comment by TheMadog24** [comment]
[ffmpegLog.txt](https://github.com/lay295/TwitchDownloader/files/11513624/ffmpegLog.txt)
I grabbed this file at 113%

**Comment by ScrubN** [comment]
This is very weird, ffmpeg reports 2 different durations. I have never seen it do this before.
![image](https://github.com/lay295/TwitchDownloader/assets/72096833/e1356ce0-a86f-482a-a56e-649a7d4b966b)

**Comment by ScrubN** [comment]
Fixed f9ba7c220fb2f248fe0a46f93fc9e7d1d7b7b085
