### ISSUE TITLE
Cant render this old file

### ISSUE THREAD

**Issue by HellbringerOnline** [lay295/TwitchDownloader#715]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

[2022.01.30 zanuda - Камера на больничном - Chat.zip](https://github.com/lay295/TwitchDownloader/files/11525757/2022.01.30.zanuda.-.-.Chat.zip)
![11](https://github.com/lay295/TwitchDownloader/assets/14059683/f30ed9ff-6da2-407d-aa26-8ea5dd927ab4)

**Comment by ScrubN** [comment]
Fixed c94aab96e180f2390a5386052815ada4ce161733. I'm not entirely sure how this one slipped by for so long.
