### ISSUE TITLE
Render chat issue

### ISSUE THREAD

**Issue by QtraxNino** [lay295/TwitchDownloader#717]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

When trying to render a chat .json file I get "ERROR: Response status code does not indicate success: 404 (Not Found)."

**Comment by ScrubN** [comment]
Duplicate #674
