### ISSUE TITLE
ERROR 404, cannot download Chat (HTML)

### ISSUE THREAD

**Issue by XmarkCombo** [lay295/TwitchDownloader#718]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates

### Write stuff here

This is my first time having a trouble downloading chat (HTML)

![image](https://github.com/lay295/TwitchDownloader/assets/129814866/f233499e-21a0-4fea-824c-21a6ba8b63e9)

**Comment by Jordynns** [comment]
Having the same issue when trying to render .json

![image](https://github.com/lay295/TwitchDownloader/assets/133882087/da874130-135a-4e3c-ae63-77b98ecf5ac0)

**Comment by XmarkCombo** [comment]
I tried to use an older version

![1234](https://github.com/lay295/TwitchDownloader/assets/129814866/c0faed84-1d2d-4f7f-8ec7-188c5713f393)

**Comment by ScrubN** [comment]
Duplicate #674. Twitch is sunsetting the old badges API.
