### ISSUE TITLE
Cannot download any clip. Huge percentage number.

### ISSUE THREAD

**Issue by stringie** [lay295/TwitchDownloader#719]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Command Line Interface

### Describe your issue here

The image says it all basically:

![Screenshot 2023-05-24 093120](https://github.com/lay295/TwitchDownloader/assets/23170702/86050915-6ee4-41d4-9647-c69cbc3a9089)

After that, the downloaded chat files are corrupted and can't be opened.

**Comment by ScrubN** [comment]
Looks like Twitch is not returning the clip duration (field name changed?) which we depend on to download chats. This might also be the same issue as #716.
![image](https://github.com/lay295/TwitchDownloader/assets/72096833/0598df7a-396c-4cfe-b4f5-b1378328fb89)

**Comment by lay295** [comment]
Yeah I dunno, it seems like Twitch is still using the durationSeconds field name even when I inspect the queries Twitch itself is using. It just seems like that clip has a blank duration being returned for some reason.

I created a brand new clip just now and the durationSeconds is populated, weird...

**Comment by stringie** [comment]
For me it seems like it's every clip, not just this one in particular. Hasn't been working for 2 days now. Was working just fine for my script for weeks before. Something must have changed. 

Will notify if it fixes itself.

**Comment by stringie** [comment]
It appears the error was only happening for a few select clips. Seems to still be working. Closing issue.
