### ISSUE TITLE
[Suggestion] Display percentage chat download progress in the CLI

### ISSUE THREAD

**Issue by crackerbear** [lay295/TwitchDownloader#72]
I'm not sure if you're aware of [Twitch Chat Downloader](https://github.com/PetterKraabol/Twitch-Chat-Downloader), but having a percentage download progress similar to how it does it ([example](https://streamable.com/crgwq5)) would be nice so as you see how much your program has downloaded, since currently it doesn't give any indication.

This can obviously be treated as very low priority. Thanks for the hard work anyway!

**Comment by lay295** [comment]
Added in 1.35, I know the logging isn't exactly pretty or very informative and it spams the console every time it updates instead of just replacing the previous line. Eventually I'll make it look nicer.

**Comment by crackerbear** [comment]
Spam is fine since it's better than nothing. The way it calculates percentage seems a little wonky though, particularly with short VODs.

For example --id 683368263 (1min 17secs VOD) gives Downloading 108% and --id 684507595 (22min 32secs VOD) gives Downloading 90%.

Only a minor thing, thanks again!
