### ISSUE TITLE
Chat Render and Vods Download Fatal Error

### ISSUE THREAD

**Issue by DatOneTankNerd** [lay295/TwitchDownloader#722]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

![Screenshot (313)](https://github.com/lay295/TwitchDownloader/assets/134635065/101d5368-51b0-4121-b191-7ccb57596a8f)

This all I get when Vods finish downloading or if I try to render chat.
Am I doing something wrong or is it just broken?

Funnily enough while writing this the program now refuses to open.

**Comment by ScrubN** [comment]
Go to `%localappdata%` and delete any folders named `TwitchDownloader` or `TwitchDownloaderWPF`, your settings file is corrupted.

**Comment by DatOneTankNerd** [comment]
> Go to `%localappdata%` and delete any folders named `TwitchDownloader` or `TwitchDownloaderWPF`, your settings file is corrupted.

so I did this and then downloaded the latest version again and this exact same issue is still persisting.

anything else I might be doing wrong?

**Comment by DatOneTankNerd** [comment]
nvm I tried it again and its working now, thx a lot @ScrubN
