### ISSUE TITLE
Can't download VOD from a specific channel.

### ISSUE THREAD

**Issue by Larveman** [lay295/TwitchDownloader#724]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

When i try to download a VOD from the channel of "Fakemonster" idk why but it tells me that it can't find the information of the VOD, and that for every VOD of his channel. There is no sub only vod or anything, so i'm confused, it works perfectly on others channel. Any idea of where the issue can come from ?

**Comment by ScrubN** [comment]
> There is no sub only vod or anything

Are you sure about that?
![image](https://github.com/lay295/TwitchDownloader/assets/72096833/1ddbc912-8390-4e26-ac82-323c7410125c)
![image](https://github.com/lay295/TwitchDownloader/assets/72096833/ac280e34-e3a7-489d-ac74-e54c586b9864)

**Comment by Larveman** [comment]
> 

I'm dumb, i forgot that i had an extension who allows me to watch sub only vod, and before this streamer didn't use that fonctionality so I didn't make the connection, sorry for the disturbing.

**Comment by ScrubN** [comment]
Oh interesting, I didn't know it was still possible to watch sub-only vods via alternative methods.
Still, I do not think this functionality should be implemented in our downloader because of piracy concerns.
