### ISSUE TITLE
User Badges have Empty Strings

### ISSUE THREAD

**Issue by TheMadog24** [lay295/TwitchDownloader#726]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

`user_badges` on some/most are being left with Empty Strings, but in an odd way...

![image](https://github.com/lay295/TwitchDownloader/assets/12008758/7b8f03e5-d6c8-4300-869e-1651bbbbccbc)

I assume this is a bug, if there is only 1 badge, why have the first item in the array be an empty string? I checked the original vod for all of these where this is an issue, and it seems that TwitchDownloader is adding empty strings.

In this example, I checked the VOD, and the person only has 1 badge, not 2. The second badge is the correct badge, and the only badge in the VOD. This really breaks a lot of things on my end.

**Comment by lay295** [comment]
Looks like Twitch is giving us these empty badges as a response? No clue... will change it to filter it out though. Unless anybody has any idea why.

![image](https://github.com/lay295/TwitchDownloader/assets/1060681/b99a14be-9923-49d1-abe1-4645877347e6)

**Comment by lay295** [comment]
Meant to type 729 in my commit comment...
