### ISSUE TITLE
Replace forbidden filename characters with full-width alternatives

### ISSUE THREAD

**Issue by 3my** [lay295/TwitchDownloader#731]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

An option to replace characters forbidden in Win10 filenames (eg Question marks, colons) with full-width versions

example:

Original VOD name:
_New Season Maxed BP Day 1???? :)_

Downloaded file name:
_New Season Maxed BP Day 1 )_

Full-width version:
_New Season Maxed BP Day 1？？？？ ：)_

**Comment by ScrubN** [comment]
I thought we replaced forbidden characters with underscores?

**Comment by ScrubN** [comment]
Looking at the code we do indeed replace them with underscores (in the WPF), and it works as expected when tested just now.

![image](https://github.com/lay295/TwitchDownloader/assets/72096833/7d3e2fd1-0402-42ae-969f-76474231f9f3)
