### ISSUE TITLE
Audio delay, when downloading cropped VOD

### ISSUE THREAD

**Issue by FloatingToast** [lay295/TwitchDownloader#733]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

I like to make clips of my fav streamer, that are often longer than 60 sec, so i crop the VOD in TwitchDownloader and that worked just fine a few weeks ago but now everytime i download a cropped VOD the audio is delayed by 500-800ms. 
Normally changing the start/end time of the clip by a few seconds fixed this but now it happens everytime.

**Comment by BennetE** [comment]
I have the same issue, and I found [this](https://github.com/lay295/TwitchDownloader/issues/556#issuecomment-1442618061) issue comment that helped me. For me, the delay is only when using VLC media player.

Hope it helps.

**Comment by ScrubN** [comment]
There is now a mitigation for this issue with #1112
