### ISSUE TITLE
Search clips by Game

### ISSUE THREAD

**Issue by KacperWilk** [lay295/TwitchDownloader#734]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

Hello I would like to ask if it's possible to add searching clips by game rather than streamers in Task Queue > Search Clips.

**Comment by artsimonenkov** [comment]
And please add the streamer language selection setting in this menu

**Comment by ScrubN** [comment]
This feature will be tracked in #812 

> And please add the streamer language selection setting in this menu

I will take that into account
