### ISSUE TITLE
Flashing Chat

### ISSUE THREAD

**Issue by RicardoR1123** [lay295/TwitchDownloader#74]
When I use the mask and the chat with the mask when I make it transparent the chat flashes white at certain points.

**Comment by lay295** [comment]
What software are you using for video editing? What chat render settings? Can you upload both the mask file and video file so I can reproduce?

**Comment by RicardoR1123** [comment]
I'm using sony vegas 14 it's latest version 

![image](https://user-images.githubusercontent.com/71105133/92950549-ac444c80-f411-11ea-9dcf-6155da53ebda.png)

**Comment by RicardoR1123** [comment]
[chat.zip](https://github.com/lay295/TwitchDownloader/files/5210711/chat.zip)

**Comment by RicardoR1123** [comment]
I left the videos in the zip file

**Comment by lay295** [comment]
Using the video files provided in Vegas 15 (sorry don't have 14) seem fine.

I imagine it must be a configuration issue on your end in Vegas 14. Sorry I don't think I can help with this one.

https://youtu.be/aavwXFjJLQc

**Comment by RicardoR1123** [comment]
I figured it out but I have another question, how do I move the chat and the mask together so I could put it in a corner without having to move them separately

**Comment by lay295** [comment]
I don't edit videos myself so not sure really, I only know of a way in premiere, if you google around there probably is an easy way.

**Comment by holeekebab** [comment]
> I figured it out but I have another question, how do I move the chat and the mask together so I could put it in a corner without having to move them separately

I have the same issue and would like to know how you fixed it 👍

**Comment by dfg555** [comment]
> I figured it out but I have another question, how do I move the chat and the mask together so I could put it in a corner without having to move them separately

Can you tell us how you fixed it? I have Vegas 15 (Build 361).

**Comment by BigBossFTW** [comment]
Thank you, worked for me 😄
