### ISSUE TITLE
wrong quality

### ISSUE THREAD

**Issue by autumnrain26** [lay295/TwitchDownloader#741]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

I select 720p30, but it downloads 720p60.

**Comment by ScrubN** [comment]
Provide your vod id.

**Comment by autumnrain26** [comment]
https://www.twitch.tv/videos/1802089274
...and it also stops at 99%

**Comment by ScrubN** [comment]
Fixed d15e6c72b7a322dadf269fe7a3aee6a93da04330
