### ISSUE TITLE
[Feature Request] Hype Chat Support

### ISSUE THREAD

**Issue by curya** [lay295/TwitchDownloader#746]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

Twitch has just introduced a "Hype Chat" feature which is similar to YouTube's Super Chats.
https://blog.twitch.tv/en/2023/06/22/introducing-hype-chat-a-new-way-to-stand-out/

Hoping we can get support for it in TwitchDownloader's chat rendering feature.

**Comment by ScrubN** [comment]
Unfortunately message metadata is no longer saved to VODs as of about November 2022, so just like redeems, subscriptions, and raids the metadata that a message was a hype chat is gone in the VOD message replay.

If you would like, you could report this as an "issue" on the twitch dev forums or UserVoice page and maybe they will re-add the metadata, but it seems unlikely to me.

If we ever add support for recording the IRC chat or they re-add the metadata to VOD replays then this will be reconsidered, but as it is now this is impossible.

![image](https://github.com/lay295/TwitchDownloader/assets/72096833/b133b1b7-22ac-49f5-9659-1147ed5ad172)
![image](https://github.com/lay295/TwitchDownloader/assets/72096833/d39e12c0-cbbc-4900-bbe4-26afa2fdd4ca)
