### ISSUE TITLE
Default font for CLI isn't Arial & --backround-color spelling error(s)

### ISSUE THREAD

**Issue by crackerbear** [lay295/TwitchDownloader#75]
From my testing with the CLI version, it seems the default font isn't Arial. I tested by rendering a version with no font command (i.e. default) and then with the font set deliberately as Arial and there's definitely a difference, albeit a very small one.

This might be because according to the CLI README, you've stated `-f/--font (Default: Ariel)` when the font name is actually spelt Ari**a**l.

Secondly the `--backround-color` command also has a slight spelling error and should be --back**g**round-color.

Both are very minor and low priority issues, but I thought I'd let you know.

**Comment by lay295** [comment]
Whoops, I thought it was spelled Ariel, I've made the changes but I wanna fix #67 before I put out another release. Thanks for catching both typos :)

**Comment by crackerbear** [comment]
No problem!

**Comment by lay295** [comment]
Changes were just made in 1.37
