### ISSUE TITLE
Only a document downloads on mac

### ISSUE THREAD

**Issue by friscoq** [lay295/TwitchDownloader#755]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Select an Option

### Describe your issue here

When I try to download the macOS version, I get a zip file and that only opens to a document.

**Comment by ScrubN** [comment]
Read the readme steps for MacOS [github.com/lay295/TwitchDownloader#macos--getting-started](https://github.com/lay295/TwitchDownloader#macos--getting-started)

**Comment by ScrubN** [comment]
Closing due to age
