### ISSUE TITLE
Deserialization error (JSON value could not be converted to System.Int32)

### ISSUE THREAD

**Issue by VisualRedux** [lay295/TwitchDownloader#759]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [x] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

When trying to render out the chat (only for a few older vods) I keep getting this error:
ERROR: The JSON value could not be converted to System.Int32. Path: $.id | LineNumber: 0 | BytePositionInLine: 36.

I tried the chat updater but it instantly crashes the application.
Any help is greatly appreciated!

### Add any related files or extra information here

Here is a link to the json file: https://drive.google.com/file/d/1LNtvJDXowB3J_YaxwkmSvrVQF91LYVkx/view

**Comment by VisualRedux** [comment]
Just figured out a fix! Just needed to remove the quotes around the id number.
For example, it was:
 {"streamer":{"name":"sodapoppin","id":"26301881"}

And I changed it to:
{"streamer":{"name":"sodapoppin","id":26301881}

dont know anything about this stuff so im pretty hyped that I figured it out haha

**Comment by VisualRedux** [comment]
Just figured out a fix! Just needed to remove the quotes around the id number.
For example, it was:
 {"streamer":{"name":"sodapoppin","id":"26301881"}

And I changed it to:
{"streamer":{"name":"sodapoppin","id":26301881}

dont know anything about this stuff so im pretty hyped that I figured it out haha

**Comment by ScrubN** [comment]
Was the json file created by an older version of TwitchDownloader? If so, this could be a problem for other users too.

**Comment by LCSQ** [comment]
thanks, this solved my issue. It is a problem with json files generated by old TwitchDownloader. It should be noted in common errors.

**Comment by ScrubN** [comment]
> It should be noted in common errors.

The user should not be expected to modify their json files. I will implement a fix in the deserializer.

**Comment by ScrubN** [comment]
Until the next version is released, you may use this workflow build to avoid any future errors with old chats: https://github.com/lay295/TwitchDownloader/actions/runs/6438276408
