### ISSUE TITLE
When Using Chat Render it will use 80 - 90% of my CPU

### ISSUE THREAD

**Issue by Neodemon90** [lay295/TwitchDownloader#76]
When rendering My Json file I'll Pick a transparent background, mp4 file format with a Generate Mask. I didn't mess with the width or the height of the chat. And bttv and FFZ Emotes  everything will work fine until it starts rendering the video. Then it will spike to 90 or 80 % CPU Usage. " I also tested other settings "
![Capture](https://user-images.githubusercontent.com/37255109/93295898-15cead00-f7bc-11ea-96fc-8353635c3dfd.JPG)
I have Windows 10 and an i5 processor it's not the worst but Wouldn't expect it to take so much resources and it's fine if I've just wanted to take a chat for maybe 5 or 6 minutes. But  I'm trying to get like 30 minute chunks, I can't have my CPU essentially clocked at 100% for that long. I was wondering if this can be fixed or if it's a bug or if it's on My end

**Comment by lay295** [comment]
This is not a bug, when you encode videos it tries to use as much system resources it can to speed things up. Like when you render a video in adobe premiere, it'll use a lot of resources. When you use the generate mask option, you're actually encoding 2 seperate video files at the same time even. You can try and edit ffmpeg command line arguments to add the "-threads 1" argument and see if it'll help. Obviously it'll be slower though.
