### ISSUE TITLE
Better error message when trying to download videos that can't be downloaded

### ISSUE THREAD

**Issue by vers-one** [lay295/TwitchDownloader#760]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

The video for the stream that has just finished cannot be downloaded using TwitchDownloader. An attempt to download it results in an `Object reference not set to an instance of an object` error coming from [here](https://github.com/lay295/TwitchDownloader/blob/f955305bfbe46bc7c951667ae6924bd020f0d903/TwitchDownloaderWPF/PageVodDownload.xaml.cs#L89) because it tries to access `taskAccessToken.Result.data.videoPlaybackAccessToken.value` for a response from Twitch which looks like this:
```
{
    "data":{"videoPlaybackAccessToken":null},
    "extensions":{"durationMilliseconds":22,"operationName":"PlaybackAccessToken_Template","requestID":"..."}
}
```

The error goes away after about 20-30 minutes.

I think a more descriptive error could be better in this case.

**Comment by ScrubN** [comment]
I really need to integrate the core video downloader info fetch into the GUI so we aren't repeating code like this.
