### ISSUE TITLE
triple click support in UI

### ISSUE THREAD

**Issue by Stelminator** [lay295/TwitchDownloader#762]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

When replacing the value for "VOD Link/ID:", it's a little bit of a chore to fully select the current value for replacement/deletion. Triple-click is a fairly standard (though somehow not default in WPF) way to support "select all" via mouse.

I'm prepared to write a PR for this, yet before that effort, I'd like to know the author's appetite for the feature, and, more specifically, if the preference would be for all text fields, not just (my) most commonly edited.

**Comment by ScrubN** [comment]
I didn't know this wasn't a default behaviour in WPF, I guess I've just
never tried it when testing.

No need to write the PR yourself, I would like to release a new update soon
and have the time tonight to implement it myself :)

**Comment by Stelminator** [comment]
awe, darn, I was looking forward to it, but, thanks for the active support!

**Comment by ScrubN** [comment]
Unfortunately because the triple click behavior overrides the default style it breaks vertical expanding for the URL Mass Downloader, which was also one of the places it was most useful :(
