### ISSUE TITLE
enter key support for "VOD/Clip Link" field for "Get Info" button

### ISSUE THREAD

**Issue by Stelminator** [lay295/TwitchDownloader#763]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

related to usability mentioned in https://github.com/lay295/TwitchDownloader/issues/762; would an enter key trigger be likely to be accepted?

similarly, I can do the PR for it, just trying to gauge support.

**Comment by ScrubN** [comment]
I'd be lying if I said I hadn't wanted this too but never bothered to implement it.

**Comment by Stelminator** [comment]
Again I'm disappointed that it cost that much copypasta, and yet it's much appreciated. Thanks!
