### ISSUE TITLE
Non-UTF8 JSON files fail to deserialize

### ISSUE THREAD

**Issue by VisualRedux** [lay295/TwitchDownloader#764]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

As soon as I press render I get this message: ERROR: '0xFF' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.

Any suggestions?

### Add any related files or extra information here

Here is the JSON file: https://drive.google.com/file/d/1VqEx_lW7-dSUBwpoJbYg0U6Pt6xIitm5/view

**Comment by ScrubN** [comment]
For some strange reason, your chat starts with 2 invalid bytes (FF FE). You can open it with a hex editor or use a hex editor plugin in a text editor like vscode to delete those bytes and save to a new file.
![image](https://github.com/lay295/TwitchDownloader/assets/72096833/b87a5f4e-dcd8-4b1f-948e-b5d189121cd7)

**Comment by ScrubN** [comment]
I just realized, those bytes are because the document was written with UTF16. You should be able to convert it to UTF8 with a text editor like vscode or notepad++

**Comment by ScrubN** [comment]
The user should not be expected to know the differences between UTF8 and UTF16 nor fix problems caused by the differences.
