### ISSUE TITLE
foreign language characters not rendering

### ISSUE THREAD

**Issue by reborn213** [lay295/TwitchDownloader#77]
hello sir, thank you for program

i am using rendering for korean stream, but alphabet not rendering, only showing boxes.
https://i.imgur.com/wuD65Gi.png
https://i.imgur.com/kQBtZap.png
https://i.imgur.com/IpxTn8p.png no settings changed

what settings to change? or not possible. vod id 735095468
thank you

**Comment by lay295** [comment]
Was an error in the way the program handled fallback fonts. Give 1.37 which I just released a try and let me know how it goes.
