### ISSUE TITLE
Queue error

### ISSUE THREAD

**Issue by Fyrlian** [lay295/TwitchDownloader#781]
### Checklist

- [x] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Select an Option

### Describe your issue here

When I queue clips as URL list they won't download, they all get stuck at 0%, started happening after I updated it from 1.52.2 to 1.53.2
Also the place to type the URL's is visually bugged (You can only see one line of text)

![image](https://github.com/lay295/TwitchDownloader/assets/73081943/790d0621-58fa-4ecb-851c-bcc418d090fd)

**Comment by ScrubN** [comment]
> When I queue clips as URL list they won't download, they all get stuck at 0%, started happening after I updated it from 1.52.2 to 1.53.2

The queue downloader doesn't report any kind of progress. I know it sucks but there isn't really a solution without using a decade-deprecated class.

> Also the place to type the URL's is visually bugged (You can only see one line of text)

This seems to be caused by #765. I will see if I can resolve it or I may just have to revert that exclusively for the URL list.

**Comment by ScrubN** [comment]
> > When I queue clips as URL list they won't download, they all get stuck at 0%, started happening after I updated it from 1.52.2 to 1.53.2
> 
> The clip downloader doesn't report any kind of progress. I know it sucks but there isn't really a solution without using a decade-deprecated class.

After some poking around I discovered that the response contains the content length. Reporting total clip download percentage is not impossible.

**Comment by ScrubN** [comment]
Apologies for the inconvenience. You may use this workflow build until the next update is released: [github.com/lay295/TwitchDownloader/actions/runs/5759322047](https://github.com/lay295/TwitchDownloader/actions/runs/5759322047)

**Comment by Fyrlian** [comment]
Thank you very much! And again thanks for this great tool.
