### ISSUE TITLE
No file when finished? Mac M1.

### ISSUE THREAD

**Issue by Justtheflu** [lay295/TwitchDownloader#784]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Select an Option

### Describe your issue here

When I try and download a VOD, after finishing the final step, the file is nowhere to be found.
Followed the mac directions and tried both with the ffmpeg download fromt the instructions and a manually downloaded external version.

Incidentally I can't exit the terminal 'enter' stops working.

**Comment by ScrubN** [comment]
I'm curious if there is a possible problem with relative paths given #776
or maybe you accidentally typed an absolute path when you mean to type a
relative one?

**Comment by ScrubN** [comment]
I say this because if no finalized video was truly present, you would have
mentioned receiving an obnoxious log message.

As for the broken terminal input, I don't know what to say without more
information such as a screenshot or video

**Comment by Justtheflu** [comment]
I specified a path and the video showed up, thanks.

The 'enter' bug still remains.
Here's an image, when I expand the window it shows many ((((, maybe it's related.

<img width="1067" alt="Screen Shot 2023-08-06 at 15 43 40" src="https://github.com/lay295/TwitchDownloader/assets/77001249/a10c7d4e-c9a9-4356-8442-f19f46ce4984">

**Comment by Justtheflu** [comment]
and a recording.

https://github.com/lay295/TwitchDownloader/assets/77001249/1fff0cb5-e5f5-49a0-8f0d-753da11bd4e8

**Comment by MarkAlexanderDev** [comment]
I have the same issue on Mac intel

**Comment by ScrubN** [comment]
> I have the same issue on Mac intel

I have confirmed the problem with a borrowed intel mac. The executable gets extracted to `~/.net/TwitchDownloaderCLI/<hash>`, which becomes the base environment directory due to an extra check that was added a while back. In the meantime, please use absolute paths instead of relative paths.

> The 'enter' bug still remains.
> Here's an image, when I expand the window it shows many ((((, maybe it's related.

I suspect your shell does not like that the final line does not end with a newline character. I can make you a debug build to confirm this theory if you would like.
