### ISSUE TITLE
Add highlight link variation to video regex

### ISSUE THREAD

**Issue by curya** [lay295/TwitchDownloader#787]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

The only issue I could find related to this was the "Highlights Collections" one. So maybe this is a bug or something rather than a feature request, but basically highlights don't work.

Example link: https://www.twitch.tv/kitboga/video/1712091473

I get an error no matter what tab I try to download from. Even chat download doesn't work.

Yt-dlp works fine with the link above, if that helps at all.

**Comment by ScrubN** [comment]
I see I need to update the regex. Your link is in the format `twitch.tv`/`streamer`/`video`/`id` but the program expects either `twitch.tv`/`videos`/`id` or `id`. You can reformat your link or use just the ID for now.

**Comment by curya** [comment]
That's literally the first thing I tried! Doesn't work...

**Comment by ScrubN** [comment]
I'm not sure what to tell you.
![image](https://github.com/lay295/TwitchDownloader/assets/72096833/36ae88fb-c6c1-4f1d-bf87-abbef9563d00)
![image](https://github.com/lay295/TwitchDownloader/assets/72096833/4df05e34-3258-4546-935f-5c3819a0a74e)

**Comment by curya** [comment]
Clarification: Changing "video" to "videos" doesn't work.

**Comment by ScrubN** [comment]
> Clarification: Changing "video" to "videos" doesn't work.

You must also remove the streamer name from the link. 
https://www.twitch.tv/kitboga/video/1712091473 -> https://www.twitch.tv/videos/1712091473

**Comment by curya** [comment]
Ah. Thank you!
