### ISSUE TITLE
Why won't this application work on macOS

### ISSUE THREAD

**Issue by TAYMERRR1** [lay295/TwitchDownloader#789]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Unsure

### Describe your issue here

When I download the application for mac it just gives me a bunch of code and no application to use for downloading the VOD or the chat. Fix or help??

### Add any related files or extra information here

(MacOS related issue)

**Comment by ScrubN** [comment]
Please refer to the [usage guide for MacOS in the readme](https://github.com/lay295/TwitchDownloader#macos--getting-started)

**Comment by TAYMERRR1** [comment]
No I downloaded the CUI for mac and I have no clue how to fix this issue I'm not so big on commands but I need help further and a more simplified solution

**Comment by ScrubN** [comment]
Open a new terminal window. You can use spotlight search to do this with `cmd` + `space`, type `terminal` and press `enter`.

From there, use the command `ls` to list out the folders you can move to. If the CLI is in your downloads folder, type `cd Downloads`. If it is on your desktop, type `cd Desktop`. If the CLI is in further subfolders, i.e. `Downloads\TwitchDownloaderCLI` then after moving to the `Downloads` folder type `cd TwitchDownloaderCLI`.

After that please type `chmod +x TwitchDownloaderCLI` to give the binary the ability to execute.

You likely do not already have FFmpeg, so you can use TDCLI to download it with `./TwitchDownloaderCLI ffmpeg -d`.

Then you need to give FFmpeg executable rights with `chmod +x ffmpeg`.

And then you are ready to use TwitchDownloaderCLI. You can see a set of examples commands in the [CLI README](https://github.com/lay295/TwitchDownloader/blob/master/TwitchDownloaderCLI/README.md#example-commands)

**Comment by ScrubN** [comment]
Please be advised that there is a problem with the current MacOS version of TwitchDownloaderCLI. Instead of using relative paths, please use absolute paths.

For example, if you would like to download something to the desktop you would run
```
./TwitchDownloaderCLI videodownload --id 123456789 --output ~/Desktop
```

The `~` is a shortcut to your user folder, the parent folder of your downloads/desktop/documents/etc. folder.

**Comment by SputNikPlop** [comment]
@ScrubN Tested the new arm64 as well as the x86_64 latest releases and they work better than the release here, this probably can be closed.
