### ISSUE TITLE
Generated mask is fully white and very tiny in filesize.

### ISSUE THREAD

**Issue by MrBrax** [lay295/TwitchDownloader#79]
`TwitchDownloaderCLI.exe --mode ChatRender --input "HAchubby_2020-09-21T11_09_43Z_667506194.chat" --chat-height "1080" --chat-width 300 --framerate 60 --update-rate 0 --font-size 12 --outline --generate-mask --output HAchubby_2020-09-21T11_09_43Z_667506194_chat.mp4"`

This command outputs a fully white mask video. I don't really see any other options for this, unless i'm really blind. Using latest release version on windows

**Comment by lay295** [comment]
Yep looks like a bug, and I can reproduce it. I won't be at my main computer for a few days so won't be able to fix it. I'll fix it when I get back.

**Comment by lay295** [comment]
I tried with --background-color "#00000000" and it works. I'll probably add a warning message in the future to the CLI if generate mask option is checked with an opaque alpha channel.

**Comment by MrBrax** [comment]
Yep it works, nice.

`ffmpeg.exe -ss 37 -i chat.mp4 -i chat_mask.mp4 -i vod.mp4 -filter_complex [0][1]alphamerge[ia];[2][ia]overlay=main_w-overlay_w:0 -c:a copy -c:v libx264 -preset slow -crf 26 burned.mp4`

dunno how useful this is, but i added this to my own project to burn chat into the vod without any video editing software

**Comment by lay295** [comment]
Awesome, I wanted to make a few miscellaneous programs to do stuff with overlaying chat it's just that I'm not too proficient in ffmpeg filters so didn't get around to it. I'll probably use your command in future programs, thanks.
