### ISSUE TITLE
Chat Update does not do anything if the Vod is expired

### ISSUE THREAD

**Issue by TheMadog24** [lay295/TwitchDownloader#790]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

I have old VODs and Chat files from before the Badges API V1 shutdown. These files are also from before the option was added to embed the badges, so I wanted to update them to get the badges and bits added.

However, it does not seem to do so. It just spits out
`ERROR: Unable to find thumbnail: Video is expired or embedded ID is corrupt`
and then completes. It seems to only add in a blank "video" section, and does not attempt to retrieve any badges or bits.

![image](https://github.com/lay295/TwitchDownloader/assets/12008758/1cf7972c-baab-4a35-b938-e958a61fbe18)

I assumed it would do this, just go through and grab the comments badges and bits, and add them in. Is this not a functionality?
Does it need a video/VOD to still be live?

if so, can this be changed/added?
The program I made that uses these also used the API V1, and with that gone, I was relying on the embedded data.
thanks.

**Comment by ScrubN** [comment]
Could you upload the chat file? The updater is fetching the badges as expected on my end.

**Comment by TheMadog24** [comment]
Nevermind, I apologize.

I unchecked and re-checked the option to replace Embeds, and it works now.

**Comment by ScrubN** [comment]
Yeah I was about to say, it seems to be working fine.
![image](https://github.com/lay295/TwitchDownloader/assets/72096833/b943d2ff-72b4-44a5-8357-0c9caa888051)

I did find an unrelated problem though that I might fix.
