### ISSUE TITLE
Twitchdownloader not opening on windows

### ISSUE THREAD

**Issue by oscar1668** [lay295/TwitchDownloader#791]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

I have tried downloading and extracting the files multiple times now but every time i try to open the software it gives me first of all some system.runtime error and then i press ok and then another one pops up but with a lot more text. I cant figure out what my problem is 
![error 1](https://github.com/lay295/TwitchDownloader/assets/73710632/a58b1c60-30d4-4fee-99d6-e454b9e5a6cd)
![error 2](https://github.com/lay295/TwitchDownloader/assets/73710632/fd44d27f-dd2e-448c-8470-298de8feca90)

**Comment by ScrubN** [comment]
Could you please press `windows` + `r` on your keyboard, then enter `winver` into the run box and press `enter`? I need a screenshot of the version at the top of the window.

For example:
![image](https://github.com/lay295/TwitchDownloader/assets/72096833/ef0b1f3e-5617-4c5d-bd8a-699aee055b07)

**Comment by Imflyin2023** [comment]
> Could you please press `windows` + `r` on your keyboard, then enter `winver` into the run box and press `enter`? I need a screenshot of the version at the top of the window.
> 
> For example: ![image](https://user-images.githubusercontent.com/72096833/260795889-ef0b1f3e-5617-4c5d-bd8a-699aee055b07.png)

Hi, can you add the ability to download the entire playlist from Twitch? That is, the program downloads several streams at the same time without having to download them separately, and if you want, you can also make it possible to download the entire playlist in one file.

For example, https://www.twitch.tv/collections/Bl3xtMYtPxcTcg [I know these streams are in Russian, but it doesn't matter]

**Comment by ScrubN** [comment]
> Hi, can you add the ability to download the entire playlist from Twitch? That is, the program downloads several videos at the same time without having to download them separately, and if you want, you can also make it possible to download the entire playlist in one file.
> 
> For example, https://www.twitch.tv/collections/Bl3xtMYtPxcTcg [I know these videos are in Russian, but it doesn't matter]

If you can make a new issue thread for this feature request, then I will consider looking into it.

**Comment by Imflyin2023** [comment]
> > Hi, can you add the ability to download the entire playlist from Twitch? That is, the program downloads several videos at the same time without having to download them separately, and if you want, you can also make it possible to download the entire playlist in one file.
> > For example, https://www.twitch.tv/collections/Bl3xtMYtPxcTcg [I know these videos are in Russian, but it doesn't matter]
> 
> If you can make a new issue thread for this feature request, then I will consider looking into it.

Good, I made it, but I didn't change the description [I guess it wasn't necessary]

**Comment by WidgyAinz** [comment]
Same issue, for me, I had to go back in time until TwitchDownloaderGUI-1.52.8-Windows-x64 for it to open. 
![2023-08-17 17_24_33-Twitchdownloader not opening on windows · Issue #791 · lay295_TwitchDownloader —](https://github.com/lay295/TwitchDownloader/assets/5060079/9b39dee8-6d00-4573-9f44-52e4d7bffe33)

**Comment by ScrubN** [comment]
> Same issue, for me, I had to go back in time until TwitchDownloaderGUI-1.52.8-Windows-x64 for it to open. ![2023-08-17 17_24_33-Twitchdownloader not opening on windows · Issue #791 · lay295_TwitchDownloader —](https://user-images.githubusercontent.com/5060079/261443806-9b39dee8-6d00-4573-9f44-52e4d7bffe33.png)

Are you able to provide the error message in English?

**Comment by ScrubN** [comment]
I was able to find information about the error online via the error code. Its likely that your windows system files are corrupted. Try running the following commands inside an administrator command prompt, then restart windows and try opening TwitchDownloader again:
```ps
dism /online /cleanup-image /scanhealth
dism /online /cleanup-image /restorehealth
dism /online /cleanup-image /scanhealth
sfc /scannow
```

**Comment by WidgyAinz** [comment]
Did nothing
![2023-08-17 23_18_26-Administrator_ Command Prompt](https://github.com/lay295/TwitchDownloader/assets/5060079/4046c7a2-6446-4b8e-bd20-6d9284f7ac29)

**Comment by 2904nando** [comment]
I had this problem before. To "fix" it, I just deleted the Desktop shortcut and created a new one from the root folder opening the "TwitchDownloaderWPF.exe".
The original shortcut was trying to open another .exe file, and it all happened after I tried to update the downloader from one version to another (unfortunately, I don't remember the specific version)

**Comment by ScrubN** [comment]
@WidgyAinz Please see if this workflow build fixes your problem: [github.com/lay295/TwitchDownloader/actions/runs/5920180947?pr=796](https://github.com/lay295/TwitchDownloader/actions/runs/5920180947?pr=796)
