### ISSUE TITLE
Audio delay when downloading stream with no delay on site. (stream offline error?)

### ISSUE THREAD

**Issue by Joyte** [lay295/TwitchDownloader#795]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

When I download this specific vod, at 3:57 in, the stream goes offline for around 20-ish seconds. When viewing on twitch, everything recovers and is still watchable, but when viewing downloaded via TwitchDownloader, there's an audio delay equivalent to the stream offline time, around 20 seconds.

### Add any related files or extra information here

VOD id: 1886581054

I fixed this by editing the downloaded VOD in davinci, and dragging the audio track back at the bug portion until it seems like it's mostly in sync, but this is a odd issue, and it's an annoying workaround, having to wait a while for the video to compile on my machine.

**Comment by ScrubN** [comment]
I have a potential solution, however it kindof corrupts the first segment (~10 secs) after the stream is revived. I'm not really sure what can be done about it.

https://github.com/lay295/TwitchDownloader/assets/72096833/b7cd0bf2-e8d1-4b72-a871-549a44eca24f

Also another side effect to this new potential solution is that it completes finalization in about 3 seconds which is a welcomed feature.

**Comment by ScrubN** [comment]
Good news, #1103 now matches the behavior seen on Twitch website!

https://github.com/lay295/TwitchDownloader/assets/72096833/62481739-6105-43b3-ad5e-1c89039ea58e
