### ISSUE TITLE
Download is not resuming after internet reconnects

### ISSUE THREAD

**Issue by MrDood3** [lay295/TwitchDownloader#798]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

When the internet disconnects and reconnects due to instability, the download doesn't resume at all and is just frozen basically. And I noticed that the app's network usage is at 0 Mbps(shown below) after the internet reconnects. I've already had to cancel and restart the download twice already, and this is the very first time this issue has happened for me. Before my download resumed perfectly fine even though my internet was unstable on certain days. Please help

![TwitchDownloader](https://github.com/lay295/TwitchDownloader/assets/142956845/9c1c0454-a175-4eac-9bac-8ee6cf0c3569)

**Comment by ScrubN** [comment]
This sounds the same as #265 / #772. Please see if this workflow build fixes the problem: [github.com/lay295/TwitchDownloader/actions/runs/5874136447](https://github.com/lay295/TwitchDownloader/actions/runs/5874136447)

**Comment by MrDood3** [comment]
Will do. Thank you so much
