### ISSUE TITLE
Render chat fails with 7tv emotes

### ISSUE THREAD

**Issue by matter1770** [lay295/TwitchDownloader#805]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

When rendering any chat file, I get the ERROR: Response status code does not indicate success: 404 (Not Found) message. After trying out different settings, this only occurs when rendering with 7tv emotes checked

**Comment by ScrubN** [comment]
Please provide your chat json. You will need to zip or rename it to upload it to github.

**Comment by matter1770** [comment]
seems to have been a temporary issue with 7tv

**Comment by ScrubN** [comment]
I see, 7TV _has_ been having a lot of downtime recently.

Do you think the program should continue regardless of the success fetching 7TV/BTTV/FFZ emotes? I'm thinking maybe but it shouldn't let emote fetching fail silently, it should log that the emote service was inaccessible.
