### ISSUE TITLE
Incorrect renders of some characters

### ISSUE THREAD

**Issue by Yusyuriv** [lay295/TwitchDownloader#81]
Hello, and thank you for this amazing software ❤

Today I noticed that some characters are not rendered correctly. For example, this phrase:
```
 🍡 𝕀 🍡 𝕗𝕖𝕖𝕝 🍡 𝕝𝕚𝕜𝕖 🍡 𝕕𝕒𝕟𝕘𝕠 🍡
```
In browser, it displays correctly:
![image](https://user-images.githubusercontent.com/3993179/94863867-cb982d80-0443-11eb-8439-6e4ea4a413c1.png)
In chat render it displays like this:
![image](https://user-images.githubusercontent.com/3993179/94864067-1c0f8b00-0444-11eb-9d8b-1ef02ece1cea.png)

It can be tested on VOD 126291793, between 03:18:58 and 03:19:00.

**Comment by lay295** [comment]
Yeah I can reproduce it. I have a better understanding now of character sets and encoding compared to when I first made this so hopefully I can fix it this weekend.

**Comment by lay295** [comment]
Should be fixed in 1.39, feel free to comment if it's not and I will re-open.

![image](https://user-images.githubusercontent.com/1060681/102758090-34ef5480-4340-11eb-86be-522a17b5cb67.png)
