### ISSUE TITLE
Downloading Chat Error

### ISSUE THREAD

**Issue by TheMadog24** [lay295/TwitchDownloader#813]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

When downloading chat, I get this error:
`ERROR: Expected end of string, but instead reached end of data. Path: $[0].data.video.comments.edges[27].__typename | LineNumber: 0 | BytePositionInLine: 22743.`

Only seems to happen on that specific video.
Gets to about 97% Downloading, and then throws the error.

### Add any related files or extra information here

VOD ID: 1912810353

EDIT:
also Happens on this VOD ID: 1923815185
`ERROR: Expected end of string, but instead reached end of data. Path: $[0].data.video.comments.edges[17].node.id | LineNumber: 0 | BytePositionInLine: 14055.`

**Comment by ScrubN** [comment]
I'm unable to reproduce, it might have been a temporary issue. Please try downloading again.

**Comment by TheMadog24** [comment]
> it might have been a temporary issue. Please try downloading again.

It is working now, sorry for the inconvenience.
