### ISSUE TITLE
Add option to specify custom output dir for downloads

### ISSUE THREAD

**Issue by Goosegit11** [lay295/TwitchDownloader#818]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

Related: #114

The TwitchDownloaderCLI AUR package saves binary to /usr/bin, which is okay.
But when you try to `TwitchDownloaderCLI chatdownload ...`, it tried to output all the downloaded files into `/usr/bin`. This is a security risk, as writing to /usr/bin requires sudo. And /usr/bin is meant for binaries, not user data. 
I think Program should instead allow specifying the output directory with a CLI argument.

**Comment by ScrubN** [comment]
This might already be fixed for the next version. That was a bad decision on my part, I genuinely have no clue what I was thinking.

**Comment by Goosegit11** [comment]
Glad to hear that, i'm waiting for the next version then

**Comment by ScrubN** [comment]
This should be fixed. Feel free to say anything if it isn't.
