### ISSUE TITLE
[CLI] Paths are ignored in macOS

### ISSUE THREAD

**Issue by superbonaci** [lay295/TwitchDownloader#819]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Command Line Interface

### Describe your issue here

Running macOS version:
```
$ cd /Volumes/USB-Stor
$ TwitchDownloaderCLI videodownload --oauth OTAUTH --id ID -o out.mp4
```
Video is not saved to `/Volumes/USB-Stor/out.mp4`, but to:
```
/Users/clang/.net/TwitchDownloaderCLI/NgR=NMxbkWrUEXsIkZUyFzjjYa04koIy/out.mp4
```

Using `-o ./out.mp4` makes no difference.

**Comment by superbonaci** [comment]
Temp path is ignored too:
```
$ cd /Volumes/USB-Stor
$ mkdir TMP
$ TwitchDownloaderCLI videodownload --oauth OTAUTH --id ID -o out.mp4 --temp-path ./TMP/
```
Still saves parts to operating system drive `/System/Volumes/*`.

**Comment by ScrubN** [comment]
Yes this was fixed for the next version, which will hopefully be out soon

**Comment by superbonaci** [comment]
Thanks!

**Comment by ScrubN** [comment]
https://github.com/lay295/TwitchDownloader/releases
