### ISSUE TITLE
Mask render output white

### ISSUE THREAD

**Issue by tolekk** [lay295/TwitchDownloader#82]
Hey, I was very excited to use the masking option with chat renders, but stumbled upon an issue where the mask file is just fully white, tried still using it as a mask but that doesn't work ( 4HEad )

It may have to do with the resolution I'm using it for the chat, will test with lower res and come back with results asap.
![](https://i.nuuls.com/XmUXf.png)

**Comment by lay295** [comment]
Make sure your background color is transparent with the mask option

**Comment by lay295** [comment]
Any update?

**Comment by No0Vad** [comment]
I had the same issue, can confirm you must select transparent as the background color, then it works fine 😀
(Version 1.39.11)
