### ISSUE TITLE
Add video description to mp4 metadata

### ISSUE THREAD

**Issue by superbonaci** [lay295/TwitchDownloader#820]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

Feature request to add the video description (if available) to mp4 file:
https://www.twitch.tv/videos/1260955824

This video description is `Reaching the 20k followers goal!`

**Comment by ScrubN** [comment]
I thought I had already implemented this but apparently not.

Metadata for videos with descriptions will look like the following:
```
<description>
------------------------
Originally aired: <videoCreation>
Video id: <videoId>
Views: <viewCount>
```
and videos without descriptions will continue to look the same:
```
Originally aired: <videoCreation>
Video id: <videoId>
Views: <viewCount>
```

**Comment by superbonaci** [comment]
Thanks!
