### ISSUE TITLE
Fails to download json file (code 1)

### ISSUE THREAD

**Issue by superbonaci** [lay295/TwitchDownloader#823]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Command Line Interface

### Describe your issue here

Using MacOS latest commit [85ca2a](https://github.com/lay295/TwitchDownloader/commit/485ca2ae36115b32055d5186437bcd756f438793):
```
TwitchDownloaderCLI videodownload --oauth OAUTH -u https://www.twitch.tv/videos/1260955824 -q best --temp-path ./TMP/ -o 1260955824.json
TwitchDownloaderCLI 1.53.2 Copyright (c) 2019 lay295 and contributors
[STATUS] - Fetching Video Info [1/5]
[STATUS] - Downloading 100% [2/5]
[STATUS] - Verifying Parts 100% [3/5]
[STATUS] - Combining Parts 100% [4/5]
[STATUS] - Finalizing Video 0% [5/5]
[LOG] - Failed to finalize video (code 1), retrying in 10 seconds...
^C
```

**Comment by ScrubN** [comment]
`videodownload` does not support json output, only mp4. Unfortunately it is not possible to download VOD chats from videos that require oauth.

**Comment by superbonaci** [comment]
@ScrubN then how do I download the json file?

**Comment by superbonaci** [comment]
Got it I must use the other option:
```
TwitchDownloaderCLI chatdownload -u https://www.twitch.tv/videos/1260955824 -o 1260955824.json
```
