### ISSUE TITLE
Add description field to json and text samples

### ISSUE THREAD

**Issue by superbonaci** [lay295/TwitchDownloader#824]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

The json and text samples in https://github.com/lay295/TwitchDownloader/blob/master/README.md could be improved containing a description field, specially if the video description has more than 1 line.

![pic](https://github.com/lay295/TwitchDownloader/assets/8339596/5b09fabd-bb9c-4e83-9a1d-3f3a2e62c12d)

**Comment by Sarioah** [comment]
Other VOD information such as the starting category might be nice to include in the .json

**Comment by ScrubN** [comment]
> Other VOD information such as the starting category might be nice to include in the .json

The starting category can be inferred by referencing `chatRoot.video.chapters[0]`

**Comment by Sarioah** [comment]
That list is not populated unless there was a category change during the stream (may be a bug?)
yt-dlp *does* however populate the `chapters` field in their own json dumps for single-chapter VODs

**Comment by ScrubN** [comment]
> That list is not populated unless there was a category change during the stream (may be a bug?)

You are right, it is not returned for streams with a single category. I will add a fallback request for when this occurs.

**Comment by ScrubN** [comment]
Looks like Github finally allows for json files to be uploaded to threads. This will become the new example in the README since pastebin has become pay-to-use for non-generic text files. [ExampleMoonMoonJsonFile.json](https://github.com/lay295/TwitchDownloader/files/13495494/ExampleMoonMoonJsonFile.json)

**Comment by ScrubN** [comment]
May as well update the text link to match it. [ExampleMoonMoonTextFile.txt](https://github.com/lay295/TwitchDownloader/files/13495523/ExampleMoonMoonTextFile.txt)
