### ISSUE TITLE
Please add auto start end info to file name and default download folder option

### ISSUE THREAD

**Issue by makedir** [lay295/TwitchDownloader#826]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

Please add option to automatically add start end time to the file name when you download. also please add option for default download folder.

**Comment by ScrubN** [comment]
> Please add option to automatically add start end time to the file name when you download

This is already an existing filename parameter in the settings. `{crop_start}` and `{crop_end}`.

> also please add option for default download folder

I assume you are talking about the enqueuing window. That already stores the last folder you saved to, though some users have reported it to be inconsistent.
