### ISSUE TITLE
Issue when opening the Twitch Downloader

### ISSUE THREAD

**Issue by Pllys** [lay295/TwitchDownloader#827]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates

### Write stuff here

Hello, I just downloaded the Twitch Downloader and everytime I try to open the app i get this fatal error

![379633144_827622705728940_7503445716151007230_n](https://github.com/lay295/TwitchDownloader/assets/145832577/ead1b249-cfb5-42e5-bbcf-db9f6e37560f)

**Comment by ScrubN** [comment]
TwitchDownloader is not designed to be stored at `C:\Program Files\`. Consider moving it to `%appdata%`.

I will still, however, fix the crash when the themes fail to extract.
