### ISSUE TITLE
class="panel-description" not included in json file

### ISSUE THREAD

**Issue by superbonaci** [lay295/TwitchDownloader#829]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Command Line Interface

### Describe your issue here

Download json:
```
TwitchDownloaderCLI chatdownload -u https://www.twitch.tv/videos/1260955824 -o 1260955824.json
```
The video description (in html as `class="panel-description"` field)
 is not included in json:
```
Reaching the 20k followers goal!
```

**Comment by ScrubN** [comment]
The video description is present at `video.description` in 71b08d48936d77bc4dffbe4a58e13d0e486f4e8e
![image](https://github.com/lay295/TwitchDownloader/assets/72096833/b3795b95-a783-4492-8eb6-5c9941fd5b23)
