### ISSUE TITLE
Description field adds empty lines between multiple lines

### ISSUE THREAD

**Issue by superbonaci** [lay295/TwitchDownloader#830]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Command Line Interface

### Describe your issue here

Download a json where description (`chatRoot.video.description`) has more than one line. I couldn't find a sample so you must create one yourself:

![twitch](https://github.com/lay295/TwitchDownloader/assets/8339596/7731e86a-83f7-47e6-a21c-f9548de32880)

However in json there's one empty line between each text line:

```
"video":{"title":"video","description":"First line.  \n\nSecond line.  \n\nThird line  \n\n:P  "
```

Let me know if you find a public video with multiple lines in description field.

**Comment by ScrubN** [comment]
`chatRoot.video.description` is a direct serialization of the API response. I presume they use the double spaces + double newlines in their markdown parser. At any rate, this is now being cleaned c2eb143d2b2bd10e620b35907c45deea3c2ee7d2

**Comment by superbonaci** [comment]
Thanks!
