### ISSUE TITLE
Cropped chat files keep original time offsets.

### ISSUE THREAD

**Issue by TheMadog24** [lay295/TwitchDownloader#832]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

When downloading a chat with a cropped time, the comments time will be set to the original time stamp of the video, and not adjusted to the cropped.
Example, I downloaded a 24 Hour chat but cropped it to start at 8 Hours in. The comments in the chat file have their original time stamp, starting at 8 hours.
The same thing applies to chapters, and I would assume the cropped video's chapters metadata is also not adjusted.

I know this is most likely not a bug, but this really effects what I use them for.

**Comment by ScrubN** [comment]
This is how cropped chats worked before I joined the project and it has many upsides for both the renderer and the updater.

For your purpose, you can try subtracting `chatRoot.video.start` from each comment offset to normalize it.

**Comment by TheMadog24** [comment]
> For your purpose, you can try subtracting `chatRoot.video.start` from each comment offset to normalize it.

This is actually perfect for what I need, thank you! I did not see that the video section shows the start time.
