### ISSUE TITLE
Multiple lines in description are separated by a dot

### ISSUE THREAD

**Issue by superbonaci** [lay295/TwitchDownloader#835]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

In case a video description has several lines, it's converted to a single line into mp4 metadata, and lines are separated by a dot:
Original description in Twitch website:
```
First line

Second line.

Third line $$$***...aÂ

:P
```
Is converted to:
```
First line.Second line..Third line $$$***...aÂ.:P.------------------------.
```
Several dashes and dot are added to last line too.
Please add this details to documentation, so it's clear what's the structure of the `Comment` field in mp4 metadata, because doesn't look "right" at first glance.

Related to https://github.com/lay295/TwitchDownloader/issues/830

**Comment by ScrubN** [comment]
Either there is a problem with your version of FFmpeg, or there is a problem with the application you are using to view the video metadata.

**Comment by superbonaci** [comment]
@ScrubN which application works or do you recommend to view the video metadata?

**Comment by ScrubN** [comment]
VLC reads the comment field correctly. 
If you're trying to automate parsing the comment field you can use FFmpeg to extract it:
```
ffmpeg -y -loglevel error -i video.mp4 -f ffmetadata meta.txt
```
or you can just read the bytes directly. They are at the very end of the file past the header `©cmt` (`A9 63 6D 74`). You can verify on your own files with a hex editor, however be wary that some hex editors replace invisible characters, such as line feed/new line (`0A`), with periods.

**Comment by superbonaci** [comment]
I see that in meta.txt the multiple lines in comment field are actually in separate lines, but how does ffmpeg know where it ends if I were to re-encode a new video with that metadata? Is the line `------------------------\` the one that ends the comment field or is just metadata missing?

```
;FFMETADATA1
major_brand=isom
minor_version=512
compatible_brands=isomiso2avc1mp41
title=Music (1123456789)
artist=Vlogs
date=2023
comment=First line\
Second line.\
Third line $$$***...aÂ\
:P\
------------------------\
Originally aired: 2023-01-20 10:51:59Z\
Video id: 1123456789\
Views: 196
encoder=Lavf60.3.100
```

**Comment by ScrubN** [comment]
> But how does ffmpeg know where it ends if I were to re-encode a new video with that metadata?

The FFMETADATA parser in FFmpeg starts at position 0 and reads forwards until it sees a line feed character. It then parses that entire token and registers that as a field. If the line feed it read was prefixed by a `\` then it is escaped and the parser continues until the next line feed or the end of the file. You can read more about the format here: https://ffmpeg.org/ffmpeg-formats.html#Metadata-1

If you want to encode that metadata to a new video file, it is already in a valid state to do so, though you would probably want to remove the encoder and brand keys since since you are probably transcoding between formats.

> Is the line `------------------------\` the one that ends the comment field or is just metadata missing?

That is a separator I put in to convey to the user that everything above is the description and everything below is miscellaneous video metadata.

**Comment by superbonaci** [comment]
> > Is the line `------------------------\` the one that ends the comment field or is just metadata missing?
> 
> That is a separator I put in to convey to the user that everything above is the description and everything below is miscellaneous video metadata.

Thank for the explanation, it's a good way to do it. Could you add such information to the documentation?
