### ISSUE TITLE
stuck at 100%

### ISSUE THREAD

**Issue by xp906** [lay295/TwitchDownloader#839]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

When I download some cods it loads it up to 100% but then stays there forever. Any idea what is causing this or how I can fix it?

I was able to download 2 vods totally fine using this application, then the third got stuck at 100%. I tried downloading it a few more times and the same thing happened. I tried instructing it to download only the first half of it but this still happened. Then I tried to download a different vod and it worked again. But then the next vod I tried to download ran into the same problem. I thought this might be because the two problem vods were very long (14h+) but I now realize that one of the first vods I successfully downloaded was 13h. Not sure what could be causing this: any tips are appreciated!

### Add any related files or extra information here

Vod ID, unsuccessful download: 1901005153
Vod ID that I was able to download: 1899129470

**Comment by ScrubN** [comment]
This is now fixed in 1.53.3 https://github.com/lay295/TwitchDownloader/releases
