### ISSUE TITLE
SUGGESTION: Luma filter, contrast for usernames

### ISSUE THREAD

**Issue by holndonner** [lay295/TwitchDownloader#84]
Sometimes I find it hard to read the usernames in the chat; I suggest implementing the following features from FFZ: 
![Képkivágás](https://user-images.githubusercontent.com/40231846/96250528-41a5a400-0faf-11eb-8e4c-b9fb7e93b15b.PNG)

**Comment by lay295** [comment]
I [have](https://github.com/lay295/TwitchDownloader/blob/ca18152c898d9b0de748aba35114ccdd4102594e/TwitchDownloaderCore/ChatRenderer.cs#L763) tried to implement something like that. Perhaps it's not aggressive enough with the values.

If you could post an example of not enough contrast that'd be helpful.

**Comment by holndonner** [comment]
I always use full black bg. for my clip segment; therefore everything that's dark looks kinda' unreadable for me.
Here's ffz:
![vlcsnap-2020-10-19-11h58m25s822](https://user-images.githubusercontent.com/40231846/96430797-e835b300-1202-11eb-8367-1df0a88645a8.png)

Here's yours:
![vlcsnap-2020-10-19-11h59m54s481](https://user-images.githubusercontent.com/40231846/96430817-ef5cc100-1202-11eb-82e1-ab028debff71.png)

**Comment by ScrubN** [comment]
While we don't expose a user adjustable contrast, I significantly improve the readable colors algorithm in #1072.

**Comment by ScrubN** [comment]
If it the new algorithm is still not sufficient, I can reopen this issue.
