### ISSUE TITLE
[Feature request] Add binary concatenation for TS files

### ISSUE THREAD

**Issue by superbonaci** [lay295/TwitchDownloader#846]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

Currently TwitchDownloader combines ts files into output.ts using ffmpeg, but that can have unknown bugs. Another method is to use binary concatenation:
- `cat` on linux or mac
- `copy /b` on Windows

So the feature for CLI could be invoked with a flag:
```
TwitchDownloaderCLI videodownload -cat
```

I can do it manually having the parts:
```
for i in {0..720} ; do cat $i.ts >> output_cat.ts ; done
```

and if user wants to use ffmpeg:
```
TwitchDownloaderCLI videodownload -ffmpeg
```

Also please add such information to documentation.

**Comment by ScrubN** [comment]
> Currently TwitchDownloader combines ts files into output.ts using ffmpeg

This is untrue.

I do, however, plan on implementing concatenation with FFmpeg as it is much faster due to not having to write to the disk twice.

**Comment by superbonaci** [comment]
Binary concatenation should not be done for Transport Stream files, output will be corrupted:
https://github.com/lay295/TwitchDownloader/issues/838#issuecomment-1752132891

I'm closing this issue since I what I suggest is wrong.
Also don't use ffmpeg yet, has bugs with concat filter/protocol and will break output.ts, they way you are doing it is the only right way for now.

**Comment by superbonaci** [comment]
TS files are designed to be concatenated in binary mode, that is raw, without any modification of its contents.
This is done by the `Stream.CopyToAsync` method.
