### ISSUE TITLE
[Feature request] Add CLI option to just save as .ts

### ISSUE THREAD

**Issue by superbonaci** [lay295/TwitchDownloader#847]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

Add CLI option to save the final file as ts, which is output.ts, so no conversion to mp4 or mkv with ffmpeg or cat:
```
$ TwitchDownloaderCLI videodownload --oauth $OAUTH -u "https://www.twitch.tv/videos/694444624" -q best --temp-path ./TMP/ -o SURPRISE.ts
```
That would mean just copying output.ts to SURPRISE.ts
in this case maybe detect file extension automatically to determine if use ffmpeg/cat or not?

Or just manually set it:
```
$ TwitchDownloaderCLI videodownload --format-ts --oauth $OAUTH -u "https://www.twitch.tv/videos/694444624" -q best --temp-path ./TMP/ -o SURPRISE.ts
```
The flag could be formatted as `--format-ts`, `--format:ts` or `--format ts` like other software does.

Also please add such information to documentation.

**Comment by superbonaci** [comment]
Once this feature is implemented, I can ask better ts support from handbrake and gpac.

**Comment by ScrubN** [comment]
The finalization pipeline has changed and output.ts is no longer created.
