### ISSUE TITLE
Incorrect saving file format when selected HTML chat.

### ISSUE THREAD

**Issue by MrDummyNL** [lay295/TwitchDownloader#849]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

Last update downloaded (10-10) and start to download right away....

but something is not right. I saw JSON files showed up in the map. Did i selected it wrong? So i did it again, choose for chat save HTML format and observe again the map. Again JSON files!

Previous version is fine, did save correct in HTML format. How the heck did you made new bug in this new version, it's just a toggle but it goes clearly wrong. HTML toggle gives me JSON files.

Go verify yourself if your program did indeed wrong file format save.

UPDATE:
After inspecting file, it's confirmed it has HTML build, but got wrong extension.
So somewhere in program code it put wrong file extension .json instead of .html.

### Add any related files or extra information here

All VODs gives me JSON files when selected HTML chat save.

**Comment by ScrubN** [comment]
While refactoring the enqueuer, it seems my IDE changed the order of some statements. Only the file extension is wrong, the actual data in the file is still correct.

**Comment by ScrubN** [comment]
I fixed this a while ago: 3f7b79e8d54f3e8d31bcefe62c77924bf9485a8d, there should be an update with the fix soon.
