### ISSUE TITLE
Fatal Error: System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by damashki** [lay295/TwitchDownloader#854]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

After a previous download had finished, I copied another twitch url into the clipboard and clicked on the VOD link textfield. Upon double-clicking the text field to select all of the old link text, a fatal error window was thrown onto the screen before I could delete or paste anything into it.

System OS is Windows 11, and Twitch Downloader is v1.53.4

![image](https://github.com/lay295/TwitchDownloader/assets/17398972/54b8b8c8-37c8-4d80-9d87-a472d9b8d876)

**Comment by ScrubN** [comment]
Strange. Apparently it's possible for the text caret position to be negative, yet there's no remarks in the documentation about it.
