### ISSUE TITLE
Can't render chat: "ERROR: Value cannot be null. Parameter name: bitmap"

### ISSUE THREAD

**Issue by Yusyuriv** [lay295/TwitchDownloader#86]
I assume it's because of a missing emote?.. Would be great to just write the name of an emote as text instead of embedding it when it no longer exists. I get this error when downloading chat with embedded emotes or when rendering chat from JSON that doesn't have embedded emotes. This can be tested on VOD 186975818, between 01:21:57 and 01:22:00.

**Comment by ScrubN** [comment]
This has more than likely been fixed
