### ISSUE TITLE
error NETSDK1100: fails to restore project on Linux

### ISSUE THREAD

**Issue by superbonaci** [lay295/TwitchDownloader#860]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Unsure

### Describe your issue here

Download and install `dotnet-sdk-7.0.402-linux-x64.tar.gz` for linux according to instructions:
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-7.0.402-linux-x64-binaries

then clone and try to restore:
```
$ dotnet restore
  Determining projects to restore...
/home/user/dotnet/sdk/7.0.402/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1100: To build a project targeting Windows on this operating system, set the EnableWindowsTargeting property to true. [/home/user/TwitchDownloader/TwitchDownloaderWPF/TwitchDownloaderWPF.csproj]
```

### Add any related files or extra information here

The CLI builds fine running the command directly, skip the restore step directly.

**Comment by ScrubN** [comment]
I forgot about this problem on Linux, you must specify `dotnet restore TwitchDownloaderCLI`. I will update the documentation.

**Comment by ScrubN** [comment]
Documentation has been updated

**Comment by superbonaci** [comment]
Thanks.
