### ISSUE TITLE
I hope there's a feature to download only the audio.

### ISSUE THREAD

**Issue by vincent97277** [lay295/TwitchDownloader#862]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

I generally convert the vods into audio files for podcasts.
Although it can be implemented using the command: 'ffmpeg -i xxx.mp4 xxx.mp3'.
Would it be possible to add a feature called "audiodownload" to simplify this process?

**Comment by ScrubN** [comment]
I have good news for you, Twitch servers already store an audio version of every VOD for the mobile app, and I already have a working prototype for downloading it. I'll see about finishing it for the next release.

**Comment by alexgbor** [comment]
Is there any way to make it download only the audio in the latest version? I'm using the CLI

**Comment by ScrubN** [comment]
This has not been implemented yet, but I will see about implementing it
soon.
