### ISSUE TITLE
Chat downloads in .json when text is chosen

### ISSUE THREAD

**Issue by OfficiallySp** [lay295/TwitchDownloader#868]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

when trying to batch download chat from vods from the task queue tab. selecting to download the chat in .txt form will instead revert to chatlogs being downloaded in .json

**Comment by ScrubN** [comment]
Only the file extension is affected. The actual file contents are still what was selected.

**Comment by ScrubN** [comment]
This was fixed
