### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Ronaldo246** [lay295/TwitchDownloader#87]
How do I download vods and the chat when the vods are sub only because I don't see a login page anywhere, thank you.

**Comment by Ronaldo246** [comment]
If you could DM me that would mean a lot also, thank you.

**Comment by lay295** [comment]
Unless Twitch changed anything, you should be able to download sub only vod chats without doing anything. To download sub only VODs you have to login to the Twitch website and use an extension to get your OAuth and put it in the program. To learn how to do this you can click on the ? next to OAuth which will open [this video](https://youtu.be/1MBsUoFGuls). Follow the instructions and you should be able to download sub only VODs if you're subbed to them.

**Comment by Ronaldo246** [comment]
> Unless Twitch changed anything, you should be able to download sub only vod chats without doing anything. To download sub only VODs you have to login to the Twitch website and use an extension to get your OAuth and put it in the program. To learn how to do this you can click on the ? next to OAuth which will open [this video](https://youtu.be/1MBsUoFGuls). Follow the instructions and you should be able to download sub only VODs if you're subbed to them.

Thank you, this helped a lot.
