### ISSUE TITLE
Unsure about How To Use

### ISSUE THREAD

**Issue by honeyarsonist** [lay295/TwitchDownloader#871]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates

### Write stuff here

hello. i just made an account. im trying to download the file in releases. but my files show me TwitchDownloaderCI and that says its a tool. i did download the ffmpeg thing. like it said to in the Windows Getting started. 
![image](https://github.com/lay295/TwitchDownloader/assets/148876054/29e1d574-ebdb-48fb-82e9-2834779cd8dc)
so im just. not sure. sorry. thanks for helping.

**Comment by ScrubN** [comment]
If you have never used a CLI tool before, I suggest you use TwitchDownloaderWPF instead as it is much friendlier to first time users.

**Comment by ScrubN** [comment]
Closing due to stale
