### ISSUE TITLE
Unable to download chat from vods

### ISSUE THREAD

**Issue by Befbo** [lay295/TwitchDownloader#872]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

When trying to download any chats, I always get one of two error messages in the log, and the chat does not get downloaded.

ERROR: 'P' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.

or

ERROR: Object reference not set to an instance of an object.

### Add any related files or extra information here

Example VOD this happened with: 1959078000

**Comment by ScrubN** [comment]
Your video ID is invalid. 
![image](https://github.com/lay295/TwitchDownloader/assets/72096833/c00bfa60-5439-450e-a4f9-c52811a59f72)

If you can provide a video where the other error occurs reliably, I would gladly look into the cause of that too.

**Comment by superbonaci** [comment]
Sometimes the ID changes for some video, maybe they do some reprocessing or something, I've noticed that before.
For example some video that has muted ts parts was renamed and doesn't have the muted anymore.

**Comment by ScrubN** [comment]
Closing due to stale
