### ISSUE TITLE
Feature Request in Search VODs Panel

### ISSUE THREAD

**Issue by walpis** [lay295/TwitchDownloader#873]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

Hi, can you add in Search VODs Panel a context menu for every search result with the following commands:
- open VOD in default browser
- copy VOD ID to clipboard
- copy VOD URL to clipboard

**Comment by ScrubN** [comment]
With the amount of times this could've been useful, I can't believe I didn't think of this myself. I'll see what I can do.
