### ISSUE TITLE
No halloween emotes in the chat render

### ISSUE THREAD

**Issue by Nutri626** [lay295/TwitchDownloader#879]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Unsure

### Describe your issue here

Hello, many streamers added halloween emotes lately and program simply does not recognize them to render it, in previous years chat was rendered with halloween emotes but with latest versions it renders as "normal"  (same will happen to new year emotes and stuff)

**Comment by sunkhaskasis** [comment]
Hint: always provide the VOD the next time you're having issues with emotes. 

With that said, I know you're referring to Forsen's channel in particular, so I think I know why TD doesn't render his halloween emotes. If you take a look at his [BTTV page](https://i.imgur.com/dxRjBe9.png), you'll notice that his editor hasn't removed the regular emotes and just lumped them together with the halloween versions. This most likely confuses TD, so it fetches whatever first image it could find and ignores the rest. I tried downloading [Forsen's most recent VOD](https://dropmefiles.com/tUiM8) and rendering chat on my end, but it doesn't display the halloween emotes. Moreover, it doesn't even fetch them if you have a look inside the cache folder.

Personally, I'd say this is not a bug with the TD, but rather with the way Forsen's editors have decided to handle halloween emotes.

**Comment by Nutri626** [comment]
> Hint: always provide the VOD the next time you're having issues with emotes.
> 
> With that said, I know you're referring to Forsen's channel in particular, so I think I know why TD doesn't render his halloween emotes. If you take a look at his [BTTV page](https://i.imgur.com/dxRjBe9.png), you'll notice that his editor hasn't removed the regular emotes and just lumped them together with the halloween versions. Essentially, what this means is that there are duplicate emotes under the same name. This most likely confuses TD, so it fetches whatever first image it can find and ignores the other. I tried downloading [Forsen's most recent VOD](https://dropmefiles.com/tUiM8) and rendering chat on my end, but it doesn't display the halloween emotes. Moreover, it doesn't even fetch them if you have a look inside the cache folder.
> 
> Personally, I'd say this is not a bug with the TD, but rather the issue is the way Forsen's editors have decided to handle halloween emotes.


yeah i knew that would be problem that caused it, case closed i guess

**Comment by ScrubN** [comment]
Apologies for this issue not having a simple solution. You can get around it by only embedding the emotes from the provider you want to take priority, then using the chat updater with "embed missing" to embed the rest of the emote providers to the chat.

I *was* working on a patch to allow the user to specify emote provider priority, however it relied on upgrading to .NET7 which didn't work out and by the time I went back to try porting it to .NET6 instead, many files had moved and it was just a huge pain.

Selectable emote priority is still planned functionality (see #476), but I'm a little burned out from this project after #880 so I'm probably going to take a short break.
