### ISSUE TITLE
Mixed files encoded with and without UTF-8 BOM

### ISSUE THREAD

**Issue by superbonaci** [lay295/TwitchDownloader#881]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Both

### Describe your issue here

Some files are coded with BOM:
```
./TwitchDownloaderCLI/Modes/Arguments/FfmpegArgs.cs: Unicode text, UTF-8 (with BOM) text
```
Other don't:
```
./TwitchDownloaderCLI/Modes/Arguments/ITwitchDownloaderArgs.cs: ASCII text
```
Looks like files with edited with different file editors or operating systems, and the are mixed up:
[Comparing changes shows changes to lines that weren't actually changed](https://github.com/orgs/community/discussions/72813)

**Comment by ScrubN** [comment]
If a handful of popular editors automatically mess with the BOM without user input, is there really any point for us to normalize all the BOMs?

**Comment by superbonaci** [comment]
It's a matter of consistency, it should compile just fine unless some later VS update forces to.

**Comment by ScrubN** [comment]
MSBuild removing BOM handling would be a pretty devastating breaking change, so I don't anticipate that ever happening.

**Comment by superbonaci** [comment]
Can text be normalized to BOM in `.gitattributes` ?

**Comment by ScrubN** [comment]
No, the BOM cannot be normalize in `.gitattributes`. You can set the text encoding for the local working tree, but UTF-8 with BOM does not seem to be an applicable option and all the documentation and examples I found only mention UTF-16.
