### ISSUE TITLE
Trying to Update broke the program

### ISSUE THREAD

**Issue by Sebast04** [lay295/TwitchDownloader#882]
### Checklist

- [x] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

I first experienced the same problem like a year ago, but somehow fixed it.
Then, a few months ago, I wanted to update the (gui windows) version because it had problems downloading chat, but it gave me fatal errors when trying to start the program again. So I tried downloading the new version manually from github, same error. I deleted everything I could find in the %appdata% folder and everywhere else I could find related to the twitchdownloader, same problem. It always first asks me if I trust the program when running the .exe, and after that, always the same fatal error messages. when downloading the new version on my laptop instead, it worked perfectly, but I cant just keep downloading vods onto my laptop and moving them to my pc. Today I again I tried everything I could think of, downloaded the newest version etc, but still get the same two fatal error windows: 
![image](https://github.com/lay295/TwitchDownloader/assets/77791868/fa50ddcd-f73c-4f0f-af2c-884d591b65b8)
![image](https://github.com/lay295/TwitchDownloader/assets/77791868/e0879afe-5e07-4076-9466-097db63cbf99)
I dont understand anything of that, so would be great to know what I should do in order to be able to use the program again!
I dont know which version originally broke everything, as I deleted everything trying to get it to work again.
Also Im not sure if this is a duplicate to https://github.com/lay295/TwitchDownloader/issues/791, but the error messages seem to be different

**Comment by ScrubN** [comment]
Are you able to provide your windows version like mentioned in the issue thread you linked? https://github.com/lay295/TwitchDownloader/issues/791#issuecomment-1679368596

After that, could you please run this debug build and show me the window that pops up https://github.com/ScrubN/TwitchDownloader/releases/tag/1.53.4-dev

**Comment by Sebast04** [comment]
1.
![image](https://github.com/lay295/TwitchDownloader/assets/77791868/c117a9b4-9773-4ad3-829e-2c1d86112a21)
2. 
![image](https://github.com/lay295/TwitchDownloader/assets/77791868/0e5b012f-de63-4142-8bce-6deddceb385b)
![image](https://github.com/lay295/TwitchDownloader/assets/77791868/34e55e44-d94d-4aad-b1a8-b245cf5fa893)

**Comment by ScrubN** [comment]
My bad, I didn't realize that I couldn't format an Enum like that, good to know.

I have uploaded a different version to the same link, could you please see if that works?

**Comment by Sebast04** [comment]
![image](https://github.com/lay295/TwitchDownloader/assets/77791868/7a39d9c7-1b0d-4099-b0ef-f35e6b24b77e)
![image](https://github.com/lay295/TwitchDownloader/assets/77791868/75144ab3-66bc-4b64-8f92-f8add8ecf1ea)

got these two error windows, but at least it opened and seems to work fine

**Comment by ScrubN** [comment]
Strange, it thinks there is another application using the configuration file. It may be possible there is another instance of TwitchDownloaderWPF still running but without a window, are you able to try searching task manager kill any programs associated with TwitchDownloaderWPF or try rebooting?

**Comment by Sebast04** [comment]
That fixed it, tho I get this error now before the program opens 
![image](https://github.com/lay295/TwitchDownloader/assets/77791868/33465539-6d34-4291-9ec7-5407061a7be7)

**Comment by ScrubN** [comment]
Great, I'm glad its working now. I may alter the wording of the error popup, but it will probably still remain. 

You can keep using that debug version until the next release is out which should hopefully be soon.
