### ISSUE TITLE
Chat Background 

### ISSUE THREAD

**Issue by TibetBy** [lay295/TwitchDownloader#884]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

When I create a chat, I select Transparency Background but it is created as white

**Comment by ScrubN** [comment]
Can you provide more details about your render options and what program you are using to validate the transparency of the video?

**Comment by ScrubN** [comment]
Stale
