### ISSUE TITLE
badges not rendering recently

### ISSUE THREAD

**Issue by matter1770** [lay295/TwitchDownloader#889]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

[11152023.json](https://github.com/lay295/TwitchDownloader/files/13384913/11152023.json)
[11162023.json](https://github.com/lay295/TwitchDownloader/files/13384915/11162023.json)

noticed that for the last two days, no badges are rendering in the chat. not sure if its the chat data or the rendering that's the issue

**Comment by ScrubN** [comment]
The VOD chats do not contain any user badge data. 

It seems Twitch might be stripping badge data from ALL vods from now on :/
| Nothernlion | Sodapoppin |
|--------|--------|
| ![image](https://github.com/lay295/TwitchDownloader/assets/72096833/4414b710-f5d9-493b-8b75-77ee4cb8660a) | ![image](https://github.com/lay295/TwitchDownloader/assets/72096833/96322dfc-ea28-4a01-8625-8cdd5989ffc5) |

**Comment by Vojtaas** [comment]
so does that mean we'll never have badges in chat again? Or is it a matter of time before it gets fixed?

**Comment by ScrubN** [comment]
It's a problem regarding Twitch. You're free to report no badges in VODs as an issue on the Twitch uservoice or dev forums (without mentioning us please), but unfortunately there's not much we can do without implementing a live chat recorder (which will likely happen eventually).

**Comment by Zibbp** [comment]
It appears it might have been a temporary issue? I downloaded a VOD the other day (`1981223534`) and it did not have any badge data. I went to check again seeing this issue and the badges are back. Confirmed after downloading the chat, the badges are present.

**Comment by ScrubN** [comment]
The badges have also returned to the videos that @matter1770 posted. Here's hoping that it was indeed a temporary issue and not Twitch doing their blackouts where they turn the switch off and on a few times before off permanently.

**Comment by ScrubN** [comment]
It seems sub badges were broken again and are not being returned in by chat playback, but VIP and Cheer badges are still showing.
