### ISSUE TITLE
download live chat

### ISSUE THREAD

**Issue by eban322** [lay295/TwitchDownloader#89]
is it possible to download chat from live translation, when vods are disabled?

**Comment by eban322** [comment]
streamer, which i work with, disabled vods due to music copirating(

**Comment by lay295** [comment]
I mean, it's probably possible to take raw IRC messages from Twitch live and convert it into a json that's compatible with the chat render. I don't think it will be a part of this program though, sorry.

**Comment by eban322** [comment]
> I mean, it's probably possible to take raw IRC messages from Twitch live and convert it into a json that's compatible with the chat render. I don't think it will be a part of this program though, sorry.

sad, but ty anyway

**Comment by Read1337** [comment]
> > I mean, it's probably possible to take raw IRC messages from Twitch live and convert it into a json that's compatible with the chat render. I don't think it will be a part of this program though, sorry.
> 
> sad, but ty anyway

Did you find any solution for live streams?

**Comment by eban322** [comment]
> > > I mean, it's probably possible to take raw IRC messages from Twitch live and convert it into a json that's compatible with the chat render. I don't think it will be a part of this program though, sorry.
> > 
> > 
> > sad, but ty anyway
> 
> Did you find any solution for live streams?
i have no choice except record with obs

**Comment by ScrubN** [comment]
This was discussed further in #400. You can try using one of the solutions suggested by Zibbp or glubsy.
