### ISSUE TITLE
Record Live Streams

### ISSUE THREAD

**Issue by N0itx** [lay295/TwitchDownloader#891]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

I'm really pleased with this program as it works flawlessly. However, with Twitch's new rules regarding VODs, where audio is disabled due to copyright issues, it would be incredible if this program could record live streams that don't have VODs, either due to copyright reasons or compliance with laws, such as those in Korea.

**Comment by ScrubN** [comment]
Duplicate #721.
With how Twitch is stripping more and more data from VOD chats, we may have to implement recording live chats as well.
