### ISSUE TITLE
Less Command Output

### ISSUE THREAD

**Issue by goldbattle** [lay295/TwitchDownloader#90]
First, thanks again for the great library and CLI! I am calling from a script it would be a lot nicer if the progress output used `\r`  carriage returns to just overwrite the progress output without appending a new line every time. Right now it looks like this for me:
```
[STATUS] - Rendering Video 99% (0h0m12s left)
[STATUS] - Rendering Video 99% (0h0m11s left)
[STATUS] - Rendering Video 99% (0h0m10s left)
[STATUS] - Rendering Video 99% (0h0m9s left)
[STATUS] - Rendering Video 99% (0h0m8s left)
[STATUS] - Rendering Video 99% (0h0m7s left)
[STATUS] - Rendering Video 99% (0h0m6s left)
[STATUS] - Rendering Video 99% (0h0m5s left)
[STATUS] - Rendering Video 99% (0h0m4s left)
```
Where in reality it would be nice to have this all just printed on top of the same line.

**Comment by lay295** [comment]
This will definitely be something that will be changed in the next release. I just wanted to push out the CLI and did it a bit lazily.
