### ISSUE TITLE
Clip downloader won't finish "encoding clip metadata"

### ISSUE THREAD

**Issue by cepe0** [lay295/TwitchDownloader#905]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Unsure

### Describe your issue here

Whenever i try to download i clip i get this error: ERROR: The process cannot access the file 'D:\videoklipp\clips\jajajaja\TwitchDownloader\clip_1701170298162_w0hlwkzb.fp1' because it is being used by another process.

What is this caused by?

**Comment by ScrubN** [comment]
Could you please go to the settings of the application and enable _Verbose Errors_? That will pop up a box with more information needed to diagnose the issue.

**Comment by cepe0** [comment]
Heres a image of it
![bild](https://github.com/lay295/TwitchDownloader/assets/152277896/364c5866-f3f6-4d10-8514-7e8214fc9a43)

**Comment by ScrubN** [comment]
I was able to fix this yesterday. A new release should be out soon, however if you're impatient you can find the link to a workflow build in #906

**Comment by cepe0** [comment]
great work!

**Comment by cepe0** [comment]
I updated it today but still doesnt work. Was todays update regarding something else?

**Comment by KamasamaK** [comment]
I also have the new update, v1.53.6, and am getting this same error.

Specifically, when I have "Encode Metadata" checked, it stays stuck at "Encoding Clip Metadata 0%". Then, when I finally Cancel, I get the following error:

![image](https://github.com/lay295/TwitchDownloader/assets/22951521/e3034d31-d25d-4817-9a3f-9c662b531eee)

Some additional information:
- This does not occur when I have "Encode Metadata" unchecked. It works fine then.
- I am not using the Queue.

Interestingly, when I **close** the Twitch Downloader application after this error occurs, it DOES actually seem to finish encoding the metadata. The file it created will not render until the application is closed so it can finish.

**Comment by KamasamaK** [comment]
> How do u "uncheck" encode metadata? Im not using queue as well

You simply click the checkbox to the right of "Encode Metadata" to toggle it. The default is being checked.

![image](https://github.com/lay295/TwitchDownloader/assets/22951521/0452b62b-5055-4f83-b5cb-656ed01129b8)

**Comment by cepe0** [comment]
oh wow, i was looking in settings, thanks!
