### ISSUE TITLE
Clips get stuck at 100% - never finish and then when I cancel it, it gives this error.

### ISSUE THREAD

**Issue by brettsloan** [lay295/TwitchDownloader#906]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

I paste in all my clip links (About 15).
I am only downloading the videos, not chat.
I set all the Parallel Task Limits to 1.

Everything seems fine but the video gets stuck at 100% (I waited while testing for over an hour) and doesn't move on to the next clip in the queue.

When I hit cancel, it shows that the download failed.
When I click the error button, this comes up (Verbose errors are on).

![image](https://github.com/lay295/TwitchDownloader/assets/25353203/6d36dec6-d00a-454a-918e-386a200cf1b1)

I'm pretty computer savvy but I couldn't understand what was being used to prevent it from downloading.
Maybe I'm doing something wrong.

Any help or tips is greatly appreciated.

### Add any related files or extra information here

This is the first clip in the list but they all did the same thing. 
https://www.twitch.tv/inabox44/clip/ObliviousFastFoxRalpherZ-HbbK2blKzipiYDGt?featured=false&filter=clips&range=all&sort=time

**Comment by ScrubN** [comment]
Thank you for mentioning that the problem is related to the task queue. None of the other reports have mentioned this.

**Comment by ScrubN** [comment]
Can you please see if the workflow build from [github.com/lay295/TwitchDownloader/actions/runs/7025281065](https://github.com/lay295/TwitchDownloader/actions/runs/7025281065) solves your issue?

**Comment by brettsloan** [comment]
Going to try it now. I originally downloaded the GUI one so I'll test that first.

**Comment by brettsloan** [comment]
The issue seems to persist even in the new build

Screenshot 1 of everything going well but this is where it stays. It's been about 5-10 minutes now and it should definitely be done. 
![image](https://github.com/lay295/TwitchDownloader/assets/25353203/1855b279-b444-4551-ab14-ae4449437089)

Second screen shot is of me hitting cancel - it says Status: Failed and the next one begins
![image](https://github.com/lay295/TwitchDownloader/assets/25353203/30effe22-477d-46d3-a8ca-619b50ed9cc9)

and here's the error:
![image](https://github.com/lay295/TwitchDownloader/assets/25353203/aa190ac4-0a03-40d0-bc8a-c588fdc8e24b)

**Comment by ScrubN** [comment]
It's times like these where I wish the task queue showed the exact status of what is happening...

Can you test if it happens outside of the task queue too?

**Comment by brettsloan** [comment]
I'll try now.

So the download was quite quick but it's been stuck on the metadata portion for about 2 minutes without moving at all.
Looks like that might be the culprit
![image](https://github.com/lay295/TwitchDownloader/assets/25353203/d4714927-5188-4fb3-bb84-f822fbff692b)

**Comment by brettsloan** [comment]
Tried with 'Encode Metadata' turned off and it just gave me this error
![image](https://github.com/lay295/TwitchDownloader/assets/25353203/b358e6a5-411c-420e-8b13-3f2fde836044)

**Comment by ScrubN** [comment]
> Tried with 'Encode Metadata' turned off and it just gave me this error ![image](https://private-user-images.githubusercontent.com/25353203/286422024-b358e6a5-411c-420e-8b13-3f2fde836044.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMTIxOTksIm5iZiI6MTcwMTIxMTg5OSwicGF0aCI6Ii8yNTM1MzIwMy8yODY0MjIwMjQtYjM1OGU2YTUtNDExYy00MjBlLThiMTMtM2YyZmRlODM2MDQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDIyNTEzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5NDIyNzdjOTFmYmE4N2I1OTgzNzBiNDhmYTkzYzFjOWY0Y2NjZTI1ZTE4MDQzZmMyMmM0ZjNlNmI1OWQ5MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tBQdd4VxdplX4rxpvqBLOx1a0qaxM2AxhWobm4tuB7w)

Check task manager for any open instances of ffmpeg.exe. If you find any, kill the processes then try again.

**Comment by brettsloan** [comment]
funnily enough, I just closed/reopened everything and re-tried with metadata turned off and it seems like it worked!
Not sure about the 0% thing in the lower right hand corner

![image](https://github.com/lay295/TwitchDownloader/assets/25353203/e1647e20-17a4-427b-b32d-f5fecb898074)


Clip is in the appropriate area in 1080p so that's amazing.
Maybe add an Encode Metadata checkbox for the queue as well?

**Comment by ScrubN** [comment]
It seems there is a bug in .NET that leads to a lockup when calling `process.WaitForExitAsync()` after a process has already exited. The reason the process has already exited is more than likely because FFmpeg could not be started.

I will push another commit that should fix the issue but it would be nice if you could still test it for me.

**Comment by brettsloan** [comment]
I will gladly! Should I try manually opening FFmpeg while it's running?

**Comment by ScrubN** [comment]
The new workflow build will be at https://github.com/lay295/TwitchDownloader/actions/runs/7025711638 shortly.

**Comment by brettsloan** [comment]
Got the new version, went straight into the queue after setting preferred paths and options.
Seems to be working like a charm now! 
They go to 100%, say finished and then move on.
![image](https://github.com/lay295/TwitchDownloader/assets/25353203/40b0c1d1-260e-4530-a588-3c73bb3ac0f2)


my issue has been fixed :)

**Comment by ScrubN** [comment]
> Maybe add an Encode Metadata checkbox for the queue as well?

I really want to rework the entire UI so we don't have to deal with multiple ways of queuing, but maybe I'll consider changing some things.

**Comment by brettsloan** [comment]
Sounds good! let me know if you need a tester for stuff LOL
