### ISSUE TITLE
Taskbar icon is now constantly flashing

### ISSUE THREAD

**Issue by Racoon8** [lay295/TwitchDownloader#909]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

Since updating to 1.53.6 the taskbar icon is now constantly flashing. I'm using Win10

**Comment by ScrubN** [comment]
Are you able to provide a video of the issue? It should stop when the window regains user focus.

**Comment by Racoon8** [comment]
User error. I manually uninstalled, rebooted, re-installed and now it's gone. Sorry!

**Comment by ScrubN** [comment]
Actually, I managed to accidentally reproduce the issue once while testing something unrelated.

**Comment by ScrubN** [comment]
Fixed a2280bbe8690ec3aa255824906eb33ffa20bc31e
