### ISSUE TITLE
Zip unpacker is marked with trojan? (Avast antivirus)

### ISSUE THREAD

**Issue by MrDummyNL** [lay295/TwitchDownloader#911]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

When i want let it update the program, suddenly Avast give me warning the zip tool has trojan on it.
Might false positive, but i just post here because it will happens to others with Avast.

(i downloaded zip package so i can bypass the problem)

### Add any related files or extra information here

Is this false positive? Please confirm it.

**Comment by ScrubN** [comment]
`ZipExtractor.exe` is part of [AutoUpdater.NET](https://github.com/ravibpatel/AutoUpdater.NET), the library we use for automatic updates, so it is very likely that the trojan is a false positive.
The version of ZipExtractor shipped with the most up-to-date version of AutoUpdater.NET is no longer flagged as malicious on virustotal, so this hopefully will not happen again: https://www.virustotal.com/gui/file/a76c4d20c78a6b0e563567a215e14a05525c316bf4eb92e7d11de7e24ae0b7c2
