### ISSUE TITLE
rendering 3rd party emotes

### ISSUE THREAD

**Issue by fkagune222** [lay295/TwitchDownloader#913]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Unsure

### Describe your issue here

when i download chat and check both embed images and third party emotes , twitch emotes show but 3rd party emotes dont

**Comment by ScrubN** [comment]
I can confirm that 3rd party emotes (in this case 7TV) are working for chat download embedding
![image](https://github.com/lay295/TwitchDownloader/assets/72096833/ee33a9b7-8ee5-4417-9cd5-3ea556a4678b)

And both 1st party and 3rd party emotes are showing in the chat render (rendered offline with embedded data only)
![image](https://github.com/lay295/TwitchDownloader/assets/72096833/1f95888d-502f-4765-b662-e7e924122837)

**Comment by ScrubN** [comment]
Closing due to stale
