### ISSUE TITLE
ERROR: Response status code does not indicate success: 403 (Forbidden).

### ISSUE THREAD

**Issue by GaspacoZanis** [lay295/TwitchDownloader#928]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Unsure

### Describe your issue here

After downloading the latest version, I get the issues which says in the log 'ERROR: Response status code does not indicate success: 403 (Forbidden).', whenever I try to get the ID of new VODs. Example, like this : https://www.twitch.tv/videos/2023591074

It just says that it is Unable to get video information.

### Add any related files or extra information here

2023591074

**Comment by CatDany** [comment]
Getting the same error on 1.53.7. Enabled verbose error output. Hope this helps

<img width="445" alt="Screenshot 2024-01-06 at 03 55 22" src="https://github.com/lay295/TwitchDownloader/assets/6011088/6b5036ee-a028-4143-a61a-f7bd588ad850">

**Comment by Dking07** [comment]
same error here

**Comment by ScrubN** [comment]
Twitch changed some API related things. This is effectively a repeat of #676.

CC @lay295

**Comment by peterzee123** [comment]
same here!

**Comment by pb243** [comment]
Longtime user, first time commenter. I'm also getting the same issue, and even if I use the EditThisCookie extension and enter my authorization code (this is for a channel I am subscribed to), I receive this error message.

**Comment by cjsahlen** [comment]
Same here, I get problems with Versions 1.53.7, 1.53.6,1.53.5,and 1.53.4.

**Comment by Cundoo** [comment]
Getting the same when running the macOS version: STATUS] - Fetching Video Info [1/5]Unhandled exception. System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 403 (Forbidden).)

**Comment by umNeo** [comment]
I'm using CLI and I get this error with this error:
![image_2024-01-05_195124491](https://github.com/lay295/TwitchDownloader/assets/84542835/fc7b3b70-3e5a-4df1-be20-bfd9c30525c6)

Hope this helps fix it.

**Comment by captainrice** [comment]
Same issue here

**Comment by bigmoochie** [comment]
Long time user. Also got the same error:  ERROR: Response status code does not indicate success: 403 (Forbidden).
Just started today with the current version and the previous.

**Comment by lay295** [comment]
Give [1.53.8](https://github.com/lay295/TwitchDownloader/releases/tag/1.53.8) a try

**Comment by bigmoochie** [comment]
Thank you for the quick update.

**Comment by pb243** [comment]
Thank you! Can confirm that the issue is also fixed in 1.53.9.
