### ISSUE TITLE
Sequence contains no elements

### ISSUE THREAD

**Issue by ranamerp** [lay295/TwitchDownloader#930]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

When trying to download VOD, the program is failing at the first step within 2 seconds. This is the screenshot I have of the error: 
![image](https://github.com/lay295/TwitchDownloader/assets/16456327/7a61b779-4a60-4265-a336-a3c0d3710005)

I have verified that the VOD is accessible publicly, with a check logged in and logged out. I also have tried a different VOD, and ran into the same issue. 

### Add any related files or extra information here

VODs tested: 
https://www.twitch.tv/videos/2023965129
https://www.twitch.tv/videos/2020020261

**Comment by ScrubN** [comment]
Duplicate #928
