### ISSUE TITLE
Unable to get video information. Please make sure the Link/ID is correct and try a gain.

### ISSUE THREAD

**Issue by tuanict** [lay295/TwitchDownloader#931]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Command Line Interface

### Describe your issue here

I had this problem with the new version 1.53.7. While on other computers the old version still works fine.
![11](https://github.com/lay295/TwitchDownloader/assets/155794205/9064f330-5af4-4134-a4c3-674e2a5d023a)

**Comment by captainrice** [comment]
Same issue here

**Comment by ScrubN** [comment]
duplicate #928
