### ISSUE TITLE
Task Queue VOD downloads fail

### ISSUE THREAD

**Issue by Th3irdEye** [lay295/TwitchDownloader#932]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

Looks like VOD downloads are fixed in v1.53.8 and I can successfully download a VOD via an ID. If I try to run downloads through the Task Queue menu however, they always fail with the error "Object reference not set to an instance of an object."

**Comment by ScrubN** [comment]
I could've sworn I tested that

**Comment by ScrubN** [comment]
Fixed [1.53.9](https://github.com/lay295/TwitchDownloader/releases/tag/1.53.9)
