### ISSUE TITLE
VOD Download problem (29.991 FPS)

### ISSUE THREAD

**Issue by GodRichy** [lay295/TwitchDownloader#933]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates

### Write stuff here

![LL6uh7IlOy0](https://github.com/lay295/TwitchDownloader/assets/38027213/75db4125-607b-4ab8-a07e-fd62b22a1c67)

What can I do to download this video? Or is this a problem on the part of the streamer/streamer?
Thx.

**Comment by ScrubN** [comment]
Please provide your VOD id

**Comment by GodRichy** [comment]
> Please provide your VOD id

videos/2023433537

**Comment by ScrubN** [comment]
I hate to say it, but I'm unable to reproduce your issue. Could you try fetching the video info again?

**Comment by GodRichy** [comment]
> I hate to say it, but I'm unable to reproduce your issue. Could you try fetching the video info again?

Omg. It's working now. Although I didn't change anything. The latest version of your program.

But thanks. I hope this problem will not occur again.

**Comment by ScrubN** [comment]
> I hope this problem will not occur again.

From the error message, it seems like it should have parsed just fine. I really don't know what the problem was. I'm glad it works now though

**Comment by GodRichy** [comment]
> > I hope this problem will not occur again.
> 
> From the error message, it seems like it should have parsed just fine. I really don't know what the problem was. I'm glad it works now though

This problem occurs when using the Russian localization of the application. Everything works stably in English.

Now such an error has occurred again, already when trying to download, and not trying to get information.

![2wlKgJJAQM2Q](https://github.com/lay295/TwitchDownloader/assets/38027213/af8bcd8d-18a4-4bca-bcbf-abe46bfc9638)

**Comment by ScrubN** [comment]
That makes so much sense. I will go ahead and fix it but I don't really want to release a 4th update in one day, so I will point you to the workflow build when it is ready

**Comment by ScrubN** [comment]
The workflow build of the patch can be found here: https://github.com/lay295/TwitchDownloader/actions/runs/7434637911
