### ISSUE TITLE
when i run ./TwitchDownloaderCLI ffmpeg --download it gives me an error (see image)

### ISSUE THREAD

**Issue by ComfortableMilk4454** [lay295/TwitchDownloader#944]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates

### Write stuff here

<img width="544" alt="image" src="https://github.com/lay295/TwitchDownloader/assets/43555540/9f3fec75-023a-4244-9445-f175f0af795f">

**Comment by ComfortableMilk4454** [comment]
& when i follow the directions and run sudo chmod +x ffmpeg and then try it again the same error returns:
<img width="682" alt="image" src="https://github.com/lay295/TwitchDownloader/assets/43555540/7682ae51-13b7-44f3-8d71-61b1622bf23d">

**Comment by ComfortableMilk4454** [comment]
nvm i fixed it by running chmod +x ffmpeg. idk why that fixed it tho lol as i installed it using twitchdlder not as a standalone file.

**Comment by ScrubN** [comment]
This looks to be working as expected
