### ISSUE TITLE
Downloading videos stuck on 99%

### ISSUE THREAD

**Issue by George620** [lay295/TwitchDownloader#95]
The video files are all downloaded, but downloading not go to step 2/3 and 3/3, so I cannot get full video. Please patch this glitch.
PS: I cropped the videos. Tried on 5 videos w/ cropping, stuck on 4/5.

**Comment by lay295** [comment]
A screenshot of the VOD and crop settings would be useful so I can reproduce it easier

**Comment by Adam-Saeed** [comment]
I guess the problem is general for any type of settings, It's present in version 1.37 but any version lower than that doesn't have it.

**Comment by George620** [comment]
> I guess the problem is general for any type of settings, It's present in version 1.37 but any version lower than that doesn't have it.

Are you really sure? I tried on 1.36, same problem.

**Comment by lay295** [comment]
I reverted the change in 1.37, and I'm able to crop fine. Again, a screenshot of a specific VOD and cutting times might help me reproduce it if it wasn't because of the changes in 1.37

**Comment by George620** [comment]
ID of video: 804823708
Cropping times: 5:59:00 to the end
Quality: 720p

**Comment by George620** [comment]
One of the video that won't work.

**Comment by George620** [comment]
So, downloaded another video with cropping, same thing. Version 1.38.

**Comment by lay295** [comment]
I downloaded with the previously mentioned vod and crop settings fine. Have you tried just leaving the program open for a while and seeing if an error pops out?

**Comment by George620** [comment]
I tried to. Waited 1 hour in one video and nothing happened.

**Comment by ScrubN** [comment]
It looks like this issue has since been resolved
