### ISSUE TITLE
i can't dowload "Unable to get video information Please make sure the Link/ID is correct and try again."

### ISSUE THREAD

**Issue by chikkatua01** [lay295/TwitchDownloader#950]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates

### Write stuff here

![Screenshot 2024-01-19 115613](https://github.com/lay295/TwitchDownloader/assets/157091212/f5af8495-bffc-4b2a-8c9b-915842afc552)

How can I fix it?

**Comment by ScrubN** [comment]
Twitch changed the request behavior, but the video is only available to subscribers.

Please give the program an OAuth token from a Twitch account that is subscribed to the channel. You can hover over the `(?)` for more information about OAuth tokens.

**Comment by chikkatua01** [comment]
how can i login account ?

**Comment by ScrubN** [comment]
If you click the `(?)`, it should show you a youtube video on how to get your account OAuth token using a browser extension. If you do not want to use a browser extension however, you can try following the instructions in this comment: https://github.com/lay295/TwitchDownloader/issues/943#issuecomment-1890777308

**Comment by mambans** [comment]
Same error here and its not about the Oauth token. Vod is public and also try with Oauth token.

**Comment by taimi7364** [comment]
This works fine to me (
![image](https://github.com/lay295/TwitchDownloader/assets/129487272/fe417a5e-384a-4808-9649-64b82b7bd661)
), it could be region block or something else.

**Comment by mambans** [comment]
> This works fine to me ( ![image](https://private-user-images.githubusercontent.com/129487272/299015661-fe417a5e-384a-4808-9649-64b82b7bd661.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMjcwMjUsIm5iZiI6MTcwNjAyNjcyNSwicGF0aCI6Ii8xMjk0ODcyNzIvMjk5MDE1NjYxLWZlNDE3YTVlLTM4NGEtNDgwOC05NjQ5LTY0YjgyYjdiZDY2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QxNjE4NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTczMjllMTA5YjllNGU1ZDkzMmExMjUyN2I4NGQ4ZTM1YmYzMTdjMjkwZTgzZWVkYzY2YTk2YWVlODA5Y2RjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7Ws0M-kF8pV5rvYhhdisiQJvhHGxgAJqADO4J5R1pI8) ), it could be region block or something else.

Interesting, I tried your video 2026098160 and I still got the same error so that might be true. I doubt toeiii have blocked Europe/Sweden himself. Maybe Twitch have done something or ..  ;/

**Comment by ScrubN** [comment]
> Interesting, I tried your video 2026098160 and I still got the same error so that might be true. I doubt toeiii have blocked Europe/Sweden himself. Maybe Twitch have done something or .. ;/

Have you rebooted your computer recently? Are you using a proxy or non-standard DNS setup?

**Comment by mambans** [comment]
> > Interesting, I tried your video 2026098160 and I still got the same error so that might be true. I doubt toeiii have blocked Europe/Sweden himself. Maybe Twitch have done something or .. ;/
> 
> Have you rebooted your computer recently? Are you using a proxy or non-standard DNS setup?

Ohhh, Your are right! It was my VPN. Thanks for the help! 

Sry for bumbing this issue when it was my own fault.
