### ISSUE TITLE
Program doesn't download source quality VOD when max resolution is 720p

### ISSUE THREAD

**Issue by theonethetron** [lay295/TwitchDownloader#952]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

I tried downloading a VOD of a stream that was streamed in 720p. When I use the program to download the VOD, there is no option for source quality, the highest quality option shown was 720p. The VOD the program downloaded was of a significantly lower bitrate and quality than the source VOD (which I downloaded by manually obtaining the m3u8). However, I noticed that the program showed the filesize of the source quality VOD in the quality selector next to the 720p option even though it downloaded a file that was about half that size.

### Add any related files or extra information here

Here is the VOD id if it helps: 2038563622

**Comment by ScrubN** [comment]
This VOD is a little strange, it seems to have two different 720p30 streams that are different bitrates which I have never seen before. Twitch has been making weird changes to their M3U8 generator, so sometimes the higher bitrate stream is parsed as just "720p" while the lower bitrate stream is "720p30", and other times they are both "720p30".

I can fix the ordering to make the higher bitrate the top priority, but I really don't want to give up the nice quality strings. Maybe I'll think of something.

**Comment by ScrubN** [comment]
Apparently this isn't as uncommon as I thought? A stream I was just watching had the exact same issue with the same quality twice but in different bitrates.
