### ISSUE TITLE
Error Updating Old Chat Files

### ISSUE THREAD

**Issue by TheMadog24** [lay295/TwitchDownloader#959]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

Trying to update an old chat file from July 2022, (Old, I know).
I assume the program has changed the file structure enough that it can't figure out the old structure to update it or something.

Anyway,
I keep getting the same error `ERROR: Value cannot be null. (Parameter 'source')` on `Updating Video Info [1/3]`
Updating a JSON to a JSON, no compression, no crop, Replace Embed and Embed Missing have the same results.

The program just freezes, and loads infinity, I have to close it to do anything else.

### Add any related files or extra information here

File I am working with:
[Error Example File.zip](https://github.com/lay295/TwitchDownloader/files/14074546/Error.Example.File.zip)
Had to ZIP, because the unzipped file was 71MBs

**Comment by ScrubN** [comment]
Fixed 👍

I will release an update soon since there's a few other improvements waiting to be released.

**Comment by ScrubN** [comment]
I just noticed there is more missing information that can be recovered from this old chat file. Expect another commit soon.

**Comment by ScrubN** [comment]
#960 Improves chat upgrading even more, as well as fixes an issue where the first commenter would sometimes be incorrectly identified as the streamer if there was not already a streamer value present.

**Comment by TheMadog24** [comment]
Thank you! I am in no rush, so I look forward to this release.
