### ISSUE TITLE
Kick support - failed to finalize video

### ISSUE THREAD

**Issue by joshmcorreia** [lay295/TwitchDownloader#962]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

I built the kick-support branch from source on Windows 11 and I can successfully get it to see videos but I haven't been able to successfully download any videos.

![image](https://github.com/lay295/TwitchDownloader/assets/86431308/381a5956-281d-4f1e-b3d5-fddfe34bce22)

Log message:
```
1 errors were encountered while downloading: Video part 0.ts failed after 10 retries at DownloadVideoPart
Failed to finalize video (code 1), retrying in 10 seconds...
Failed to finalize video (code 1), retrying in 10 seconds...
ERROR: Failed to finalize video. The download cache has not been cleared and can be found at C:\Users\JoshCorreia\AppData\Local\Temp\TwitchDownloader\ca5c695b-5ca4-4e03-b4b5-3b20752ff865_1706515385082 along with a log file.
```

Is there anything I can do to fix this? I tried it on multiple videos and it fails every time.

Thank you!

---
# Download cache files:

ffmpegLog.txt:
```
C:\Users\JoshCorreia\AppData\Local\Temp\TwitchDownloader\ca5c695b-5ca4-4e03-b4b5-3b20752ff865_1706515385082\output.ts: Invalid data found when processing input
C:\Users\JoshCorreia\AppData\Local\Temp\TwitchDownloader\ca5c695b-5ca4-4e03-b4b5-3b20752ff865_1706515385082\output.ts: Invalid data found when processing input
```

metadata.txt:
```
;FFMETADATA1
title=NIGHT STREAM -> WAKING UP -> CHILL -> GAMES WITH JESSE PROB -> BE BACK LATER ALSO (ca5c695b-5ca4-4e03-b4b5-3b20752ff865)
artist=xqc
date=2024
comment=Originally aired: 2024-01-05 21:08:20Z\
Video id: ca5c695b-5ca4-4e03-b4b5-3b20752ff865\
Views: 1
```

outputs.ts is an empty file

### Add any related files or extra information here

https://kick.com/video/ca5c695b-5ca4-4e03-b4b5-3b20752ff865

**Comment by ScrubN** [comment]
Kick has been changing their API at a very fast rate, so download kick videos is currently not supported.

**Comment by joshmcorreia** [comment]
> Kick has been changing their API at a very fast rate, so downloading kick videos is currently not supported.

Damn that sucks. Thank you!
