### ISSUE TITLE
Not able to download / re-download vod if it has same name

### ISSUE THREAD

**Issue by MrDummyNL** [lay295/TwitchDownloader#968]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

I have some streams that was stopped midway and restarted again. This result in two vods with exact same name.
But program has one problem: it will ignore next download if it found same name and will not finish the job (it just say its finished -nothing added).
Re-download vod is also problem, it will also just finish it early without generate a vod and text chat file.

### Add any related files or extra information here

Here my possible checkpoints:
- verify the video time (if it found same vod name) so it will know it has another video length.
- rename the filename with (2) behind as rename.
- so it will download another vod and make video file without stop it too early with finished.
- option to force download vod
- can give you question with [rename] or [overwrite] if it found same vod name file.

Right now i must go to other pc to download another vod. Because program just refuse to download it (again). The download itself is running but it will not finish it correctly.

**Comment by ScrubN** [comment]
I'm not sure I entirely understand the issue you are describing, however I am not opposed to allowing the user to choose between rename and overwrite. As a temporary solution I added `{random_string}` as a filename parameter some months ago, but I think its about time I implement a real solution.

**Comment by superbonaci** [comment]
Some streams are cut in several pieces so they are not very long. Basically they all have same title and description, but different ID and were started at different time.

Relying on the title to tell one stream apart from another is not reliable.

**Comment by superbonaci** [comment]
Save the file as `ID_Title.mp4` and not `Title.mp4`.
