### ISSUE TITLE
Unable to Render Chat

### ISSUE THREAD

**Issue by OrionRedStar** [lay295/TwitchDownloader#969]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

I'm running into an error when rendering a couple of downloaded chats. Note that I tried rendering it on 3 different versions (1.53.0, 1.53.4, and the latest, 1.54.0) and they all ran into an error. I'll include an image of the error. I assume it's the same error for all the versions, but here's the one for the latest version. Please let me know if you need any additional information.
![Temp2](https://github.com/lay295/TwitchDownloader/assets/159993626/a762a842-6555-4458-9045-14e558b2aed1)

### Add any related files or extra information here

The IDs are 1783466626 and 1783559522, but the videos have been taken off of Twitch for a several months by now.

**Comment by ScrubN** [comment]
It looks like one of the third party emote providers (bttv, ffz, or 7tv) is declining your request.

If you are using a proxy or VPN try disabling it. If it still throws error code 552, then your location might be being blocked and you will just have to disable whichever emote provider is causing the error.

**Comment by OrionRedStar** [comment]
Looks like 7tv was the culprit, thanks!
