### ISSUE TITLE
Windows defender detects Trojan:Win32/Znyonm in TwitchDownloaderCLI-1.54.0-Windows-x64.zip 

### ISSUE THREAD

**Issue by ArdianaLeek** [lay295/TwitchDownloader#976]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates

### Write stuff here

This only seems to happen for 1.54.0 and not 1.53.5 - 1.53.9
link to virus total scan: https://www.virustotal.com/gui/file/95a1b0f7a5950ffd976fa62b95107393d2126f43966a7df53d7a8893f857d78b

**Comment by ScrubN** [comment]
Windows defender probably doesn't like the reverse proxy for windows 7 users. You can view the code difference from 1.53.9 -> 1.54.0 for yourself and see that there were very few changes https://github.com/lay295/TwitchDownloader/compare/1.53.9...1.54.0

**Comment by ScrubN** [comment]
1.54.1 is no longer detected by Fortinet, however windefender timed out. Hopefully when defender eventually catches up, it won't give the false positive.

https://www.virustotal.com/gui/file/982fcb62a6917659b7143d53e39a4184b56dcb558d34c7008e2603d8c57f6a89?nocache=1

**Comment by ScrubN** [comment]
Windows defender on my machine does not think 1.54.1 is a trojan.
