### ISSUE TITLE
How to download Subscriber-Only VoDs?

### ISSUE THREAD

**Issue by holeekebab** [lay295/TwitchDownloader#979]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates

### Write stuff here

Just as the title says.

How can I download VoDs that are for Sub-Only people? :)

**Comment by ScrubN** [comment]
Please see if https://github.com/lay295/TwitchDownloader/issues/943#issuecomment-1890777308 answers your question

**Comment by holeekebab** [comment]
Im gonna be honest, I dont know what I should do :D

Im not that good when it comes to IT

**Comment by superbonaci** [comment]
But are you a subscriber to that channel?

**Comment by holeekebab** [comment]
Yea I am

**Comment by superbonaci** [comment]
If you are a subscriber you can download any video by using your twitch OAUTH token, did you try that already?

```
TwitchDownloaderCLI videodownload -u video_id -q best --temp-path './TMP' --oauth yout_oauth -o output.mp4
```

**Comment by holeekebab** [comment]
I dont know how I setup Twitch 0AUTH token thats the thing :D

**Comment by ScrubN** [comment]
OAuth is the authorization technology that Twitch uses and an OAuth token is the value that lets you authenticate with Twitch servers. By providing the token to this program, it lets the program authenticate with Twitch servers to access subscriber only videos. The OAuth token is not used anywhere else in the program.

You can find the OAuth token for your current login session on Twitch with cookie inspector browser extensions or by using the browser's dev tools. You can find a guide on how to get your auth token using a browser extension here: https://www.youtube.com/watch?v=1MBsUoFGuls.

**Do not share your OAuth token with anyone. If you accidentally send it anywhere, change your password immediately to invalidate the token.**

**Comment by holeekebab** [comment]
Thanks! didnt really know how to properly google for a guide this helps a lot!

**Comment by Albabit** [comment]
Hi all,
Sorry to re-open this, but just a clarification please :
With dev tools, is the "OAuth token" we're searching for, is named as the "auth-token" in the cookies ?
Thank you.

Also, I'm using Firefox extension "TwitchNoSub" to access Sub-Only VODs for free, do you think there is a way to use TwitchDownloader by taking advantage of the VODs access provided by this extension?

Best regards.

**Comment by superbonaci** [comment]
@Albabit yes it's that auth token. For sub only use https://github.com/DmitryScaletta/twitch-dlp

**Comment by LavenderMP** [comment]
> [@Albabit](https://github.com/Albabit) yes it's that auth token. For sub only use https://github.com/DmitryScaletta/twitch-dlp

Big W bro!
