### ISSUE TITLE
Can't render chat

### ISSUE THREAD

**Issue by loomkoom** [lay295/TwitchDownloader#98]
I'm getting an error when trying to render chat from the json file:
`ERROR: Cannot start process because a file name has not been provided.`

I've tried turning off embed emotes when making the json, using another vod link,  changing file format, using mask or background color, changing file name. Same error remains

**Comment by lay295** [comment]
Yeah, was a bug in original 1.38. I fixed it but didn't wanna do another release so I just updated the binary. Redownload and it should work.

**Comment by loomkoom** [comment]
yup works fine now, thx
