### ISSUE TITLE
Queue issue

### ISSUE THREAD

**Issue by krowgoat** [lay295/TwitchDownloader#990]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates

### Write stuff here

Just downloaded this after I found out that TwitchLeecher died. How does the Task Queue work? I looked up a streamer and selected a video to download. It did its work, but, just hung at 100% (kept saying "running"). The file is there in the folder I put it in, but it's nothing. What did I do wrong? Also, if I try to delete whatever was downloaded, it says I can't because it's open in ffmpeg. If I restart my computer, I can delete it.  What am I doing wrong? (Apologies ahead if I'm an idiot.) Thanks!

**Comment by superbonaci** [comment]
Because probably it's converting output.ts to output.mp4?

**Comment by krowgoat** [comment]
So, just wait for a while until it's done?

**Comment by krowgoat** [comment]
FWIW, yup. Waiting did the trick. Should've been more patient.

**Comment by superbonaci** [comment]
You had the issue because the last step does not display percentage:
```
[STATUS] - Finalizing Video... [5/5]
```
This is because there are cases where the percentage is above 100% or below 0% so it displays the 3 dots all the time instead.

Maybe the program should calculate the percentage based on file size instead the current way. A new bug has been submitted: https://github.com/lay295/TwitchDownloader/issues/991

**Comment by ScrubN** [comment]
> It did its work, but, just hung at 100% (kept saying "running").

This is strange, when the percent issue occurs its supposed to report 0% instead of 100%.

**Comment by krowgoat** [comment]
Agreed. If it did while it was converting, that would be a nice step.

**Comment by superbonaci** [comment]
@krowgoat maybe that's an issue with the specific ID. if you could tell which one it was.

**Comment by krowgoat** [comment]
Do you mean which Twitch streamer?

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by superbonaci** [comment]
@krowgoat we've found the issue happens with all videos. https://github.com/lay295/TwitchDownloader/issues/991
