### ISSUE TITLE
worst quality parameter does not work

### ISSUE THREAD

**Issue by superbonaci** [lay295/TwitchDownloader#992]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Unsure

### Describe your issue here

Try to download worst audio+video:
```
TwitchDownloaderCLI videodownload -u 2065608792 -q worst -e 16 -o worst.mp4
```
It downloads 1080p60 instead of 160p (which is the worst in this case).

**Comment by ScrubN** [comment]
"worst" is not a supported keyword. The only supported keywords are
"source," "chunked," and "audio."

**Comment by superbonaci** [comment]
I've just realized that. I'll add it to the PR.

**Comment by ScrubN** [comment]
I don't see any practical use for a "worst" keyword.

**Comment by superbonaci** [comment]
I use it to do some ffmpeg tests with very long videos, so I don't have to manually check what's the minimum resolution available for each ID.
