### ISSUE TITLE
Is there any 140p Twitch stream? (not 1440p)

### ISSUE THREAD

**Issue by superbonaci** [lay295/TwitchDownloader#993]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates

### Write stuff here

I've seen the screenshot of Windows WPF where the quality 144p (not 1440p) is available to choose. Is there any Twitch video at such resolution? I thought the minimum resolution to be 160p. I know that IPTV transmissions can have that quality, but never heard about Twitch. Maybe it existed before but was removed?

![image](https://private-user-images.githubusercontent.com/72096833/298797190-1cddaafd-77f6-4fe6-a207-54297ab64b31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NTMxOTEsIm5iZiI6MTcxMDc1Mjg5MSwicGF0aCI6Ii83MjA5NjgzMy8yOTg3OTcxOTAtMWNkZGFhZmQtNzdmNi00ZmU2LWEyMDctNTQyOTdhYjY0YjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDA5MDgxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0M2EyN2EyN2JjMTQ5Y2M5NzlhMTQ0MGQwYjliNWY1ZjA5MWUwMzg0ZDk5NDAyMDljODMxOWQxMzg1MjM3NzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IEi53_jBBpGIWZjH3140rXtXUr04LZ_12QIoByTx4vI)

https://github.com/lay295/TwitchDownloader/pull/955

**Comment by ScrubN** [comment]
Here is a video that is available in 144p: https://www.twitch.tv/videos/123456789
