### ISSUE TITLE
Add `Audio Only` & `Worst` options to task queue preferred quality

### ISSUE THREAD

**Issue by ScrubN** [lay295/TwitchDownloader#994]
Please add "Audio Only" option to the task queue.

_Originally posted by @ZeusLT in https://github.com/lay295/TwitchDownloader/issues/955#issuecomment-1983985427_
            

Prerequisites:
- [x] Do not hard code enqueuer file extension
- [x] Figure out keywords for the clip downloader (preferred), or hide certain options when enqueuing clips

**Comment by ScrubN** [comment]
In order to achieve this, we should probably move the current file extension guessing from CLI to Core so we aren't hard coding in the enqueuer:
https://github.com/lay295/TwitchDownloader/blob/1afcc3ce2166ab128cb6ca0463fae46acc2e59b5/TwitchDownloaderCLI/Modes/DownloadVideo.cs#L50-L58
https://github.com/lay295/TwitchDownloader/blob/1afcc3ce2166ab128cb6ca0463fae46acc2e59b5/TwitchDownloaderWPF/WindowQueueOptions.xaml.cs#L477-L480

**Comment by superbonaci** [comment]
I think the whole file extension guessing is something done only on Windows, and generally speaking it shouldn't matter. `quality` should be the only way to set what has to be downloaded, any file extension or none at all.

**Comment by ScrubN** [comment]
FFmpeg uses the file extension to automatically determine several things.

**Comment by ScrubN** [comment]
After #998, we may as well add the "worst" keyword to the enqueuer as well.
