### ISSUE TITLE
Warn when about to overwrite file

### ISSUE THREAD

**Issue by OrionRedStar** [lay295/TwitchDownloader#997]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

It would be nice if the program would warn you if it's about to overwrite files when you enqueue render. I just had a few stream videos overwritten (and the Twitch past broadcasts are expired) because I didn't realize the JSON file was the same name as the video file name. Thanks!

**Comment by superbonaci** [comment]
Do you want to just warn or to ask before overwriting?

**Comment by OrionRedStar** [comment]
Either one would be fine. Something like, "Are you sure you want to overwrite?"
